/** A compact OpenAPI 3.1 description of the RideNow API (served at GET /openapi.json). */
const secured = [{ bearer: [] }];
const op = (summary: string, tag: string, auth = true) => ({ summary, tags: [tag], ...(auth ? { security: secured } : {}), responses: { "200": { description: "OK" } } });

export const openapi = {
  openapi: "3.1.0",
  info: { title: "RideNow API", version: "1.0.0", description: "Ride-hailing API shared by the rider app, driver app and operations console." },
  components: { securitySchemes: { bearer: { type: "http", scheme: "bearer", bearerFormat: "JWT" } } },
  paths: {
    "/health": { get: op("Health check (verifies the database)", "system", false) },
    "/config": { get: op("City, currency and vehicle types", "public", false) },
    "/places/search": { get: op("Search well-known places", "public", false) },
    "/fare/estimate": { post: op("Fare estimates for every vehicle type (optional promo code)", "public", false) },
    "/auth/register": { post: op("Register a rider (includes a welcome credit)", "auth", false) },
    "/auth/register-driver": { post: op("Apply as a driver (pending approval)", "auth", false) },
    "/auth/login": { post: op("Sign in with email and password", "auth", false) },
    "/auth/otp/request": { post: op("Send a one-time code by SMS", "auth", false) },
    "/auth/otp/verify": { post: op("Sign in with a one-time code", "auth", false) },
    "/auth/refresh": { post: op("Rotate the refresh token", "auth", false) },
    "/auth/logout": { post: op("Revoke the refresh token", "auth", false) },
    "/auth/me": { get: op("Current account", "auth"), patch: op("Update name, phone or password", "auth") },
    "/rider/trips": { get: op("Trip history", "rider"), post: op("Book a ride", "rider") },
    "/rider/trips/active": { get: op("The rider's active trip", "rider") },
    "/rider/trips/{id}": { get: op("Trip detail with events", "rider") },
    "/rider/trips/{id}/cancel": { post: op("Cancel a ride", "rider") },
    "/rider/trips/{id}/rate": { post: op("Rate the driver", "rider") },
    "/rider/wallet": { get: op("Wallet balance", "rider") },
    "/rider/wallet/transactions": { get: op("Wallet ledger", "rider") },
    "/rider/wallet/topup": { post: op("Add money with a card", "rider") },
    "/rider/places": { get: op("Saved places", "rider"), post: op("Save a place", "rider") },
    "/rider/places/{id}": { delete: op("Remove a saved place", "rider") },
    "/rider/promos": { get: op("Available promo codes", "rider") },
    "/rider/promos/check": { post: op("Check a promo code", "rider") },
    "/driver/me": { get: op("Driver profile, vehicle and documents", "driver") },
    "/driver/online": { post: op("Go online or offline", "driver") },
    "/driver/location": { post: op("Report location", "driver") },
    "/driver/offers/current": { get: op("The pending ride request", "driver") },
    "/driver/offers/{id}/accept": { post: op("Accept a ride request", "driver") },
    "/driver/offers/{id}/decline": { post: op("Decline a ride request", "driver") },
    "/driver/trips/active": { get: op("The driver's active trip", "driver") },
    "/driver/trips/{id}/arrive": { post: op("Arrived at pickup", "driver") },
    "/driver/trips/{id}/start": { post: op("Start the ride with the rider's PIN", "driver") },
    "/driver/trips/{id}/complete": { post: op("Complete the ride and settle the fare", "driver") },
    "/driver/trips/{id}/cancel": { post: op("Cancel with a reason", "driver") },
    "/driver/trips/{id}/rate": { post: op("Rate the rider", "driver") },
    "/driver/trips": { get: op("Trip history", "driver") },
    "/driver/earnings": { get: op("Earnings for today, the week or the month", "driver") },
    "/driver/wallet": { get: op("Wallet, ledger and payouts", "driver") },
    "/driver/payouts": { post: op("Request a payout", "driver") },
    "/driver/ratings": { get: op("Ratings received", "driver") },
    "/support/tickets": { get: op("My support tickets", "support"), post: op("Open a ticket", "support") },
    "/support/tickets/{id}": { get: op("Ticket thread", "support") },
    "/support/tickets/{id}/messages": { post: op("Reply to a ticket", "support") },
    "/support/notifications": { get: op("Notifications", "support") },
    "/support/notifications/read": { post: op("Mark all as read", "support") },
    "/admin/dashboard": { get: op("KPIs, 14-day series, vehicle mix, top drivers", "admin") },
    "/admin/live": { get: op("Online drivers, active trips, zones", "admin") },
    "/admin/trips": { get: op("Search trips", "admin") },
    "/admin/trips/{id}": { get: op("Trip detail with offers and ledger", "admin") },
    "/admin/trips/{id}/cancel": { post: op("Cancel a trip", "admin") },
    "/admin/trips/{id}/refund": { post: op("Refund a paid trip", "admin") },
    "/admin/riders": { get: op("Riders", "admin") },
    "/admin/riders/{id}": { get: op("Rider detail", "admin") },
    "/admin/users/{id}/status": { post: op("Suspend or reactivate an account", "admin") },
    "/admin/drivers": { get: op("Drivers", "admin") },
    "/admin/drivers/{id}": { get: op("Driver detail", "admin") },
    "/admin/drivers/{id}/status": { post: op("Approve, suspend or review a driver", "admin") },
    "/admin/documents/{id}/review": { post: op("Approve or reject a document", "admin") },
    "/admin/vehicle-types": { get: op("Pricing", "admin") },
    "/admin/vehicle-types/{id}": { put: op("Update pricing", "admin") },
    "/admin/zones": { get: op("Surge zones", "admin") },
    "/admin/zones/{id}": { patch: op("Set surge", "admin") },
    "/admin/promos": { get: op("Promo codes", "admin"), post: op("Create a promo code", "admin") },
    "/admin/promos/{code}": { patch: op("Pause or resume a promo", "admin") },
    "/admin/payouts": { get: op("Payout requests", "admin") },
    "/admin/payouts/{id}/decision": { post: op("Mark paid or reject", "admin") },
    "/admin/finance": { get: op("Platform finance summary", "admin") },
    "/admin/tickets": { get: op("Support queue", "admin") },
    "/admin/tickets/{id}": { patch: op("Set ticket status and priority", "admin") },
    "/admin/audit": { get: op("Audit log", "admin") },
    "/admin/wallets/{userId}": { get: op("Any wallet's ledger", "admin") },
    "/admin/wallets/{userId}/adjust": { post: op("Credit or debit a wallet", "admin") },
    "/stream": { get: op("Server-Sent Events (token in the query string)", "realtime", false) },
  },
};
