"""The pack catalog: every horizontal and vertical pack the platform will offer.

Reconciled on 2026-09-26 from four sources, tagged per pack:
  spec      R_&_D/specs/pack-framework/03 (horizontal) and /04 (vertical)
  registry  docs/PACK_REGISTRY.md (45 horizontal, ~100 vertical)
  PRD       R_&_D/OmniStackAI_Product_PRD_and_Industry_Blueprints.md (blueprints §4, stack-aware packs §5.1)
  new       added on the founder's request for more packs in both layers

Every pack is stack-aware (PRD §5.1): one logical capability with an implementation per supported
stack — Next.js web/admin, React Native (Expo), Kotlin/Compose, Swift/SwiftUI, and the Python/Go/
Node backend. Native implementations arrive with Phase 5 (PC-082).

Statuses use the master list's vocabulary. "Pending" means something already exists to build on
(named in the note); the pack itself — a manifest v2 unit that works alone and composes — does not.
"""

N, P = "Not Started", "Pending"

# (category, [(pack id, provides, source, priority, status, note)])
HORIZONTAL = [
    ("Core platform", [
        ("database-pg", "PostgreSQL schema, migrations, seeds, row-level security", "registry", "P1", P, "Schema/migrations/seeds exist (R-238, R-248)."),
        ("database-mongo", "MongoDB collections, schema validation, indexes, seeds", "new", "P2", N, "Founder decision D-8; built by PC-048."),
        ("api-core", "REST API, validation, OpenAPI, errors, rate limiting", "registry", "P1", P, "Python/Go/Node APIs exist (R-229, R-230, R-517)."),
        ("auth-rbac", "Login, register, roles, sessions, MFA, OAuth, passkeys", "spec, registry", "P1", P, "Auth exists (R-461, R-241..R-243); Go login R-591."),
        ("config-env", "Typed env config, secret references, multi-environment", "registry", "P2", P, "Credential templates exist (R-547)."),
        ("admin-crud", "Generated admin: tables, filters, bulk actions, exports", "spec", "P1", P, "Admin app exists (R-542, R-270, R-271)."),
        ("multi-app", "Shared API, cross-app auth, preview proxy, deploy coordination", "spec", "P1", P, "Ecosystem monorepo exists (R-554, R-447, R-553)."),
        ("multi-tenancy", "Tenant isolation, per-tenant data, tenant switching", "new (registry dependency)", "P1", N, ""),
        ("onboarding-invitations", "Sign-up flows, invitations, first-run checklists", "new (registry dependency)", "P2", N, ""),
        ("api-docs", "OpenAPI, Swagger UI, Postman collection, SDKs", "spec", "P2", P, "OpenAPI exists (R-260, R-588)."),
        ("observability", "Logs, metrics, traces, error tracking, alerting", "spec, registry", "P2", N, "PC-057."),
        ("ci-cd", "CI workflows, containers, Helm, preview environments", "registry", "P2", P, "CI/CD workflow generation exists (R-452)."),
        ("git-ops", "Conventional commits, changelog, releases", "registry", "P3", N, ""),
        ("custom-domains", "Custom domains, DNS, TLS certificates", "new (registry dependency 'dns')", "P2", P, "Custom domains exist for published apps (R-510)."),
    ]),
    ("Security & compliance", [
        ("rbac-advanced", "Ownership rules, row-level and field-level permissions, org hierarchies, impersonation", "spec", "P1", N, "R-570."),
        ("security-headers", "CSP, HSTS, permissions policy, nonces", "registry", "P2", N, ""),
        ("audit-log", "Append-only, tamper-evident audit log with query API", "registry", "P2", N, "PC-057."),
        ("encryption", "Field-level encryption, key rotation, KMS", "registry", "P2", N, ""),
        ("secrets", "Secret management, rotation, audit", "spec", "P2", P, "Platform secrets exist (R-503)."),
        ("compliance-gdpr", "Data export, deletion, consent, retention", "registry", "P2", N, "PC-012."),
        ("consent-management", "Consent capture and ledger, cookie preferences", "new (registry dependency)", "P2", P, "Cookie consent component exists (R-402)."),
        ("compliance-hipaa", "PHI masking, access audit, breach notification", "registry", "P2", N, ""),
        ("compliance-soc2", "Control mapping, evidence collection, access reviews", "registry", "P3", N, ""),
        ("identity-verification", "KYC/KYB, document and selfie checks, verification status", "new (registry dependency 'verification')", "P2", N, ""),
        ("moderation", "Content moderation (AI + human queue), reports, bans", "new (registry dependency)", "P2", N, ""),
        ("fraud-risk", "Risk scoring, velocity rules, device fingerprints, blocklists", "new", "P3", N, ""),
    ]),
    ("Data & storage", [
        ("files-storage", "S3-compatible uploads, presigned URLs, image transforms, CDN", "spec, registry", "P1", N, "PC-052."),
        ("queue-jobs", "Background jobs, retries, schedules, dead letter", "spec, registry", "P1", N, "R-568."),
        ("search-engine", "Meilisearch/Typesense, facets, typo tolerance", "spec, registry", "P3", P, "Keyword search exists (R-261); PC-058."),
        ("cache-layer", "Redis/Valkey caching, invalidation, locks", "spec, registry", "P3", N, ""),
        ("analytics-events", "Event tracking, funnels, cohorts (PostHog/GA4)", "spec, registry", "P2", P, "Published-app analytics exists (R-513)."),
        ("pdf-documents", "Document templates, PDF generation, document store", "new (registry dependencies 'documents', 'pdf-generation')", "P2", P, "PDF viewer component exists (R-388)."),
        ("data-import-export", "CSV/Excel import with mapping and validation; bulk export", "new", "P2", P, "CSV/JSON export exists (R-271, R-308)."),
        ("reporting", "Scheduled reports, report builder, PDF/Excel delivery", "new (registry dependency)", "P2", N, ""),
        ("data-archival", "Tiered storage, retention, legal hold", "registry", "P3", N, ""),
        ("backups-restore", "Point-in-time backups and self-service restore for generated apps", "new", "P3", N, ""),
        ("vector-search", "Embeddings and semantic search on pgvector", "new", "P2", N, ""),
    ]),
    ("Realtime & communication", [
        ("realtime-core", "Live updates, presence, broadcast", "spec, registry", "P1", N, "R-569."),
        ("notifications", "Email, SMS, push, in-app centre, preferences, digests", "spec, registry", "P1", P, "Email exists (R-516); PC-053."),
        ("communications", "1:1 and group chat, threads, mentions, reactions, attachments", "spec, registry", "P2", P, "Chat component exists (R-384)."),
        ("activity-feed", "Activity streams, timelines, follow/subscribe", "new (registry dependency)", "P2", P, "Timeline component exists (R-336)."),
        ("video-calling", "WebRTC calls, screen share, recording, transcripts", "registry", "P2", N, ""),
        ("webhooks", "Outgoing webhooks, retries, signatures, replay", "spec, registry", "P2", P, "Cross-surface webhooks exist (R-448); PC-057."),
        ("support-helpdesk", "Tickets, knowledge base, live-chat widget, SLAs", "new", "P2", N, ""),
    ]),
    ("Business logic & workflow", [
        ("workflows-core", "State machines, transitions, guards, actions, audit", "spec, registry", "P1", P, "Transitions done (R-566, R-588, R-589); guards R-571; buttons R-590."),
        ("rules-engine", "Business rules on create/update/transition", "new (architecture plan)", "P1", N, "R-571."),
        ("scheduling", "Calendars, recurrence, conflicts, time zones, bookings, reminders", "spec, registry", "P1", P, "Calendar/time-picker components exist (R-366, R-371)."),
        ("calendar-sync", "Google/Outlook/iCal sync", "new (registry dependency 'calendar')", "P2", N, ""),
        ("approvals", "Multi-step approval chains, escalation, delegation", "registry", "P2", N, ""),
        ("task-management", "Tasks, assignees, due dates, boards", "new (registry dependency 'tasks')", "P2", P, "Kanban component exists (R-367)."),
        ("crm", "Contacts, companies, leads, pipeline, activities", "new (registry dependency)", "P2", N, ""),
        ("e-sign", "Document signing, signer flows, certificates", "new (registry dependency)", "P2", P, "Signature pad exists (R-372)."),
        ("billing-metering", "Usage metering, rating, invoicing, dunning", "registry", "P2", N, ""),
        ("feature-flags", "Flags, rollouts, experiments, kill switches", "spec, registry", "P3", N, "PC-056."),
        ("audit-trail", "Entity history, diffs, point-in-time queries", "registry", "P2", N, ""),
        ("ratings-reviews", "Stars, reviews, moderation, aggregates", "spec", "P2", P, "Rating component exists (R-333)."),
        ("referrals-affiliates", "Referral codes, tracking, rewards", "spec", "P3", N, ""),
        ("gamification", "Points, badges, levels, leaderboards, streaks", "new (registry dependency)", "P3", N, ""),
        ("pricing-engine", "Price rules, tiers, dynamic pricing, quotes", "new (registry dependencies 'pricing', 'rate-engine')", "P2", N, ""),
        ("forecasting", "Demand and cash forecasts from history", "new (registry dependency)", "P3", N, ""),
    ]),
    ("Commerce & payments", [
        ("payments-core", "Stripe/Razorpay/Paddle payments, refunds, disputes", "spec, registry, PRD", "P1", P, "Checkout exists (R-512)."),
        ("wallet-ledger", "Double-entry ledger, accounts, transfers, reconciliation", "registry, PRD", "P1", N, "R-567."),
        ("subscriptions", "Plans, trials, proration, pausing, dunning", "spec, registry", "P2", N, "R-567."),
        ("marketplace-payments", "Split payments, escrow, payouts, seller onboarding", "spec ('marketplace-core'), registry", "P2", N, "R-567; Bazaar shows the shape."),
        ("invoicing", "Invoices, PDFs, recurring invoices, reminders", "registry", "P2", N, ""),
        ("tax-compliance", "VAT/GST/sales tax calculation and validation", "registry", "P3", N, ""),
        ("coupons-promotions", "Coupons, discounts, promotions, gift cards", "new", "P2", N, ""),
        ("multi-currency", "Currencies, exchange rates, price lists", "registry (listed under commerce)", "P2", P, "Currency input exists (R-409)."),
    ]),
    ("UI & experience", [
        ("design-system", "Design tokens, components, motion, dark mode", "registry", "P1", P, "Design system exists (R-558, R-324, R-491)."),
        ("theming-branding", "Brand kit applied to every surface", "new", "P2", P, "brand.json exists (R-548); PC-020."),
        ("pwa", "Installable app, service worker, offline, push, QR", "spec", "P0", P, "R-573."),
        ("forms-engine", "Multi-step wizards, conditional fields, drafts", "registry", "P2", N, "PC-059."),
        ("data-tables", "Virtualised tables, grouping, column picker, export", "registry", "P2", P, "Data grid exists (R-329)."),
        ("charts-dashboards", "Charts, dashboards, live series", "registry", "P2", P, "Chart suite exists (R-370)."),
        ("rich-text", "Rich text editor, mentions, slash commands", "registry", "P2", P, "Markdown editor exists (R-365)."),
        ("maps-geo", "Maps, geocoding, geofences, routes, address autocomplete", "registry ('mapping', listed under mobility), PRD", "P1", P, "Geo-map component exists (R-387)."),
        ("localization", "i18n, RTL, currency and date formatting", "spec", "P2", N, "PC-055."),
        ("accessibility", "WCAG 2.1 AA, automated axe checks", "spec", "P2", P, "Accessible UI exists (R-296)."),
        ("performance", "Bundle analysis, Core Web Vitals, Lighthouse CI", "spec", "P2", N, "PC-037."),
        ("seo", "Metadata, sitemaps, structured data, AI-search readiness", "new (registry dependency)", "P2", P, "SEO exists (R-505)."),
        ("cms-marketing-site", "Landing pages, blog, CMS for non-developers", "new", "P2", N, ""),
        ("onboarding-tours", "Product tours and spotlight guides", "new", "P3", P, "Tour component exists (R-363)."),
        ("storybook", "Component docs and visual playground", "spec", "P3", N, ""),
    ]),
    ("Mobile & device (stack-aware: React Native, Kotlin, Swift)", [
        ("mobile-push", "Push notifications (Expo, FCM, APNs), deep-link on tap", "PRD", "P1", N, "PC-053."),
        ("secure-storage", "Keychain/Keystore-backed storage for tokens and secrets", "PRD", "P1", N, ""),
        ("geolocation", "Foreground/background location, live tracking", "PRD", "P1", N, "Needs R-569."),
        ("camera-qr", "Camera, photo/video capture, QR and barcode scanning", "PRD (+ registry 'barcode')", "P1", P, "QR generation exists (R-382)."),
        ("biometrics", "Face ID / Touch ID / BiometricPrompt, passkeys", "PRD", "P2", N, ""),
        ("offline-sync", "Offline-first storage, sync queue, conflict resolution", "new", "P1", N, ""),
        ("deep-links", "Universal/app links, share links into screens", "new", "P1", N, ""),
        ("in-app-purchases", "Apple and Google in-app purchases and subscriptions", "new", "P1", N, "Required by store rules for digital goods; keys at PC-070."),
        ("app-store-assets", "Icons, splash, screenshots, store listing metadata", "new", "P1", P, "Icons and EAS config exist (R-546, R-547); R-574."),
        ("ota-updates", "Over-the-air updates and in-app update prompts", "new", "P2", N, ""),
        ("crash-reporting", "Crash and ANR reporting with symbolication", "new", "P2", N, ""),
        ("background-tasks", "Background fetch, scheduled local work", "new", "P2", N, ""),
        ("media-player-device", "Audio/video playback, background audio, casting", "new", "P3", P, "Web media players exist (R-376, R-390)."),
        ("health-fitness-data", "HealthKit and Health Connect", "new", "P3", N, ""),
        ("bluetooth-nfc", "Bluetooth LE and NFC", "new", "P3", N, ""),
        ("share-contacts", "Share sheet, contacts picker, calendar events", "new (registry dependency 'sharing')", "P3", N, ""),
    ]),
    ("Integration & AI", [
        ("ai-assistant", "In-app AI: chat assistant, summarise, extract, generate, over the app's own data", "new", "P1", N, "Uses the platform's model gateway pattern; keys at PC-070."),
        ("integration-hub", "Connectors (Slack, HubSpot, Salesforce ...), workflow builder", "registry", "P2", P, "Connectors v1 exist (R-511)."),
        ("ml-inference", "Model inference endpoints for scoring and classification", "new (registry dependency)", "P3", N, ""),
        ("api-gateway", "Rate limits, API keys, transformations", "registry", "P3", N, ""),
        ("developer-portal", "API keys, docs, usage for third-party developers", "new (registry dependency)", "P3", N, ""),
        ("plugin-system", "Sandboxed plugins and extension marketplace", "registry", "P3", N, ""),
        ("mcp-gateway", "MCP server exposing the app's tools to AI agents", "registry", "P3", N, ""),
        ("iot-telematics", "Device registry, telemetry ingestion, alerts", "new (registry dependencies 'iot', 'telematics')", "P3", N, ""),
    ]),
    ("Quality", [
        ("testing", "Generated unit, contract and end-to-end tests", "spec", "P1", N, "PC-054."),
    ]),
]

# (domain, bundle id, wave, source, [(pack id, provides, source, status, note)])
# Wave 1 = P1 (from existing templates), wave 2 = P2 (the PRD/spec blueprints), wave 3 = P3.
VERTICAL = [
    ("Healthcare & life sciences", "healthcare-core", 1, "spec, registry, PRD", [
        ("patients", "Patients, records, insurance, consent", "registry", P, "CareClinic template."),
        ("providers", "Providers, specialties, licences, schedules", "registry", P, "CareClinic template."),
        ("appointments", "Appointments, slots, reminders, waitlist", "registry", P, "CareClinic template."),
        ("emr", "Encounters, notes, diagnoses, vitals", "registry", P, "CareClinic template (partial)."),
        ("prescriptions", "Prescriptions, medications, pharmacies", "registry", P, "CareClinic template (partial)."),
        ("lab-orders", "Lab orders, specimens, results", "registry", N, ""),
        ("telehealth", "Video consults, consent, technical checks", "registry", P, "CareClinic template."),
        ("billing-codes", "Claims, codes, payers, remittance", "registry", N, ""),
        ("hipaa-compliance", "Access logs, breach reports, risk assessments", "registry", N, ""),
        ("clinical-trials", "Trials, protocols, enrolment, adverse events", "registry", N, ""),
        ("pharmacy-integration", "Formulary, dispense, interaction checks", "registry", N, ""),
        ("lab-integration", "Lab interfaces, HL7 mapping, QC", "registry", N, ""),
        ("dental-clinic", "Dental charts, treatment plans, recalls", "new", N, ""),
        ("mental-health", "Therapy sessions, journals, assessments", "new", N, ""),
    ]),
    ("Mobility & on-demand", "mobility-core", 1, "spec, registry, PRD", [
        ("rides", "Rides, routes, fares, matching, receipts", "registry", P, "RideNow template."),
        ("drivers", "Drivers, vehicles, documents, earnings", "registry", P, "RideNow template."),
        ("dispatch", "Zones, assignment rules, heatmaps", "registry", P, "RideNow template (partial)."),
        ("fleet", "Fleet, vehicles, maintenance, inspections", "registry (+ dependencies 'vehicles', 'maintenance')", N, ""),
        ("deliveries", "Packages, pickups, drop-offs, proof of delivery", "registry (+ dependency 'proof-of-delivery')", N, ""),
        ("last-mile", "Route plans, stop sequencing, time windows", "registry (+ dependency 'routing')", N, ""),
        ("surge-pricing", "Demand/supply signals, multipliers", "registry", N, ""),
        ("background-checks", "Driver checks, adverse actions", "registry", N, ""),
        ("insurance-commercial", "Commercial policies, claims", "registry (+ dependency 'insurance')", N, ""),
        ("vehicle-rentals", "Car/bike/scooter rental, unlock, trip billing", "new", N, ""),
        ("parking", "Parking spots, bookings, enforcement", "new", N, ""),
    ]),
    ("Marketplace & commerce", "commerce-core", 1, "spec, registry", [
        ("listings", "Listings, categories, variants, media", "registry", P, "Bazaar template."),
        ("cart-checkout", "Cart, coupons, checkout sessions", "registry", P, "Bazaar template."),
        ("orders", "Orders, line items, timelines", "new (registry dependency)", P, "Bazaar template."),
        ("inventory", "Stock levels, reservations, reorder points", "registry", N, ""),
        ("fulfillment", "Fulfilment orders, shipments, labels, tracking", "registry (+ dependency 'shipping')", N, ""),
        ("vendors", "Vendors, storefronts, verification", "registry", P, "Bazaar template."),
        ("commissions", "Commission rules, splits, payout cycles", "registry", P, "Bazaar ledger."),
        ("reviews", "Verified-purchase reviews, moderation", "registry", N, ""),
        ("returns", "Returns, inspections, refunds, exchanges", "registry", N, ""),
        ("subscriptions-commerce", "Subscription boxes, physical + digital", "registry", N, ""),
        ("affiliates", "Affiliate links, conversions, tiers", "registry", N, ""),
        ("marketplace-seo", "Programmatic SEO, structured data", "registry", N, ""),
        ("purchase-orders", "B2B purchase orders and approvals", "new (registry dependency)", N, ""),
        ("wishlists-recommendations", "Wishlists, recently viewed, recommendations", "new", N, ""),
        ("auctions-bidding", "Auctions, bids, reserve prices", "new", N, ""),
    ]),
    ("Quick commerce & grocery", "quick-commerce-core", 2, "PRD §4.1, template FreshCart", [
        ("dark-stores", "Dark stores, picking, packing", "PRD", N, ""),
        ("grocery-catalog", "Grocery catalogue, weights, substitutions", "PRD", N, ""),
        ("delivery-slots", "Delivery slots and capacity", "PRD", N, ""),
        ("rider-batching", "Batching orders per rider", "PRD", N, ""),
        ("substitutions", "Out-of-stock substitution approval", "new", N, ""),
        ("basket-reorder", "Reorder, smart baskets", "new", N, ""),
    ]),
    ("FinTech & banking", "fintech-core", 2, "spec, registry, PRD §4.3", [
        ("accounts", "Accounts, holders, beneficiaries, limits", "registry", N, ""),
        ("ledger-core", "Journals, periods, reconciliation", "registry", N, ""),
        ("transfers", "Transfers, ACH/SEPA/UPI, FX", "registry (+ dependency 'transactions')", N, ""),
        ("cards", "Card issuing, authorisations, disputes", "registry", N, ""),
        ("lending", "Loan origination, underwriting, amortisation", "registry", N, ""),
        ("credit-scoring", "Score models, decisions", "registry", N, ""),
        ("compliance-aml", "AML alerts, cases, watchlists", "registry (+ dependency 'case-management')", N, ""),
        ("compliance-kyc", "KYC profiles, verification, risk rating", "registry", N, ""),
        ("treasury", "Cash positions, forecasts, sweeps", "registry", N, ""),
        ("trade-finance", "Letters of credit, guarantees", "registry (+ dependency 'letters-of-credit')", N, ""),
        ("digital-assets", "Wallets, custody, transfers", "registry (+ dependency 'custody')", N, ""),
        ("open-banking", "Consent, data access, payment initiation", "registry", N, ""),
        ("regulatory-reporting", "Regulatory reports and filings", "registry", N, ""),
        ("wealth-management", "Portfolios, rebalancing, goals", "registry (+ dependency 'portfolio')", N, ""),
        ("bill-payments-upi", "Bill payments, UPI, QR payments", "new", N, ""),
        ("personal-finance", "Budgets, expense categorisation, savings goals", "new (registry dependencies 'budgeting', 'expenses')", N, ""),
    ]),
    ("Food delivery & hospitality", "food-delivery-core", 2, "spec, registry", [
        ("restaurants", "Restaurants, hours, locations", "registry (+ dependency 'multi-location')", N, ""),
        ("menus", "Menus, modifiers, allergens, nutrition", "registry", N, ""),
        ("food-orders", "Orders, kitchen tickets, timelines", "registry ('orders')", N, ""),
        ("kitchen", "Kitchen display, stations, prep times", "registry", N, ""),
        ("couriers", "Couriers, shifts, earnings, incentives", "registry", N, ""),
        ("delivery-tracking", "Live location, ETA, share links", "registry (+ dependency 'tracking')", N, ""),
        ("loyalty", "Points, tiers, rewards", "registry", N, ""),
        ("catering", "Catering orders, proposals, deposits", "registry", N, ""),
        ("ghost-kitchens", "Virtual brands, capacity", "registry", N, ""),
        ("table-reservations", "Tables, reservations, waitlist", "new", N, ""),
    ]),
    ("Real estate & proptech", "real-estate-core", 2, "spec, registry, PRD §4.6, template Estately", [
        ("properties", "Properties, units, amenities, valuations", "registry", N, ""),
        ("listings-re", "Property listings, price history, disclosures", "registry", N, ""),
        ("tours", "Tour scheduling, self-guided, virtual", "registry (+ dependency 'virtual-tours')", N, ""),
        ("offers", "Offers, counters, contingencies", "registry", N, ""),
        ("contracts", "Contracts, clauses, addenda", "registry (+ dependency 'compliance-re')", N, ""),
        ("escrow", "Escrow accounts, disbursements", "registry", N, ""),
        ("property-mgmt", "Leases, tenants, maintenance, rent", "registry (+ dependencies 'portals', 'accounting')", N, ""),
        ("investment-analysis", "Pro formas, cash flow, IRR", "registry", N, ""),
        ("agent-crm", "Agent leads, pipelines, follow-ups", "new (template Estately)", N, ""),
        ("co-living-rentals", "Rooms, short stays, house rules", "new", N, ""),
    ]),
    ("Education & edtech", "edtech-core", 2, "spec, registry, PRD §4.5, template LearnHub", [
        ("courses", "Courses, modules, lessons, prerequisites", "registry", N, ""),
        ("enrollments", "Enrolments, progress, completion", "registry", N, ""),
        ("assignments", "Assignments, submissions, rubrics, peer review", "registry (+ dependencies 'submissions', 'plagiarism')", N, ""),
        ("grading", "Gradebooks, schemes, exports", "registry (+ dependency 'gradebook')", N, ""),
        ("certificates", "Certificates, verifiable credentials", "registry", N, ""),
        ("lms-admin", "Schools, departments, instructors", "registry", N, ""),
        ("video-streaming", "Video lessons, captions, DRM", "registry (+ dependency 'drm')", N, ""),
        ("cohorts", "Cohorts, mentors, leaderboards", "registry", N, ""),
        ("compliance-education", "FERPA/COPPA consent and audit", "registry", N, ""),
        ("quizzes-exams", "Question banks, timed exams, proctoring", "new", N, ""),
        ("live-classes", "Live classes, attendance, recordings", "new", N, ""),
    ]),
    ("SaaS & B2B", "saas-b2b-core", 2, "spec, registry, PRD §4.10", [
        ("organizations", "Organisations, memberships, domains", "registry", N, ""),
        ("teams", "Teams, members, channels", "registry", N, ""),
        ("seats", "Seats, assignment, true-ups", "registry", N, ""),
        ("entitlements", "Per-feature and per-seat entitlements", "registry", N, ""),
        ("sso-saml", "SAML SSO, JIT provisioning", "registry", N, ""),
        ("sso-oidc", "OIDC SSO", "registry", N, ""),
        ("usage-metering", "Meters, quotas, alerts", "registry", N, ""),
        ("api-management", "API products, keys, monetisation", "registry", N, ""),
        ("marketplace-saas", "App listings, provisioning", "registry (+ dependency 'provisioning')", N, ""),
        ("white-label", "Brands, custom domains, rollouts", "registry", N, ""),
        ("scim-provisioning", "SCIM user provisioning", "new", N, ""),
        ("customer-success", "Health scores, renewals, churn signals", "new", N, ""),
    ]),
    ("Logistics & supply chain", "logistics-core", 2, "spec, registry, PRD §4.8", [
        ("shipments", "Shipments, legs, bills of lading", "registry", N, ""),
        ("warehouses", "Warehouses, zones, slotting, labour", "registry (+ dependencies 'warehouse', 'slotting', 'labor')", N, ""),
        ("inventory-wms", "Locations, cycle counts, pick paths", "registry (+ dependencies 'rfid', 'voice-picking')", N, ""),
        ("transportation", "Loads, carriers, tenders, rates", "registry (+ dependency 'compliance-dot')", N, ""),
        ("customs", "Entries, HS classification, duty", "registry (+ dependency 'hs-codes')", N, ""),
        ("freight-forwarding", "Quotes, bookings, milestones", "registry", N, ""),
        ("last-mile-logistics", "Routes, stops, exceptions", "registry", N, ""),
        ("supply-chain-visibility", "Control tower, ETAs, risk scores", "registry", N, ""),
        ("procurement", "Requisitions, POs, three-way match", "registry (+ dependency 'spend-analysis')", N, ""),
        ("fleet-management", "Assets, fuel, utilisation, TCO", "registry (+ dependency 'fuel-cards')", N, ""),
        ("yard-management", "Yard slots, gate check-in, docks", "new", N, ""),
    ]),
    ("On-demand home services", "home-services-core", 2, "PRD §4.7, template FixIt", [
        ("service-catalog", "Services, pricing, service areas", "PRD", N, ""),
        ("provider-matching", "Match jobs to nearby qualified pros", "PRD", N, ""),
        ("job-quotes", "Quotes, estimates, approvals", "PRD", N, ""),
        ("job-lifecycle", "Booked -> en route -> in progress -> done", "PRD", N, ""),
        ("service-warranty", "Warranties, callbacks, disputes", "new", N, ""),
    ]),
    ("Beauty, salon & wellness", "beauty-wellness-core", 2, "PRD §4.9, template Glow", [
        ("salon-booking", "Service booking with staff and chairs", "PRD", N, ""),
        ("staff-schedules", "Stylist schedules, commissions", "PRD", N, ""),
        ("service-menu", "Services, durations, add-ons", "PRD", N, ""),
        ("memberships-packages", "Memberships, packages, prepaid sessions", "new", N, ""),
        ("client-profiles", "Client history, preferences, before/after photos", "new", N, ""),
    ]),
    ("HR & recruiting", "hr-core", 2, "spec", [
        ("jobs-ats", "Job posts, applicant tracking", "spec", N, ""),
        ("candidate-pipeline", "Stages, interviews, scorecards, offers", "new", N, ""),
        ("employee-onboarding", "Onboarding checklists, documents", "spec", N, ""),
        ("payroll", "Payroll runs, payslips, deductions", "spec", N, ""),
        ("attendance-leave", "Attendance, shifts, leave requests", "spec", N, ""),
        ("performance-reviews", "Goals, reviews, feedback", "spec (+ registry dependencies 'people', 'skills')", N, ""),
    ]),
    ("Professional services & agencies", "professional-services-core", 3, "registry", [
        ("projects", "Projects, phases, milestones, budgets", "registry", N, ""),
        ("time-tracking", "Time entries, timers, approvals", "registry", N, ""),
        ("invoicing-ps", "Progress and milestone invoicing", "registry", N, ""),
        ("retainers", "Retainer balances, drawdowns", "registry (+ dependency 'retainer')", N, ""),
        ("resource-planning", "Allocations, capacity, skills", "registry", N, ""),
        ("client-portal", "Client portal, approvals, reports", "registry (+ dependencies 'customer-portal', 'clients')", N, ""),
        ("proposals", "Proposals, SOWs, e-sign", "registry (+ dependency 'crm-integration')", N, ""),
        ("compliance-ps", "Engagement letters, conflict checks", "registry", N, ""),
    ]),
    ("Content, media & publishing", "content-core", 3, "template Inkwell", [
        ("articles-cms", "Articles, authors, categories, SEO", "new", N, ""),
        ("editorial-workflow", "Draft -> review -> scheduled -> published", "new", N, ""),
        ("paywall-membership", "Paywalls, memberships, metered access", "new", N, ""),
        ("newsletters", "Newsletters, subscribers, campaigns", "new", N, ""),
        ("podcasts-video", "Episodes, feeds, players", "new", N, ""),
        ("community-comments", "Comments, reactions, moderation", "new", N, ""),
    ]),
    ("Travel & hospitality", "travel-core", 3, "new", [
        ("hotel-pms", "Rooms, reservations, housekeeping, folios", "new", N, ""),
        ("channel-manager", "Rates and availability across channels", "new", N, ""),
        ("travel-booking", "Flights/stays/packages search and booking", "new", N, ""),
        ("itineraries", "Trips, itineraries, documents", "new", N, ""),
        ("tours-activities", "Experiences, guides, capacity", "new", N, ""),
    ]),
    ("Events & ticketing", "events-core", 3, "new", [
        ("events", "Events, agendas, speakers, venues", "new", N, ""),
        ("ticketing", "Ticket types, sales, QR tickets", "new", N, ""),
        ("seating-maps", "Seat maps and reservations", "new", N, ""),
        ("check-in", "Scan-in, badges, capacity", "new", N, ""),
        ("sponsors-exhibitors", "Sponsors, booths, leads", "new", N, ""),
    ]),
    ("Fitness & sports", "fitness-core", 3, "new", [
        ("gym-memberships", "Memberships, access, freezes", "new", N, ""),
        ("class-booking", "Classes, instructors, capacity, waitlists", "new", N, ""),
        ("workout-plans", "Programs, workouts, progress", "new", N, ""),
        ("personal-training", "Trainers, sessions, packages", "new", N, ""),
        ("clubs-leagues", "Teams, fixtures, standings", "new", N, ""),
    ]),
    ("Social & community", "social-core", 3, "new", [
        ("profiles-social", "Profiles, follows, blocks", "new", N, ""),
        ("feeds-posts", "Posts, media, feeds, ranking", "new", N, ""),
        ("groups-communities", "Groups, roles, rules", "new", N, ""),
        ("creator-monetization", "Tips, subscriptions, paid content", "new", N, ""),
        ("dating-matching", "Matching, swipes, safety tools", "new", N, ""),
        ("forums-qa", "Forums, Q&A, accepted answers", "new", N, ""),
    ]),
    ("Insurance", "insurance-core", 3, "new", [
        ("policies", "Policies, coverages, endorsements", "new", N, ""),
        ("quotes-underwriting", "Quotes, rating, underwriting rules", "new", N, ""),
        ("claims", "FNOL, adjusting, settlement", "new", N, ""),
        ("agents-brokers", "Agents, commissions, books", "new", N, ""),
        ("premium-billing", "Premium schedules, collections", "new", N, ""),
    ]),
    ("Automotive", "automotive-core", 3, "new", [
        ("dealer-inventory", "Vehicles for sale, specs, photos", "new", N, ""),
        ("test-drives", "Test-drive booking", "new", N, ""),
        ("service-center", "Service bookings, job cards, parts", "new", N, ""),
        ("parts-catalog", "Parts catalogue, fitment", "new", N, ""),
        ("vehicle-history", "Ownership and service history", "new", N, ""),
    ]),
    ("Retail & restaurant POS", "pos-core", 3, "new", [
        ("pos-terminal", "Point of sale, receipts, cash drawer", "new", N, ""),
        ("store-inventory", "Store stock, transfers, counts", "new", N, ""),
        ("shift-cash-management", "Shifts, cash-ups, variances", "new", N, ""),
        ("customer-loyalty-pos", "In-store loyalty and offers", "new", N, ""),
    ]),
    ("Manufacturing & field operations", "manufacturing-core", 3, "new", [
        ("production-orders", "Work orders, routings", "new", N, ""),
        ("bill-of-materials", "BOMs, versions, costing", "new", N, ""),
        ("quality-control", "Inspections, non-conformances", "new", N, ""),
        ("maintenance-cmms", "Assets, preventive maintenance", "new", N, ""),
        ("field-service", "Technician dispatch, job sheets, signatures", "new", N, ""),
    ]),
    ("Legal", "legal-core", 3, "new", [
        ("matters-cases", "Matters, parties, deadlines", "new", N, ""),
        ("legal-documents", "Templates, clause library, versions", "new", N, ""),
        ("client-intake", "Intake forms, conflict checks", "new", N, ""),
        ("court-calendar", "Hearings, filings, reminders", "new", N, ""),
    ]),
    ("Nonprofit & civic", "civic-core", 3, "new", [
        ("donations-fundraising", "Donations, campaigns, receipts", "new", N, ""),
        ("volunteers", "Volunteer shifts and hours", "new", N, ""),
        ("grants", "Grant applications and reporting", "new", N, ""),
        ("citizen-services", "Service requests, status tracking", "new", N, ""),
        ("permits-licensing", "Applications, inspections, licences", "new", N, ""),
    ]),
    ("Utilities & energy", "utilities-core", 3, "new", [
        ("meter-reading", "Meters, readings, anomalies", "new", N, ""),
        ("utility-billing", "Tariffs, bills, payments", "new", N, ""),
        ("outage-management", "Outages, crews, notifications", "new", N, ""),
        ("ev-charging", "Chargers, sessions, billing", "new", N, ""),
    ]),
    ("Pets & veterinary", "pets-core", 3, "new", [
        ("pet-profiles", "Pets, vaccinations, records", "new", N, ""),
        ("vet-clinic", "Vet appointments, treatments", "new", N, ""),
        ("pet-services", "Grooming, boarding, walking", "new", N, ""),
    ]),
    ("Schools & childcare (K-12)", "schools-core", 3, "new", [
        ("school-admin", "Students, classes, timetables, fees", "new", N, ""),
        ("attendance-school", "Attendance and absence alerts", "new", N, ""),
        ("parent-portal", "Parent messages, report cards, payments", "new", N, ""),
        ("school-transport", "Bus routes and live tracking", "new", N, ""),
    ]),
    ("Construction & property services", "construction-core", 3, "new", [
        ("construction-projects", "Projects, phases, site teams", "new", N, ""),
        ("bids-estimates", "Estimates, bids, change orders", "new", N, ""),
        ("site-diary", "Daily logs, photos, safety incidents", "new", N, ""),
        ("subcontractors", "Subcontractors, compliance, payments", "new", N, ""),
    ]),
    ("Agriculture", "agri-core", 3, "new", [
        ("farms-fields", "Farms, fields, crops, seasons", "new", N, ""),
        ("agri-marketplace", "Produce listings, buyers, logistics", "new", N, ""),
        ("farm-advisory", "Weather, advisories, input orders", "new", N, ""),
    ]),
]

# Names that docs/PACK_REGISTRY.md uses as dependencies without defining them, and the pack in
# this catalog that answers each. A name that is its own pack here maps to itself.
ALIASES = {
    "accessibility": "accessibility", "accounting": "property-mgmt", "activity-feed": "activity-feed",
    "alerting": "observability", "barcode": "camera-qr", "billing": "payments-core",
    "blockchain": "(deferred: no concrete need)", "budgeting": "personal-finance",
    "calendar": "scheduling", "case-management": "compliance-aml", "cdn": "files-storage",
    "clients": "client-portal", "compliance-dot": "transportation", "compliance-re": "contracts",
    "consent-management": "consent-management", "crm": "crm", "crm-integration": "integration-hub",
    "custody": "digital-assets", "customer-portal": "client-portal",
    "developer-portal": "developer-portal", "dns": "custom-domains", "documents": "pdf-documents",
    "drm": "video-streaming", "e-sign": "e-sign", "expenses": "personal-finance",
    "forecasting": "forecasting", "fuel-cards": "fleet-management", "gamification": "gamification",
    "gradebook": "grading", "hs-codes": "customs", "insurance": "insurance-commercial",
    "invitations": "onboarding-invitations", "iot": "iot-telematics", "labor": "warehouses",
    "letters-of-credit": "trade-finance", "maintenance": "fleet", "ml-inference": "ml-inference",
    "moderation": "moderation", "multi-location": "restaurants", "multi-tenancy": "multi-tenancy",
    "onboarding": "onboarding-invitations", "pdf-generation": "pdf-documents",
    "people": "performance-reviews", "plagiarism": "assignments", "portals": "client-portal",
    "portfolio": "wealth-management", "pricing": "pricing-engine", "privacy": "compliance-gdpr",
    "proof-of-delivery": "deliveries", "provisioning": "marketplace-saas",
    "purchase-orders": "purchase-orders", "rate-engine": "pricing-engine",
    "rbac-extended": "rbac-advanced", "reporting": "reporting", "retainer": "retainers",
    "rfid": "inventory-wms", "routing": "last-mile", "seo": "seo", "sharing": "share-contacts",
    "shipping": "fulfillment", "skills": "performance-reviews", "slotting": "warehouses",
    "spend-analysis": "procurement", "submissions": "assignments", "tasks": "task-management",
    "telematics": "iot-telematics", "tracking": "delivery-tracking", "transactions": "transfers",
    "users": "auth-rbac", "vehicles": "fleet", "verification": "identity-verification",
    "virtual-tours": "tours", "voice-picking": "inventory-wms", "warehouse": "warehouses",
}

WAVE_PRIORITY = {1: "P1", 2: "P2", 3: "P3"}

# Every vertical pack delivers on every surface its industry uses (founder, 2026-09-26): the API
# and database, the web app, the mobile app (React Native by default, Kotlin/Swift when asked)
# and the admin panel. A pack is not done until each role below gets its screens for it.
SURFACE_RULE = (
    "Each vertical pack ships: API + database (entities, endpoints, state machines, permissions); "
    "Web (Next.js pages for each role that uses it); App (React Native screens, or Kotlin/Swift "
    "when native is asked); Admin panel (management, moderation, reports for the operator). "
    "Mobile apps also get the PWA + QR."
)

# bundle id -> [(role, surfaces)]. Surfaces: App = mobile app, Web = web app, Admin = admin panel.
DOMAIN_SURFACES = {
    "healthcare-core": [("Patient", "App + Web"), ("Doctor / provider", "Web + App"), ("Pharmacy / lab", "Web"), ("Clinic operator", "Admin")],
    "mobility-core": [("Rider", "App + Web"), ("Driver", "App"), ("Dispatcher", "Web"), ("Operator", "Admin")],
    "commerce-core": [("Buyer", "App + Web"), ("Seller / vendor", "Web + App"), ("Marketplace operator", "Admin")],
    "quick-commerce-core": [("Customer", "App + Web"), ("Picker / packer", "App"), ("Rider", "App"), ("Store manager", "Web"), ("Operator", "Admin")],
    "fintech-core": [("Customer", "App + Web"), ("Merchant", "Web + App"), ("Compliance officer", "Web"), ("Operator", "Admin")],
    "food-delivery-core": [("Customer", "App + Web"), ("Restaurant", "Web + App"), ("Courier", "App"), ("Operator", "Admin")],
    "real-estate-core": [("Buyer / tenant", "App + Web"), ("Agent / broker", "Web + App"), ("Landlord", "Web"), ("Operator", "Admin")],
    "edtech-core": [("Learner", "App + Web"), ("Instructor", "Web + App"), ("Parent", "App"), ("Institution admin", "Admin")],
    "saas-b2b-core": [("End user", "Web + App"), ("Customer admin", "Web"), ("Platform operator", "Admin")],
    "logistics-core": [("Shipper", "Web + App"), ("Driver / carrier", "App"), ("Warehouse staff", "App"), ("Dispatcher", "Web"), ("Operator", "Admin")],
    "home-services-core": [("Customer", "App + Web"), ("Service pro", "App"), ("Business owner", "Web"), ("Operator", "Admin")],
    "beauty-wellness-core": [("Client", "App + Web"), ("Stylist / therapist", "App"), ("Salon owner", "Web"), ("Operator", "Admin")],
    "hr-core": [("Candidate", "Web + App"), ("Employee", "App + Web"), ("Recruiter / HR", "Web"), ("HR admin", "Admin")],
    "professional-services-core": [("Client", "Web + App"), ("Consultant", "Web + App"), ("Partner / manager", "Web"), ("Firm admin", "Admin")],
    "content-core": [("Reader", "App + Web"), ("Writer / editor", "Web"), ("Publisher", "Admin")],
    "travel-core": [("Traveller", "App + Web"), ("Host / hotel staff", "Web + App"), ("Operator", "Admin")],
    "events-core": [("Attendee", "App + Web"), ("Organiser", "Web"), ("Door staff", "App"), ("Operator", "Admin")],
    "fitness-core": [("Member", "App + Web"), ("Trainer", "App"), ("Gym manager", "Web"), ("Operator", "Admin")],
    "social-core": [("Member", "App + Web"), ("Creator", "App + Web"), ("Moderator", "Admin")],
    "insurance-core": [("Policyholder", "App + Web"), ("Agent / broker", "Web + App"), ("Adjuster / underwriter", "Web"), ("Operator", "Admin")],
    "automotive-core": [("Buyer / owner", "App + Web"), ("Sales / service advisor", "Web + App"), ("Dealer admin", "Admin")],
    "pos-core": [("Cashier", "App (tablet)"), ("Store manager", "Web"), ("Owner", "Admin")],
    "manufacturing-core": [("Operator on the floor", "App"), ("Planner / QC", "Web"), ("Field technician", "App"), ("Plant admin", "Admin")],
    "legal-core": [("Client", "Web + App"), ("Lawyer / paralegal", "Web"), ("Firm admin", "Admin")],
    "civic-core": [("Citizen / donor", "App + Web"), ("Case worker / volunteer", "Web + App"), ("Agency admin", "Admin")],
    "utilities-core": [("Customer", "App + Web"), ("Field crew", "App"), ("Operator", "Admin")],
    "pets-core": [("Pet owner", "App + Web"), ("Vet / groomer", "Web + App"), ("Clinic admin", "Admin")],
    "schools-core": [("Parent", "App + Web"), ("Teacher", "Web + App"), ("Student", "App"), ("School admin", "Admin")],
    "construction-core": [("Site supervisor", "App"), ("Project manager", "Web"), ("Subcontractor", "App + Web"), ("Company admin", "Admin")],
    "agri-core": [("Farmer", "App"), ("Buyer", "Web + App"), ("Field advisor", "App"), ("Operator", "Admin")],
}

# Names used by the spec or the registry that this catalog renamed, so nothing looks lost.
RENAMES = {
    "mapping (registry, mobility)": "maps-geo (horizontal: every industry needs maps)",
    "analytics (spec)": "analytics-events", "audit-compliance (spec)": "audit-log + compliance-gdpr",
    "cache (spec)": "cache-layer", "marketplace-core (spec)": "marketplace-payments",
    "payments (spec)": "payments-core", "queue (spec)": "queue-jobs",
    "real-time (spec)": "realtime-core", "search (spec)": "search-engine",
    "workflows (spec)": "workflows-core", "orders (registry, food)": "food-orders",
    "<industry>-core (spec 04)": "the industry bundle id, e.g. healthcare-core = every healthcare pack",
}
