"""The data behind the master task list. Edit this file, then run build_master_tasks.py.

Every open task in R_&_D and its sub-folders is listed here once. A source item that is folded
into a bigger task keeps its own row and points at that task in `tracked_in`, so nothing is lost
and nothing is counted twice.

A task is marked Completed automatically when CHANGELOG.md has an entry for its id, so the list
cannot drift from the repository. Everything else is set by hand here.
"""

# --- Vocabulary ----------------------------------------------------------------------------------

STATUSES = {
    "Completed": "Built, tested and in CHANGELOG.md.",
    "Completed - needs live proof": "Built and tested offline, never run against a real account "
    "(Vercel, Stripe, app stores ...). Done in code, not proven in the world.",
    "In Progress": "Being worked on now.",
    "Pending": "Partly built, or waiting on a founder decision. Something exists to build on.",
    "Not Started": "Nothing built yet.",
    "Superseded": "Replaced by a different task that already did the job another way.",
    "Deferred": "Useful, but only after launch. Do not start until the queue is empty.",
    "Dropped": "Against the current stack policy or no longer wanted. Will not be built.",
}

PRIORITIES = {
    "P0": "Launch blocker. Vibe Mode cannot go live with real users without it.",
    "P1": "Core promise. Needed for 'maximum features per prompt' and Engineering Mode.",
    "P2": "Hardening and depth. Production trust, native apps, quality.",
    "P3": "Nice to have. Do when everything above is done.",
}

PHASES = {
    "0 Foundation": "Reconcile, decide, set the stack policy.",
    "1 Vibe Mode live": "Prompt -> running app with real API + DB -> live URL, for real users.",
    "2 Maximum features": "Every prompt yields the most complete product the IR can express.",
    "3 Engineering Mode": "Plan, stack choice, repo import, diffs, verification report, PRs, memory.",
    "4 Production ops": "Security audits, backup/recovery, compliance, observability.",
    "5 Native mobile (last)": "Kotlin/Compose + Swift/SwiftUI, through to Play Store and App Store.",
    "6 Go-live (credentials last)": "The founder supplies accounts and keys; every live proof "
    "is run; the platform opens to real users.",
    "7 Win the category": "Measure against every competitor and close each gap until we lead. "
    "Done last, after native and go-live, by founder decision (2026-09-26).",
    "Post-launch": "Deferred until the platform is live and the queue above is empty.",
    "Delivered": "Already built.",
}

# --- The work queue ------------------------------------------------------------------------------
# In the order they should be done. (id, title, phase, mode, status, priority, depends, notes)
# `mode` says whose promise the task serves: Vibe, Engineering, Both, Platform.

QUEUE = [
    # Phase 0
    ("PC-001", "Master task list: reconcile every R_&_D source into one queue", "0 Foundation",
     "Platform", "In Progress", "P0", "", "This document. Done when the founder approves it."),
    ("PC-002", "Founder decisions that block later phases (see Decisions sheet)", "0 Foundation",
     "Platform", "Pending", "P0", "PC-001",
     "Pricing/free tier, hosting cloud + region, payment processor, email verification, "
     "in-browser preview engine licence, app-store accounts. D-5, D-8, D-9 answered 2026-09-26."),
    ("PC-062", "Native mobile preview: R&D and plan (open source first)", "0 Foundation",
     "Both", "Not Started", "P0", "", "NATIVE_MOBILE_PREVIEW_PLAN.md in this folder."),
    ("PC-047", "NVIDIA model provider (nemotron-3-ultra) for builds, configured from .env",
     "0 Foundation", "Platform", "Not Started", "P0", "",
     "Founder's chosen LLM (D-9). OpenAI-compatible, so one provider entry plus the "
     "NVIDIA_MODEL_BASE_URL override, prices and tests. The key stays in .env only. Includes a "
     "first comparison against the providers we already support on the same build prompts."),
    ("PC-093", "Intake repairs instead of rejecting: a model's status-change endpoint becomes a "
     "workflow transition, and an undeclared request-schema reference is fixed, not fatal",
     "0 Foundation", "Both", "Not Started", "P0", "",
     "Found by PC-047's comparison (2026-09-26): 3 of 6 real intake runs, on both NVIDIA and "
     "Gemini, were rejected for the same reason. Roughly half of real prompts fail at the first "
     "step whichever model runs, so this comes before everything else."),
    ("PC-003", "Stack policy in code: an app request gets a store-ready React Native app AND "
     "an installable PWA with QR; Flutter and React.js refused with the reason", "0 Foundation",
     "Both", "Pending", "P0", "",
     "R-562 already builds the React Native app; the PWA + QR half is R-573. Native Kotlin/Swift "
     "only after Phase 5. Uses the R-559 'nearest thing we can build, with a reason' path."),
    # Phase 1 - Vibe Mode live
    ("R-591", "Complete auth for the Go backend: register, login, logout, me, forgot password, "
     "reset password", "1 Vibe Mode live", "Both", "Not Started", "P0", "",
     "A Go app with auth has no way for a real user to sign in. Parity with the Python "
     "backend's auth (R-461, R-463), companions included."),
    ("R-590", "Workflow transitions as buttons on the generated screens", "1 Vibe Mode live",
     "Both", "Not Started", "P0", "R-588", "The user-visible half of R-566."),
    ("R-573", "PWA really by default: manifest, service worker, icons, install prompt, QR",
     "1 Vibe Mode live", "Vibe", "Pending", "P0", "PC-003",
     "Works for templates only today; generated projects must install on a real phone."),
    ("PC-004", "Real API + DB for every feature: a Vibe build fails if any screen or action is "
     "not wired to a real endpoint and table", "1 Vibe Mode live", "Vibe", "Not Started", "P0",
     "R-590", "No mock data, no 501 stubs, no dead buttons. From specs/vibe-mode-pro."),
    ("PC-005", "Vibe / Engineering mode switch in the Studio", "1 Vibe Mode live", "Both",
     "Not Started", "P0", "", "From specs/studio-ux/01. Vibe hides the machinery; "
     "Engineering shows plan, stack, diffs, report, PRs."),
    ("PC-006", "'Wow in 30 seconds': first screen streams fast, latest modern UI, maximum "
     "polish per page", "1 Vibe Mode live", "Vibe", "Pending", "P0", "",
     "R-558 fixed the design system; still needs speed-to-first-screen and visual quality. "
     "From specs/table-stakes/01 and the buildout 'intent card' idea."),
    ("PC-084", "Speed targets measured on every build and enforced: prompt -> preview under "
     "90 s, prompt -> live URL under 3 min, as a dashboard and a regression gate",
     "1 Vibe Mode live", "Vibe", "Not Started", "P1", "PC-006",
     "The Targets sheet had numbers but no task measured them. Founder-approved 2026-09-26."),
    ("PC-085", "Model quality evals and best-model routing: score every provider (NVIDIA, "
     "cloud, local) per task type and route each job to the best one", "1 Vibe Mode live",
     "Both", "Not Started", "P1", "PC-047",
     "NVIDIA nemotron is unproven for code; this keeps quality independent of one vendor. "
     "Founder-approved 2026-09-26."),
    ("PC-007", "Instant in-browser preview (no local toolchain needed)", "1 Vibe Mode live",
     "Vibe", "Not Started", "P0", "",
     "From specs/table-stakes/02 and tracker R-174. Built behind a preview-engine interface with "
     "an open-source engine first; a paid engine licence (D-6) is only a key at the end."),
    ("PC-008", "One-click publish to a live URL: web, admin, API and database together, code "
     "complete and proven against local stand-ins", "1 Vibe Mode live", "Vibe", "Pending", "P0",
     "PC-049", "R-509/R-510 publish the web app only and were never run for real. From "
     "specs/table-stakes/03. Real accounts are plugged in at PC-070."),
    ("PC-009", "Hosted multi-tenant service: per-user isolation of builds, sessions and "
     "previews; quotas; egress policy", "1 Vibe Mode live", "Platform", "Not Started", "P0",
     "", "Today the Studio is one trusted operator's tool. Built cloud-neutral and proven "
     "locally (Colima); the cloud account (D-2) is plugged in at PC-070. "
     "Covers R-100, R-214, R-071, R-175."),
    ("PC-010", "Credit fairness: estimate before a build, no charge for internal retries, "
     "per-task budgets, cost guardrails", "1 Vibe Mode live", "Platform", "Not Started", "P0",
     "", "Covers R-046, R-047, R-025, R-104."),
    ("PC-011", "Plans, entitlements, credit top-up and super_admin console (Phase E)",
     "1 Vibe Mode live", "Platform", "Not Started", "P0", "",
     "Stripe and Razorpay adapters complete and tested in their test modes; live keys (D-3) at "
     "PC-070. Covers R-109."),
    ("PC-012", "Legal and account basics: ToS, privacy, retention, deletion/export, email "
     "verification", "1 Vibe Mode live", "Platform", "Not Started", "P0", "", "Covers R-108."),
    ("PC-013", "Verified integrations catalog with health tests", "1 Vibe Mode live", "Vibe",
     "Pending", "P1", "", "R-511 Connectors v1 exists. Covers R-055, R-056."),
    ("PC-014", "Local/offline models as a first-class path: build fully on Ollama, recommend "
     "a model per machine", "1 Vibe Mode live", "Both", "Pending", "P1", "",
     "Ollama adapter exists (R-003/R-006). Covers R-080, R-194."),
    ("R-574", "Store publishing for React Native apps: EAS build and submit to Play Store and "
     "App Store, proven with real accounts", "1 Vibe Mode live", "Both", "Pending", "P1",
     "PC-003", "R-546/R-547 generate the EAS config. Everything up to the upload is built and "
     "tested; the Apple and Google accounts (D-7) are plugged in at PC-070. Covers R-062, R-063."),
    ("PC-049", "Managed database for published apps: provision PostgreSQL (Neon, Supabase or "
     "self-hosted) and run migrations and seeds on publish", "1 Vibe Mode live", "Vibe",
     "Not Started", "P0", "", "A live URL needs a live database. Provider interface with a "
     "local Docker implementation; MongoDB Atlas once PC-048 exists. From the architecture plan."),
    ("PC-050", "Design System Pro: widen the LLM UI allowlist (motion, charts, rich text, "
     "command menu, drawer, toasts, tables, forms, maps, uploads)", "1 Vibe Mode live", "Vibe",
     "Not Started", "P1", "", "framer-motion, recharts, tiptap, cmdk, vaul, sonner, "
     "tanstack-table, react-hook-form + zod, date-fns, maplibre, uppy: pinned, validated, "
     "repaired like today's allowlist. From the architecture plan."),
    ("PC-063", "Android emulator preview without Android Studio: SDK command-line bootstrap, "
     "headless emulator, auto-install, streamed into the Studio", "1 Vibe Mode live", "Both",
     "Not Started", "P1", "", "See NATIVE_MOBILE_PREVIEW_PLAN.md. Open source first; local "
     "on the founder's Mac, then hosted in PC-065. Covers R-052."),
    # Phase 2 - Maximum features
    ("R-582", "Smarter IR synthesis: multi-pass planning and self-critique before generation",
     "2 Maximum features", "Both", "Not Started", "P1", "", "Where 'more features per prompt' is won."),
    ("R-580", "Domain knowledge in ecosystem detection ('logistics' implies drivers)",
     "2 Maximum features", "Both", "Not Started", "P1", "", ""),
    ("R-570", "Permissions beyond role: ownership and row-level rules", "2 Maximum features",
     "Both", "Not Started", "P1", "", "'A driver sees only their own orders'."),
    ("R-567", "Money: ledgers, payments, payouts, refunds, commission", "2 Maximum features",
     "Both", "Not Started", "P1", "", "R-512 gives Stripe/Razorpay checkout; this is the ledger."),
    ("R-568", "Background jobs and scheduling", "2 Maximum features", "Both", "Not Started", "P1",
     "", ""),
    ("R-569", "Realtime channels: tracking, notifications, live status", "2 Maximum features",
     "Both", "Not Started", "P1", "", ""),
    ("R-571", "Escape hatch: behaviour the IR declares and the model implements, verified",
     "2 Maximum features", "Both", "Not Started", "P1", "R-560", "No hard ceiling, only a typed boundary."),
    ("PC-016", "Edit a workflow by chat (add/rename states and transitions safely)",
     "2 Maximum features", "Both", "Not Started", "P1", "R-584, R-590", ""),
    ("R-572", "Shared contract package: one generated packages/ for types, client, validation",
     "2 Maximum features", "Both", "Not Started", "P1", "",
     "Covers R-116, R-127, R-137, R-143, R-152 and pack-framework 06d."),
    ("R-585", "Template customisation as a first-class flow", "2 Maximum features", "Both",
     "Not Started", "P1", "R-584", ""),
    ("PC-017", "Pack framework core: manifest v2 schema, registry/loader, composer (merge, "
     "wire, validate, conflict rules)", "2 Maximum features", "Both", "Pending", "P1", "R-572",
     "Solution Pack manifests, registry and application exist (R-434..R-445); v2 adds ir_delta, "
     "state machines, page templates, dependencies. From specs/pack-framework 01, 02."),
    ("PC-075", "Role-based app generator: a complete app per role (nav, pages, API scope, "
     "permissions)", "2 Maximum features", "Both", "Pending", "P1", "PC-017, R-570",
     "R-555/R-562 already build one app per role; the spec asks for role-scoped pages and "
     "APIs. From specs/pack-framework/06b."),
    ("PC-076", "Page template engine: domain pages from templates with IR slots (dispatch "
     "board, SOAP notes ...)", "2 Maximum features", "Both", "Not Started", "P1", "PC-017",
     "From specs/pack-framework/06c."),
    ("PC-077", "Rich seed data generator: realistic, domain-aware, deterministic demo data",
     "2 Maximum features", "Both", "Pending", "P2", "PC-017",
     "Fixture seeds exist (R-248) and must stay deterministic (R-586). From "
     "specs/pack-framework/06e."),
    ("PC-072", "Blueprint conversion: turn RideNow, Bazaar and CareClinic templates into "
     "blueprints that regenerate them (golden-file test)", "2 Maximum features", "Both",
     "Not Started", "P1", "PC-017, PC-075, PC-076", "From specs/pack-framework/05."),
    ("PC-088", "Pack quality bar: a pack counts as done only when it builds a working demo app on "
     "every surface, passes its generated tests and passes a UI review",
     "2 Maximum features", "Both", "Not Started", "P1", "PC-017, PC-054",
     "321 packs: a mediocre pack hurts more than a missing one. Applies to every wave. "
     "Founder-approved 2026-09-26."),
    ("PC-073", "Horizontal packs, wave 1: the P0/P1 universal packs as manifest v2 packs that "
     "work alone and compose (HP-* rows)", "2 Maximum features", "Both", "Pending", "P1",
     "PC-017", "Core first (auth, database, API, design system, admin, payments, notifications, "
     "files, realtime, workflows), then the mobile & device and AI packs. Each pack packages a "
     "capability built by its own task. Full list: PACK_CATALOG.md."),
    ("PC-074", "Vertical packs, wave 1: healthcare, mobility, commerce (VP-* rows) on every "
     "surface: API, web, app, admin panel", "2 Maximum features", "Both", "Pending", "P1",
     "PC-073, PC-072", "Built from the CareClinic, RideNow and Bazaar templates."),
    ("PC-078", "Horizontal packs, wave 2 (P2 HP-* rows)", "2 Maximum features", "Both",
     "Not Started", "P2", "PC-073", "Full list: PACK_CATALOG.md."),
    ("PC-080", "Vertical packs, wave 2: the PRD's blueprints (quick commerce, fintech, food, "
     "real estate, edtech, SaaS/B2B, logistics, home services, beauty & wellness, HR) on every "
     "surface", "2 Maximum features", "Both", "Not Started", "P2", "PC-074",
     "Each domain's templates (Pocket, FreshCart, Estately, LearnHub, FixIt, Glow) showcase it."),
    ("PC-079", "Horizontal packs, wave 3 (P3 HP-* rows)", "2 Maximum features", "Both",
     "Not Started", "P3", "PC-078", "Full list: PACK_CATALOG.md."),
    ("PC-081", "Vertical packs, wave 3: 16 further industries (professional services, content, "
     "travel, events, fitness, social, insurance, automotive, POS, manufacturing, legal, civic, "
     "utilities, pets, schools, construction, agriculture) on every surface",
     "2 Maximum features", "Both", "Not Started", "P3", "PC-080",
     "One industry at a time, ordered by what users actually build."),
    ("PC-018", "Template marketplace v2: blueprint catalog and pack publishing",
     "2 Maximum features", "Vibe", "Not Started", "P2", "PC-017",
     "From specs/template-marketplace/01."),
    ("TPL-POCKET", "Template: Pocket, digital wallet (fintech)", "2 Maximum features", "Vibe",
     "Not Started", "P2", "R-567", "Template plan section 6.3."),
    ("TPL-LEARNHUB", "Template: LearnHub, LMS + course marketplace", "2 Maximum features",
     "Vibe", "Not Started", "P2", "", "Template plan section 6.4."),
    ("TPL-GLOW", "Template: Glow, salon and spa booking", "2 Maximum features", "Vibe",
     "Not Started", "P3", "", "Template plan section 6.5."),
    ("TPL-FRESHCART", "Template: FreshCart, quick-commerce grocery", "2 Maximum features",
     "Vibe", "Not Started", "P3", "R-569", "Template plan section 6.6."),
    ("TPL-ESTATELY", "Template: Estately, property marketplace + agent CRM",
     "2 Maximum features", "Vibe", "Not Started", "P3", "", "Template plan section 6.7."),
    ("TPL-FIXIT", "Template: FixIt, home-services marketplace", "2 Maximum features", "Vibe",
     "Not Started", "P3", "", "Template plan section 6.8."),
    ("TPL-INKWELL", "Template: Inkwell Press, blogging/publishing", "2 Maximum features",
     "Vibe", "Not Started", "P3", "", "Template plan section 6.9."),
    ("PC-019", "Visual click-to-edit in the preview (design tokens and copy only)",
     "2 Maximum features", "Vibe", "Not Started", "P2", "", "Buildout plan idea 'R-520'."),
    ("PC-020", "Brand kit / Style DNA UI across all surfaces", "2 Maximum features", "Vibe",
     "Pending", "P2", "", "brand.json exists (R-548); needs the UI. Buildout idea 'R-526'."),
    ("PC-021", "Screenshot or Figma to app", "2 Maximum features", "Vibe", "Not Started", "P3",
     "", "Buildout idea 'R-527'."),
    ("PC-048", "Database choice: MongoDB as an option beside PostgreSQL (the default)",
     "2 Maximum features", "Both", "Not Started", "P2", "R-570",
     "D-8. Every backend adapter needs a Mongo data layer; lifecycle and uniqueness rules move "
     "from SQL constraints to schema validation and indexes. Lifts the Phase T 'PostgreSQL "
     "only' gate. Covers R-075."),
    ("PC-052", "File uploads and storage in generated apps (S3-compatible, presigned URLs, "
     "image processing)", "2 Maximum features", "Both", "Not Started", "P1", "",
     "Local MinIO-style store for dev; any S3 provider on publish. From the architecture plan."),
    ("PC-053", "Notifications in generated apps: email, push (Expo and native), in-app, "
     "user preferences", "2 Maximum features", "Both", "Not Started", "P1", "R-568",
     "R-516 gives email. From the architecture plan."),
    ("PC-054", "Tests generated with every app: API contract, end-to-end (Playwright), unit",
     "2 Maximum features", "Both", "Not Started", "P1", "",
     "Architecture-plan target: over 80% coverage of generated code."),
    ("PC-059", "Form and wizard engine: multi-step, conditional fields, draft autosave",
     "2 Maximum features", "Both", "Not Started", "P2", "", "From the architecture plan."),
    ("PC-057", "Generated-app operations: rate limiting, signed webhooks with retries, audit "
     "log, error tracking and tracing hooks", "2 Maximum features", "Both", "Not Started", "P2",
     "", "From the architecture plan (api-gateway, webhooks, audit, observability packs)."),
    ("PC-055", "Internationalisation in generated apps (web, admin, mobile)",
     "2 Maximum features", "Both", "Not Started", "P2", "", "From the architecture plan."),
    ("PC-064", "iOS Simulator preview: Xcode installed and driven from the command line, "
     "simulator streamed into the Studio (Mac only)", "2 Maximum features", "Both",
     "Not Started", "P2", "PC-063", "See NATIVE_MOBILE_PREVIEW_PLAN.md. No open-source iOS "
     "simulator exists; Xcode is free but Mac-only. Covers R-053."),
    ("PC-056", "Feature flags and A/B tests in generated apps", "2 Maximum features", "Both",
     "Not Started", "P3", "", "From the architecture plan."),
    ("PC-058", "Search engine option (Meilisearch or Typesense) beyond keyword search",
     "2 Maximum features", "Both", "Not Started", "P3", "", "From the architecture plan."),
    ("R-583", "Next.js static export mode", "2 Maximum features", "Both", "Not Started", "P3", "",
     "The cheap answer to 'no SSR, no Vercel'."),
    # Phase 3 - Engineering Mode
    ("PC-022", "Plan view: see and edit the plan (apps, roles, entities, flows) before building",
     "3 Engineering Mode", "Engineering", "Not Started", "P1", "PC-005",
     "Buildout idea 'intent cards'; specs/engineering-mode/01."),
    ("PC-023", "Stack chooser: pick web/admin/mobile/backend, refused with a reason when "
     "unsupported", "3 Engineering Mode", "Engineering", "Pending", "P1", "PC-005",
     "R-565 carries the stack in the IR; needs the UI. Covers R-135."),
    ("R-577", "Agentic mode core: plan -> edit files -> verify -> repair, bounded, auditable",
     "3 Engineering Mode", "Engineering", "Not Started", "P1", "",
     "Covers R-042, R-176..R-180, R-183, R-184, R-185."),
    ("R-578", "Import an existing local project (agentic mode, not IR mode)",
     "3 Engineering Mode", "Engineering", "Not Started", "P1", "R-577",
     "Covers R-076, R-018, specs/repo-intelligence, specs/studio-ux/02."),
    ("R-579", "GitHub import and push-back", "3 Engineering Mode", "Engineering", "Pending", "P1",
     "R-578", "R-501 can push a generated project; import is missing."),
    ("PC-024", "Diff review per change, with change impact / blast radius", "3 Engineering Mode",
     "Engineering", "Not Started", "P1", "R-577",
     "Covers R-016, R-017 and T-5 (editable code, diff view, API explorer)."),
    ("PC-025", "Verification report view: per-surface compile, tests, security, in the Studio",
     "3 Engineering Mode", "Engineering", "Pending", "P1", "",
     "R-560/R-561/R-508 produce the data; nothing shows it as a report."),
    ("PC-026", "Open GitHub pull requests (branch per change, PR naming)", "3 Engineering Mode",
     "Engineering", "Not Started", "P1", "R-579", "Covers R-021, R-125."),
    ("R-581", "Memory across sessions: semantic project memory on pgvector", "3 Engineering Mode",
     "Both", "Not Started", "P1", "", "Covers R-019, R-027, R-057."),
    ("PC-027", "Version timeline and safe, non-destructive rollback", "3 Engineering Mode",
     "Both", "Not Started", "P1", "", "Covers R-022 and buildout idea 'R-524'."),
    ("PC-051", "Graduation bridge: open a Vibe project in Engineering Mode with nothing lost, "
     "and back", "3 Engineering Mode", "Both", "Not Started", "P1", "PC-005, PC-022",
     "Projects already keep ir.json, so the IR carries over; custom UI and history must too. "
     "From the architecture plan."),
    ("PC-028", "Cloud deploy adapters beyond Vercel/Netlify: containers, Kubernetes (Helm), "
     "Terraform", "3 Engineering Mode",
     "Engineering", "Not Started", "P2", "PC-008", "From specs/deploy-adapters/01 and the "
     "architecture plan."),
    ("PC-029", "Team collaboration: roles, approvals, preview comments", "3 Engineering Mode",
     "Engineering", "Pending", "P2", "", "R-515 gives teams. Covers R-064, R-065."),
    ("PC-030", "Tool registry and MCP gateway with a tool secret broker", "3 Engineering Mode",
     "Engineering", "Not Started", "P2", "R-577", "Covers R-185, R-186, R-187."),
    # Phase 4 - Production ops
    ("PC-031", "Backup, restore drills and disaster recovery", "4 Production ops", "Platform",
     "Not Started", "P1", "PC-009", "Covers R-096, R-097."),
    ("PC-032", "Security audits: independent pen test, DAST, prompt-injection and MCP isolation "
     "tests", "4 Production ops", "Platform", "Not Started", "P1", "PC-009",
     "Covers R-098, R-069, R-213."),
    ("PC-033", "Observability: platform logs, metrics, task trace, SLOs, incident process",
     "4 Production ops", "Platform", "Not Started", "P1", "PC-009",
     "Covers R-044, R-043, R-094, R-102."),
    ("PC-034", "Load and capacity tests", "4 Production ops", "Platform", "Not Started", "P1",
     "PC-009", "Covers R-103."),
    ("PC-035", "Compliance: SOC 2 readiness, SBOM + licence gate, OSS licence review",
     "4 Production ops", "Platform", "Not Started", "P2", "",
     "Covers R-099, R-070, R-219, R-190, R-154."),
    ("PC-036", "Migration safety checks for generated schema changes", "4 Production ops",
     "Both", "Pending", "P1", "", "R-584 flags data loss; needs a real gate. Covers R-040."),
    ("PC-037", "Release quality: qualification suite, API contract tests, visual regression, "
     "performance budgets", "4 Production ops", "Platform", "Not Started", "P2", "",
     "Covers R-105, R-039, R-059, R-060."),
    ("PC-038", "Reliability of runs: crash-resume, no duplicate side effects, stream replay",
     "4 Production ops", "Platform", "Not Started", "P2", "R-577",
     "Covers R-210, R-211, R-212, R-182, R-216."),
    ("PC-039", "Unit economics dashboard", "4 Production ops", "Platform", "Not Started", "P2",
     "PC-010", "Covers R-110."),
    ("PC-040", "Environments per project (dev / preview / prod)", "4 Production ops", "Both",
     "Not Started", "P2", "", "Covers R-126 (org and workspace parts exist)."),
    ("PC-065", "Hosted Android emulators for every user: Linux + KVM pool, per-session "
     "isolation, browser streaming, metering", "4 Production ops", "Both", "Not Started", "P2",
     "PC-009, PC-063", "See NATIVE_MOBILE_PREVIEW_PLAN.md. Built and proven on a local Linux "
     "VM; the server account is plugged in at PC-070."),
    ("PC-067", "Production readiness sign-off: every blocking gate PG-01..PG-21 has evidence",
     "4 Production ops", "Platform", "Not Started", "P1", "PC-031..PC-041",
     "The tracker's Production_Gates sheet. The platform is not called production-ready "
     "before this."),
    ("PC-041", "HA control plane and canary platform releases", "4 Production ops", "Platform",
     "Not Started", "P2", "PC-009", "Covers R-095, R-106."),
    # Phase 5 - Native, last
    ("PC-042", "Native go-ahead gate: founder approval, toolchains, Apple and Google accounts",
     "5 Native mobile (last)", "Both", "Not Started", "P2", "Phases 1-4",
     "Standing rule: stop and ask before native mobile work."),
    ("R-575", "Native Android: Kotlin + Jetpack Compose, best in class", "5 Native mobile (last)",
     "Both", "Not Started", "P2", "PC-042",
     "Covers R-144, R-145, R-035, specs/native-mobile."),
    ("R-576", "Native iOS: Swift + SwiftUI, best in class", "5 Native mobile (last)", "Both",
     "Not Started", "P2", "PC-042", "Covers R-146, R-147, R-036, R-010."),
    ("PC-043", "Native recommendation: when to offer native instead of PWA", "5 Native mobile (last)",
     "Both", "Not Started", "P2", "R-575, R-576", "Covers R-120."),
    ("PC-044", "Signed native builds (AAB/IPA), signing-key hardening, and store submission "
     "through the R-574 pipeline", "5 Native mobile (last)",
     "Both", "Not Started", "P2", "R-575, R-576", "Covers R-049, R-050, R-101."),
    ("PC-082", "Native implementations of every mobile & device pack and every vertical pack's "
     "app screens in Kotlin/Compose and Swift/SwiftUI", "5 Native mobile (last)", "Both",
     "Not Started", "P2", "R-575, R-576", "PRD §5.1: packs are stack-aware; React Native "
     "implementations come first with the pack itself."),
    ("PC-045", "Native modules and PWA-to-native migration", "5 Native mobile (last)", "Both",
     "Not Started", "P3", "R-575, R-576", "Covers R-163, R-165."),
    ("PC-066", "Hosted iOS simulators on Mac hosts (on demand, metered)", "5 Native mobile (last)",
     "Both", "Not Started", "P3", "PC-064", "Apple allows macOS only on Apple hardware, so this "
     "needs Mac servers. See NATIVE_MOBILE_PREVIEW_PLAN.md."),
    ("PC-046", "Local Mac agent for iOS builds and simulators", "5 Native mobile (last)",
     "Engineering", "Not Started", "P3", "R-576", "Covers R-054, R-161."),
    # Phase 6 - Go-live: the founder supplies accounts and keys at the very end
    ("PC-070", "Credentials handover: founder supplies cloud, database, payment, email, Apple "
     "and Google accounts and keys; each is plugged in without code changes",
     "6 Go-live (credentials last)", "Platform", "Not Started", "P0", "Phases 1-5",
     "Everything before this is built so that only keys and secrets are missing. Keys go into "
     "the secrets store (R-503) or .env, never into code, prompts or logs. D-2, D-3, D-6, D-7."),
    ("PC-071", "Live proof of every 'Completed - needs live proof' item with the real accounts",
     "6 Go-live (credentials last)", "Platform", "Not Started", "P0", "PC-070",
     "Publish to a real URL, a real payment, a real email, EAS/store uploads to both stores."),
    ("PC-015", "Private beta with real users: product KPIs, minimal support tooling, feedback",
     "6 Go-live (credentials last)", "Platform", "Not Started", "P0", "PC-071",
     "Covers R-051, R-107. The platform is not 'live' until strangers use it."),
    # Phase 7 - Win the category (last, by founder decision 2026-09-26)
    ("PC-083", "Head-to-head benchmark: the same 20 prompts on OmniStackAI, Lovable, Bolt, v0, "
     "Emergent and Replit; score UI quality, working features, build success and time",
     "7 Win the category", "Both", "Not Started", "P1", "PC-015",
     "Without measurement 'best' is an opinion. Re-run every quarter (PC-087)."),
    ("PC-089", "Win on UI polish and speed against Lovable, Bolt and v0: iterate on the benchmark "
     "until we lead it", "7 Win the category", "Vibe", "Not Started", "P1", "PC-083, PC-084",
     "Their whole focus, improved weekly; matching needs features, beating needs measurement."),
    ("PC-090", "Engineering Mode positioning and proof: 'designs and builds structured multi-app "
     "platforms with verification', benchmarked against Cursor, Claude Code, Codex and Devin "
     "on platform-building tasks", "7 Win the category", "Engineering", "Not Started", "P1",
     "PC-083", "We do not try to be a better general code editor; we win where they do not "
     "compete: whole platforms from a plan, verified."),
    ("PC-091", "Native lead: match or beat the native Swift/Kotlin builders on quality and speed",
     "7 Win the category", "Both", "Not Started", "P2", "R-575, R-576, PC-083",
     "Some builders already generate native apps; ours arrives in Phase 5."),
    ("PC-086", "Public launch: docs site, tutorials and videos, pricing page, community, launch "
     "campaign", "7 Win the category", "Platform", "Not Started", "P1", "PC-015",
     "The plan otherwise stops at a private beta."),
    ("PC-092", "Users and brand: growth loops (referrals, template showcase, made-with gallery), "
     "partnerships, content, measured activation and retention", "7 Win the category",
     "Platform", "Not Started", "P1", "PC-086",
     "Competitors already have millions of users."),
    ("PC-087", "Quarterly competitor review: re-run the benchmark, update the plan and this queue",
     "7 Win the category", "Platform", "Not Started", "P2", "PC-083",
     "Recurring; competitors ship weekly."),
]

# --- Tracker items that are not Done in the v6 tracker ----------------------------------------
# id -> (status, priority, tracked_in, note). Tracker items marked Done there are Completed.

C, S, D, X, P, N = "Completed", "Superseded", "Deferred", "Dropped", "Pending", "Not Started"

TRACKER = {
    "R-010": (S, "", "R-576", "Native iOS is built by the R-576 adapter, not a separate agent."),
    "R-011": (S, "", "R-227", "IR + deterministic adapters replaced per-surface agents."),
    "R-012": (S, "", "R-229", "Python/Go/Node backend adapters."),
    "R-013": (S, "", "R-238", "Schema and migrations generated from the IR."),
    "R-014": (S, "", "R-560", "Compile-verify-repair loop in the build path."),
    "R-015": (S, "", "R-508", "Security scanning and automated tests."),
    "R-016": (N, "P1", "PC-024", ""),
    "R-017": (N, "P1", "PC-024", ""),
    "R-018": (N, "P1", "R-578", ""),
    "R-019": (N, "P1", "R-581", ""),
    "R-020": (C, "", "R-237", "IR diff -> patch (R-237, R-246, R-584)."),
    "R-021": (N, "P1", "PC-026", ""),
    "R-022": (N, "P1", "PC-027", ""),
    "R-023": (C, "", "R-005", "Model gateway (R-005..R-009)."),
    "R-024": (C, "", "R-221", "Routing, fallback, circuit breaker (R-007, R-221, R-223)."),
    "R-025": (N, "P0", "PC-010", "Usage and cost are recorded; no per-task budget."),
    "R-026": (C, "", "R-002", "PostgreSQL."),
    "R-027": (P, "P1", "R-581", "Extension installed, no embeddings table."),
    "R-028": (D, "P3", "", "Redis: no need until load says so."),
    "R-029": (D, "P3", "", "NATS / managed queue: no need yet."),
    "R-030": (D, "P2", "", "Object storage: needed when generated apps store files at scale."),
    "R-031": (C, "", "R-486", "Sandbox drivers (R-486..R-489)."),
    "R-032": (C, "", "R-503", "Encrypted per-project secrets."),
    "R-033": (C, "", "R-421", "Studio preview."),
    "R-034": (C, "", "R-500", "Multi-process preview."),
    "R-035": (N, "P2", "R-575", ""),
    "R-036": (N, "P2", "R-576", ""),
    "R-037": (C, "", "", "Offline test suite runs in every gate."),
    "R-038": (C, "", "", "scripts/verify.sh gate and CI."),
    "R-039": (N, "P2", "PC-037", "OpenAPI exists (R-260); no contract tests."),
    "R-040": (P, "P1", "PC-036", ""),
    "R-041": (C, "", "R-508", "Plus scripts/security-quick.sh."),
    "R-042": (N, "P1", "R-577", ""),
    "R-043": (N, "P2", "PC-033", ""),
    "R-044": (N, "P1", "PC-033", ""),
    "R-045": (C, "", "R-472", "Credit ledger with real cost debiting."),
    "R-046": (N, "P0", "PC-010", ""),
    "R-047": (N, "P0", "PC-010", ""),
    "R-048": ("Completed - needs live proof", "P0", "PC-008", "R-509 publish."),
    "R-049": (N, "P2", "PC-044", ""),
    "R-050": (N, "P2", "PC-044", ""),
    "R-051": (N, "P0", "PC-015", ""),
    "R-052": (N, "P1", "PC-063", "Android emulator streaming (founder asked for it)."),
    "R-053": (N, "P2", "PC-064", "iOS Simulator streaming."),
    "R-054": (N, "P3", "PC-046", ""),
    "R-055": (P, "P1", "PC-013", ""),
    "R-056": (N, "P1", "PC-013", ""),
    "R-057": (N, "P1", "R-581", ""),
    "R-058": (D, "P3", "", "Language-specific structured editors."),
    "R-059": (N, "P2", "PC-037", ""),
    "R-060": (N, "P2", "PC-037", ""),
    "R-061": (D, "P3", "", ""),
    "R-062": (P, "P1", "R-574", "React Native first; native reuses the pipeline (PC-044)."),
    "R-063": (P, "P1", "R-574", "React Native first; native reuses the pipeline (PC-044)."),
    "R-064": (P, "P2", "PC-029", ""),
    "R-065": (N, "P2", "PC-029", ""),
    "R-066": (C, "", "R-504", "BYOK."),
    "R-067": (C, "", "R-560", "Hybrid repair loop (R-466, R-560)."),
    "R-068": (D, "P3", "", "Project health score."),
    "R-069": (N, "P1", "PC-032", ""),
    "R-070": (N, "P2", "PC-035", ""),
    "R-071": (N, "P0", "PC-009", ""),
    "R-072": (D, "P3", "", "Build artifact caching."),
    "R-073": (D, "P3", "", "Incremental test selection."),
    "R-074": (C, "", "R-565", "Python, Go, Node backends (R-229, R-230, R-517, R-565)."),
    "R-075": (N, "P2", "PC-048", "MongoDB as an option (D-8)."),
    "R-076": (N, "P1", "R-578", ""),
    "R-077": (X, "", "", "Flutter: removed by the stack policy."),
    "R-078": (C, "", "R-514", "React Native (Expo) is a default for app requests (D-5)."),
    "R-079": (D, "P3", "", ""),
    "R-080": (P, "P1", "PC-014", "Ollama adapter exists (R-003, R-006)."),
    "R-111": (S, "", "R-514", ""),
    "R-112": (C, "", "R-559", "resolve_stack recommends and substitutes with a reason."),
    "R-113": (C, "", "R-559", ""),
    "R-114": (C, "", "R-565", ""),
    "R-115": (C, "", "R-559", "AdapterRegistry."),
    "R-116": (N, "P1", "R-572", ""),
    "R-117": (C, "", "R-227", ""),
    "R-118": (X, "", "", "Flutter Web: removed by the stack policy."),
    "R-119": (X, "", "", "React Native Web: removed by the stack policy."),
    "R-120": (N, "P2", "PC-043", ""),
    "R-121": (C, "", "R-001", ""),
    "R-122": (C, "", "R-228", ""),
    "R-123": (C, "", "R-554", ""),
    "R-124": (D, "P3", "", "Repository naming convention."),
    "R-125": (N, "P1", "PC-026", ""),
    "R-126": (P, "P2", "PC-040", "Org, workspace and project exist (R-499, R-515)."),
    "R-127": (N, "P1", "R-572", "packages/contracts is an empty folder."),
    "R-128": (C, "", "", "Taskfile.yml orchestrates Go, Python and Node."),
    "R-129": (D, "P3", "", ""),
    "R-131": (D, "P3", "", "CODEOWNERS + protected paths."),
    "R-132": (S, "", "R-232", "Adapters generate the project; no separate repo templates."),
    "R-133": (C, "", "R-563", "Ecosystem edits (R-563, R-584)."),
    "R-134": (D, "P3", "", ""),
    "R-135": (P, "P1", "PC-023", ""),
    "R-136": (S, "", "R-559", ""),
    "R-137": (N, "P1", "R-572", ""),
    "R-138": (C, "", "R-232", ""),
    "R-139": (C, "", "R-552", "Generated README and run plan."),
    "R-140": (X, "", "", "Flutter: removed by the stack policy."),
    "R-141": (X, "", "", "Flutter: removed by the stack policy."),
    "R-142": (C, "", "R-514", ""),
    "R-143": (N, "P1", "R-572", ""),
    "R-144": (N, "P2", "R-575", ""),
    "R-145": (N, "P2", "R-575", ""),
    "R-146": (N, "P2", "R-576", ""),
    "R-147": (N, "P2", "R-576", ""),
    "R-148": (C, "", "R-227", ""),
    "R-149": (C, "", "R-542", ""),
    "R-150": (C, "", "R-230", ""),
    "R-151": (C, "", "R-229", ""),
    "R-152": (N, "P1", "R-572", ""),
    "R-153": (C, "", "R-519", ""),
    "R-154": (N, "P2", "PC-035", ""),
    "R-155": (C, "", "R-004", ""),
    "R-156": (C, "", "R-472", ""),
    "R-157": (D, "P3", "", "services/runner-manager is empty; sandbox drivers cover it for now."),
    "R-158": (C, "", "", ".github/workflows/ci.yml runs scripts/verify.sh."),
    "R-159": (D, "P3", "", ""),
    "R-160": (D, "P3", "", ""),
    "R-161": (N, "P3", "PC-046", ""),
    "R-162": (D, "P3", "", ""),
    "R-163": (N, "P3", "PC-045", ""),
    "R-164": (D, "P3", "", ""),
    "R-165": (N, "P3", "PC-045", ""),
    "R-169": (D, "P3", "", ""),
    "R-170": (D, "P3", "", ""),
    "R-171": (C, "", "R-486", ""),
    "R-172": (C, "", "R-486", ""),
    "R-173": (C, "", "R-490", ""),
    "R-174": (N, "P0", "PC-007", ""),
    "R-175": (N, "P0", "PC-009", ""),
    "R-176": (N, "P1", "R-577", ""),
    "R-177": (N, "P1", "R-577", ""),
    "R-178": (N, "P1", "R-577", ""),
    "R-179": (N, "P1", "R-577", ""),
    "R-180": (N, "P1", "R-577", ""),
    "R-181": (C, "", "R-484", "SSE build streaming."),
    "R-182": (N, "P2", "PC-038", ""),
    "R-183": (N, "P1", "R-577", ""),
    "R-184": (N, "P1", "R-577", ""),
    "R-185": (N, "P2", "PC-030", ""),
    "R-186": (N, "P2", "PC-030", ""),
    "R-187": (N, "P2", "PC-030", ""),
    "R-188": (X, "", "", "BaaS profile: generated apps own a real API + DB."),
    "R-189": (D, "P3", "", ""),
    "R-190": (N, "P2", "PC-035", ""),
    "R-191": (D, "P3", "", ""),
    "R-192": (D, "P3", "", ""),
    "R-193": (D, "P3", "", "The platform already runs locally."),
    "R-194": (P, "P1", "PC-014", ""),
    "R-195": (C, "", "R-487", ""),
    "R-196": (D, "P3", "", ""),
    "R-197": (D, "P3", "", ""),
    "R-198": (D, "P3", "", ""),
    "R-199": (D, "P3", "", ""),
    "R-200": (X, "", "", "BaaS expansion: see R-188."),
    "R-210": (N, "P2", "PC-038", ""),
    "R-211": (N, "P2", "PC-038", ""),
    "R-212": (N, "P2", "PC-038", ""),
    "R-213": (N, "P1", "PC-032", ""),
    "R-214": (N, "P0", "PC-009", ""),
    "R-215": (D, "P3", "", ""),
    "R-216": (N, "P2", "PC-038", ""),
    "R-217": (X, "", "", "BaaS migration: see R-188."),
    "R-218": (D, "P3", "", ""),
    "R-219": (N, "P2", "PC-035", ""),
    "R-224": (S, "", "R-470", "The Next.js console shipped in R-470 and R-491..R-497."),
    "R-462": (C, "", "", "Status was blank in the tracker; it is in CHANGELOG."),
    "R-094": (N, "P1", "PC-033", ""),
    "R-095": (N, "P2", "PC-041", ""),
    "R-096": (N, "P1", "PC-031", ""),
    "R-097": (N, "P1", "PC-031", ""),
    "R-098": (N, "P1", "PC-032", ""),
    "R-099": (N, "P2", "PC-035", ""),
    "R-100": (N, "P0", "PC-009", ""),
    "R-101": (N, "P2", "PC-044", ""),
    "R-102": (N, "P2", "PC-033", ""),
    "R-103": (N, "P1", "PC-034", ""),
    "R-104": (N, "P0", "PC-010", ""),
    "R-105": (N, "P2", "PC-037", ""),
    "R-106": (N, "P2", "PC-041", ""),
    "R-107": (N, "P0", "PC-015", ""),
    "R-108": (N, "P0", "PC-012", ""),
    "R-109": (N, "P0", "PC-011", ""),
    "R-110": (N, "P2", "PC-039", ""),
}
# ADVANCED-phase ideas not listed above are deferred until after launch.
for _id in ("R-081", "R-082", "R-083", "R-084", "R-085", "R-086", "R-087", "R-088", "R-089",
            "R-090", "R-091", "R-092", "R-093", "R-130", "R-166", "R-167", "R-168", "R-201",
            "R-202", "R-203", "R-204", "R-205", "R-206", "R-207", "R-208", "R-209"):
    TRACKER.setdefault(_id, (D, "P3", "", "Advanced / enterprise: after launch."))

# Completed in CHANGELOG but only in code, never run against a real external account.
NEEDS_LIVE_PROOF = {
    "R-509": "PC-008", "R-510": "PC-008", "R-511": "PC-013", "R-512": "R-567",
    "R-513": "PC-015", "R-516": "PC-012", "R-546": "R-574",
}

# --- Other R_&_D sources (specs, plans, gap analysis) ------------------------------------------
# (id, title, source, status, priority, tracked_in, note)

OTHER = [
    ("SPEC-VIBE-01", "Vibe Mode Pro: AI builds it with a real backend",
     "specs/vibe-mode-pro/01", N, "P0", "PC-004", "Draft spec."),
    ("SPEC-STUDIO-01", "Unified Studio UX: mode-aware interface", "specs/studio-ux/01", N, "P0",
     "PC-005", "Draft spec."),
    ("SPEC-STUDIO-02", "Existing repo import + edit (both modes)", "specs/studio-ux/02", N, "P1",
     "R-578", "Draft spec."),
    ("SPEC-TS-01", "Instant chat -> pretty UI", "specs/table-stakes/01", P, "P0", "PC-006",
     "Draft spec."),
    ("SPEC-TS-02", "Live in-browser preview", "specs/table-stakes/02", N, "P0", "PC-007",
     "Draft spec."),
    ("SPEC-TS-03", "One-click deploy", "specs/table-stakes/03", P, "P0", "PC-008", "Draft spec."),
    ("SPEC-ENG-01", "Multi-app architect (Engineering Mode core)", "specs/engineering-mode/01", N,
     "P1", "PC-022", "Draft spec."),
    ("SPEC-REPO-01", "Repo intelligence: import, analyse, edit", "specs/repo-intelligence/01", N,
     "P1", "R-578", "Draft spec."),
    ("SPEC-DEPLOY-01", "Cloud deploy adapters", "specs/deploy-adapters/01", N, "P2", "PC-028",
     "Draft spec."),
    ("SPEC-NATIVE-01", "True native mobile (Kotlin/Compose + Swift/SwiftUI)",
     "specs/native-mobile/01", N, "P2", "R-575", "Draft spec. Covers R-575 and R-576."),
    ("SPEC-PACK-01", "Pack manifest v2 schema", "specs/pack-framework/01", P, "P1", "PC-017",
     "Draft spec (called R-600 inside)."),
    ("SPEC-PACK-02", "Pack composer: merge, wire, validate", "specs/pack-framework/02", N, "P1",
     "PC-017", "Draft spec."),
    ("SPEC-PACK-03", "Horizontal packs registry (the spec says 30; its table lists 31)", "specs/pack-framework/03", N, "P1",
     "PC-073", "Draft spec."),
    ("SPEC-PACK-04", "MVP vertical packs (first 10)", "specs/pack-framework/04", N, "P1",
     "PC-074", "Draft spec."),
    ("SPEC-PACK-05", "Blueprint structure and template-to-blueprint conversion",
     "specs/pack-framework/05", N, "P1", "PC-072", "Draft spec."),
    ("SPEC-PACK-06A", "State machine codegen", "specs/pack-framework/06a", S, "", "R-566",
     "Delivered by R-566, R-588, R-589."),
    ("SPEC-PACK-06B", "Role-based app generator", "specs/pack-framework/06b", P, "P1", "PC-075",
     "R-555 and R-562 build one app per role; the spec asks for more."),
    ("SPEC-PACK-06C", "Page template engine", "specs/pack-framework/06c", N, "P1", "PC-076",
     "Draft spec."),
    ("SPEC-PACK-06D", "Shared package generator", "specs/pack-framework/06d", N, "P1", "R-572",
     "Draft spec."),
    ("SPEC-PACK-06E", "Rich seed data generator", "specs/pack-framework/06e", P, "P2", "PC-077",
     "Seeds exist (R-248); the spec asks for realistic volume."),
    ("SPEC-TPL-01", "Template marketplace: blueprint catalog and pack publishing",
     "specs/template-marketplace/01", N, "P2", "PC-018", "Draft spec."),
    ("T-5", "Workspace upgrades: editable code, diff per edit, API explorer",
     "Template_Marketplace_Plan section 7", N, "P1", "PC-024", ""),
    ("PHASE-E", "Plan-gated features, credit top-up, super_admin console",
     "Commercial_Platform_Kickoff section 3", N, "P0", "PC-011", ""),
    ("MULTI-TENANT", "Per-user backend multi-tenancy of the Studio server",
     "Commercial_Platform_Kickoff section 3", N, "P0", "PC-009",
     "'A single trusted operator's tool that looks like a SaaS.'"),
    ("BP-INTENT", "Simple vs Pro mode and 'What I understood' intent cards",
     "Platform_Buildout section 8 ('R-519')", N, "P0", "PC-005",
     "The buildout plan's R-518..R-529 numbers were reused for other tasks."),
    ("BP-CLICKEDIT", "Visual click-to-edit mode", "Platform_Buildout section 8 ('R-520')", N, "P2",
     "PC-019", ""),
    ("BP-SWITCHER", "Multi-app ecosystem switcher and persona simulator",
     "Platform_Buildout section 8 ('R-521')", P, "P1", "PC-006",
     "Multi-app preview exists (R-520, R-553); personas do not."),
    ("BP-TURBO", "Instant preview preservation and fast-path edits",
     "Platform_Buildout section 8 ('R-522')", N, "P0", "PC-007", ""),
    ("BP-AUTOFIX", "Error detect -> fix -> verify -> retry loop",
     "Platform_Buildout section 8 ('R-523')", C, "", "R-560", "R-560, R-561."),
    ("BP-TIMELINE", "Version timeline and safe semantic undo",
     "Platform_Buildout section 8 ('R-524')", N, "P1", "PC-027", ""),
    ("BP-SHIPCHECK", "Pre-deployment 'safe to ship' health check",
     "Platform_Buildout section 8 ('R-525')", N, "P1", "PC-008", ""),
    ("BP-BRANDKIT", "Style DNA UI and brand kit studio",
     "Platform_Buildout section 8 ('R-526')", P, "P2", "PC-020", ""),
    ("BP-FIGMA", "Screenshot and Figma to app", "Platform_Buildout section 8 ('R-527')", N, "P3",
     "PC-021", ""),
    ("BP-COMMENTS", "Preview-pinned comments and @Omni threads",
     "Platform_Buildout section 8 ('R-528')", N, "P2", "PC-029", ""),
    ("BP-FLUTTER", "Flutter mobile adapter", "Platform_Buildout section 8 ('R-529')", X, "", "",
     "Removed by the stack policy."),
    ("GAP-TESTTOOLS", "Pin the testing toolchain (Playwright, pytest, go test, k6)",
     "V6_Review_and_Gap_Analysis section 3", P, "P2", "PC-037",
     "pytest/unittest, go test and Playwright (templates) are in use; k6 is not."),
    ("GAP-OPENAPI", "A worked OpenAPI contract example", "V6_Review_and_Gap_Analysis section 3", C,
     "", "R-260", "Every generated project ships openapi.json."),
    ("GAP-WIREFRAMES", "Console wireframes", "V6_Review_and_Gap_Analysis section 3", S, "",
     "R-491", "The console was built directly (R-491..R-497)."),
    ("GAP-LEGAL", "Legal layer: ToS, DPA, code-handling agreement",
     "V6_Review_and_Gap_Analysis section 3", N, "P0", "PC-012", ""),
    ("GAP-EVALS", "Model eval and benchmark suite for ai/evals",
     "V6_Review_and_Gap_Analysis section 3", N, "P2", "PC-014",
     "Needed to recommend a local model honestly."),
    ("ARCH-PACKS", "Pack manifest v2, composition engine, ~30 horizontal and ~80 vertical packs",
     "docs/ARCHITECTURE_MASTER_PLAN.md §4.2, §5.1, §10", N, "P1", "PC-073", ""),
    ("ARCH-VERTICALS", "Vertical packs for 10 domains (healthcare, mobility, commerce, fintech, food, real estate, education, SaaS, logistics, services)",
     "docs/ARCHITECTURE_MASTER_PLAN.md §5.1", N, "P2", "PC-074", ""),
    ("ARCH-PIPELINE", "Vibe pipeline: classify -> select packs -> compose IR -> generate -> provision -> preview in 90 s",
     "docs/ARCHITECTURE_MASTER_PLAN.md §4.1", P, "P0", "PC-004", "Generate and preview exist; provision is PC-049."),
    ("ARCH-SUPABASE", "Real managed database for Vibe apps (Supabase in the plan; any managed PostgreSQL here)",
     "docs/ARCHITECTURE_MASTER_PLAN.md §4.3", N, "P0", "PC-049", "The plan's Supabase Auth/Storage are replaced by the generated backend's own auth and PC-052."),
    ("ARCH-WEBCONTAINER", "WebContainer instant preview with a local Docker fallback",
     "docs/ARCHITECTURE_MASTER_PLAN.md §4.1, §11", N, "P0", "PC-007", ""),
    ("ARCH-ALLOWLIST", "Expanded LLM UI import allowlist",
     "docs/ARCHITECTURE_MASTER_PLAN.md §4.4", N, "P1", "PC-050", ""),
    ("ARCH-DOMAIN-IR", "Domain IR: guards, business rules, field masks, row filters, page templates",
     "docs/ARCHITECTURE_MASTER_PLAN.md §5.2", P, "P1", "R-570", "State machines done (R-566); field masks and row filters are R-570; guards and rules R-571."),
    ("ARCH-GENERATORS", "Advanced generators: state machine, role app, page template, shared package, seed data, form wizard, realtime",
     "docs/ARCHITECTURE_MASTER_PLAN.md §5.3", P, "P1", "PC-017", "State machine done (R-566/588/589); shared package R-572; form wizard PC-059; realtime R-569."),
    ("ARCH-GRADUATION", "Graduation bridge Vibe <-> Engineering",
     "docs/ARCHITECTURE_MASTER_PLAN.md §6", N, "P1", "PC-051", ""),
    ("ARCH-STUDIO-MODES", "Mode-aware Studio: Vibe shows only what matters, Engineering shows everything",
     "docs/ARCHITECTURE_MASTER_PLAN.md §7", N, "P0", "PC-005", ""),
    ("ARCH-ENG-OPTIONS", "Engineering options: IR editor, dependency graph, pack selector, per-app framework, CI/CD editor",
     "docs/ARCHITECTURE_MASTER_PLAN.md §7.2", N, "P1", "PC-022", "Flutter in that list is dropped by the stack policy."),
    ("ARCH-DB-OPTIONS", "Database choice per project (the plan lists PG/MySQL/SQLite)",
     "docs/ARCHITECTURE_MASTER_PLAN.md §7.2", N, "P2", "PC-048", "MongoDB first (D-8); others if they prove best."),
    ("ARCH-K8S", "Kubernetes (Helm/Kustomize) and Terraform deploy generator",
     "docs/ARCHITECTURE_MASTER_PLAN.md §10 Phase 3", N, "P2", "PC-028", ""),
    ("ARCH-IMPORT-SOURCES", "Import from GitHub/GitLab/Bitbucket, local folder, Vercel/Netlify, Supabase",
     "docs/ARCHITECTURE_MASTER_PLAN.md §8.1", N, "P1", "R-579", ""),
    ("ARCH-IMPORT-MODES", "Import modes: analyse only, add feature as PR, modernise UI, add mobile, full migration",
     "docs/ARCHITECTURE_MASTER_PLAN.md §8.3", N, "P1", "R-578", ""),
    ("ARCH-PAYMENTS", "Payment flow generator: Stripe Connect, webhooks, subscriptions",
     "docs/ARCHITECTURE_MASTER_PLAN.md §10 Phase 3", N, "P1", "R-567", ""),
    ("ARCH-REALTIME", "Realtime adapter: hooks, presence, optimistic UI",
     "docs/ARCHITECTURE_MASTER_PLAN.md §5.3", N, "P1", "R-569", ""),
    ("ARCH-FILES", "File upload pipeline: S3 direct, processing, PDF generation",
     "docs/ARCHITECTURE_MASTER_PLAN.md §10 Phase 3", N, "P1", "PC-052", ""),
    ("ARCH-NOTIFY", "Notification system: multi-channel, templates, preferences",
     "docs/ARCHITECTURE_MASTER_PLAN.md §10 Phase 3", N, "P1", "PC-053", ""),
    ("ARCH-SEARCH", "Search/filter engine (Meilisearch)",
     "docs/ARCHITECTURE_MASTER_PLAN.md §10 Phase 2", N, "P3", "PC-058", ""),
    ("ARCH-FORMS", "Form/wizard engine",
     "docs/ARCHITECTURE_MASTER_PLAN.md §5.3", N, "P2", "PC-059", ""),
    ("ARCH-PWA", "PWA / offline support",
     "docs/ARCHITECTURE_MASTER_PLAN.md §10 Phase 4", P, "P0", "R-573", ""),
    ("ARCH-I18N", "i18n framework",
     "docs/ARCHITECTURE_MASTER_PLAN.md §10 Phase 4", N, "P2", "PC-055", ""),
    ("ARCH-FLAGS", "A/B testing and feature-flag runtime",
     "docs/ARCHITECTURE_MASTER_PLAN.md §10 Phase 4", N, "P3", "PC-056", ""),
    ("ARCH-OBSERVABILITY", "Advanced observability for generated apps (tracing, dashboards)",
     "docs/ARCHITECTURE_MASTER_PLAN.md §10 Phase 4", N, "P2", "PC-057", ""),
    ("ARCH-PERF", "Performance: bundle analysis, lazy loading, edge caching",
     "docs/ARCHITECTURE_MASTER_PLAN.md §10 Phase 4", N, "P2", "PC-037", ""),
    ("ARCH-TESTS", "Generated tests with over 80% coverage",
     "docs/ARCHITECTURE_MASTER_PLAN.md §12", N, "P1", "PC-054", ""),
    ("ARCH-TEMPLATES-UX", "Template marketplace UX",
     "docs/ARCHITECTURE_MASTER_PLAN.md §10 Phase 4", N, "P2", "PC-018", ""),
    ("ARCH-COMPONENT-BROWSER", "Component library browser",
     "docs/ARCHITECTURE_MASTER_PLAN.md §7.3", N, "P3", "PC-020", ""),
    ("ARCH-NATIVE", "True native mobile (Kotlin/Compose + Swift/SwiftUI)",
     "docs/ARCHITECTURE_MASTER_PLAN.md §10 Phase 3", N, "P2", "R-575", "Also R-576."),
    ("ARCH-ENTERPRISE", "Enterprise: SSO (SAML/OIDC), SCIM, audit export, data residency",
     "docs/ARCHITECTURE_MASTER_PLAN.md §10 Phase 4", D, "P3", "", "After launch."),
    ("PG-01", "All P0 MVP architecture requirements complete",
     "Tracker Production_Gates", N, "P1", "PC-067", ""),
    ("PG-02", "Critical flows have automated E2E and regression tests",
     "Tracker Production_Gates", N, "P1", "PC-037", ""),
    ("PG-03", "Release qualification suite passes across supported target versions",
     "Tracker Production_Gates", N, "P2", "PC-037", ""),
    ("PG-04", "No unresolved critical/high security findings",
     "Tracker Production_Gates", N, "P1", "PC-032", ""),
    ("PG-05", "Tenant isolation test suite passes",
     "Tracker Production_Gates", N, "P0", "PC-009", ""),
    ("PG-06", "External penetration test completed, critical items fixed",
     "Tracker Production_Gates", N, "P1", "PC-032", ""),
    ("PG-07", "On-call, incident runbooks, status page, postmortems",
     "Tracker Production_Gates", N, "P2", "PC-033", ""),
    ("PG-08", "Backup restore drill completed",
     "Tracker Production_Gates", N, "P1", "PC-031", ""),
    ("PG-09", "Load test meets target concurrent builds/previews",
     "Tracker Production_Gates", N, "P1", "PC-034", ""),
    ("PG-10", "SLOs and alerting live",
     "Tracker Production_Gates", N, "P1", "PC-033", ""),
    ("PG-11", "Canary/rollback platform release process proven",
     "Tracker Production_Gates", N, "P2", "PC-041", ""),
    ("PG-12", "Usage ledger reconciles with provider invoices",
     "Tracker Production_Gates", N, "P2", "PC-039", ""),
    ("PG-13", "Spending caps and anomaly kill switches tested",
     "Tracker Production_Gates", N, "P0", "PC-010", ""),
    ("PG-14", "Deletion/export/retention workflows tested",
     "Tracker Production_Gates", N, "P0", "PC-012", ""),
    ("PG-15", "Redacted diagnostic bundle and support workflow",
     "Tracker Production_Gates", N, "P1", "PC-015", ""),
    ("PG-16", "Plan entitlements and quota enforcement tested",
     "Tracker Production_Gates", N, "P0", "PC-011", ""),
    ("PG-17", "A fresh AI/developer session resumes the task from Git + durable state",
     "Tracker Production_Gates", P, "P1", "PC-067", "AGENTS.md, CURRENT_TASK.yaml and this queue exist; the formal drill does not."),
    ("PG-18", "Local/cloud model providers pass conformance and quality evals",
     "Tracker Production_Gates", N, "P1", "PC-014", ""),
    ("PG-19", "Local model endpoint exposure/auth/network policy",
     "Tracker Production_Gates", P, "P1", "PC-014", "Ollama is loopback-only (R-003)."),
    ("PG-20", "Expand/migrate/contract migration and rollback rehearsal",
     "Tracker Production_Gates", N, "P1", "PC-036", ""),
    ("PG-21", "Prompt/tool poisoning, secret exfiltration, replay tests",
     "Tracker Production_Gates", N, "P1", "PC-032", ""),
    ("GA-01", "Portable AI start contract (AGENTS.md + adapters)",
     "Tracker RND_Gap_Audit", C, "", "", "AGENTS.md, CLAUDE.md."),
    ("GA-02", "Work resume: PROJECT_STATE + CURRENT_TASK + handoff",
     "Tracker RND_Gap_Audit", C, "", "", ""),
    ("GA-03", "First-class Ollama-compatible provider with quality eval",
     "Tracker RND_Gap_Audit", P, "P1", "PC-014", "Provider done (R-006); eval missing."),
    ("GA-04", "Per-model safe context registry, no silent truncation",
     "Tracker RND_Gap_Audit", P, "P1", "PC-014", "Safe input budget exists (R-522)."),
    ("GA-05", "Route by measured task, eval, latency, context and cost",
     "Tracker RND_Gap_Audit", P, "P2", "PC-014", ""),
    ("GA-06", "doctor / bootstrap / status / handoff commands",
     "Tracker RND_Gap_Audit", C, "", "R-551", ""),
    ("GA-07", "Environments local -> test -> preview -> staging -> prod with typed config",
     "Tracker RND_Gap_Audit", P, "P2", "PC-040", ""),
    ("GA-08", "Expand/migrate/contract database releases",
     "Tracker RND_Gap_Audit", N, "P1", "PC-036", ""),
    ("GA-09", "Agentic threat model and red-team corpus",
     "Tracker RND_Gap_Audit", N, "P1", "PC-032", ""),
    ("GA-10", "Extended production evidence set",
     "Tracker RND_Gap_Audit", N, "P1", "PC-067", ""),
    ("GA-11", "Pinned supply chain, SBOM/provenance, patch SLA",
     "Tracker RND_Gap_Audit", P, "P2", "PC-035", "Lockfiles pinned; SBOM missing."),
    ("GA-12", "Feature flags with owner/expiry, canary/blue-green",
     "Tracker RND_Gap_Audit", N, "P2", "PC-041", ""),
]

# --- Founder decisions ---------------------------------------------------------------------------
# (id, question, why it matters, blocks, recommendation)

DECISIONS = [
    # (id, question, why it matters, blocks, recommendation, founder answer)
    ("D-1", "Pricing: free-tier credits and paid plans",
     "Plans, entitlements and top-up cannot be built without numbers.", "PC-011, PC-015",
     "Keep 100 signup credits and 1 credit = $0.001 for the beta; set paid plans after beta usage data.",
     "Accepted 2026-09-26 for the beta."),
    ("D-2", "Hosting cloud and region for the live service", "New infrastructure needs sign-off.",
     "PC-009, PC-008, Phase 4", "One region, one managed Postgres, container hosting; decide after cost quotes.",
     "Keys last (founder, 2026-09-26): all code and integrations are finished first; the account and keys are plugged in at PC-070."),
    ("D-3", "Payment processor for platform billing", "Paid cloud service needs sign-off.",
     "PC-011", "Stripe (global) with Razorpay for India, as generated apps already support both.",
     "Keys last (founder, 2026-09-26): all code and integrations are finished first; the account and keys are plugged in at PC-070."),
    ("D-4", "Email verification and password reset required for beta?", "Changes PC-012 scope.",
     "PC-012", "Yes: strangers are signing up.", "Accepted 2026-09-26."),
    ("D-5", "What does an app request produce?",
     "R-562 answers an app request with React Native today.", "PC-003, R-573, R-574",
     "React Native plus PWA + QR.",
     "2026-09-26: when the user names no stack, a React Native (Expo) app ready to publish on "
     "Google Play and the App Store AND an installable PWA with a QR code. When the user asks for "
     "native, Kotlin/Compose and Swift/SwiftUI are generated (R-575/R-576)."),
    ("D-10", "Native mobile preview approach", "The founder asked for emulators and simulators "
     "without Android Studio or Xcode GUIs, open source first.", "PC-063, PC-064, PC-065, PC-066",
     "See NATIVE_MOBILE_PREVIEW_PLAN.md.",
     "2026-09-26: open source first; Android Studio, Xcode GUI and paid services only later."),
    ("D-6", "In-browser preview engine (WebContainers needs a commercial licence; alternatives exist)",
     "PC-007 cannot start without it.", "PC-007", "Evaluate licence cost vs a server-side sandbox preview.",
     "Open source first (founder, 2026-09-26). Keys last (founder, 2026-09-26): all code and integrations are finished first; the account and keys are plugged in at PC-070."),
    ("D-7", "Apple Developer and Google Play accounts; go-ahead for Kotlin/Swift native",
     "Store publishing needs real accounts; standing rule: stop and ask before native work.",
     "R-574, PC-042 and all of Phase 5",
     "Accounts when R-574 is reached; native when Phases 1-4 are done.",
     "Keys last (founder, 2026-09-26): all code and integrations are finished first; the account and keys are plugged in at PC-070."),
    ("D-8", "Database options beyond PostgreSQL", "Changes every backend adapter.", "PC-048",
     "PostgreSQL default; add MongoDB as an option.",
     "2026-09-26: PostgreSQL by default; MongoDB as an option (more later if they are the best choice)."),
    ("D-9", "Which LLM the platform uses for builds", "Quality and cost of every build.", "PC-047",
     "Use the founder's NVIDIA key.",
     "2026-09-26: NVIDIA nemotron-3-ultra via the NVIDIA API; key, model and base URL are in .env."),
]

# Where each part of the v6 tracker's phase table (Phase_Roadmap rows 4-8) is covered.
# (tracker phase, dimension, what the tracker asks, where it is now)
TRACKER_PHASES = [
    ("MVP", "Outcome", "Reliable software factory", "Delivered for generation; hardening in Phases 1 and 4."),
    ("MVP", "Mobile", "Flutter + Expo/RN; native beta", "RN/Expo delivered (R-514, R-545, R-546); Flutter dropped; native in Phase 5 (R-575, R-576)."),
    ("MVP", "Web/Admin", "Next.js", "Delivered."),
    ("MVP", "Backend/DB", "Go/Python; Postgres default + DB recommender", "Delivered (Python, Go, Node; PostgreSQL). MongoDB option PC-048."),
    ("MVP", "Context/Memory", "IR + Context Engine v1", "IR v2 delivered (R-564); memory R-581."),
    ("MVP", "Runtime/Preview", "Browser first + QR paths; Linux; iOS build", "Local preview + QR delivered; in-browser PC-007; Linux sandboxes delivered (R-486..R-490); iOS build via EAS R-574."),
    ("MVP", "Workflow/Agents", "Temporal + model gateway", "Gateway delivered; durable runs in R-577/PC-038 (Temporal itself deferred)."),
    ("MVP", "Git/Delivery", "Task worktrees/PR", "Push delivered (R-501); PRs PC-026."),
    ("MVP", "Security", "Isolation + secret broker + scans", "Scans and secrets delivered; tenant isolation PC-009."),
    ("MVP", "Cost", "Cost per successful task", "Ledger delivered; PC-010, PC-039."),
    ("MVP", "Enterprise", "Foundations only", "Teams delivered (R-515)."),
    ("MVP", "Gate", "Build/test/deploy evidence", "Build/test evidence delivered (R-560, R-561); deploy evidence PC-008 + PC-071."),
    ("MID", "Outcome", "Professional developer / agency", "Phases 2 and 3."),
    ("MID", "Mobile", "Native GA", "Phase 5 (R-575, R-576, R-574, PC-044)."),
    ("MID", "Web/Admin", "Enhanced", "Phase 2 (R-572, PC-050, PC-019, PC-020)."),
    ("MID", "Backend/DB", "Store APIs + more DB profiles", "R-574 (stores), PC-048 (MongoDB)."),
    ("MID", "Context/Memory", "Evidence-backed memory + richer graph", "R-581, R-578."),
    ("MID", "Runtime/Preview", "Streamed emulators/simulators + Local Agent", "PC-063, PC-064, PC-065, PC-066, PC-046."),
    ("MID", "Workflow/Agents", "Remote debug + BYOK", "BYOK delivered (R-504); remote/time-travel debug deferred (R-197)."),
    ("MID", "Git/Delivery", "Existing repo + handover", "R-578, R-579; download/push delivered (R-501)."),
    ("MID", "Security", "Visual/DAST/SBOM", "PC-032, PC-035, PC-037."),
    ("MID", "Cost", "Native rebuild avoidance", "PC-044 (build fingerprinting); Expo fingerprint in R-574."),
    ("MID", "Enterprise", "RBAC/SSO-ready", "PC-029; SSO deferred (ARCH-ENTERPRISE)."),
    ("MID", "Gate", "Quality + supportability", "PC-037, PC-054, PC-015."),
    ("ADVANCED", "Outcome", "Enterprise flexibility", "Deferred until after launch, on purpose. Pull any item forward if a customer needs it."),
    ("ADVANCED", "Mobile", "Device cloud + migration", "Hosted emulators PC-065/PC-066; PWA/RN-to-native migration PC-045; physical device cloud deferred."),
    ("ADVANCED", "Other dimensions", "BYOC, private runners, multi-region, policy-as-code, private models, two-person approval, predictive scheduling", "Deferred (R-081..R-093, R-130, R-166..R-168, R-201..R-209)."),
    ("PRODUCTION", "Outcome", "Operational trust", "Phase 4 + Phase 6; signed off by PC-067 against PG-01..PG-21."),
    ("PRODUCTION", "Web/Admin", "HA hosting", "PC-041."),
    ("PRODUCTION", "Backend/DB", "HA/DR data, restore drills", "PC-031."),
    ("PRODUCTION", "Runtime", "Multi-region as sold", "Deferred (R-084) until a customer needs it."),
    ("PRODUCTION", "Workflow", "Workflow failover", "PC-038."),
    ("PRODUCTION", "Git/Delivery", "Release qualification", "PC-037."),
    ("PRODUCTION", "Security", "Pen test / SOC 2-ready controls", "PC-032, PC-035."),
    ("PRODUCTION", "Cost", "Positive unit economics", "PC-039."),
    ("PRODUCTION", "Enterprise", "SLA/process", "PC-033."),
    ("PRODUCTION", "Gate", "Measured outcomes", "PC-015 (beta KPIs), PC-067."),
]

TARGETS = [
    ("Vibe: prompt -> live preview", "under 90 seconds"),
    ("Vibe: prompt -> deployed URL", "under 3 minutes"),
    ("Engineering: prompt -> multi-app monorepo", "under 3 minutes"),
    ("Graduation Vibe -> Engineering", "under 30 seconds, nothing lost"),
    ("Generated code", "TypeScript strict 0 errors; every surface builds"),
    ("Generated tests", "over 80% coverage"),
    ("Project import success", "over 90%"),
]

GOAL = {
    "title": "OmniStackAI: finish the platform",
    "vision": "A futuristic platform that turns a prompt into anything from one app to a whole "
    "ecosystem. Every app gets modern, latest UI and the maximum features the prompt implies, and "
    "can be customised afterwards.",
    "vibe": "Vibe Mode: prompt -> running app -> live URL, with all the machinery hidden. The API "
    "and database behind every feature are real, not only a pretty UI.",
    "engineering": "Engineering Mode: see the plan, choose the stack, import a repo, review diffs, "
    "see the verification report, open GitHub pull requests.",
    "stack": [
        "Web and admin panel: Next.js by default.",
        "App requested without naming a stack (either mode): a React Native (Expo) app ready "
        "to publish on Google Play and the App Store, plus an installable PWA with a QR code.",
        "App requested as native: Kotlin + Jetpack Compose (Android) and/or Swift + SwiftUI (iOS) "
        "is generated, best in class, through to store publishing. Until R-575/R-576 ship, the "
        "React Native app is built instead and the user is told why (the R-559 rule).",
        "Accounts and keys (cloud, database, payments, email, Apple, Google, sandboxes) come "
        "last: all code and integrations are finished first, so go-live is only credentials.",
        "Flutter and React.js: not offered. A request for either is answered with the nearest "
        "supported stack and the reason.",
        "Backend: Python by default; Go and Node on request.",
        "Database: PostgreSQL by default; MongoDB as an option.",
        "LLM: NVIDIA nemotron-3-ultra through the NVIDIA API (key in .env only), with the "
        "existing providers and local Ollama as alternatives.",
    ],
    "strengthen": [
        ("Local / offline models", "PC-014"),
        ("UI polish and 'wow in 30 seconds'", "PC-006"),
        ("Instant preview, one-click hosting, integrations", "PC-007, PC-008, PC-013"),
        ("Import an existing repo", "R-578, R-579"),
        ("Store-ready mobile apps", "R-574 (React Native), R-575, R-576 (native)"),
        ("A live product with real users", "PC-009, PC-015"),
    ],
    "focus_rule": "Work only from this folder's Work Queue, top to bottom. Other R_&_D plans and "
    "the v6 tracker are sources, not queues: every open item from them is already in 'All Tasks' "
    "with a pointer to the queue item that covers it. Do not start anything that is not in the "
    "queue until the queue is finished.",
}
