"""Customer project assembler.

Turns one Application IR into a complete customer monorepo (Brief 6/34/35): it selects the framework
adapters implied by the IR project strategy, generates each target, places it under the monorepo
layout (`apps/web` for the Next.js web app, `services/api` for the Go/Python backend), and merges
everything into a single `GeneratedProject`. With the Git service, one IR becomes one customer-owned
repository. Pure and deterministic — nothing is installed, built, run, or written to disk here.
"""

from __future__ import annotations

from dataclasses import dataclass

from ..application_ir import ApplicationIR, BackendStrategy, WebStrategy
from .adapter import AdapterRegistry, GenerationTarget
from .backend_go import GoBackendAdapter
from .backend_python import PythonBackendAdapter
from .files import GeneratedFile, GeneratedProject
from .nextjs import NextjsWebAdapter
from .openapi import render_openapi_json

MONOREPO_TARGET = "customer-monorepo"

_BACKEND_TARGET = {
    BackendStrategy.GO: GenerationTarget.BACKEND_GO,
    BackendStrategy.PYTHON: GenerationTarget.BACKEND_PYTHON,
}


def default_registry() -> AdapterRegistry:
    """An AdapterRegistry with every currently-implemented framework adapter registered."""

    registry = AdapterRegistry()
    registry.register(NextjsWebAdapter())
    registry.register(PythonBackendAdapter())
    registry.register(GoBackendAdapter())
    return registry


@dataclass(frozen=True, slots=True)
class AssembledApp:
    label: str
    directory: str
    target: str


def _prefixed(project: GeneratedProject, directory: str) -> list[GeneratedFile]:
    return [GeneratedFile(f"{directory}/{f.path}", f.content, f.executable) for f in project.files()]


def _root_readme(ir: ApplicationIR, apps: list[AssembledApp], skipped: list[str]) -> str:
    lines = [
        f"# {ir.name}",
        "",
        ir.description,
        "",
        "Customer monorepo generated by OmniStackAI from a single Application IR.",
        "",
        "## Apps",
        "",
    ]
    for app in apps:
        lines.append(f"- **{app.label}** — `{app.directory}/` (target `{app.target}`)")
    if ir.apis:
        lines.append("")
        lines.append("## API Contracts")
        lines.append("")
        lines.append("- **OpenAPI 3.1** — `contracts/openapi.json`")
    if skipped:
        lines.append("")
        lines.append("## Not yet assembled")
        lines.append("")
        for note in skipped:
            lines.append(f"- {note}")
    lines.append("")
    return "\n".join(lines) + "\n"


def _plan_assembly(ir: ApplicationIR) -> tuple[list[AssembledApp], list[str]]:
    """Decide which apps the IR assembles and where — the single source of the monorepo layout."""

    apps: list[AssembledApp] = []
    skipped: list[str] = []
    strategy = ir.project_strategy

    if strategy.web_strategy is WebStrategy.NEXTJS:
        apps.append(AssembledApp("web (Next.js)", "apps/web", GenerationTarget.NEXTJS_WEB.value))
    elif strategy.web_strategy is not WebStrategy.NONE:
        skipped.append(f"web_strategy {strategy.web_strategy.value!r} has no adapter yet")

    backend_target = _BACKEND_TARGET.get(strategy.backend_strategy)
    if backend_target is not None:
        apps.append(AssembledApp(f"backend ({strategy.backend_strategy.value})", "services/api", backend_target.value))
    else:
        skipped.append(f"backend_strategy {strategy.backend_strategy.value!r} has no adapter yet")

    if strategy.admin_strategy.value != "none":
        skipped.append(f"admin_strategy {strategy.admin_strategy.value!r} is not assembled yet")
    if strategy.mobile_profile.value != "none":
        skipped.append(f"mobile_profile {strategy.mobile_profile.value!r} is not assembled yet")
    return apps, skipped


def assembled_targets(ir: ApplicationIR, registry: AdapterRegistry | None = None) -> tuple[AssembledApp, ...]:
    """The apps an IR assembles (label, directory, target) — without generating any files.

    `registry` is accepted for signature symmetry with `assemble_project` (the layout does not depend
    on it); passing one lets a caller reason about a custom adapter set.
    """

    if not isinstance(ir, ApplicationIR):
        raise TypeError("assembled_targets expects an ApplicationIR")
    apps, _ = _plan_assembly(ir)
    return tuple(apps)


def assemble_project(ir: ApplicationIR, registry: AdapterRegistry | None = None) -> GeneratedProject:
    """Assemble one customer monorepo GeneratedProject from an Application IR."""

    if not isinstance(ir, ApplicationIR):
        raise TypeError("assemble_project expects an ApplicationIR")
    registry = registry if registry is not None else default_registry()

    apps, skipped = _plan_assembly(ir)
    files: list[GeneratedFile] = []
    for app in apps:
        project = registry.get(app.target).generate(ir)
        files += _prefixed(project, app.directory)

    if ir.apis:
        files.append(GeneratedFile("contracts/openapi.json", render_openapi_json(ir)))

    files.append(GeneratedFile("README.md", _root_readme(ir, apps, skipped)))
    files.append(GeneratedFile(".gitignore", "node_modules/\n.next/\n.venv/\n__pycache__/\nbin/\n.env\n"))

    return GeneratedProject(MONOREPO_TARGET, tuple(files))
