"""Password recovery pages for the generated web app and admin console (R-591).

The old `/forgot-password` page took an email address and a new password and set it — no email,
no link, no proof the person owned the account. The backend refused it (501), which was the only
thing standing between that form and taking over any account by typing its address.

Now it is the ordinary, safe flow: `/forgot-password` asks for an email and says a link is on its
way (the same words whether or not the account exists); the emailed link opens
`/reset-password?token=...`, which sets the new password once.
"""

from __future__ import annotations

from ..application_ir import ApplicationIR
from .auth_templates import MIN_PASSWORD_LENGTH

_SHELL_OPEN = (
    '    <main style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center",\n'
    '      background: "radial-gradient(1000px 500px at 50% 10%, rgba(99, 102, 241, 0.12), transparent 70%), #f8fafc",\n'
    '      padding: 24 }}>\n'
    '      <div style={{ width: "100%", maxWidth: 420, padding: "36px 32px", background: "rgba(255,255,255,0.95)",\n'
    '        borderRadius: 20, boxShadow: "0 25px 50px -12px rgba(15,23,42,0.08), 0 0 0 1px rgba(226,232,240,0.8)" }}>\n'
)
_SHELL_CLOSE = "      </div>\n    </main>\n"
_INPUT = ('{ padding: "10px 14px", border: "1px solid #cbd5e1", borderRadius: 10, fontSize: 14, '
          'outline: "none", background: "#fcfdfe" }')
_LABEL = '{ display: "flex", flexDirection: "column", gap: 6, fontSize: 13, fontWeight: 600, color: "#334155" }'
_BUTTON = ('{ padding: "11px 14px", border: "none", borderRadius: 10, fontSize: 14, fontWeight: 700, '
           'color: "#fff", background: "linear-gradient(135deg, #3b82f6, #6366f1)", cursor: "pointer" }')
_ERROR = ('{ padding: "10px 14px", background: "#fef2f2", border: "1px solid #fca5a5", borderRadius: 8, '
          'color: "#b91c1c", fontSize: 13, marginBottom: 16 }')
_OK = ('{ padding: "10px 14px", background: "#f0fdf4", border: "1px solid #86efac", borderRadius: 8, '
       'color: "#15803d", fontSize: 13, marginBottom: 16 }')


def forgot_password_page(ir: ApplicationIR) -> str:  # noqa: ARG001
    return (
        '"use client";\n\n'
        "// Generated by OmniStackAI (R-591). Asks for an email; the reset itself happens from the link.\n"
        'import { useState } from "react";\n'
        'import Link from "next/link";\n\n'
        'const BASE_URL = process.env.NEXT_PUBLIC_API_URL || "";\n\n'
        "export default function ForgotPasswordPage() {\n"
        '  const [email, setEmail] = useState("");\n'
        "  const [sent, setSent] = useState(false);\n"
        "  const [error, setError] = useState<string | null>(null);\n"
        "  const [loading, setLoading] = useState(false);\n\n"
        "  async function handleSubmit(e: React.FormEvent) {\n"
        "    e.preventDefault();\n"
        "    setError(null);\n"
        "    setLoading(true);\n"
        "    try {\n"
        "      const res = await fetch(`${BASE_URL}/auth/forgot-password`, {\n"
        '        method: "POST",\n'
        '        headers: { "Content-Type": "application/json" },\n'
        "        body: JSON.stringify({ email: email.trim() }),\n"
        "      });\n"
        '      if (!res.ok) throw new Error("request_failed");\n'
        "      setSent(true);\n"
        "    } catch {\n"
        '      setError("We could not send the link just now. Please try again.");\n'
        "    } finally {\n"
        "      setLoading(false);\n"
        "    }\n"
        "  }\n\n"
        "  return (\n"
        + _SHELL_OPEN
        + '        <h1 style={{ fontSize: 24, fontWeight: 800, color: "#0f172a", margin: "0 0 6px" }}>Reset your password</h1>\n'
        "        {sent ? (\n"
        "          <>\n"
        f'            <div id="forgot-success-banner" role="status" style={{{_OK}}}>\n'
        "              If an account exists for {email.trim()}, we have emailed a link to choose a new password.\n"
        "              It works once, for one hour.\n"
        "            </div>\n"
        '            <Link href="/login" style={{ fontSize: 14, fontWeight: 600, color: "#4f46e5" }}>Back to sign in</Link>\n'
        "          </>\n"
        "        ) : (\n"
        "          <>\n"
        '            <p style={{ color: "#64748b", fontSize: 14, margin: "0 0 20px" }}>Enter your email and we will send you a reset link.</p>\n'
        f'            {{error && <div id="forgot-error-banner" role="alert" style={{{_ERROR}}}>{{error}}</div>}}\n'
        '            <form onSubmit={handleSubmit} style={{ display: "flex", flexDirection: "column", gap: 14 }}>\n'
        f"              <label style={{{_LABEL}}}>\n"
        "                Email address\n"
        '                <input id="forgot-email" type="email" autoComplete="email" required value={email}\n'
        f'                  onChange={{(e) => setEmail(e.target.value)}} placeholder="you@company.com" style={{{_INPUT}}} />\n'
        "              </label>\n"
        f'              <button id="forgot-submit" type="submit" disabled={{loading}} style={{{_BUTTON}}}>\n'
        '                {loading ? "Sending…" : "Send reset link"}\n'
        "              </button>\n"
        "            </form>\n"
        '            <p style={{ marginTop: 18, fontSize: 13, color: "#64748b", textAlign: "center" }}>\n'
        '              Remembered it? <Link href="/login" style={{ color: "#4f46e5", fontWeight: 600 }}>Sign in</Link>\n'
        "            </p>\n"
        "          </>\n"
        "        )}\n"
        + _SHELL_CLOSE
        + "  );\n"
        "}\n"
    )


def reset_password_page(ir: ApplicationIR) -> str:  # noqa: ARG001
    return (
        '"use client";\n\n'
        "// Generated by OmniStackAI (R-591). Opened from the emailed link: /reset-password?token=...\n"
        'import { Suspense, useState } from "react";\n'
        'import Link from "next/link";\n'
        'import { useRouter, useSearchParams } from "next/navigation";\n\n'
        'const BASE_URL = process.env.NEXT_PUBLIC_API_URL || "";\n'
        f"const MIN_PASSWORD_LENGTH = {MIN_PASSWORD_LENGTH};\n\n"
        "function ResetPasswordForm() {\n"
        "  const router = useRouter();\n"
        '  const token = useSearchParams().get("token") || "";\n'
        '  const [password, setPassword] = useState("");\n'
        '  const [confirm, setConfirm] = useState("");\n'
        "  const [error, setError] = useState<string | null>(null);\n"
        "  const [done, setDone] = useState(false);\n"
        "  const [loading, setLoading] = useState(false);\n\n"
        "  async function handleSubmit(e: React.FormEvent) {\n"
        "    e.preventDefault();\n"
        "    setError(null);\n"
        "    if (password.length < MIN_PASSWORD_LENGTH) {\n"
        "      setError(`Use at least ${MIN_PASSWORD_LENGTH} characters.`);\n"
        "      return;\n"
        "    }\n"
        "    if (password !== confirm) {\n"
        '      setError("The two passwords do not match.");\n'
        "      return;\n"
        "    }\n"
        "    setLoading(true);\n"
        "    try {\n"
        "      const res = await fetch(`${BASE_URL}/auth/reset-password`, {\n"
        '        method: "POST",\n'
        '        headers: { "Content-Type": "application/json" },\n'
        "        body: JSON.stringify({ token, new_password: password }),\n"
        "      });\n"
        "      if (!res.ok) {\n"
        "        const data = await res.json().catch(() => ({}));\n"
        '        throw new Error(data?.detail === "invalid_or_expired_token"\n'
        '          ? "This link has expired or was already used. Ask for a new one."\n'
        '          : "We could not reset your password. Please try again.");\n'
        "      }\n"
        "      setDone(true);\n"
        '      setTimeout(() => router.push("/login"), 1500);\n'
        "    } catch (err) {\n"
        '      setError(err instanceof Error ? err.message : "Reset failed");\n'
        "    } finally {\n"
        "      setLoading(false);\n"
        "    }\n"
        "  }\n\n"
        "  if (!token) {\n"
        "    return (\n"
        f'      <div role="alert" style={{{_ERROR}}}>\n'
        '        This page needs the link from your email. <Link href="/forgot-password">Ask for a new link</Link>.\n'
        "      </div>\n"
        "    );\n"
        "  }\n"
        "  if (done) {\n"
        f'    return <div id="reset-success-banner" role="status" style={{{_OK}}}>Your password is changed. Taking you to sign in…</div>;\n'
        "  }\n"
        "  return (\n"
        "    <>\n"
        f'      {{error && <div id="reset-error-banner" role="alert" style={{{_ERROR}}}>{{error}}</div>}}\n'
        '      <form onSubmit={handleSubmit} style={{ display: "flex", flexDirection: "column", gap: 14 }}>\n'
        f"        <label style={{{_LABEL}}}>\n"
        "          New password\n"
        '          <input id="reset-password" type="password" autoComplete="new-password" required value={password}\n'
        f"            onChange={{(e) => setPassword(e.target.value)}} style={{{_INPUT}}} />\n"
        "        </label>\n"
        f"        <label style={{{_LABEL}}}>\n"
        "          Confirm new password\n"
        '          <input id="reset-confirm" type="password" autoComplete="new-password" required value={confirm}\n'
        f"            onChange={{(e) => setConfirm(e.target.value)}} style={{{_INPUT}}} />\n"
        "        </label>\n"
        f'        <button id="reset-submit" type="submit" disabled={{loading}} style={{{_BUTTON}}}>\n'
        '          {loading ? "Saving…" : "Set new password"}\n'
        "        </button>\n"
        "      </form>\n"
        "    </>\n"
        "  );\n"
        "}\n\n"
        "export default function ResetPasswordPage() {\n"
        "  return (\n"
        + _SHELL_OPEN
        + '        <h1 style={{ fontSize: 24, fontWeight: 800, color: "#0f172a", margin: "0 0 18px" }}>Choose a new password</h1>\n'
        "        {/* useSearchParams needs a Suspense boundary in the App Router. */}\n"
        "        <Suspense fallback={null}>\n"
        "          <ResetPasswordForm />\n"
        "        </Suspense>\n"
        + _SHELL_CLOSE
        + "  );\n"
        "}\n"
    )
