"""Node.js backend framework adapter (Express / Hono).

Turns an Application IR into a real, production-ready Node.js/TypeScript backend as a `GeneratedProject`:
- TypeScript entity models and Zod validation schemas from IR entities;
- Express or Hono routers from IR APIs (grouped by resource segment) with full CRUD wiring via `route_wiring.py`;
- PostgreSQL connection pool (`pg`) with parameterized queries (no in-memory fallback: PC-004);
- JWT authentication guard with Bearer token verification;
- Application entry point with CORS, JSON body parser, health checks (/healthz, /readyz, /health), and graceful shutdown;
- Packaging files: package.json (ESM), tsconfig.json, .env.example, README.md;
- OpenAPI 3.1 contract (`contracts/openapi.json`), PostgreSQL schema.sql, and seed.sql.

Pure and deterministic — nothing is installed, built, run, or written to disk here.
"""

from __future__ import annotations

import json
import re
from typing import Any

from ..application_ir import (
    ApiEndpoint,
    ApplicationIR,
    DatabaseStrategy,
    Entity,
    Field,
    FieldType,
)
from .adapter import FrameworkAdapter, GenerationTarget
from .auth_guard import needs_auth
from ..application_ir.workflow import workflows_of
from .auth_templates import (
    EMAIL_ENV_EXAMPLE,
    NODE_AUTH_CORE,
    NODE_AUTH_ROUTER_EXPRESS,
    NODE_AUTH_ROUTER_HONO,
    is_account_route,
)
from .errors import GenerationError
from .field_validation import filter_fields, parse_field_rules
from .files import GeneratedFile, GeneratedProject
from .openapi import render_openapi_json
from .workflow_routes import transition_routes
from .route_wiring import Op, fk_relations, wire_endpoint
from .schema_sql import render_postgres_schema, sql_identifier, table_name
from .seed_sql import render_postgres_seed

_TS_TYPE: dict[FieldType, str] = {
    FieldType.STRING: "string",
    FieldType.TEXT: "string",
    FieldType.UUID: "string",
    FieldType.INT: "number",
    FieldType.FLOAT: "number",
    FieldType.BOOL: "boolean",
    FieldType.DATETIME: "Date | string",
    FieldType.JSON: "Record<string, unknown> | unknown[]",
    FieldType.ATTACHMENT: "string",
}


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-") or "app"


def _segment(path: str) -> str:
    first = path.strip("/").split("/")[0] if path.strip("/") else ""
    module = re.sub(r"\W+", "_", first).strip("_").lower()
    return module or "root"


def _pascal(value: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^A-Za-z0-9]+", value) if part)


def _camel(value: str) -> str:
    p = _pascal(value)
    return p[:1].lower() + p[1:] if p else "item"


def _path_params(path: str) -> list[str]:
    return re.findall(r"\{(\w+)\}", path)


def _to_express_path(path: str) -> str:
    # Converts /users/{id} to /users/:id
    return re.sub(r"\{(\w+)\}", r":\1", path)


def _models_file(ir: ApplicationIR) -> str:
    lines = [
        "// Generated by OmniStackAI: TypeScript Entity Models",
        "",
    ]
    if not ir.entities:
        lines.append("// No entities defined in the IR.")
        return "\n".join(lines) + "\n"

    for entity in ir.entities:
        declared_names = {f.name for f in entity.fields}
        lines.append(f"export interface {entity.name} {{")
        for field in entity.fields:
            ts_type = _TS_TYPE[field.type]
            opt = "" if field.required else "?"
            lines.append(f"  {field.name}{opt}: {ts_type};")

        # Auto audit fields if not already explicitly declared
        if "created_at" not in declared_names:
            lines.append("  created_at?: Date | string;")
        if "updated_at" not in declared_names:
            lines.append("  updated_at?: Date | string;")

        if entity.relations:
            lines.append("  // Relations")
            for rel in entity.relations:
                lines.append(f"  // {rel.name} -> {rel.target_entity} ({rel.kind.value})")

        lines.append("}")
        lines.append("")

        # Create input type (omits auto id / created_at / updated_at)
        lifecycle = next((w.field for w in workflows_of(ir) if w.entity == entity.name), None)
        if lifecycle:
            # R-590: the lifecycle field is optional on input and ignored on write.
            lines.append(
                f"export type Create{entity.name}Input = Omit<{entity.name}, 'id' | 'created_at' | 'updated_at' | '{lifecycle}'>"
                f" & {{ {lifecycle}?: string }};"
            )
        else:
            lines.append(f"export type Create{entity.name}Input = Omit<{entity.name}, 'id' | 'created_at' | 'updated_at'>;")
        lines.append(f"export type Update{entity.name}Input = Partial<Create{entity.name}Input>;")
        lines.append("")

    return "\n".join(lines) + "\n"


def _zod_field_schema(field: Field, rules: Any) -> str:
    if rules.enum:
        literals = ", ".join(f"'{v}'" for v in rules.enum)
        base = f"z.enum([{literals}])"
    elif field.type in (FieldType.STRING, FieldType.TEXT):
        base = "z.string()"
        if rules.max_length is not None:
            base += f".max({rules.max_length})"
    elif field.type is FieldType.UUID:
        base = "z.string().uuid()"
    elif field.type is FieldType.INT:
        base = "z.number().int()"
        if rules.minimum is not None:
            base += f".min({rules.minimum})"
        if rules.maximum is not None:
            base += f".max({rules.maximum})"
    elif field.type is FieldType.FLOAT:
        base = "z.number()"
        if rules.minimum is not None:
            base += f".min({rules.minimum})"
        if rules.maximum is not None:
            base += f".max({rules.maximum})"
    elif field.type is FieldType.BOOL:
        base = "z.boolean()"
    elif field.type is FieldType.DATETIME:
        base = "z.union([z.string().datetime(), z.date()])"
    elif field.type is FieldType.JSON:
        base = "z.union([z.record(z.unknown()), z.array(z.unknown())])"
    else:
        base = "z.string()"

    if not field.required:
        base += ".optional()"
    return base


def _validation_file(ir: ApplicationIR) -> str:
    lines = [
        "// Generated by OmniStackAI: Zod Validation Schemas",
        "import { z } from 'zod';",
        "",
    ]
    if not ir.entities:
        lines.append("// No entity validation required.")
        return "\n".join(lines) + "\n"

    from ..application_ir.workflow import workflows_of

    lifecycle_fields = {(w.entity, w.field) for w in workflows_of(ir)}
    for entity in ir.entities:
        lines.append(f"export const create{entity.name}Schema = z.object({{")
        for field in entity.fields:
            if field.name in ("id", "created_at", "updated_at"):
                continue
            if (entity.name, field.name) in lifecycle_fields:
                # R-590: accepted and ignored — only a transition moves the lifecycle field.
                lines.append(f"  {field.name}: z.string().optional(),")
                continue
            rules = parse_field_rules(field)
            zod_expr = _zod_field_schema(field, rules)
            lines.append(f"  {field.name}: {zod_expr},")
        lines.append("});")
        lines.append("")
        lines.append(f"export const update{entity.name}Schema = create{entity.name}Schema.partial();")
        lines.append("")

    return "\n".join(lines) + "\n"


def _config_file() -> str:
    return """// Generated by OmniStackAI: Server Configuration
import 'dotenv/config';

export interface AppConfig {
  port: number;
  databaseUrl: string;
  jwtSecret: string;
  corsOrigin: string;
  nodeEnv: string;
}

export const config: AppConfig = {
  port: Number(process.env.PORT) || 8000,
  databaseUrl: process.env.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5432/app',
  // R-591: no default. A default secret containing 'dev-secret' switched on the no-token admin
  // bypass below, so a deployment that forgot JWT_SECRET let every visitor in as admin.
  jwtSecret: process.env.JWT_SECRET || '',
  corsOrigin: process.env.CORS_ORIGIN || '*',
  nodeEnv: process.env.NODE_ENV || 'development',
};
"""


def _auth_file(ir: ApplicationIR, framework: str) -> str:
    """The request guard. Token checks live in `auth/core.ts`, shared with the account routes.

    R-591 fixed three things here: tokens never expired (the signature was checked, `exp` never
    was), signatures were compared with `!==` rather than in constant time, and the no-token dev
    bypass fired whenever the secret merely contained 'dev-secret' — which the config supplied by
    default. The bypass now needs OMNISTACKAI_DEV_MODE=1 or a secret explicitly set to a dev value,
    and a missing secret is a 500, as in the Python and Go backends.
    """
    roles = ", ".join(f"'{role.id}'" for role in ir.roles)
    roles_type = " | ".join(f"'{role.id}'" for role in ir.roles) if ir.roles else "string"
    shared = f"""import {{ config }} from '../config.js';
import {{ verifyToken, type AuthClaims }} from '../auth/core.js';

export type {{ AuthClaims }};
export const ROLES = [{roles}] as const;
export type UserRole = {roles_type};

const DEV_SECRETS = ['local-dev-secret', 'dev-secret'];

/** Claims for the request, or an error to send. */
function authorize(header: string | undefined): {{ claims?: AuthClaims; status?: number; detail?: string }} {{
  const secret = config.jwtSecret;
  if (!header || !header.startsWith('Bearer ')) {{
    if (process.env.OMNISTACKAI_DEV_MODE === '1' || DEV_SECRETS.includes(secret)) {{
      return {{ claims: {{ sub: 'dev-admin', roles: [...ROLES], email: 'admin@example.local' }} }};
    }}
    if (!secret) return {{ status: 500, detail: 'auth_not_configured' }};
    return {{ status: 401, detail: 'unauthorized' }};
  }}
  if (!secret) return {{ status: 500, detail: 'auth_not_configured' }};
  const claims = verifyToken(header.slice(7).trim(), secret);
  if (!claims) return {{ status: 401, detail: 'invalid_token' }};
  return {{ claims }};
}}
"""
    if framework == "hono":
        return (
            "// Generated by OmniStackAI: Hono JWT Authentication Guard\n"
            "import { Context, Next } from 'hono';\n"
            + shared
            + """
export async function requireAuth(c: Context, next: Next) {
  const result = authorize(c.req.header('Authorization'));
  if (!result.claims) return c.json({ error: result.detail, detail: result.detail }, result.status as any);
  c.set('user', result.claims);
  await next();
}
"""
        )
    return (
        "// Generated by OmniStackAI: Express JWT Authentication Guard\n"
        "import { Request, Response, NextFunction } from 'express';\n"
        + shared
        + """
export interface AuthenticatedRequest extends Request {
  user?: AuthClaims;
}

export function requireAuth(req: AuthenticatedRequest, res: Response, next: NextFunction) {
  const result = authorize(req.headers.authorization);
  if (!result.claims) return res.status(result.status!).json({ error: result.detail, detail: result.detail });
  req.user = result.claims;
  next();
}
"""
    )


def _db_pool_file() -> str:
    return """// Generated by OmniStackAI: PostgreSQL Connection Pool
import pg from 'pg';
import { config } from '../config.js';

const { Pool } = pg;

export const pool = new Pool({
  connectionString: config.databaseUrl,
  max: 20,
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 5000,
});

export async function checkDbHealth(): Promise<boolean> {
  try {
    const res = await pool.query('SELECT 1 as healthy');
    return res.rows.length > 0;
  } catch (err) {
    return false;
  }
}
"""


def _db_repository_file(entity: Entity, workflow=None) -> str:
    tbl = table_name(entity.name)
    # R-590: the lifecycle field is never written here; a new row takes the initial state from the
    # column DEFAULT and only a transition moves it after that.
    skip = {"id", "created_at", "updated_at"} | ({workflow.field} if workflow is not None else set())
    ins_cols = [f.name for f in entity.fields if f.name not in skip]
    col_list = ", ".join(sql_identifier(f.name) for f in entity.fields)
    ins_col_list = ", ".join(sql_identifier(c) for c in ins_cols)
    placeholders = ", ".join(f"${i+1}" for i in range(len(ins_cols)))
    insert_sql = (
        f"INSERT INTO {sql_identifier(tbl)} ({ins_col_list}) VALUES ({placeholders}) RETURNING {col_list}"
        if ins_cols else f"INSERT INTO {sql_identifier(tbl)} DEFAULT VALUES RETURNING {col_list}"
    )

    return f"""// Generated by OmniStackAI: {entity.name} Repository
//
// PC-004: every call goes to PostgreSQL. This used to fall back to an in-memory Map on any database
// error and report success, so a user "saved" data that vanished on restart and nobody was told.
// A database error is now an error: the route's error handler answers 500/503 and it is logged.
import {{ pool }} from './pool.js';
import type {{ {entity.name}, Create{entity.name}Input, Update{entity.name}Input }} from '../models/types.js';

const WRITABLE: string[] = {json.dumps(ins_cols)};

export class {entity.name}Repository {{
  static async list(options: {{ limit?: number; offset?: number; search?: string }} = {{}}): Promise<{entity.name}[]> {{
    const limit = options.limit || 50;
    const offset = options.offset || 0;
    const query = 'SELECT {col_list} FROM {sql_identifier(tbl)} LIMIT $1 OFFSET $2';
    const result = await pool.query(query, [limit, offset]);
    return result.rows as {entity.name}[];
  }}

  static async getById(id: string): Promise<{entity.name} | null> {{
    const query = 'SELECT {col_list} FROM {sql_identifier(tbl)} WHERE id = $1';
    const result = await pool.query(query, [id]);
    return (result.rows[0] as {entity.name}) ?? null;
  }}

  static async create(input: Create{entity.name}Input): Promise<{entity.name}> {{
    const cols = [{", ".join(f"(input as any).{c}" for c in ins_cols)}];
    const query = `{insert_sql}`;
    const result = await pool.query(query, cols);
    return result.rows[0] as {entity.name};
  }}

  static async update(id: string, input: Update{entity.name}Input): Promise<{entity.name} | null> {{
    // Only known, writable columns: column names never come from the request (R-590).
    const keys = Object.keys(input).filter((k) => WRITABLE.includes(k));
    if (keys.length === 0) return this.getById(id);
    const setClauses = keys.map((k, idx) => `"${{k}}" = $${{idx + 2}}`).join(', ');
    const values = keys.map((k) => (input as any)[k]);
    const query = `UPDATE {sql_identifier(tbl)} SET ${{setClauses}} WHERE id = $1 RETURNING {col_list}`;
    const result = await pool.query(query, [id, ...values]);
    return (result.rows[0] as {entity.name}) ?? null;
  }}
{_node_lifecycle_setter(tbl, col_list, entity.name, workflow)}
  static async delete(id: string): Promise<boolean> {{
    const query = 'DELETE FROM {sql_identifier(tbl)} WHERE id = $1';
    const result = await pool.query(query, [id]);
    return (result.rowCount ?? 0) > 0;
  }}

  static async listBy(relationCol: string, parentId: string): Promise<{entity.name}[]> {{
    const query = `SELECT {col_list} FROM {sql_identifier(tbl)} WHERE "${{relationCol}}" = $1`;
    const result = await pool.query(query, [parentId]);
    return result.rows as {entity.name}[];
  }}
}}
"""


def _express_router_file(
    segment: str,
    apis: list[ApiEndpoint],
    repo_entities: frozenset[str],
    fk_by_entity: dict[str, tuple[str, ...]],
    has_auth: bool,
    transitions: tuple = (),
) -> str:
    lines = [
        f"// Generated by OmniStackAI: Express Router for {segment}",
        "import { Router, Request, Response } from 'express';",
    ]
    if has_auth:
        lines.append("import { requireAuth } from '../middleware/auth.js';")

    # Determine required models, repositories, and schemas
    used_entities: set[str] = set()
    for api in apis:
        wiring = wire_endpoint(api, repo_entities, fk_by_entity)
        if wiring:
            used_entities.add(wiring.entity)

    for ent in sorted(used_entities):
        lines.append(f"import {{ {ent}Repository }} from '../db/{table_name(ent)}.js';")
        lines.append(f"import {{ create{ent}Schema, update{ent}Schema }} from '../models/validation.js';")

    lines.append("")
    lines.append("export const router = Router();")
    lines.append("")

    for api in apis:
        wiring = wire_endpoint(api, repo_entities, fk_by_entity)
        method = api.method.value.lower()
        # Relative path within this segment's router
        # If api.path is /users/:id, and mounted on /api/users, rel_path is /:id
        rel = "/" + "/".join([s for s in api.path.strip("/").split("/")[1:]])
        rel_express = _to_express_path(rel)
        if not rel_express:
            rel_express = "/"

        middleware_str = "requireAuth, " if api.auth else ""

        if not wiring:
            lines.append(f"router.{method}('{rel_express}', {middleware_str}async (req: Request, res: Response) => {{")
            # PC-004: this answered 200 with a placeholder body, so a client believed the call
            # worked. It is honest now, like Python and Go, and the build report names it.
            lines.append(f"  res.status(501).json({{ detail: 'not_implemented', endpoint: '{api.method.value} {api.path}' }});")
            lines.append("});")
            lines.append("")
            continue

        ent = wiring.entity
        if wiring.op is Op.LIST:
            lines.append(f"router.{method}('{rel_express}', {middleware_str}async (req: Request, res: Response) => {{")
            lines.append("  const limit = req.query.limit ? Number(req.query.limit) : 50;")
            lines.append("  const offset = req.query.offset ? Number(req.query.offset) : 0;")
            lines.append(f"  const items = await {ent}Repository.list({{ limit, offset }});")
            lines.append("  res.json(items);")
            lines.append("});")
        elif wiring.op is Op.GET:
            param = wiring.id_param or "id"
            lines.append(f"router.{method}('{rel_express}', {middleware_str}async (req: Request, res: Response) => {{")
            lines.append(f"  const item = await {ent}Repository.getById(String(req.params.{param}));")
            lines.append("  if (!item) return res.status(404).json({ error: 'not_found', message: 'Item not found' });")
            lines.append("  res.json(item);")
            lines.append("});")
        elif wiring.op is Op.CREATE:
            lines.append(f"router.{method}('{rel_express}', {middleware_str}async (req: Request, res: Response) => {{")
            lines.append(f"  const parsed = create{ent}Schema.safeParse(req.body);")
            lines.append("  if (!parsed.success) {")
            lines.append("    return res.status(400).json({ error: 'validation_error', details: parsed.error.format() });")
            lines.append("  }")
            lines.append(f"  const created = await {ent}Repository.create(parsed.data);")
            lines.append("  res.status(201).json(created);")
            lines.append("});")
        elif wiring.op is Op.UPDATE:
            param = wiring.id_param or "id"
            lines.append(f"router.{method}('{rel_express}', {middleware_str}async (req: Request, res: Response) => {{")
            lines.append(f"  const parsed = update{ent}Schema.safeParse(req.body);")
            lines.append("  if (!parsed.success) {")
            lines.append("    return res.status(400).json({ error: 'validation_error', details: parsed.error.format() });")
            lines.append("  }")
            lines.append(f"  const updated = await {ent}Repository.update(String(req.params.{param}), parsed.data);")
            lines.append("  if (!updated) return res.status(404).json({ error: 'not_found', message: 'Item not found' });")
            lines.append("  res.json(updated);")
            lines.append("});")
        elif wiring.op is Op.DELETE:
            param = wiring.id_param or "id"
            lines.append(f"router.{method}('{rel_express}', {middleware_str}async (req: Request, res: Response) => {{")
            lines.append(f"  const ok = await {ent}Repository.delete(String(req.params.{param}));")
            lines.append("  if (!ok) return res.status(404).json({ error: 'not_found', message: 'Item not found' });")
            lines.append("  res.status(204).send();")
            lines.append("});")
        elif wiring.op is Op.LIST_BY:
            param = wiring.id_param or "id"
            fk_col = f"{wiring.relation}_id" if wiring.relation else "parent_id"
            lines.append(f"router.{method}('{rel_express}', {middleware_str}async (req: Request, res: Response) => {{")
            lines.append(f"  const items = await {ent}Repository.listBy('{fk_col}', String(req.params.{param}));")
            lines.append("  res.json(items);")
            lines.append("});")

        lines.append("")


    # R-589: lifecycle transitions. Node has requireAuth but no requireRoles, so the role is checked
    # inline against the roles the token carries; the from-state is checked the same way as in the
    # Python and Go backends. update() here already takes a partial, so no setter is needed.
    for route in transitions:
        allowed = route.transition.sources or route.workflow.states
        allowed_js = ", ".join(f"'{s}'" for s in allowed)
        param = _to_express_path(f"/{{{route.id_param}}}/{route.transition.name}")
        lines.append(f"router.post('{param}', requireAuth, async (req: Request, res: Response) => {{")
        if route.roles:
            roles_js = ", ".join(f"'{r}'" for r in route.roles)
            lines.append(f"  const held: string[] = ((req as any).user?.roles as string[] | undefined) ?? [];")
            lines.append(f"  if (![{roles_js}].some((r) => held.includes(r))) return res.status(403).json({{ error: 'forbidden' }});")
        lines.append(f"  const item = await {route.workflow.entity}Repository.getById(String(req.params.{route.id_param}));")
        lines.append("  if (!item) return res.status(404).json({ error: 'not_found', message: 'Item not found' });")
        lines.append(f"  const allowed = [{allowed_js}];")
        lines.append(f"  if (!allowed.includes((item as any).{route.workflow.field})) return res.status(409).json({{ error: 'conflict', message: `cannot {route.transition.name} from ${{(item as any).{route.workflow.field}}}; allowed from: {', '.join(allowed)}` }});")
        lines.append(f"  const updated = await {route.workflow.entity}Repository.setLifecycle(String(req.params.{route.id_param}), '{route.transition.to}');")
        lines.append("  res.json(updated);")
        lines.append("});")
        lines.append("")
    return "\n".join(lines) + "\n"


def _hono_router_file(
    segment: str,
    apis: list[ApiEndpoint],
    repo_entities: frozenset[str],
    fk_by_entity: dict[str, tuple[str, ...]],
    has_auth: bool,
    transitions: tuple = (),
) -> str:
    lines = [
        f"// Generated by OmniStackAI: Hono Router for {segment}",
        "import { Hono } from 'hono';",
    ]
    if has_auth:
        lines.append("import { requireAuth } from '../middleware/auth.js';")

    used_entities: set[str] = set()
    for api in apis:
        wiring = wire_endpoint(api, repo_entities, fk_by_entity)
        if wiring:
            used_entities.add(wiring.entity)

    for ent in sorted(used_entities):
        lines.append(f"import {{ {ent}Repository }} from '../db/{table_name(ent)}.js';")
        lines.append(f"import {{ create{ent}Schema, update{ent}Schema }} from '../models/validation.js';")

    lines.append("")
    lines.append("export const router = new Hono();")
    lines.append("")

    for api in apis:
        wiring = wire_endpoint(api, repo_entities, fk_by_entity)
        method = api.method.value.lower()
        rel = "/" + "/".join([s for s in api.path.strip("/").split("/")[1:]])
        rel_hono = _to_express_path(rel)  # Hono also uses /:id param syntax
        if not rel_hono:
            rel_hono = "/"

        middleware_str = "requireAuth, " if api.auth else ""

        if not wiring:
            lines.append(f"router.{method}('{rel_hono}', {middleware_str}async (c) => {{")
            lines.append(f"  return c.json({{ detail: 'not_implemented', endpoint: '{api.method.value} {api.path}' }}, 501);")
            lines.append("});")
            lines.append("")
            continue

        ent = wiring.entity
        if wiring.op is Op.LIST:
            lines.append(f"router.{method}('{rel_hono}', {middleware_str}async (c) => {{")
            lines.append("  const limit = c.req.query('limit') ? Number(c.req.query('limit')) : 50;")
            lines.append("  const offset = c.req.query('offset') ? Number(c.req.query('offset')) : 0;")
            lines.append(f"  const items = await {ent}Repository.list({{ limit, offset }});")
            lines.append("  return c.json(items);")
            lines.append("});")
        elif wiring.op is Op.GET:
            param = wiring.id_param or "id"
            lines.append(f"router.{method}('{rel_hono}', {middleware_str}async (c) => {{")
            lines.append(f"  const item = await {ent}Repository.getById(c.req.param('{param}') ?? '');")
            lines.append("  if (!item) return c.json({ error: 'not_found', message: 'Item not found' }, 404);")
            lines.append("  return c.json(item);")
            lines.append("});")
        elif wiring.op is Op.CREATE:
            lines.append(f"router.{method}('{rel_hono}', {middleware_str}async (c) => {{")
            lines.append("  const body = await c.req.json();")
            lines.append(f"  const parsed = create{ent}Schema.safeParse(body);")
            lines.append("  if (!parsed.success) {")
            lines.append("    return c.json({ error: 'validation_error', details: parsed.error.format() }, 400);")
            lines.append("  }")
            lines.append(f"  const created = await {ent}Repository.create(parsed.data);")
            lines.append("  return c.json(created, 201);")
            lines.append("});")
        elif wiring.op is Op.UPDATE:
            param = wiring.id_param or "id"
            lines.append(f"router.{method}('{rel_hono}', {middleware_str}async (c) => {{")
            lines.append("  const body = await c.req.json();")
            lines.append(f"  const parsed = update{ent}Schema.safeParse(body);")
            lines.append("  if (!parsed.success) {")
            lines.append("    return c.json({ error: 'validation_error', details: parsed.error.format() }, 400);")
            lines.append("  }")
            lines.append(f"  const updated = await {ent}Repository.update(c.req.param('{param}') ?? '', parsed.data);")
            lines.append("  if (!updated) return c.json({ error: 'not_found', message: 'Item not found' }, 404);")
            lines.append("  return c.json(updated);")
            lines.append("});")
        elif wiring.op is Op.DELETE:
            param = wiring.id_param or "id"
            lines.append(f"router.{method}('{rel_hono}', {middleware_str}async (c) => {{")
            lines.append(f"  const ok = await {ent}Repository.delete(c.req.param('{param}') ?? '');")
            lines.append("  if (!ok) return c.json({ error: 'not_found', message: 'Item not found' }, 404);")
            lines.append("  return c.body(null, 204);")
            lines.append("});")
        elif wiring.op is Op.LIST_BY:
            param = wiring.id_param or "id"
            fk_col = f"{wiring.relation}_id" if wiring.relation else "parent_id"
            lines.append(f"router.{method}('{rel_hono}', {middleware_str}async (c) => {{")
            lines.append(f"  const items = await {ent}Repository.listBy('{fk_col}', c.req.param('{param}') ?? '');")
            lines.append("  return c.json(items);")
            lines.append("});")

        lines.append("")


    # R-589: lifecycle transitions (see the Express router for the reasoning).
    for route in transitions:
        allowed = route.transition.sources or route.workflow.states
        allowed_js = ", ".join(f"'{s}'" for s in allowed)
        param = _to_express_path(f"/{{{route.id_param}}}/{route.transition.name}")
        lines.append(f"router.post('{param}', requireAuth, async (c) => {{")
        if route.roles:
            roles_js = ", ".join(f"'{r}'" for r in route.roles)
            lines.append("  const held: string[] = (((c as any).get('user') as any)?.roles as string[] | undefined) ?? [];")
            lines.append(f"  if (![{roles_js}].some((r) => held.includes(r))) return c.json({{ error: 'forbidden' }}, 403);")
        lines.append(f"  const item = await {route.workflow.entity}Repository.getById(c.req.param('{route.id_param}') ?? '');")
        lines.append("  if (!item) return c.json({ error: 'not_found', message: 'Item not found' }, 404);")
        lines.append(f"  const allowed = [{allowed_js}];")
        lines.append(f"  if (!allowed.includes((item as any).{route.workflow.field})) return c.json({{ error: 'conflict', message: `cannot {route.transition.name} from ${{(item as any).{route.workflow.field}}}; allowed from: {', '.join(allowed)}` }}, 409);")
        lines.append(f"  const updated = await {route.workflow.entity}Repository.setLifecycle(c.req.param('{route.id_param}') ?? '', '{route.transition.to}');")
        lines.append("  return c.json(updated);")
        lines.append("});")
        lines.append("")
    return "\n".join(lines) + "\n"


def _express_app_file(segments: list[str], has_auth: bool = False) -> str:
    lines = [
        "// Generated by OmniStackAI: Express Application",
        "import express, { Express, Request, Response, NextFunction } from 'express';",
        "import cors from 'cors';",
        "import { config } from './config.js';",
        "import { checkDbHealth } from './db/pool.js';",
    ]
    for seg in sorted(segments):
        lines.append(f"import {{ router as {seg}Router }} from './routes/{seg}.js';")
    if has_auth:
        lines.append("import { router as accountRouter } from './routes/account.js';")

    lines.append("")
    lines.append("export const app: Express = express();")
    lines.append("")
    lines.append("app.use(cors({ origin: config.corsOrigin }));")
    lines.append("app.use(express.json());")
    lines.append("")
    lines.append("// Health Check endpoints")
    lines.append("app.get(['/healthz', '/readyz', '/health'], async (req: Request, res: Response) => {")
    lines.append("  const dbOk = await checkDbHealth();")
    lines.append("  res.json({")
    lines.append("    status: 'ok',")
    lines.append("    timestamp: new Date().toISOString(),")
    lines.append("    database: dbOk ? 'connected' : 'unavailable',")
    lines.append("  });")
    lines.append("});")
    lines.append("")

    for seg in sorted(segments):
        lines.append(f"app.use('/{seg}', {seg}Router);")
    if has_auth:
        lines.append("app.use('/auth', accountRouter);  // R-591: the account flow")

    lines.append("")
    lines.append("// Global error handler")
    lines.append("app.use((err: any, req: Request, res: Response, next: NextFunction) => {")
    # PC-004: the error is logged here and never sent to the client — it used to return err.message,
    # which for a database error carries SQL and schema details.
    # A value the database cannot read (SQLSTATE class 22, e.g. a malformed id) is a 422.
    lines.append("  if (typeof err?.code === 'string' && err.code.startsWith('22')) return res.status(422).json({ detail: 'invalid_value' });")
    lines.append("  const status = err.status || 500;")
    lines.append("  if (status >= 500) console.error(err);")
    lines.append("  res.status(status).json({ detail: status >= 500 ? 'internal_error' : (err.expose ? err.message : 'request_error') });")
    lines.append("});")
    lines.append("")

    return "\n".join(lines) + "\n"


def _hono_app_file(segments: list[str], has_auth: bool = False) -> str:
    lines = [
        "// Generated by OmniStackAI: Hono Application",
        "import { Hono } from 'hono';",
        "import { cors } from 'hono/cors';",
        "import { config } from './config.js';",
        "import { checkDbHealth } from './db/pool.js';",
    ]
    for seg in sorted(segments):
        lines.append(f"import {{ router as {seg}Router }} from './routes/{seg}.js';")
    if has_auth:
        lines.append("import { router as accountRouter } from './routes/account.js';")

    lines.append("")
    lines.append("export const app = new Hono();")
    lines.append("")
    lines.append("app.use('*', cors({ origin: config.corsOrigin }));")
    lines.append("")
    lines.append("// Health Check endpoints")
    lines.append("app.get('/healthz', async (c) => {")
    lines.append("  const dbOk = await checkDbHealth();")
    lines.append("  return c.json({ status: 'ok', timestamp: new Date().toISOString(), database: dbOk ? 'connected' : 'unavailable' });")
    lines.append("});")
    lines.append("app.get('/readyz', async (c) => {")
    lines.append("  const dbOk = await checkDbHealth();")
    lines.append("  return c.json({ status: 'ok', timestamp: new Date().toISOString(), database: dbOk ? 'connected' : 'unavailable' });")
    lines.append("});")
    lines.append("app.get('/health', async (c) => {")
    lines.append("  const dbOk = await checkDbHealth();")
    lines.append("  return c.json({ status: 'ok', timestamp: new Date().toISOString(), database: dbOk ? 'connected' : 'unavailable' });")
    lines.append("});")
    lines.append("")

    for seg in sorted(segments):
        lines.append(f"app.route('/{seg}', {seg}Router);")
    if has_auth:
        lines.append("app.route('/auth', accountRouter);  // R-591: the account flow")
    # PC-004: errors are logged and answered as JSON without internals, as in the Express app.
    lines.append("app.onError((err, c) => {")
    lines.append("  const code = (err as any)?.code;")
    lines.append("  if (typeof code === 'string' && code.startsWith('22')) return c.json({ detail: 'invalid_value' }, 422);")
    lines.append("  console.error(err);")
    lines.append("  return c.json({ detail: 'internal_error' }, 500);")
    lines.append("});")

    lines.append("")
    return "\n".join(lines) + "\n"


def _index_file(framework: str) -> str:
    if framework == "hono":
        return """// Generated by OmniStackAI: Hono Server Entry Point
import { serve } from '@hono/node-server';
import { app } from './app.js';
import { config } from './config.js';

const server = serve({
  fetch: app.fetch,
  port: config.port,
}, (info) => {
  console.log(`[OmniStackAI Hono API] Server listening on port ${info.port}`);
});

process.on('SIGTERM', () => {
  server.close();
  process.exit(0);
});

process.on('SIGINT', () => {
  server.close();
  process.exit(0);
});
"""

    return """// Generated by OmniStackAI: Express Server Entry Point
import { app } from './app.js';
import { config } from './config.js';

const server = app.listen(config.port, () => {
  console.log(`[OmniStackAI Express API] Server listening on port ${config.port}`);
});

process.on('SIGTERM', () => {
  server.close(() => process.exit(0));
});

process.on('SIGINT', () => {
  server.close(() => process.exit(0));
});
"""


def _package_json(app_name: str, framework: str) -> str:
    slug = _slug(app_name)
    if framework == "hono":
        data = {
            "name": f"{slug}-api",
            "version": "0.1.0",
            "private": True,
            "type": "module",
            "scripts": {
                "dev": "tsx watch src/index.ts",
                "build": "tsc",
                "start": "node dist/index.js",
            },
            "dependencies": {
                "@hono/node-server": "^1.13.0",
                "dotenv": "^16.4.5",
                "hono": "^4.6.0",
                "pg": "^8.13.0",
                "zod": "^3.23.8",
            },
            "devDependencies": {
                "@types/node": "^22.7.0",
                "@types/pg": "^8.11.10",
                "tsx": "^4.19.1",
                "typescript": "^5.6.2",
            },
        }
    else:
        data = {
            "name": f"{slug}-api",
            "version": "0.1.0",
            "private": True,
            "type": "module",
            "scripts": {
                "dev": "tsx watch src/index.ts",
                "build": "tsc",
                "start": "node dist/index.js",
            },
            "dependencies": {
                "cors": "^2.8.5",
                "dotenv": "^16.4.5",
                "express": "^5.1.0",
                "pg": "^8.13.0",
                "zod": "^3.23.8",
            },
            "devDependencies": {
                "@types/cors": "^2.8.17",
                "@types/express": "^5.0.3",
                "@types/node": "^22.7.0",
                "@types/pg": "^8.11.10",
                "tsx": "^4.19.1",
                "typescript": "^5.6.2",
            },
        }
    return json.dumps(data, indent=2) + "\n"


def _tsconfig_json() -> str:
    data = {
        "compilerOptions": {
            "target": "ES2022",
            "module": "NodeNext",
            "moduleResolution": "NodeNext",
            "esModuleInterop": True,
            "strict": True,
            "skipLibCheck": True,
            "forceConsistentCasingInFileNames": True,
            "outDir": "./dist",
            "rootDir": "./src",
        },
        "include": ["src/**/*"],
        "exclude": ["node_modules", "dist"],
    }
    return json.dumps(data, indent=2) + "\n"


def _readme_file(app_name: str, framework: str) -> str:
    name = "Hono" if framework == "hono" else "Express"
    return f"""# {app_name} — Node.js Backend API ({name})

This service was generated by OmniStackAI from your Application IR.

## Prerequisites

- Node.js >= 20
- PostgreSQL (required; a database error is reported, never hidden)

## Getting Started

1. Install dependencies:
   ```bash
   npm install
   ```

2. Configure environment:
   ```bash
   cp .env.example .env
   ```

3. Run in development mode:
   ```bash
   npm run dev
   ```
   The API will listen on `http://localhost:8000`.

4. Health check:
   ```bash
   curl http://localhost:8000/healthz
   ```

## Production Build

```bash
npm run build
npm start
```
"""


class NodeBackendAdapter:
    """Framework adapter generating an idiomatic Node.js/TypeScript backend (Express or Hono)."""

    def __init__(self, framework: str = "express") -> None:
        self.framework = framework.lower().strip()
        if self.framework not in ("express", "hono"):
            raise GenerationError(f"unsupported node backend framework: {self.framework!r} (must be 'express' or 'hono')")

    @property
    def target(self) -> GenerationTarget:
        return GenerationTarget.BACKEND_NODE

    def generate(self, ir: ApplicationIR) -> GeneratedProject:
        # Detect if Hono was specifically requested in prompt or description
        framework = self.framework
        if "hono" in ir.description.lower() or "hono" in ir.name.lower():
            framework = "hono"

        files: list[GeneratedFile] = []

        # 1. Project Configuration & Metadata
        files.append(GeneratedFile("package.json", _package_json(ir.name, framework)))
        files.append(GeneratedFile("tsconfig.json", _tsconfig_json()))
        files.append(GeneratedFile(".env.example", "PORT=8000\nDATABASE_URL=postgresql://postgres:postgres@localhost:5432/app\nJWT_SECRET=\nCORS_ORIGIN=*\nNODE_ENV=development\n# Set to 1 only on a developer machine: requests without a token act as a dev admin.\nOMNISTACKAI_DEV_MODE=\n" + EMAIL_ENV_EXAMPLE))
        files.append(GeneratedFile("README.md", _readme_file(ir.name, framework)))

        # 2. Application Entry & Config
        files.append(GeneratedFile("src/index.ts", _index_file(framework)))
        files.append(GeneratedFile("src/config.ts", _config_file()))

        # 3. Models & Validation
        files.append(GeneratedFile("src/models/types.ts", _models_file(ir)))
        files.append(GeneratedFile("src/models/validation.ts", _validation_file(ir)))

        # 4. Database Connection & Repositories
        files.append(GeneratedFile("src/db/pool.ts", _db_pool_file()))
        repo_entities = frozenset(e.name for e in ir.entities)
        for entity in ir.entities:
            files.append(GeneratedFile(
            f"src/db/{table_name(entity.name)}.ts",
            _db_repository_file(entity, next((w for w in workflows_of(ir) if w.entity == entity.name), None)),
        ))

        # 5. Auth Middleware
        has_auth = needs_auth(ir)
        files.append(GeneratedFile("src/auth/core.ts", NODE_AUTH_CORE))
        files.append(GeneratedFile("src/middleware/auth.ts", _auth_file(ir, framework)))
        if has_auth:
            files.append(GeneratedFile(
                "src/routes/account.ts",
                NODE_AUTH_ROUTER_HONO if framework == "hono" else NODE_AUTH_ROUTER_EXPRESS,
            ))

        # 6. Routing Layer
        fk_by_entity = fk_relations(ir)
        apis_by_segment: dict[str, list[ApiEndpoint]] = {}
        for api in ir.apis:
            if has_auth and is_account_route(api.path):
                continue  # R-591: the generated account flow owns /auth/*
            seg = _segment(api.path)
            apis_by_segment.setdefault(seg, []).append(api)

        # If entities exist without explicit APIs, provide default segment for them
        for entity in ir.entities:
            tbl = table_name(entity.name)
            if tbl not in apis_by_segment:
                apis_by_segment[tbl] = []

        segments = sorted(apis_by_segment.keys())

        for seg, apis in apis_by_segment.items():
            if framework == "hono":
                seg_transitions = tuple(r for r in transition_routes(ir) if r.path.strip('/').split('/')[0] == seg)
                router_code = _hono_router_file(seg, apis, repo_entities, fk_by_entity, has_auth, seg_transitions)
            else:
                seg_transitions = tuple(r for r in transition_routes(ir) if r.path.strip('/').split('/')[0] == seg)
                router_code = _express_router_file(seg, apis, repo_entities, fk_by_entity, has_auth, seg_transitions)
            files.append(GeneratedFile(f"src/routes/{seg}.ts", router_code))

        # 7. Main Application Assembly
        if framework == "hono":
            files.append(GeneratedFile("src/app.ts", _hono_app_file(segments, has_auth)))
        else:
            files.append(GeneratedFile("src/app.ts", _express_app_file(segments, has_auth)))

        # 8. Schema and Seed SQL
        if ir.project_strategy.database_strategy is DatabaseStrategy.POSTGRES:
            files.append(GeneratedFile("schema.sql", render_postgres_schema(ir)))
            files.append(GeneratedFile("seed.sql", render_postgres_seed(ir)))

        # 9. OpenAPI Contract
        if ir.apis:
            files.append(GeneratedFile("contracts/openapi.json", render_openapi_json(ir)))

        return GeneratedProject(GenerationTarget.BACKEND_NODE.value, files)


class ExpressBackendAdapter(NodeBackendAdapter):
    """Convenience alias for NodeBackendAdapter with framework='express'."""

    def __init__(self) -> None:
        super().__init__(framework="express")


class HonoBackendAdapter(NodeBackendAdapter):
    """Convenience alias for NodeBackendAdapter with framework='hono'."""

    def __init__(self) -> None:
        super().__init__(framework="hono")


def _node_lifecycle_setter(table: str, col_list: str, entity_name: str, workflow) -> str:
    """R-590: the one way to change a lifecycle field, used only by the transition routes.

    Transitions used to call the ordinary `update`, which no longer writes the lifecycle field —
    it would have made every Node transition a silent no-op. Python and Go already had a setter.
    """
    if workflow is None:
        return ""
    field = sql_identifier(workflow.field)
    return (
        f"  static async setLifecycle(id: string, value: string): Promise<{entity_name} | null> {{\n"
        f"    const query = `UPDATE {sql_identifier(table)} SET {field} = $2 WHERE id = $1 RETURNING {col_list}`;\n"
        f"    const result = await pool.query(query, [id, value]);\n"
        f"    return (result.rows[0] as {entity_name}) ?? null;\n"
        f"  }}\n"
    )
