"""Node.js backend framework adapter (Express / Hono).

Turns an Application IR into a real, production-ready Node.js/TypeScript backend as a `GeneratedProject`:
- TypeScript entity models and Zod validation schemas from IR entities;
- Express or Hono routers from IR APIs (grouped by resource segment) with full CRUD wiring via `route_wiring.py`;
- PostgreSQL connection pool (`pg`) with parameterized queries and fallback in-memory repository;
- JWT authentication guard with Bearer token verification;
- Application entry point with CORS, JSON body parser, health checks (/healthz, /readyz, /health), and graceful shutdown;
- Packaging files: package.json (ESM), tsconfig.json, .env.example, README.md;
- OpenAPI 3.1 contract (`contracts/openapi.json`), PostgreSQL schema.sql, and seed.sql.

Pure and deterministic — nothing is installed, built, run, or written to disk here.
"""

from __future__ import annotations

import json
import re
from typing import Any

from ..application_ir import (
    ApiEndpoint,
    ApplicationIR,
    DatabaseStrategy,
    Entity,
    Field,
    FieldType,
)
from .adapter import FrameworkAdapter, GenerationTarget
from .auth_guard import needs_auth
from .errors import GenerationError
from .field_validation import filter_fields, parse_field_rules
from .files import GeneratedFile, GeneratedProject
from .openapi import render_openapi_json
from .route_wiring import Op, fk_relations, wire_endpoint
from .schema_sql import render_postgres_schema, sql_identifier, table_name
from .seed_sql import render_postgres_seed

_TS_TYPE: dict[FieldType, str] = {
    FieldType.STRING: "string",
    FieldType.TEXT: "string",
    FieldType.UUID: "string",
    FieldType.INT: "number",
    FieldType.FLOAT: "number",
    FieldType.BOOL: "boolean",
    FieldType.DATETIME: "Date | string",
    FieldType.JSON: "Record<string, unknown> | unknown[]",
    FieldType.ATTACHMENT: "string",
}


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-") or "app"


def _segment(path: str) -> str:
    first = path.strip("/").split("/")[0] if path.strip("/") else ""
    module = re.sub(r"\W+", "_", first).strip("_").lower()
    return module or "root"


def _pascal(value: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^A-Za-z0-9]+", value) if part)


def _camel(value: str) -> str:
    p = _pascal(value)
    return p[:1].lower() + p[1:] if p else "item"


def _path_params(path: str) -> list[str]:
    return re.findall(r"\{(\w+)\}", path)


def _to_express_path(path: str) -> str:
    # Converts /users/{id} to /users/:id
    return re.sub(r"\{(\w+)\}", r":\1", path)


def _models_file(ir: ApplicationIR) -> str:
    lines = [
        "// Generated by OmniStackAI: TypeScript Entity Models",
        "",
    ]
    if not ir.entities:
        lines.append("// No entities defined in the IR.")
        return "\n".join(lines) + "\n"

    for entity in ir.entities:
        declared_names = {f.name for f in entity.fields}
        lines.append(f"export interface {entity.name} {{")
        for field in entity.fields:
            ts_type = _TS_TYPE[field.type]
            opt = "" if field.required else "?"
            lines.append(f"  {field.name}{opt}: {ts_type};")

        # Auto audit fields if not already explicitly declared
        if "created_at" not in declared_names:
            lines.append("  created_at?: Date | string;")
        if "updated_at" not in declared_names:
            lines.append("  updated_at?: Date | string;")

        if entity.relations:
            lines.append("  // Relations")
            for rel in entity.relations:
                lines.append(f"  // {rel.name} -> {rel.target_entity} ({rel.kind.value})")

        lines.append("}")
        lines.append("")

        # Create input type (omits auto id / created_at / updated_at)
        lines.append(f"export type Create{entity.name}Input = Omit<{entity.name}, 'id' | 'created_at' | 'updated_at'>;")
        lines.append(f"export type Update{entity.name}Input = Partial<Create{entity.name}Input>;")
        lines.append("")

    return "\n".join(lines) + "\n"


def _zod_field_schema(field: Field, rules: Any) -> str:
    if rules.enum:
        literals = ", ".join(f"'{v}'" for v in rules.enum)
        base = f"z.enum([{literals}])"
    elif field.type in (FieldType.STRING, FieldType.TEXT):
        base = "z.string()"
        if rules.max_length is not None:
            base += f".max({rules.max_length})"
    elif field.type is FieldType.UUID:
        base = "z.string().uuid()"
    elif field.type is FieldType.INT:
        base = "z.number().int()"
        if rules.minimum is not None:
            base += f".min({rules.minimum})"
        if rules.maximum is not None:
            base += f".max({rules.maximum})"
    elif field.type is FieldType.FLOAT:
        base = "z.number()"
        if rules.minimum is not None:
            base += f".min({rules.minimum})"
        if rules.maximum is not None:
            base += f".max({rules.maximum})"
    elif field.type is FieldType.BOOL:
        base = "z.boolean()"
    elif field.type is FieldType.DATETIME:
        base = "z.union([z.string().datetime(), z.date()])"
    elif field.type is FieldType.JSON:
        base = "z.union([z.record(z.unknown()), z.array(z.unknown())])"
    else:
        base = "z.string()"

    if not field.required:
        base += ".optional()"
    return base


def _validation_file(ir: ApplicationIR) -> str:
    lines = [
        "// Generated by OmniStackAI: Zod Validation Schemas",
        "import { z } from 'zod';",
        "",
    ]
    if not ir.entities:
        lines.append("// No entity validation required.")
        return "\n".join(lines) + "\n"

    for entity in ir.entities:
        lines.append(f"export const create{entity.name}Schema = z.object({{")
        for field in entity.fields:
            if field.name in ("id", "created_at", "updated_at"):
                continue
            rules = parse_field_rules(field)
            zod_expr = _zod_field_schema(field, rules)
            lines.append(f"  {field.name}: {zod_expr},")
        lines.append("});")
        lines.append("")
        lines.append(f"export const update{entity.name}Schema = create{entity.name}Schema.partial();")
        lines.append("")

    return "\n".join(lines) + "\n"


def _config_file() -> str:
    return """// Generated by OmniStackAI: Server Configuration
import 'dotenv/config';

export interface AppConfig {
  port: number;
  databaseUrl: string;
  jwtSecret: string;
  corsOrigin: string;
  nodeEnv: string;
}

export const config: AppConfig = {
  port: Number(process.env.PORT) || 8000,
  databaseUrl: process.env.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5432/app',
  jwtSecret: process.env.JWT_SECRET || 'dev-secret-change-in-production',
  corsOrigin: process.env.CORS_ORIGIN || '*',
  nodeEnv: process.env.NODE_ENV || 'development',
};
"""


def _auth_file(ir: ApplicationIR, framework: str) -> str:
    roles = ", ".join(f"'{role.id}'" for role in ir.roles)
    roles_type = " | ".join(f"'{role.id}'" for role in ir.roles) if ir.roles else "string"

    if framework == "hono":
        return f"""// Generated by OmniStackAI: Hono JWT Authentication Guard
import {{ Context, Next }} from 'hono';
import * as crypto from 'node:crypto';
import {{ config }} from '../config.js';

export const ROLES = [{roles}] as const;
export type UserRole = {roles_type};

export interface AuthClaims {{
  sub: string;
  email?: string;
  roles?: UserRole[];
  [key: string]: unknown;
}}

function verifyToken(token: string, secret: string): AuthClaims | null {{
  try {{
    const parts = token.split('.');
    if (parts.length !== 3) return null;
    const [headerB64, payloadB64, signatureB64] = parts;
    const expectedSig = crypto
      .createHmac('sha256', secret)
      .update(`${{headerB64}}.${{payloadB64}}`)
      .digest('base64url');
    if (signatureB64 !== expectedSig) return null;
    return JSON.parse(Buffer.from(payloadB64, 'base64url').toString('utf-8')) as AuthClaims;
  }} catch {{
    return null;
  }}
}}

export async function requireAuth(c: Context, next: Next) {{
  const authHeader = c.req.header('Authorization');
  const secret = config.jwtSecret;

  // Development bypass when running in dev mode or with known dev secret
  if (!authHeader || !authHeader.startsWith('Bearer ')) {{
    if (process.env.OMNISTACKAI_DEV_MODE === '1' || secret.includes('dev-secret')) {{
      c.set('user', {{ sub: 'dev-admin', roles: [...ROLES], email: 'admin@example.local' }});
      return await next();
    }}
    return c.json({{ error: 'unauthorized', message: 'Missing or invalid Authorization header' }}, 401);
  }}

  const token = authHeader.slice(7).trim();
  const claims = verifyToken(token, secret);
  if (!claims) {{
    return c.json({{ error: 'unauthorized', message: 'Invalid or expired token' }}, 401);
  }}

  c.set('user', claims);
  await next();
}}
"""
    # Default: Express
    return f"""// Generated by OmniStackAI: Express JWT Authentication Guard
import {{ Request, Response, NextFunction }} from 'express';
import * as crypto from 'node:crypto';
import {{ config }} from '../config.js';

export const ROLES = [{roles}] as const;
export type UserRole = {roles_type};

export interface AuthClaims {{
  sub: string;
  email?: string;
  roles?: UserRole[];
  [key: string]: unknown;
}}

export interface AuthenticatedRequest extends Request {{
  user?: AuthClaims;
}}

function verifyToken(token: string, secret: string): AuthClaims | null {{
  try {{
    const parts = token.split('.');
    if (parts.length !== 3) return null;
    const [headerB64, payloadB64, signatureB64] = parts;
    const expectedSig = crypto
      .createHmac('sha256', secret)
      .update(`${{headerB64}}.${{payloadB64}}`)
      .digest('base64url');
    if (signatureB64 !== expectedSig) return null;
    return JSON.parse(Buffer.from(payloadB64, 'base64url').toString('utf-8')) as AuthClaims;
  }} catch {{
    return null;
  }}
}}

export function requireAuth(req: AuthenticatedRequest, res: Response, next: NextFunction) {{
  const authHeader = req.headers.authorization;
  const secret = config.jwtSecret;

  // Development bypass when running in dev mode or with known dev secret
  if (!authHeader || !authHeader.startsWith('Bearer ')) {{
    if (process.env.OMNISTACKAI_DEV_MODE === '1' || secret.includes('dev-secret')) {{
      req.user = {{ sub: 'dev-admin', roles: [...ROLES], email: 'admin@example.local' }};
      return next();
    }}
    return res.status(401).json({{ error: 'unauthorized', message: 'Missing or invalid Authorization header' }});
  }}

  const token = authHeader.slice(7).trim();
  const claims = verifyToken(token, secret);
  if (!claims) {{
    return res.status(401).json({{ error: 'unauthorized', message: 'Invalid or expired token' }});
  }}

  req.user = claims;
  next();
}}
"""


def _db_pool_file() -> str:
    return """// Generated by OmniStackAI: PostgreSQL Connection Pool
import pg from 'pg';
import { config } from '../config.js';

const { Pool } = pg;

export const pool = new Pool({
  connectionString: config.databaseUrl,
  max: 20,
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 5000,
});

export async function checkDbHealth(): Promise<boolean> {
  try {
    const res = await pool.query('SELECT 1 as healthy');
    return res.rows.length > 0;
  } catch (err) {
    return false;
  }
}
"""


def _db_repository_file(entity: Entity) -> str:
    tbl = table_name(entity.name)
    ins_cols = [f.name for f in entity.fields if f.name not in ("id", "created_at", "updated_at")]
    col_list = ", ".join(sql_identifier(f.name) for f in entity.fields)
    ins_col_list = ", ".join(sql_identifier(c) for c in ins_cols)
    placeholders = ", ".join(f"${i+1}" for i in range(len(ins_cols)))

    return f"""// Generated by OmniStackAI: {entity.name} Repository
import {{ pool }} from './pool.js';
import type {{ {entity.name}, Create{entity.name}Input, Update{entity.name}Input }} from '../models/types.js';

// In-memory store fallback when PostgreSQL database is unavailable
const memoryStore = new Map<string, {entity.name}>();

export class {entity.name}Repository {{
  static async list(options: {{ limit?: number; offset?: number; search?: string }} = {{}}): Promise<{entity.name}[]> {{
    const limit = options.limit || 50;
    const offset = options.offset || 0;
    try {{
      const query = 'SELECT {col_list} FROM {sql_identifier(tbl)} LIMIT $1 OFFSET $2';
      const result = await pool.query(query, [limit, offset]);
      return result.rows as {entity.name}[];
    }} catch {{
      // Fallback to in-memory store
      return Array.from(memoryStore.values()).slice(offset, offset + limit);
    }}
  }}

  static async getById(id: string): Promise<{entity.name} | null> {{
    try {{
      const query = 'SELECT {col_list} FROM {sql_identifier(tbl)} WHERE id = $1';
      const result = await pool.query(query, [id]);
      if (result.rows.length === 0) return null;
      return result.rows[0] as {entity.name};
    }} catch {{
      return memoryStore.get(id) || null;
    }}
  }}

  static async create(input: Create{entity.name}Input): Promise<{entity.name}> {{
    const id = (input as any).id || (typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : String(Date.now()));
    try {{
      const cols = [{", ".join(f"input.{c}" for c in ins_cols)}];
      const query = `
        INSERT INTO {sql_identifier(tbl)} (id, {ins_col_list})
        VALUES ($1, {", ".join(f"${i+2}" for i in range(len(ins_cols)))})
        RETURNING {col_list}
      `;
      const result = await pool.query(query, [id, ...cols]);
      return result.rows[0] as {entity.name};
    }} catch {{
      const record = {{ ...input, id, created_at: new Date(), updated_at: new Date() }} as unknown as {entity.name};
      memoryStore.set(id, record);
      return record;
    }}
  }}

  static async update(id: string, input: Update{entity.name}Input): Promise<{entity.name} | null> {{
    const existing = await this.getById(id);
    if (!existing) return null;

    try {{
      const keys = Object.keys(input);
      if (keys.length === 0) return existing;
      const setClauses = keys.map((k, idx) => `"${{k}}" = $${{idx + 2}}`).join(', ');
      const values = keys.map((k) => (input as any)[k]);
      const query = `UPDATE {sql_identifier(tbl)} SET ${{setClauses}} WHERE id = $1 RETURNING {col_list}`;
      const result = await pool.query(query, [id, ...values]);
      return result.rows[0] as {entity.name};
    }} catch {{
      const updated = {{ ...existing, ...input, updated_at: new Date() }} as {entity.name};
      memoryStore.set(id, updated);
      return updated;
    }}
  }}

  static async delete(id: string): Promise<boolean> {{
    try {{
      const query = 'DELETE FROM {sql_identifier(tbl)} WHERE id = $1';
      const result = await pool.query(query, [id]);
      return (result.rowCount ?? 0) > 0;
    }} catch {{
      return memoryStore.delete(id);
    }}
  }}

  static async listBy(relationCol: string, parentId: string): Promise<{entity.name}[]> {{
    try {{
      const query = `SELECT {col_list} FROM {sql_identifier(tbl)} WHERE "${{relationCol}}" = $1`;
      const result = await pool.query(query, [parentId]);
      return result.rows as {entity.name}[];
    }} catch {{
      return Array.from(memoryStore.values()).filter((item: any) => item[relationCol] === parentId);
    }}
  }}
}}
"""


def _express_router_file(
    segment: str,
    apis: list[ApiEndpoint],
    repo_entities: frozenset[str],
    fk_by_entity: dict[str, tuple[str, ...]],
    has_auth: bool,
) -> str:
    lines = [
        f"// Generated by OmniStackAI: Express Router for {segment}",
        "import { Router, Request, Response } from 'express';",
    ]
    if has_auth:
        lines.append("import { requireAuth } from '../middleware/auth.js';")

    # Determine required models, repositories, and schemas
    used_entities: set[str] = set()
    for api in apis:
        wiring = wire_endpoint(api, repo_entities, fk_by_entity)
        if wiring:
            used_entities.add(wiring.entity)

    for ent in sorted(used_entities):
        lines.append(f"import {{ {ent}Repository }} from '../db/{table_name(ent)}.js';")
        lines.append(f"import {{ create{ent}Schema, update{ent}Schema }} from '../models/validation.js';")

    lines.append("")
    lines.append("export const router = Router();")
    lines.append("")

    for api in apis:
        wiring = wire_endpoint(api, repo_entities, fk_by_entity)
        method = api.method.value.lower()
        # Relative path within this segment's router
        # If api.path is /users/:id, and mounted on /api/users, rel_path is /:id
        rel = "/" + "/".join([s for s in api.path.strip("/").split("/")[1:]])
        rel_express = _to_express_path(rel)
        if not rel_express:
            rel_express = "/"

        middleware_str = "requireAuth, " if api.auth else ""

        if not wiring:
            lines.append(f"router.{method}('{rel_express}', {middleware_str}async (req: Request, res: Response) => {{")
            lines.append(f"  // Scaffold for custom API endpoint: {api.method.value} {api.path}")
            lines.append(f"  res.json({{ message: '{api.path}' }});")
            lines.append("});")
            lines.append("")
            continue

        ent = wiring.entity
        if wiring.op is Op.LIST:
            lines.append(f"router.{method}('{rel_express}', {middleware_str}async (req: Request, res: Response) => {{")
            lines.append("  const limit = req.query.limit ? Number(req.query.limit) : 50;")
            lines.append("  const offset = req.query.offset ? Number(req.query.offset) : 0;")
            lines.append(f"  const items = await {ent}Repository.list({{ limit, offset }});")
            lines.append("  res.json(items);")
            lines.append("});")
        elif wiring.op is Op.GET:
            param = wiring.id_param or "id"
            lines.append(f"router.{method}('{rel_express}', {middleware_str}async (req: Request, res: Response) => {{")
            lines.append(f"  const item = await {ent}Repository.getById(req.params.{param});")
            lines.append("  if (!item) return res.status(404).json({ error: 'not_found', message: 'Item not found' });")
            lines.append("  res.json(item);")
            lines.append("});")
        elif wiring.op is Op.CREATE:
            lines.append(f"router.{method}('{rel_express}', {middleware_str}async (req: Request, res: Response) => {{")
            lines.append(f"  const parsed = create{ent}Schema.safeParse(req.body);")
            lines.append("  if (!parsed.success) {")
            lines.append("    return res.status(400).json({ error: 'validation_error', details: parsed.error.format() });")
            lines.append("  }")
            lines.append(f"  const created = await {ent}Repository.create(parsed.data);")
            lines.append("  res.status(201).json(created);")
            lines.append("});")
        elif wiring.op is Op.UPDATE:
            param = wiring.id_param or "id"
            lines.append(f"router.{method}('{rel_express}', {middleware_str}async (req: Request, res: Response) => {{")
            lines.append(f"  const parsed = update{ent}Schema.safeParse(req.body);")
            lines.append("  if (!parsed.success) {")
            lines.append("    return res.status(400).json({ error: 'validation_error', details: parsed.error.format() });")
            lines.append("  }")
            lines.append(f"  const updated = await {ent}Repository.update(req.params.{param}, parsed.data);")
            lines.append("  if (!updated) return res.status(404).json({ error: 'not_found', message: 'Item not found' });")
            lines.append("  res.json(updated);")
            lines.append("});")
        elif wiring.op is Op.DELETE:
            param = wiring.id_param or "id"
            lines.append(f"router.{method}('{rel_express}', {middleware_str}async (req: Request, res: Response) => {{")
            lines.append(f"  const ok = await {ent}Repository.delete(req.params.{param});")
            lines.append("  if (!ok) return res.status(404).json({ error: 'not_found', message: 'Item not found' });")
            lines.append("  res.status(204).send();")
            lines.append("});")
        elif wiring.op is Op.LIST_BY:
            param = wiring.id_param or "id"
            fk_col = f"{wiring.relation}_id" if wiring.relation else "parent_id"
            lines.append(f"router.{method}('{rel_express}', {middleware_str}async (req: Request, res: Response) => {{")
            lines.append(f"  const items = await {ent}Repository.listBy('{fk_col}', req.params.{param});")
            lines.append("  res.json(items);")
            lines.append("});")

        lines.append("")

    return "\n".join(lines) + "\n"


def _hono_router_file(
    segment: str,
    apis: list[ApiEndpoint],
    repo_entities: frozenset[str],
    fk_by_entity: dict[str, tuple[str, ...]],
    has_auth: bool,
) -> str:
    lines = [
        f"// Generated by OmniStackAI: Hono Router for {segment}",
        "import { Hono } from 'hono';",
    ]
    if has_auth:
        lines.append("import { requireAuth } from '../middleware/auth.js';")

    used_entities: set[str] = set()
    for api in apis:
        wiring = wire_endpoint(api, repo_entities, fk_by_entity)
        if wiring:
            used_entities.add(wiring.entity)

    for ent in sorted(used_entities):
        lines.append(f"import {{ {ent}Repository }} from '../db/{table_name(ent)}.js';")
        lines.append(f"import {{ create{ent}Schema, update{ent}Schema }} from '../models/validation.js';")

    lines.append("")
    lines.append("export const router = new Hono();")
    lines.append("")

    for api in apis:
        wiring = wire_endpoint(api, repo_entities, fk_by_entity)
        method = api.method.value.lower()
        rel = "/" + "/".join([s for s in api.path.strip("/").split("/")[1:]])
        rel_hono = _to_express_path(rel)  # Hono also uses /:id param syntax
        if not rel_hono:
            rel_hono = "/"

        middleware_str = "requireAuth, " if api.auth else ""

        if not wiring:
            lines.append(f"router.{method}('{rel_hono}', {middleware_str}async (c) => {{")
            lines.append(f"  return c.json({{ message: '{api.path}' }});")
            lines.append("});")
            lines.append("")
            continue

        ent = wiring.entity
        if wiring.op is Op.LIST:
            lines.append(f"router.{method}('{rel_hono}', {middleware_str}async (c) => {{")
            lines.append("  const limit = c.req.query('limit') ? Number(c.req.query('limit')) : 50;")
            lines.append("  const offset = c.req.query('offset') ? Number(c.req.query('offset')) : 0;")
            lines.append(f"  const items = await {ent}Repository.list({{ limit, offset }});")
            lines.append("  return c.json(items);")
            lines.append("});")
        elif wiring.op is Op.GET:
            param = wiring.id_param or "id"
            lines.append(f"router.{method}('{rel_hono}', {middleware_str}async (c) => {{")
            lines.append(f"  const item = await {ent}Repository.getById(c.req.param('{param}'));")
            lines.append("  if (!item) return c.json({ error: 'not_found', message: 'Item not found' }, 404);")
            lines.append("  return c.json(item);")
            lines.append("});")
        elif wiring.op is Op.CREATE:
            lines.append(f"router.{method}('{rel_hono}', {middleware_str}async (c) => {{")
            lines.append("  const body = await c.req.json();")
            lines.append(f"  const parsed = create{ent}Schema.safeParse(body);")
            lines.append("  if (!parsed.success) {")
            lines.append("    return c.json({ error: 'validation_error', details: parsed.error.format() }, 400);")
            lines.append("  }")
            lines.append(f"  const created = await {ent}Repository.create(parsed.data);")
            lines.append("  return c.json(created, 201);")
            lines.append("});")
        elif wiring.op is Op.UPDATE:
            param = wiring.id_param or "id"
            lines.append(f"router.{method}('{rel_hono}', {middleware_str}async (c) => {{")
            lines.append("  const body = await c.req.json();")
            lines.append(f"  const parsed = update{ent}Schema.safeParse(body);")
            lines.append("  if (!parsed.success) {")
            lines.append("    return c.json({ error: 'validation_error', details: parsed.error.format() }, 400);")
            lines.append("  }")
            lines.append(f"  const updated = await {ent}Repository.update(c.req.param('{param}'), parsed.data);")
            lines.append("  if (!updated) return c.json({ error: 'not_found', message: 'Item not found' }, 404);")
            lines.append("  return c.json(updated);")
            lines.append("});")
        elif wiring.op is Op.DELETE:
            param = wiring.id_param or "id"
            lines.append(f"router.{method}('{rel_hono}', {middleware_str}async (c) => {{")
            lines.append(f"  const ok = await {ent}Repository.delete(c.req.param('{param}'));")
            lines.append("  if (!ok) return c.json({ error: 'not_found', message: 'Item not found' }, 404);")
            lines.append("  return c.body(null, 204);")
            lines.append("});")
        elif wiring.op is Op.LIST_BY:
            param = wiring.id_param or "id"
            fk_col = f"{wiring.relation}_id" if wiring.relation else "parent_id"
            lines.append(f"router.{method}('{rel_hono}', {middleware_str}async (c) => {{")
            lines.append(f"  const items = await {ent}Repository.listBy('{fk_col}', c.req.param('{param}'));")
            lines.append("  return c.json(items);")
            lines.append("});")

        lines.append("")

    return "\n".join(lines) + "\n"


def _express_app_file(segments: list[str]) -> str:
    lines = [
        "// Generated by OmniStackAI: Express Application",
        "import express, { Express, Request, Response, NextFunction } from 'express';",
        "import cors from 'cors';",
        "import { config } from './config.js';",
        "import { checkDbHealth } from './db/pool.js';",
    ]
    for seg in sorted(segments):
        lines.append(f"import {{ router as {seg}Router }} from './routes/{seg}.js';")

    lines.append("")
    lines.append("export const app: Express = express();")
    lines.append("")
    lines.append("app.use(cors({ origin: config.corsOrigin }));")
    lines.append("app.use(express.json());")
    lines.append("")
    lines.append("// Health Check endpoints")
    lines.append("app.get(['/healthz', '/readyz', '/health'], async (req: Request, res: Response) => {")
    lines.append("  const dbOk = await checkDbHealth();")
    lines.append("  res.json({")
    lines.append("    status: 'ok',")
    lines.append("    timestamp: new Date().toISOString(),")
    lines.append("    database: dbOk ? 'connected' : 'in-memory',")
    lines.append("  });")
    lines.append("});")
    lines.append("")

    for seg in sorted(segments):
        lines.append(f"app.use('/api/{seg}', {seg}Router);")

    lines.append("")
    lines.append("// Global error handler")
    lines.append("app.use((err: any, req: Request, res: Response, next: NextFunction) => {")
    lines.append("  const status = err.status || 500;")
    lines.append("  res.status(status).json({ error: 'internal_server_error', message: err.message || 'An unexpected error occurred' });")
    lines.append("});")
    lines.append("")

    return "\n".join(lines) + "\n"


def _hono_app_file(segments: list[str]) -> str:
    lines = [
        "// Generated by OmniStackAI: Hono Application",
        "import { Hono } from 'hono';",
        "import { cors } from 'hono/cors';",
        "import { config } from './config.js';",
        "import { checkDbHealth } from './db/pool.js';",
    ]
    for seg in sorted(segments):
        lines.append(f"import {{ router as {seg}Router }} from './routes/{seg}.js';")

    lines.append("")
    lines.append("export const app = new Hono();")
    lines.append("")
    lines.append("app.use('*', cors({ origin: config.corsOrigin }));")
    lines.append("")
    lines.append("// Health Check endpoints")
    lines.append("app.get('/healthz', async (c) => {")
    lines.append("  const dbOk = await checkDbHealth();")
    lines.append("  return c.json({ status: 'ok', timestamp: new Date().toISOString(), database: dbOk ? 'connected' : 'in-memory' });")
    lines.append("});")
    lines.append("app.get('/readyz', async (c) => {")
    lines.append("  const dbOk = await checkDbHealth();")
    lines.append("  return c.json({ status: 'ok', timestamp: new Date().toISOString(), database: dbOk ? 'connected' : 'in-memory' });")
    lines.append("});")
    lines.append("app.get('/health', async (c) => {")
    lines.append("  const dbOk = await checkDbHealth();")
    lines.append("  return c.json({ status: 'ok', timestamp: new Date().toISOString(), database: dbOk ? 'connected' : 'in-memory' });")
    lines.append("});")
    lines.append("")

    for seg in sorted(segments):
        lines.append(f"app.route('/api/{seg}', {seg}Router);")

    lines.append("")
    return "\n".join(lines) + "\n"


def _index_file(framework: str) -> str:
    if framework == "hono":
        return """// Generated by OmniStackAI: Hono Server Entry Point
import { serve } from '@hono/node-server';
import { app } from './app.js';
import { config } from './config.js';

const server = serve({
  fetch: app.fetch,
  port: config.port,
}, (info) => {
  console.log(`[OmniStackAI Hono API] Server listening on port ${info.port}`);
});

process.on('SIGTERM', () => {
  server.close();
  process.exit(0);
});

process.on('SIGINT', () => {
  server.close();
  process.exit(0);
});
"""

    return """// Generated by OmniStackAI: Express Server Entry Point
import { app } from './app.js';
import { config } from './config.js';

const server = app.listen(config.port, () => {
  console.log(`[OmniStackAI Express API] Server listening on port ${config.port}`);
});

process.on('SIGTERM', () => {
  server.close(() => process.exit(0));
});

process.on('SIGINT', () => {
  server.close(() => process.exit(0));
});
"""


def _package_json(app_name: str, framework: str) -> str:
    slug = _slug(app_name)
    if framework == "hono":
        data = {
            "name": f"{slug}-api",
            "version": "0.1.0",
            "private": True,
            "type": "module",
            "scripts": {
                "dev": "tsx watch src/index.ts",
                "build": "tsc",
                "start": "node dist/index.js",
            },
            "dependencies": {
                "@hono/node-server": "^1.13.0",
                "dotenv": "^16.4.5",
                "hono": "^4.6.0",
                "pg": "^8.13.0",
                "zod": "^3.23.8",
            },
            "devDependencies": {
                "@types/node": "^22.7.0",
                "@types/pg": "^8.11.10",
                "tsx": "^4.19.1",
                "typescript": "^5.6.2",
            },
        }
    else:
        data = {
            "name": f"{slug}-api",
            "version": "0.1.0",
            "private": True,
            "type": "module",
            "scripts": {
                "dev": "tsx watch src/index.ts",
                "build": "tsc",
                "start": "node dist/index.js",
            },
            "dependencies": {
                "cors": "^2.8.5",
                "dotenv": "^16.4.5",
                "express": "^4.21.0",
                "pg": "^8.13.0",
                "zod": "^3.23.8",
            },
            "devDependencies": {
                "@types/cors": "^2.8.17",
                "@types/express": "^4.17.21",
                "@types/node": "^22.7.0",
                "@types/pg": "^8.11.10",
                "tsx": "^4.19.1",
                "typescript": "^5.6.2",
            },
        }
    return json.dumps(data, indent=2) + "\n"


def _tsconfig_json() -> str:
    data = {
        "compilerOptions": {
            "target": "ES2022",
            "module": "NodeNext",
            "moduleResolution": "NodeNext",
            "esModuleInterop": True,
            "strict": True,
            "skipLibCheck": True,
            "forceConsistentCasingInFileNames": True,
            "outDir": "./dist",
            "rootDir": "./src",
        },
        "include": ["src/**/*"],
        "exclude": ["node_modules", "dist"],
    }
    return json.dumps(data, indent=2) + "\n"


def _readme_file(app_name: str, framework: str) -> str:
    name = "Hono" if framework == "hono" else "Express"
    return f"""# {app_name} — Node.js Backend API ({name})

This service was generated by OmniStackAI from your Application IR.

## Prerequisites

- Node.js >= 20
- PostgreSQL (optional, falls back to in-memory store)

## Getting Started

1. Install dependencies:
   ```bash
   npm install
   ```

2. Configure environment:
   ```bash
   cp .env.example .env
   ```

3. Run in development mode:
   ```bash
   npm run dev
   ```
   The API will listen on `http://localhost:8000`.

4. Health check:
   ```bash
   curl http://localhost:8000/healthz
   ```

## Production Build

```bash
npm run build
npm start
```
"""


class NodeBackendAdapter:
    """Framework adapter generating an idiomatic Node.js/TypeScript backend (Express or Hono)."""

    def __init__(self, framework: str = "express") -> None:
        self.framework = framework.lower().strip()
        if self.framework not in ("express", "hono"):
            raise GenerationError(f"unsupported node backend framework: {self.framework!r} (must be 'express' or 'hono')")

    @property
    def target(self) -> GenerationTarget:
        return GenerationTarget.BACKEND_NODE

    def generate(self, ir: ApplicationIR) -> GeneratedProject:
        # Detect if Hono was specifically requested in prompt or description
        framework = self.framework
        if "hono" in ir.description.lower() or "hono" in ir.name.lower():
            framework = "hono"

        files: list[GeneratedFile] = []

        # 1. Project Configuration & Metadata
        files.append(GeneratedFile("package.json", _package_json(ir.name, framework)))
        files.append(GeneratedFile("tsconfig.json", _tsconfig_json()))
        files.append(GeneratedFile(".env.example", "PORT=8000\nDATABASE_URL=postgresql://postgres:postgres@localhost:5432/app\nJWT_SECRET=dev-secret-change-in-production\nCORS_ORIGIN=*\nNODE_ENV=development\n"))
        files.append(GeneratedFile("README.md", _readme_file(ir.name, framework)))

        # 2. Application Entry & Config
        files.append(GeneratedFile("src/index.ts", _index_file(framework)))
        files.append(GeneratedFile("src/config.ts", _config_file()))

        # 3. Models & Validation
        files.append(GeneratedFile("src/models/types.ts", _models_file(ir)))
        files.append(GeneratedFile("src/models/validation.ts", _validation_file(ir)))

        # 4. Database Connection & Repositories
        files.append(GeneratedFile("src/db/pool.ts", _db_pool_file()))
        repo_entities = frozenset(e.name for e in ir.entities)
        for entity in ir.entities:
            files.append(GeneratedFile(f"src/db/{table_name(entity.name)}.ts", _db_repository_file(entity)))

        # 5. Auth Middleware
        has_auth = needs_auth(ir)
        files.append(GeneratedFile("src/middleware/auth.ts", _auth_file(ir, framework)))

        # 6. Routing Layer
        fk_by_entity = fk_relations(ir)
        apis_by_segment: dict[str, list[ApiEndpoint]] = {}
        for api in ir.apis:
            seg = _segment(api.path)
            apis_by_segment.setdefault(seg, []).append(api)

        # If entities exist without explicit APIs, provide default segment for them
        for entity in ir.entities:
            tbl = table_name(entity.name)
            if tbl not in apis_by_segment:
                apis_by_segment[tbl] = []

        segments = sorted(apis_by_segment.keys())

        for seg, apis in apis_by_segment.items():
            if framework == "hono":
                router_code = _hono_router_file(seg, apis, repo_entities, fk_by_entity, has_auth)
            else:
                router_code = _express_router_file(seg, apis, repo_entities, fk_by_entity, has_auth)
            files.append(GeneratedFile(f"src/routes/{seg}.ts", router_code))

        # 7. Main Application Assembly
        if framework == "hono":
            files.append(GeneratedFile("src/app.ts", _hono_app_file(segments)))
        else:
            files.append(GeneratedFile("src/app.ts", _express_app_file(segments)))

        # 8. Schema and Seed SQL
        if ir.project_strategy.database_strategy is DatabaseStrategy.POSTGRES:
            files.append(GeneratedFile("schema.sql", render_postgres_schema(ir)))
            files.append(GeneratedFile("seed.sql", render_postgres_seed(ir)))

        # 9. OpenAPI Contract
        if ir.apis:
            files.append(GeneratedFile("contracts/openapi.json", render_openapi_json(ir)))

        return GeneratedProject(GenerationTarget.BACKEND_NODE.value, files)


class ExpressBackendAdapter(NodeBackendAdapter):
    """Convenience alias for NodeBackendAdapter with framework='express'."""

    def __init__(self) -> None:
        super().__init__(framework="express")


class HonoBackendAdapter(NodeBackendAdapter):
    """Convenience alias for NodeBackendAdapter with framework='hono'."""

    def __init__(self) -> None:
        super().__init__(framework="hono")
