"""One `brand.json` every generated surface derives from (R-548).

Branding used to be scattered across files that did not know about each other. Changing one colour
meant editing `apps/web/styles/tokens.css`, the same eleven variables again in `apps/admin`,
`apps/mobile/app.json` twice and `apps/mobile/src/design-system/tokens.ts` — then regenerating four
PNGs by hand, which a user could not do at all because the generator is Python inside the platform.

`brand.json` holds **inputs only**: the name, the one colour everything derives from, the font, the
corner style and the store identifier. It deliberately does *not* store the derived palette. A
derived palette written into the file would go stale the moment someone edited the base colour by
hand — which is exactly what a user will do — and a stale palette is worse than none, because it
looks deliberate. Instead `brand/derive.mjs` computes the palette, and every consumer calls it:
`app.config.js` at Expo start-up, and (R-549) `pnpm run brand` when regenerating stylesheets and
icons.

The maths in `derive.mjs` mirrors `codegen/brand.py` exactly, because the two must agree: a project
regenerated by the platform and one rebranded by its owner have to produce the same palette.
"""

from __future__ import annotations

import json

from ..application_ir import ApplicationIR
from .files import GeneratedFile
from .mobile_release import bundle_identifier


def brand_json(ir: ApplicationIR, slug: str) -> GeneratedFile:
    """The single source of truth. Inputs only — the palette is derived, never stored."""
    document = {
        "$comment": [
            "The one place this product's branding is defined. Every app derives from it.",
            "Change a value here, then run `pnpm run brand` to regenerate stylesheets and icons.",
            "The palette is NOT stored here on purpose: it is derived from primaryColor, so it can",
            "never fall out of step with it. See brand/derive.mjs.",
        ],
        "name": ir.name,
        "description": ir.description,
        "primaryColor": ir.brand.primary_color,
        "fontFamily": ir.brand.font_family,
        "borderRadius": ir.brand.border_radius,
        "identity": {
            "$comment": [
                "bundleId is PERMANENT once the app has been submitted to either store.",
                "Apple ties it to the App Store Connect record and Google Play uses it as the",
                "listing's primary key; neither can be changed, and Google never lets anyone reuse",
                "one. Change it to a domain you own BEFORE your first submission.",
                "Set published to true after that first submission so tooling stops offering to",
                "change it. Everything else here — name, colour, icon — can still change in an",
                "update; only this identifier cannot.",
            ],
            "bundleId": bundle_identifier(slug),
            "published": False,
            # R-550: set to the value of bundleId at the moment you publish. Keeping it separate is
            # what makes a later change *detectable* — a lone `published: true` flag cannot tell
            # anyone whether the identifier beside it is still the one the stores know.
            "publishedBundleId": None,
        },
    }
    return GeneratedFile("brand.json", json.dumps(document, indent=2) + "\n")


def derive_mjs() -> GeneratedFile:
    """The palette derivation, in the project, so its owner can rebrand without the platform.

    A direct port of `codegen/brand.py`. Shades mix toward black or white rather than shifting HSL
    lightness, so a derived hover state cannot wander to a different hue; the dark theme lifts
    toward white because on a dark surface the brand has to come forward; and the foreground is
    chosen by WCAG relative luminance, so a yellow brand gets dark button text instead of
    unreadable white.
    """
    return GeneratedFile(
        "brand/derive.mjs",
        """// Derives a full palette from one brand colour. Used by apps/mobile/app.config.js and by
// `pnpm run brand`. Mirrors the platform's own derivation so a project rebranded by its owner
// produces exactly the palette the platform would have generated.
//
// No dependencies on purpose: this has to run anywhere Node runs, including inside eas build.

const BLACK = '#000000';
const WHITE = '#ffffff';

export function rgb(hex) {
  const value = String(hex).replace('#', '');
  if (!/^[0-9a-fA-F]{6}$/.test(value)) {
    throw new Error(`brand.json: primaryColor must be a 6-digit hex colour, got ${hex}`);
  }
  return [
    parseInt(value.slice(0, 2), 16),
    parseInt(value.slice(2, 4), 16),
    parseInt(value.slice(4, 6), 16),
  ];
}

// Python's round() is half-to-even; JavaScript's Math.round() is half-up. The platform derives
// palettes in Python, so this must match it exactly or a project rebranded by its owner would
// drift by one in a channel from the one the platform generated. Caught by comparing the two.
function roundHalfToEven(value) {
  const floor = Math.floor(value);
  const diff = value - floor;
  if (diff > 0.5) return floor + 1;
  if (diff < 0.5) return floor;
  return floor % 2 === 0 ? floor : floor + 1;
}

const hex = ([r, g, b]) =>
  '#' + [r, g, b].map((c) => Math.max(0, Math.min(255, roundHalfToEven(c))).toString(16).padStart(2, '0')).join('');

/** Blend `colour` toward `toward` by `amount` (0 keeps it, 1 reaches the target). */
export function mix(colour, toward, amount) {
  const [r1, g1, b1] = rgb(colour);
  const [r2, g2, b2] = rgb(toward);
  const t = Math.max(0, Math.min(1, amount));
  return hex([r1 + (r2 - r1) * t, g1 + (g2 - g1) * t, b1 + (b2 - b1) * t]);
}

/** WCAG relative luminance — decides whether text on the brand should be black or white. */
export function luminance(colour) {
  const [r, g, b] = rgb(colour).map((channel) => {
    const c = channel / 255;
    return c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/** Black or white — whichever is actually readable on this colour. */
export const readableOn = (colour) => (luminance(colour) > 0.45 ? '#0f172a' : '#ffffff');

export function lightPalette(primary) {
  return {
    '--color-primary': primary,
    '--color-primary-hover': mix(primary, BLACK, 0.14),
    '--color-primary-focus': mix(primary, BLACK, 0.28),
    '--color-primary-subtle': mix(primary, WHITE, 0.86),
    '--color-primary-foreground': readableOn(primary),
    '--color-border-focus': primary,
  };
}

export function darkPalette(primary) {
  const [r, g, b] = rgb(primary);
  const lifted = mix(primary, WHITE, 0.18);
  return {
    '--color-primary': lifted,
    '--color-primary-hover': mix(primary, WHITE, 0.34),
    '--color-primary-focus': mix(primary, WHITE, 0.5),
    '--color-primary-subtle': `rgba(${r}, ${g}, ${b}, 0.15)`,
    '--color-primary-foreground': readableOn(lifted),
    '--color-border-focus': lifted,
  };
}

export const RADIUS_VALUES = {
  none: '0',
  sm: '0.25rem',
  md: '0.375rem',
  lg: '0.5rem',
  xl: '0.75rem',
  full: '9999px',
};
""",
    )


def app_config_js() -> GeneratedFile:
    """Expo's documented dynamic config, replacing the static `app.json`.

    Two files competing to configure one app is a bug waiting to happen — Expo merges them with
    `app.config.js` winning, so a user editing `app.json` would see nothing change and have no way
    to tell why. Only this file is generated.
    """
    return GeneratedFile(
        "app.config.js",
        """// Expo reads this at every start, so editing ../../brand.json takes effect on reload —
// no regeneration step for the mobile app's name, colours or identifier.
//
// Icons are files rather than values, so they are regenerated by `pnpm run brand` at the repo root.
const fs = require('node:fs');
const path = require('node:path');

const brandPath = path.resolve(__dirname, '..', '..', 'brand.json');
const brand = JSON.parse(fs.readFileSync(brandPath, 'utf8'));

const identity = brand.identity ?? {};
const bundleId = identity.bundleId;

if (!bundleId) {
  throw new Error('brand.json: identity.bundleId is required to build this app.');
}

module.exports = () => ({
  expo: {
    name: brand.name,
    slug: String(brand.name).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
    version: brand.version ?? '1.0.0',
    orientation: 'portrait',
    userInterfaceStyle: 'automatic',
    icon: './assets/icon.png',
    splash: {
      image: './assets/splash.png',
      resizeMode: 'contain',
      backgroundColor: brand.primaryColor,
    },
    assetBundlePatterns: ['**/*'],
    ios: {
      supportsTablet: true,
      // Permanent once submitted: Apple ties it to the App Store Connect record.
      bundleIdentifier: bundleId,
      buildNumber: String(brand.buildNumber ?? 1),
      infoPlist: { ITSAppUsesNonExemptEncryption: false },
    },
    android: {
      // Permanent once published: Play uses it as the listing's primary key.
      package: bundleId,
      versionCode: Number(brand.versionCode ?? 1),
      adaptiveIcon: {
        foregroundImage: './assets/adaptive-icon.png',
        backgroundColor: brand.primaryColor,
      },
      // Declared empty deliberately: Play rejects permissions an app cannot justify.
      permissions: [],
    },
    web: { favicon: './assets/favicon.png' },
  },
});
""",
    )


def brand_readme() -> GeneratedFile:
    return GeneratedFile(
        "brand/README.md",
        """# Branding

`../brand.json` is the one place this product's look is defined. Change a value there and every
app follows.

| Field | Changes | How it takes effect |
| --- | --- | --- |
| `name` | the app's name everywhere | mobile: on reload. web/admin: `pnpm run brand` |
| `primaryColor` | the whole palette, derived | `pnpm run brand` regenerates stylesheets and icons |
| `fontFamily` | typography | `pnpm run brand` |
| `borderRadius` | corner style | `pnpm run brand` |
| `identity.bundleId` | the store identifier | **see below** |

## The palette is derived, not stored

`brand.json` holds only `primaryColor`. Hover, focus, subtle, dark-theme and focus-ring values are
computed by `derive.mjs`. That is deliberate: a palette written into the file would go stale the
moment someone edited the base colour by hand, and a stale palette looks intentional, which makes
it worse than none.

Text on the brand colour is chosen by WCAG relative luminance, so a light brand gets dark button
text automatically rather than unreadable white.

## `identity.bundleId` is permanent once you publish

Apple ties the bundle identifier to the App Store Connect record. Google Play uses it as the
listing's primary key and never lets anyone reuse one. **Neither can be changed after your first
submission** — you would be creating a different app, with no reviews, no ratings, and no update
path for anyone who already installed it.

Change it to a domain you own *before* you publish. Afterwards, set `identity.published` to `true`
so tooling stops offering to change it.

Everything else can still change after publishing — icon, colours, name — by shipping an update.
That needs a new build and a higher `buildNumber`/`versionCode`, and the store listing title is
edited separately in each console.
""",
    )


def web_brand_ts() -> GeneratedFile:
    """The per-app bridge from `brand.json` to CSS custom properties (R-549).

    CSS cannot read JSON at runtime, so a Next.js app has to do it at build time. This imports the
    repo's `brand.json` and the same `derive.mjs` the mobile config uses — one derivation, three
    surfaces, no chance of the web app and the phone showing different greens.

    The output is injected into `<head>` after `styles/tokens.css`, so it overrides the generated
    defaults rather than fighting them.
    """
    return GeneratedFile(
        "lib/brand.ts",
        """// Generated. Reads the repo's brand.json at build time and turns it into CSS custom
// properties. Editing brand.json and reloading is all a rebrand takes for this app.
//
// Both imports resolve on their own: resolveJsonModule handles the JSON, and allowJs handles
// derive.mjs, which is plain ESM so that apps/mobile/app.config.js can load the same file.
// They need no compiler suppression, and adding one here is a build error rather than a nicety.
import brand from "../../../brand.json";
import { lightPalette, darkPalette, RADIUS_VALUES } from "../../../brand/derive.mjs";

const block = (selector: string, values: Record<string, string>, extra: string[] = []) =>
  `${selector}{${Object.entries(values)
    .map(([name, value]) => `${name}:${value};`)
    .join("")}${extra.join("")}}`;

/** Every CSS variable this product's branding sets, light and dark. */
export function brandCss(): string {
  const primary = (brand as { primaryColor: string }).primaryColor;
  const font = (brand as { fontFamily?: string }).fontFamily;
  const radius = (brand as { borderRadius?: string }).borderRadius;

  const extras: string[] = [];
  if (font) extras.push(`--font-sans:${font},system-ui,-apple-system,sans-serif;`);
  // RADIUS_VALUES comes from a .js module, so TypeScript infers its exact keys and refuses a
  // plain string index under `strict`. Widened once here rather than cast at the use site.
  const radiusScale = (RADIUS_VALUES as Record<string, string | undefined>)[radius ?? ""];
  if (radiusScale) extras.push(`--radius-md:${radiusScale};`);

  const dark = block(":root", darkPalette(primary));
  return [
    block(":root", lightPalette(primary), extras),
    // Matches the structure styles/tokens.css already uses, so a user reading either file sees
    // the same shape: a media query for the system preference, and an explicit override.
    `@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){${dark.slice(":root{".length, -1)}}}`,
    `:root[data-theme="dark"]{${dark.slice(":root{".length, -1)}}`,
  ].join("");
}
""",
    )


def brand_script_mjs() -> GeneratedFile:
    """`pnpm run brand` — regenerates what cannot be derived at render time (R-549).

    Colours reach the apps live, so this exists for the icons: PNGs are binary and nothing can
    produce them while a page renders. It **never overwrites artwork a user has supplied** — each
    generated icon carries a marker, and an icon without one is left alone. Losing someone's logo
    to a rebuild would be a far worse failure than a stale icon.
    """
    return GeneratedFile(
        "brand/generate.mjs",
        """#!/usr/bin/env node
// Regenerates the brand's icons from ../brand.json. Run with `pnpm run brand`.
//
// Colours, fonts and corner styles do NOT need this: the apps derive those from brand.json when
// they render. Icons are binary, so they are written here instead.
//
// Icons this script generated carry a marker in a PNG text chunk. An icon without that marker was
// put there by you, and is never overwritten — a rebuild must not eat somebody's logo.

import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { rgb } from './derive.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));

// R-550: never regenerate from a brand.json that is invalid, or from one whose identifier has
// drifted since publication. Writing icons for an app that can no longer be shipped helps nobody.
execFileSync(process.execPath, [path.join(here, 'check.mjs')], { stdio: 'inherit' });
const root = path.resolve(here, '..');
const brand = JSON.parse(fs.readFileSync(path.join(root, 'brand.json'), 'utf8'));

const MARKER = 'OmniStackAI-generated-icon';

const crcTable = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(buf) {
  let c = -1;
  for (const byte of buf) c = crcTable[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ -1) >>> 0;
}

function chunk(tag, payload) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(payload.length);
  const body = Buffer.concat([Buffer.from(tag, 'ascii'), payload]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([length, body, crc]);
}

function png(size, rows) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8;   // bit depth
  ihdr[9] = 2;   // colour type: truecolour
  const raw = Buffer.concat(rows.map((row) => Buffer.concat([Buffer.from([0]), row])));
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('tEXt', Buffer.from(`Software\0${MARKER}`, 'latin1')),
    chunk('IDAT', zlib.deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

/** A vertically mirrored grid derived from the app's name — unique, symmetric, deterministic. */
function markGrid(seed, cells = 5) {
  const digest = crypto.createHash('sha256').update(seed, 'utf8').digest();
  const half = Math.floor(cells / 2) + (cells % 2);
  const grid = Array.from({ length: cells }, () => Array(cells).fill(false));
  let bit = 0;
  for (let row = 0; row < cells; row++) {
    for (let col = 0; col < half; col++) {
      const filled = Boolean(digest[bit % digest.length] & (1 << (Math.floor(bit / digest.length) % 8)));
      bit++;
      grid[row][col] = filled;
      grid[row][cells - 1 - col] = filled;
    }
  }
  const density = () => grid.flat().filter(Boolean).length;
  const floor = cells * 2;
  for (let row = 0; row < cells && density() < floor; row++) grid[row][half - 1] = true;
  for (let col = half - 1; col >= 0 && density() < floor; col--) {
    for (let row = 0; row < cells && density() < floor; row++) {
      if (!grid[row][col]) {
        grid[row][col] = true;
        grid[row][cells - 1 - col] = true;
      }
    }
  }
  return grid;
}

function renderMark(size, background, ink, seed, marginRatio) {
  const bg = rgb(background);
  const fg = rgb(ink);
  const cells = 5;
  const margin = Math.floor(size * marginRatio);
  const cell = (size - 2 * margin) / cells;
  const radius = cell * 0.5;
  const grid = markGrid(seed, cells);

  const rows = [];
  for (let y = 0; y < size; y++) {
    const row = Buffer.alloc(size * 3);
    for (let x = 0; x < size; x++) {
      let colour = bg;
      const gx = (x - margin) / cell;
      const gy = (y - margin) / cell;
      if (gx >= 0 && gx < cells && gy >= 0 && gy < cells && grid[Math.floor(gy)][Math.floor(gx)]) {
        const fx = (gx - Math.floor(gx)) * cell;
        const fy = (gy - Math.floor(gy)) * cell;
        if ((fx - radius) ** 2 + (fy - radius) ** 2 <= radius ** 2) colour = fg;
      }
      row[x * 3] = colour[0];
      row[x * 3 + 1] = colour[1];
      row[x * 3 + 2] = colour[2];
    }
    rows.push(row);
  }
  return png(size, rows);
}

/** True when this file was written by us and may be replaced. */
function isGenerated(file) {
  if (!fs.existsSync(file)) return true;
  return fs.readFileSync(file).includes(MARKER);
}

const targets = [
  ['assets/icon.png', 1024, 0.18],
  ['assets/adaptive-icon.png', 1024, 0.28],
  ['assets/splash.png', 1024, 0.34],
  ['assets/favicon.png', 48, 0.16],
];

const mobile = path.join(root, 'apps', 'mobile');
if (!fs.existsSync(mobile)) {
  console.log('No apps/mobile in this project — nothing to regenerate.');
  process.exit(0);
}

let written = 0;
let kept = 0;
for (const [relative, size, margin] of targets) {
  const file = path.join(mobile, relative);
  if (!isGenerated(file)) {
    console.log(`kept    ${relative}  (yours — not overwritten)`);
    kept++;
    continue;
  }
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, renderMark(size, brand.primaryColor, '#ffffff', brand.name, margin));
  console.log(`wrote   ${relative}`);
  written++;
}

console.log(`\n${written} regenerated, ${kept} of yours left alone.`);
console.log('Colours, fonts and corners need no regeneration — the apps read brand.json directly.');
""",
    )


def brand_check_mjs() -> GeneratedFile:
    """`pnpm run brand:check` — the one rule that cannot be undone (R-550).

    Only the identifier is refused. Icon, colours and display name can all change in an update,
    so blocking those would be wrong and would teach a user to ignore the tool. They warn
    instead, naming what a change actually costs: a new build, a higher version, another review.
    """
    return GeneratedFile("brand/check.mjs", '#!/usr/bin/env node\n// Validates ../brand.json. Run by `pnpm run brand:check`, and by `pnpm run brand` before it\n// regenerates anything.\n//\n// There is exactly one thing here that cannot be undone, so it is the only thing refused.\n\nimport fs from \'node:fs\';\nimport path from \'node:path\';\nimport { fileURLToPath } from \'node:url\';\nimport { rgb } from \'./derive.mjs\';\n\nconst root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), \'..\');\nconst brand = JSON.parse(fs.readFileSync(path.join(root, \'brand.json\'), \'utf8\'));\nconst identity = brand.identity ?? {};\n\nconst errors = [];\nconst warnings = [];\n\nif (!brand.name || typeof brand.name !== \'string\') {\n  errors.push(\'name must be a non-empty string.\');\n}\n\ntry {\n  rgb(brand.primaryColor);\n} catch (error) {\n  errors.push(String(error.message));\n}\n\nconst IDENTIFIER = /^[a-z][a-z0-9]*(\\.[a-z][a-z0-9]*)+$/;\n\nif (!identity.bundleId) {\n  errors.push(\'identity.bundleId is required to build this app.\');\n} else if (!IDENTIFIER.test(identity.bundleId)) {\n  errors.push(\n    `identity.bundleId "${identity.bundleId}" is not a valid reverse-DNS identifier. Both stores ` +\n      \'require something like com.yourcompany.yourapp: lowercase, dot-separated, each part \' +\n      \'starting with a letter.\'\n  );\n}\n\nif (identity.published) {\n  if (!identity.publishedBundleId) {\n    errors.push(\n      \'identity.published is true but identity.publishedBundleId is not set. Record the \' +\n        \'identifier you published with, so a later change can be caught.\'\n    );\n  } else if (identity.publishedBundleId !== identity.bundleId) {\n    errors.push(\n      [\n        \'The bundle identifier has changed since this app was published.\',\n        \'\',\n        `  published with: ${identity.publishedBundleId}`,\n        `  brand.json now: ${identity.bundleId}`,\n        \'\',\n        \'This is the one change that cannot be made. Apple ties the identifier to the App Store\',\n        "Connect record, and Google Play uses it as the listing\'s primary key and never lets",\n        \'anyone reuse one. Building with a different identifier does not update your app: it is\',\n        \'a different app, with no reviews, no ratings, and no update path for anyone who already\',\n        \'installed yours.\',\n        \'\',\n        `Restore it to ${identity.publishedBundleId}. If you genuinely want a separate app, start`,\n        \'a new project rather than renaming this one.\',\n      ].join(\'\\n\')\n    );\n  }\n\n  // Everything else is legal after publishing, and saying so matters as much as the refusal above.\n  warnings.push(\n    [\n      \'This app is published. Changing its icon, colours, font or display name is fine, but it\',\n      \'reaches users only through a new build:\',\n      \'  1. raise buildNumber (iOS) and versionCode (Android)\',\n      \'  2. eas build --platform all --profile production\',\n      \'  3. eas submit --platform all --profile production, then wait for review\',\n      \'A display-name change also needs the listing title edited in each store console.\',\n    ].join(\'\\n\')\n  );\n}\n\nfor (const warning of warnings) console.warn(`\\nwarning: ${warning}\\n`);\n\nif (errors.length) {\n  console.error(\'\\nbrand.json is not valid:\\n\');\n  for (const error of errors) console.error(`  - ${error}\\n`);\n  process.exit(1);\n}\n\nconsole.log(\'brand.json looks good.\');\n')


def brand_files(ir: ApplicationIR, slug: str) -> list[GeneratedFile]:
    """The root-level branding files, shared by every app in the monorepo."""
    return [brand_json(ir, slug), derive_mjs(), brand_script_mjs(), brand_check_mjs(), brand_readme()]
