"""One `brand.json` every generated surface derives from (R-548).

Branding used to be scattered across files that did not know about each other. Changing one colour
meant editing `apps/web/styles/tokens.css`, the same eleven variables again in `apps/admin`,
`apps/mobile/app.json` twice and `apps/mobile/src/design-system/tokens.ts` — then regenerating four
PNGs by hand, which a user could not do at all because the generator is Python inside the platform.

`brand.json` holds **inputs only**: the name, the one colour everything derives from, the font, the
corner style and the store identifier. It deliberately does *not* store the derived palette. A
derived palette written into the file would go stale the moment someone edited the base colour by
hand — which is exactly what a user will do — and a stale palette is worse than none, because it
looks deliberate. Instead `brand/derive.mjs` computes the palette, and every consumer calls it:
`app.config.js` at Expo start-up, and (R-549) `pnpm run brand` when regenerating stylesheets and
icons.

The maths in `derive.mjs` mirrors `codegen/brand.py` exactly, because the two must agree: a project
regenerated by the platform and one rebranded by its owner have to produce the same palette.
"""

from __future__ import annotations

import json

from ..application_ir import ApplicationIR
from .files import GeneratedFile
from .mobile_release import bundle_identifier


def brand_json(ir: ApplicationIR, slug: str) -> GeneratedFile:
    """The single source of truth. Inputs only — the palette is derived, never stored."""
    document = {
        "$comment": [
            "The one place this product's branding is defined. Every app derives from it.",
            "Change a value here, then run `pnpm run brand` to regenerate stylesheets and icons.",
            "The palette is NOT stored here on purpose: it is derived from primaryColor, so it can",
            "never fall out of step with it. See brand/derive.mjs.",
        ],
        "name": ir.name,
        "description": ir.description,
        "primaryColor": ir.brand.primary_color,
        "fontFamily": ir.brand.font_family,
        "borderRadius": ir.brand.border_radius,
        "identity": {
            "$comment": [
                "bundleId is PERMANENT once the app has been submitted to either store.",
                "Apple ties it to the App Store Connect record and Google Play uses it as the",
                "listing's primary key; neither can be changed, and Google never lets anyone reuse",
                "one. Change it to a domain you own BEFORE your first submission.",
                "Set published to true after that first submission so tooling stops offering to",
                "change it. Everything else here — name, colour, icon — can still change in an",
                "update; only this identifier cannot.",
            ],
            "bundleId": bundle_identifier(slug),
            "published": False,
        },
    }
    return GeneratedFile("brand.json", json.dumps(document, indent=2) + "\n")


def derive_mjs() -> GeneratedFile:
    """The palette derivation, in the project, so its owner can rebrand without the platform.

    A direct port of `codegen/brand.py`. Shades mix toward black or white rather than shifting HSL
    lightness, so a derived hover state cannot wander to a different hue; the dark theme lifts
    toward white because on a dark surface the brand has to come forward; and the foreground is
    chosen by WCAG relative luminance, so a yellow brand gets dark button text instead of
    unreadable white.
    """
    return GeneratedFile(
        "brand/derive.mjs",
        """// Derives a full palette from one brand colour. Used by apps/mobile/app.config.js and by
// `pnpm run brand`. Mirrors the platform's own derivation so a project rebranded by its owner
// produces exactly the palette the platform would have generated.
//
// No dependencies on purpose: this has to run anywhere Node runs, including inside eas build.

const BLACK = '#000000';
const WHITE = '#ffffff';

export function rgb(hex) {
  const value = String(hex).replace('#', '');
  if (!/^[0-9a-fA-F]{6}$/.test(value)) {
    throw new Error(`brand.json: primaryColor must be a 6-digit hex colour, got ${hex}`);
  }
  return [
    parseInt(value.slice(0, 2), 16),
    parseInt(value.slice(2, 4), 16),
    parseInt(value.slice(4, 6), 16),
  ];
}

// Python's round() is half-to-even; JavaScript's Math.round() is half-up. The platform derives
// palettes in Python, so this must match it exactly or a project rebranded by its owner would
// drift by one in a channel from the one the platform generated. Caught by comparing the two.
function roundHalfToEven(value) {
  const floor = Math.floor(value);
  const diff = value - floor;
  if (diff > 0.5) return floor + 1;
  if (diff < 0.5) return floor;
  return floor % 2 === 0 ? floor : floor + 1;
}

const hex = ([r, g, b]) =>
  '#' + [r, g, b].map((c) => Math.max(0, Math.min(255, roundHalfToEven(c))).toString(16).padStart(2, '0')).join('');

/** Blend `colour` toward `toward` by `amount` (0 keeps it, 1 reaches the target). */
export function mix(colour, toward, amount) {
  const [r1, g1, b1] = rgb(colour);
  const [r2, g2, b2] = rgb(toward);
  const t = Math.max(0, Math.min(1, amount));
  return hex([r1 + (r2 - r1) * t, g1 + (g2 - g1) * t, b1 + (b2 - b1) * t]);
}

/** WCAG relative luminance — decides whether text on the brand should be black or white. */
export function luminance(colour) {
  const [r, g, b] = rgb(colour).map((channel) => {
    const c = channel / 255;
    return c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/** Black or white — whichever is actually readable on this colour. */
export const readableOn = (colour) => (luminance(colour) > 0.45 ? '#0f172a' : '#ffffff');

export function lightPalette(primary) {
  return {
    '--color-primary': primary,
    '--color-primary-hover': mix(primary, BLACK, 0.14),
    '--color-primary-focus': mix(primary, BLACK, 0.28),
    '--color-primary-subtle': mix(primary, WHITE, 0.86),
    '--color-primary-foreground': readableOn(primary),
    '--color-border-focus': primary,
  };
}

export function darkPalette(primary) {
  const [r, g, b] = rgb(primary);
  const lifted = mix(primary, WHITE, 0.18);
  return {
    '--color-primary': lifted,
    '--color-primary-hover': mix(primary, WHITE, 0.34),
    '--color-primary-focus': mix(primary, WHITE, 0.5),
    '--color-primary-subtle': `rgba(${r}, ${g}, ${b}, 0.15)`,
    '--color-primary-foreground': readableOn(lifted),
    '--color-border-focus': lifted,
  };
}

export const RADIUS_VALUES = {
  none: '0',
  sm: '0.25rem',
  md: '0.375rem',
  lg: '0.5rem',
  xl: '0.75rem',
  full: '9999px',
};
""",
    )


def app_config_js() -> GeneratedFile:
    """Expo's documented dynamic config, replacing the static `app.json`.

    Two files competing to configure one app is a bug waiting to happen — Expo merges them with
    `app.config.js` winning, so a user editing `app.json` would see nothing change and have no way
    to tell why. Only this file is generated.
    """
    return GeneratedFile(
        "app.config.js",
        """// Expo reads this at every start, so editing ../../brand.json takes effect on reload —
// no regeneration step for the mobile app's name, colours or identifier.
//
// Icons are files rather than values, so they are regenerated by `pnpm run brand` at the repo root.
const fs = require('node:fs');
const path = require('node:path');

const brandPath = path.resolve(__dirname, '..', '..', 'brand.json');
const brand = JSON.parse(fs.readFileSync(brandPath, 'utf8'));

const identity = brand.identity ?? {};
const bundleId = identity.bundleId;

if (!bundleId) {
  throw new Error('brand.json: identity.bundleId is required to build this app.');
}

module.exports = () => ({
  expo: {
    name: brand.name,
    slug: String(brand.name).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
    version: brand.version ?? '1.0.0',
    orientation: 'portrait',
    userInterfaceStyle: 'automatic',
    icon: './assets/icon.png',
    splash: {
      image: './assets/splash.png',
      resizeMode: 'contain',
      backgroundColor: brand.primaryColor,
    },
    assetBundlePatterns: ['**/*'],
    ios: {
      supportsTablet: true,
      // Permanent once submitted: Apple ties it to the App Store Connect record.
      bundleIdentifier: bundleId,
      buildNumber: String(brand.buildNumber ?? 1),
      infoPlist: { ITSAppUsesNonExemptEncryption: false },
    },
    android: {
      // Permanent once published: Play uses it as the listing's primary key.
      package: bundleId,
      versionCode: Number(brand.versionCode ?? 1),
      adaptiveIcon: {
        foregroundImage: './assets/adaptive-icon.png',
        backgroundColor: brand.primaryColor,
      },
      // Declared empty deliberately: Play rejects permissions an app cannot justify.
      permissions: [],
    },
    web: { favicon: './assets/favicon.png' },
  },
});
""",
    )


def brand_readme() -> GeneratedFile:
    return GeneratedFile(
        "brand/README.md",
        """# Branding

`../brand.json` is the one place this product's look is defined. Change a value there and every
app follows.

| Field | Changes | How it takes effect |
| --- | --- | --- |
| `name` | the app's name everywhere | mobile: on reload. web/admin: `pnpm run brand` |
| `primaryColor` | the whole palette, derived | `pnpm run brand` regenerates stylesheets and icons |
| `fontFamily` | typography | `pnpm run brand` |
| `borderRadius` | corner style | `pnpm run brand` |
| `identity.bundleId` | the store identifier | **see below** |

## The palette is derived, not stored

`brand.json` holds only `primaryColor`. Hover, focus, subtle, dark-theme and focus-ring values are
computed by `derive.mjs`. That is deliberate: a palette written into the file would go stale the
moment someone edited the base colour by hand, and a stale palette looks intentional, which makes
it worse than none.

Text on the brand colour is chosen by WCAG relative luminance, so a light brand gets dark button
text automatically rather than unreadable white.

## `identity.bundleId` is permanent once you publish

Apple ties the bundle identifier to the App Store Connect record. Google Play uses it as the
listing's primary key and never lets anyone reuse one. **Neither can be changed after your first
submission** — you would be creating a different app, with no reviews, no ratings, and no update
path for anyone who already installed it.

Change it to a domain you own *before* you publish. Afterwards, set `identity.published` to `true`
so tooling stops offering to change it.

Everything else can still change after publishing — icon, colours, name — by shipping an update.
That needs a new build and a higher `buildNumber`/`versionCode`, and the store listing title is
edited separately in each console.
""",
    )


def brand_files(ir: ApplicationIR, slug: str) -> list[GeneratedFile]:
    """The root-level branding files, shared by every app in the monorepo."""
    return [brand_json(ir, slug), derive_mjs(), brand_readme()]
