"""R-568: scheduled jobs in the generated admin console, over the scheduler's API.

A "Scheduled jobs" page: each schedule in a sentence, when it last ran and what it changed, run it
now, pause and resume it; and the recent runs, with the failed and dead ones retried from here.
The API admits only the admin; the page shows what it answers.
"""

from __future__ import annotations

JOBS_PAGE_PATH = "app/scheduled-jobs/page.tsx"
JOBS_NAV = ("/scheduled-jobs", "Scheduled jobs")

JOBS_CLIENT = r'''// Generated by OmniStackAI (R-568): the scheduler's API for the admin console.
const BASE_URL = process.env.NEXT_PUBLIC_API_URL || "";

async function call<T>(path: string, method = "GET"): Promise<T> {
  const token = typeof localStorage !== "undefined" ? localStorage.getItem("auth_token") : null;
  const res = await fetch(`${BASE_URL}${path}`, { method, headers: token ? { Authorization: `Bearer ${token}` } : {} });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error((data as { detail?: string }).detail || `Request failed (${res.status})`);
  return data as T;
}

export interface Schedule { name: string; entity: string; action: string; description: string; every_seconds: number;
  paused: boolean | null; next_run_at: string | null; last_run_at: string | null; last_status: string | null;
  last_affected: number | null; last_error: string | null }
export interface Run { id: string; schedule: string; trigger: string; status: string; attempts: number; max_attempts: number;
  run_at: string; affected: number | null; error: string | null; created_at: string; finished_at: string | null }

export const schedules = () => call<Schedule[]>("/scheduler/schedules");
export const runs = () => call<Run[]>("/scheduler/runs");
export const runNow = (name: string) => call<{ status: string; affected?: number; error?: string }>(`/scheduler/schedules/${encodeURIComponent(name)}/run`, "POST");
export const pause = (name: string) => call(`/scheduler/schedules/${encodeURIComponent(name)}/pause`, "POST");
export const resume = (name: string) => call(`/scheduler/schedules/${encodeURIComponent(name)}/resume`, "POST");
export const retry = (id: string) => call<Run>(`/scheduler/runs/${id}/retry`, "POST");
'''

JOBS_PAGE = r'''"use client";

// Generated by OmniStackAI (R-568): what the app does on its own - each schedule, its last run, and
// the runs that failed. Only the admin gets answers from the API.
import { useCallback, useEffect, useState } from "react";
import { pause, resume, retry, runNow, runs, schedules, type Run, type Schedule } from "@/lib/jobs";

const TONE: Record<string, { bg: string; fg: string }> = {
  done: { bg: "#dcfce7", fg: "#166534" }, running: { bg: "#e0e7ff", fg: "#3730a3" }, queued: { bg: "#f1f5f9", fg: "#334155" },
  failed: { bg: "#fef3c7", fg: "#92400e" }, dead: { bg: "#fee2e2", fg: "#991b1b" },
};

function when(value: string | null): string {
  return value ? new Date(value).toLocaleString() : "—";
}

function Badge({ status }: { status: string | null }) {
  if (!status) return <span style={{ color: "#64748b" }}>never run</span>;
  const tone = TONE[status] ?? TONE.queued;
  return <span style={{ padding: "2px 9px", borderRadius: 999, fontSize: 12, fontWeight: 700, background: tone.bg, color: tone.fg, textTransform: "capitalize" }}>{status}</span>;
}

export default function ScheduledJobsPage() {
  const [items, setItems] = useState<Schedule[]>([]);
  const [recent, setRecent] = useState<Run[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      const [s, r] = await Promise.all([schedules(), runs()]);
      setItems(s); setRecent(r); setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Scheduled jobs could not be loaded.");
    }
  }, []);

  useEffect(() => {
    let cancelled = false;
    (async () => { if (!cancelled) await load(); })();
    return () => { cancelled = true; };
  }, [load]);

  async function act(key: string, work: () => Promise<unknown>, done?: (out: unknown) => string) {
    setBusy(key); setError(null); setNotice(null);
    try { const out = await work(); if (done) setNotice(done(out)); await load(); }
    catch (err) { setError(err instanceof Error ? err.message : "That could not be done."); }
    finally { setBusy(null); }
  }

  const card = { border: "1px solid #e2e8f0", borderRadius: 12, background: "#fff" } as const;
  const small = { padding: "5px 10px", border: "1px solid #c7d2fe", borderRadius: 6, background: "#fff", color: "#4338ca", fontSize: 13, fontWeight: 600 } as const;
  const failing = recent.filter((r) => r.status === "failed" || r.status === "dead");
  return (
    <main style={{ maxWidth: 1100, margin: "0 auto", padding: "28px 16px" }}>
      <h1 style={{ fontSize: 26, fontWeight: 700, margin: "0 0 6px" }}>Scheduled jobs</h1>
      <p style={{ margin: "0 0 18px", color: "#475569" }}>What the app does on its own, on a clock. A run that fails is tried again; after its last attempt it waits here for you.</p>
      {error && <p role="alert" style={{ color: "#b91c1c" }}>{error}</p>}
      {notice && <p role="status" style={{ color: "#166534" }}>{notice}</p>}
      {items.length === 0 ? <p style={{ color: "#475569" }}>No scheduled jobs.</p> : (
        <ul style={{ ...card, listStyle: "none", margin: "0 0 28px", padding: 0 }}>
          {items.map((s) => (
            <li key={s.name} style={{ padding: "14px 16px", borderBottom: "1px solid #f1f5f9", display: "flex", flexWrap: "wrap", gap: 12, justifyContent: "space-between", alignItems: "center" }}>
              <div style={{ minWidth: 0, flex: "1 1 420px" }}>
                <p style={{ margin: 0, fontWeight: 600 }}>{s.description}</p>
                <p style={{ margin: "4px 0 0", fontSize: 13, color: "#475569" }}>
                  <Badge status={s.paused ? "paused" : s.last_status} />
                  <span style={{ marginLeft: 8 }}>Last run {when(s.last_run_at)}{s.last_affected != null ? ` · ${s.last_affected} changed` : ""}</span>
                  {!s.paused && <span style={{ marginLeft: 8 }}>· next {when(s.next_run_at)}</span>}
                </p>
                {s.last_error && <p style={{ margin: "4px 0 0", fontSize: 12, color: "#b91c1c", overflowWrap: "anywhere" }}>{s.last_error}</p>}
              </div>
              <span style={{ display: "flex", gap: 6 }}>
                <button type="button" style={small} disabled={busy !== null}
                  onClick={() => act(`run-${s.name}`, () => runNow(s.name), (out) => {
                    const o = out as { status: string; affected?: number; error?: string };
                    return o.status === "done" ? `Ran: ${o.affected ?? 0} changed.` : `The run ${o.status}: ${o.error ?? ""}`;
                  })}>
                  {busy === `run-${s.name}` ? "…" : "Run now"}
                </button>
                <button type="button" style={small} disabled={busy !== null}
                  onClick={() => act(`pause-${s.name}`, () => (s.paused ? resume(s.name) : pause(s.name)))}>
                  {s.paused ? "Resume" : "Pause"}
                </button>
              </span>
            </li>
          ))}
        </ul>
      )}
      {failing.length > 0 && (
        <>
          <h2 style={{ fontSize: 18, fontWeight: 600, margin: "0 0 8px" }}>Needs attention</h2>
          <ul style={{ ...card, listStyle: "none", margin: "0 0 28px", padding: 0 }}>
            {failing.map((r) => (
              <li key={r.id} style={{ padding: "12px 16px", borderBottom: "1px solid #f1f5f9", display: "flex", flexWrap: "wrap", gap: 10, justifyContent: "space-between", alignItems: "center" }}>
                <span style={{ minWidth: 0, flex: "1 1 420px" }}>
                  <Badge status={r.status} /> <strong style={{ marginLeft: 6 }}>{r.schedule}</strong>
                  <span style={{ marginLeft: 8, fontSize: 13, color: "#475569" }}>attempt {r.attempts} of {r.max_attempts} · {when(r.finished_at)}</span>
                  {r.error && <span style={{ display: "block", fontSize: 12, color: "#b91c1c", overflowWrap: "anywhere" }}>{r.error}</span>}
                </span>
                <button type="button" style={small} disabled={busy !== null} onClick={() => act(`retry-${r.id}`, () => retry(r.id), () => "Queued again.")}>
                  {busy === `retry-${r.id}` ? "…" : "Retry"}
                </button>
              </li>
            ))}
          </ul>
        </>
      )}
      <h2 style={{ fontSize: 18, fontWeight: 600, margin: "0 0 8px" }}>Recent runs</h2>
      {recent.length === 0 ? <p style={{ color: "#475569" }}>Nothing has run yet.</p> : (
        <div style={{ ...card, overflowX: "auto" }}>
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 14 }}>
            <thead><tr style={{ textAlign: "left", color: "#475569" }}>
              <th style={{ padding: "10px 16px" }}>Job</th><th>Started by</th><th>Status</th><th>Changed</th><th>Finished</th>
            </tr></thead>
            <tbody>
              {recent.slice(0, 50).map((r) => (
                <tr key={r.id} style={{ borderTop: "1px solid #f1f5f9" }}>
                  <td style={{ padding: "10px 16px" }}>{r.schedule}</td>
                  <td style={{ textTransform: "capitalize" }}>{r.trigger}</td>
                  <td><Badge status={r.status} /></td>
                  <td>{r.affected ?? "—"}</td>
                  <td>{when(r.finished_at)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </main>
  );
}
'''
