"""R-568: scheduled jobs in a generated Node backend - one service, an Express and a Hono router.

The same scheduler as Python and Go (see `jobs_python.py`): a timer started with the server turns
due schedules into runs, claims them with SKIP LOCKED and runs each schedule's statement from
`jobs_sql`; the admin's endpoints list, run, pause and retry.
"""

from __future__ import annotations

import json

from ..application_ir import ApplicationIR
from . import jobs_sql as q

#: (method, path, service function) - every one behind requireAuth; the service admits the admin.
NODE_JOBS_ROUTES = (
    ("get", "/scheduler/schedules", "listSchedules"),
    ("post", "/scheduler/schedules/:name/run", "runNow"),
    ("post", "/scheduler/schedules/:name/pause", "pause"),
    ("post", "/scheduler/schedules/:name/resume", "resume"),
    ("get", "/scheduler/runs", "listRuns"),
    ("post", "/scheduler/runs/:runId/retry", "retry"),
)


def node_jobs_service(ir: ApplicationIR) -> str:
    compiled = q.compiled_schedules(ir)
    schedules = {
        c.name: {"entity": c.entity, "everySeconds": c.every_seconds, "action": c.action,
                 "description": c.description, "sql": c.sql}
        for c in compiled
    }
    statements = {
        "enqueueDue": q.ENQUEUE_DUE, "claim": q.CLAIM, "manual": q.MANUAL, "done": q.DONE, "failed": q.FAILED,
        "record": q.RECORD, "prune": q.PRUNE, "schedules": q.SCHEDULES, "runs": q.RUNS,
        "runsWithStatus": q.RUNS_WITH_STATUS, "retry": q.RETRY, "pause": q.PAUSE,
    }
    config = (
        f"const SCHEDULES: Record<string, Schedule> = {json.dumps(schedules, indent=2)};\n\n"
        f"const SYNC: string[] = {json.dumps(list(q.sync_statements(ir)), indent=2)};\n\n"
        f"const BATCH = {q.BATCH};\n"
        f"const MAX_BATCHES = {q.MAX_BATCHES};\n\n"
        f"const SQL = {json.dumps(statements, indent=2)};\n"
    )
    return _SERVICE.replace("__CONFIG__", config)


def node_jobs_router(framework: str) -> str:
    lines = [f"// Generated by OmniStackAI: scheduled jobs routes (R-568) for {framework}."]
    if framework == "hono":
        lines += [
            "import { Hono } from 'hono';",
            "import { requireAuth } from '../middleware/auth.js';",
            "import * as jobs from './service.js';",
            "",
            "export const router = new Hono();",
            "",
        ]
        for method, path, fn in NODE_JOBS_ROUTES:
            lines += [
                f"router.{method}('{path}', requireAuth, async (c) => {{",
                f"  const out = await jobs.{fn}({{ claims: (c as any).get('user'), params: c.req.param() as any, query: c.req.query() }});",
                "  return c.json(out.body as any, out.status as any);",
                "});",
                "",
            ]
    else:
        lines += [
            "import { Router, Request, Response } from 'express';",
            "import { requireAuth } from '../middleware/auth.js';",
            "import * as jobs from './service.js';",
            "",
            "export const router = Router();",
            "",
        ]
        for method, path, fn in NODE_JOBS_ROUTES:
            lines += [
                f"router.{method}('{path}', requireAuth, async (req: Request, res: Response) => {{",
                f"  const out = await jobs.{fn}({{ claims: (req as any).user, params: req.params as any, query: req.query as any }});",
                "  res.status(out.status).json(out.body);",
                "});",
                "",
            ]
    return "\n".join(lines) + "\n"


_SERVICE = r'''// Generated by OmniStackAI: scheduled jobs (R-568) - rules the app runs on its own, on a clock.
//
// Each schedule is one bounded statement over its rows. Runs are rows in scheduler_run: a failed run
// is retried with backoff and is dead after its last attempt; an admin can retry it. Rows are claimed
// with SKIP LOCKED, so several replicas share the work without running it twice.
import { pool } from '../db/pool.js';
import { seesAll, type AuthClaims } from '../middleware/auth.js';

interface Schedule { entity: string; everySeconds: number; action: string; description: string; sql: string }
interface Call { claims?: AuthClaims; params: Record<string, string>; query: Record<string, unknown> }
type Out = { status: number; body: unknown };

__CONFIG__
/** Run one schedule's statement until a batch comes back short; the rows it changed. */
export async function runSchedule(name: string): Promise<number> {
  const schedule = SCHEDULES[name];
  if (!schedule) throw new Error(`no schedule named ${JSON.stringify(name)} in this version of the app`);
  let total = 0;
  for (let i = 0; i < MAX_BATCHES; i++) {
    const res = await pool.query(schedule.sql);
    const changed = res.rowCount ?? 0;
    total += changed;
    if (changed < BATCH) break;
  }
  return total;
}

/** Run a claimed run and record how it went, on the run and on its schedule. */
async function finish(runId: string, name: string): Promise<Record<string, unknown>> {
  let affected: number;
  try {
    affected = await runSchedule(name);
  } catch (error) {
    const message = String((error as Error)?.message ?? error).slice(0, 500);
    const res = await pool.query(SQL.failed, [message, runId]);
    const status = res.rows[0]?.status ?? 'failed';
    await pool.query(SQL.record, [status, null, message, name]);
    console.warn(`job ${name} ${status}: ${message}`);
    return { status, error: message };
  }
  await pool.query(SQL.done, [affected, runId]);
  await pool.query(SQL.record, ['done', affected, null, name]);
  return { status: 'done', affected };
}

/** Enqueue what is due and run what is claimable; how many runs this replica ran. */
export async function tick(): Promise<number> {
  await pool.query(SQL.enqueueDue);
  await pool.query(SQL.prune);
  let ran = 0;
  for (let i = 0; i < 20; i++) {
    const res = await pool.query(SQL.claim);
    if (res.rows.length === 0) break;
    await finish(String(res.rows[0].id), res.rows[0].schedule);
    ran++;
  }
  return ran;
}

let timer: ReturnType<typeof setTimeout> | null = null;

/** Started by the server: make the schedule table match this app, then look for due work. */
export function startScheduler(): void {
  if (['1', 'true', 'yes'].includes((process.env.SCHEDULER_DISABLED ?? '').trim().toLowerCase())) {
    console.log('scheduler disabled here (SCHEDULER_DISABLED)');
    return;
  }
  const seconds = Number(process.env.SCHEDULER_TICK_SECONDS);
  const interval = Number.isFinite(seconds) && seconds >= 1 ? seconds * 1000 : 10_000;
  let synced = false;
  const loop = async () => {
    try {
      if (!synced) {
        for (const statement of SYNC) await pool.query(statement);
        synced = true;
      }
      await tick();
    } catch (error) {
      console.warn('scheduler:', (error as Error)?.message ?? error);
    }
    timer = setTimeout(loop, interval);
  };
  void loop();
}

export function stopScheduler(): void {
  if (timer) clearTimeout(timer);
  timer = null;
}

// --- the admin's view ---------------------------------------------------------------------------

const forbidden: Out = { status: 403, body: { detail: 'forbidden' } };

export async function listSchedules({ claims }: Call): Promise<Out> {
  if (!seesAll(claims, [])) return forbidden;
  const res = await pool.query(SQL.schedules);
  const states = new Map(res.rows.map((r: any) => [r.name, r]));
  const body = Object.entries(SCHEDULES).map(([name, s]) => {
    const row: any = states.get(name) ?? {};
    return {
      name, entity: s.entity, action: s.action, description: s.description, every_seconds: s.everySeconds,
      paused: row.paused ?? null, next_run_at: row.next_run_at ?? null, last_run_at: row.last_run_at ?? null,
      last_status: row.last_status ?? null, last_affected: row.last_affected ?? null, last_error: row.last_error ?? null,
    };
  });
  return { status: 200, body };
}

export async function runNow({ claims, params }: Call): Promise<Out> {
  if (!seesAll(claims, [])) return forbidden;
  if (!SCHEDULES[params.name]) return { status: 404, body: { detail: 'not_found' } };
  const res = await pool.query(SQL.manual, [params.name]);
  const id = String(res.rows[0].id);
  return { status: 200, body: { id, schedule: params.name, ...(await finish(id, params.name)) } };
}

async function setPaused(name: string, paused: boolean): Promise<Out> {
  const res = await pool.query(SQL.pause, [paused, name]);
  if (res.rows.length === 0) return { status: 404, body: { detail: 'not_found' } };
  return { status: 200, body: { name, paused } };
}

export async function pause({ claims, params }: Call): Promise<Out> {
  if (!seesAll(claims, [])) return forbidden;
  return setPaused(params.name, true);
}

export async function resume({ claims, params }: Call): Promise<Out> {
  if (!seesAll(claims, [])) return forbidden;
  return setPaused(params.name, false);
}

export async function listRuns({ claims, query }: Call): Promise<Out> {
  if (!seesAll(claims, [])) return forbidden;
  const status = typeof query.status === 'string' && query.status ? query.status : null;
  const res = status ? await pool.query(SQL.runsWithStatus, [status]) : await pool.query(SQL.runs);
  return { status: 200, body: res.rows };
}

/** A failed or dead run, queued again with a fresh set of attempts. */
export async function retry({ claims, params }: Call): Promise<Out> {
  if (!seesAll(claims, [])) return forbidden;
  const res = await pool.query(SQL.retry, [params.runId]);
  if (res.rows.length === 0) return { status: 409, body: { detail: 'only a failed or dead run can be retried' } };
  return { status: 200, body: res.rows[0] };
}
'''
