"""A lifecycle, operable from the screens (R-590).

R-566 made a lifecycle real in the database and the backend, R-588 put the transitions in the
contract and the typed client, and R-589 brought every backend to parity. What was left was the
half a person sees: nothing on any page moved an order from `placed` to `accepted`. The only way to
use a lifecycle was to know its endpoint and call it by hand.

This module emits, per workflow, one panel for the web app and admin console and one for the mobile
app. Both show where the record is in its lifecycle and offer exactly the moves that are legal from
that state — computed from the same `Workflow` the backend enforces, so a button can never promise
a move the API will refuse for its state. Moves the signed-in user's role cannot make are hidden;
the backend still refuses them, which is what makes the rule true rather than cosmetic.
"""

from __future__ import annotations

import json

from ..application_ir import ApplicationIR
from ..application_ir.workflow import Workflow, workflows_of
from .route_wiring import table_name
from .workflow_routes import transition_routes


def _label(name: str) -> str:
    """`mark_delivered` -> "Mark delivered", `accept` -> "Accept"."""
    words = name.replace("_", " ").strip()
    return words[:1].upper() + words[1:]


def _client_function(route) -> str:
    parts = route.function.split("_")
    return parts[0] + "".join(w.capitalize() for w in parts[1:])


def lifecycle_component_path(workflow: Workflow) -> str:
    return f"components/lifecycle/{table_name(workflow.entity)}-lifecycle.tsx"


def lifecycle_component_name(workflow: Workflow) -> str:
    return f"{workflow.entity}Lifecycle"


def web_lifecycle_component(ir: ApplicationIR, workflow: Workflow, *, has_auth: bool) -> str:
    routes = [r for r in transition_routes(ir) if r.workflow.entity == workflow.entity]
    functions = sorted({_client_function(r) for r in routes})
    moves = [
        {
            "name": r.transition.name,
            "label": _label(r.transition.name),
            "to": r.transition.to,
            "from": list(r.transition.sources),
            "roles": list(r.transition.roles),
            "call": _client_function(r),
        }
        for r in routes
    ]
    moves_ts = ",\n".join(
        f'  {{ name: {json.dumps(m["name"])}, label: {json.dumps(m["label"])}, to: {json.dumps(m["to"])}, '
        f'from: {json.dumps(m["from"])}, roles: {json.dumps(m["roles"])}, call: {m["call"]} }}'
        for m in moves
    )
    name = lifecycle_component_name(workflow)
    entity = workflow.entity
    auth_import = 'import { useAuth } from "@/components/auth-provider";\n' if has_auth else ""
    role_line = (
        "  const role = useAuth().user?.role ?? null;\n" if has_auth else "  const role: string | null = null;\n"
    )
    return (
        '"use client";\n\n'
        f"// Generated by OmniStackAI (R-590): the {entity} lifecycle as actions on the page.\n"
        "// Legal moves come from the same workflow the backend enforces; the backend still refuses a\n"
        "// wrong state or role, so hiding a button is courtesy, not security.\n"
        'import { useState } from "react";\n'
        f'import {{ {", ".join(functions)} }} from "@/lib/api";\n'
        f'import type {{ {entity} }} from "@/lib/types";\n'
        + auth_import
        + "\n"
        f"const STATES = {json.dumps(list(workflow.states))} as const;\n"
        f"const FIELD = {json.dumps(workflow.field)};\n"
        f"const MOVES: {{ name: string; label: string; to: string; from: string[]; roles: string[]; call: (id: string) => Promise<{entity}> }}[] = [\n"
        + moves_ts
        + ",\n];\n\n"
        "const pretty = (s: string) => s.replace(/_/g, \" \");\n\n"
        f"export function {name}({{ record, onChanged, compact = false }}: {{ record: {entity}; onChanged?: (updated: {entity}) => void; compact?: boolean }}) {{\n"
        + role_line
        + "  const [busy, setBusy] = useState<string | null>(null);\n"
        "  const [error, setError] = useState<string | null>(null);\n"
        "  const current = String((record as unknown as Record<string, unknown>)[FIELD] ?? STATES[0]);\n"
        "  const position = Math.max(0, STATES.indexOf(current as (typeof STATES)[number]));\n"
        "  const moves = MOVES.filter((m) => (m.from.length === 0 || m.from.includes(current)) && m.to !== current)\n"
        "    // A signed-in user whose role cannot make a move does not see it; the API refuses it anyway.\n"
        "    .filter((m) => m.roles.length === 0 || role === null || m.roles.includes(role));\n\n"
        "  async function run(move: (typeof MOVES)[number]) {\n"
        "    setBusy(move.name);\n"
        "    setError(null);\n"
        "    try {\n"
        "      const updated = await move.call(String((record as unknown as Record<string, unknown>).id));\n"
        "      onChanged?.(updated);\n"
        "    } catch (err) {\n"
        '      setError(err instanceof Error ? err.message : "That change could not be made.");\n'
        "    } finally {\n"
        "      setBusy(null);\n"
        "    }\n"
        "  }\n\n"
        "  if (compact) {\n"
        "    // In a table row: the state and its legal moves, without opening the record.\n"
        "    return (\n"
        '      <span onClick={(e) => e.stopPropagation()} style={{ display: "inline-flex", alignItems: "center", gap: 6, marginRight: 8 }}>\n'
        '        <span style={{ padding: "2px 8px", borderRadius: 999, fontSize: 11, fontWeight: 600, background: "#eef2ff", color: "#3730a3", textTransform: "capitalize" }}>{pretty(current)}</span>\n'
        "        {moves.map((m) => (\n"
        '          <button key={m.name} type="button" onClick={() => run(m)} disabled={busy !== null} title={error ?? undefined}\n'
        '            style={{ padding: "3px 8px", border: "1px solid #c7d2fe", borderRadius: 4, fontSize: 12, background: "#fff", color: "#4338ca", cursor: busy ? "default" : "pointer" }}>\n'
        "            {busy === m.name ? \"\\u2026\" : m.label}\n"
        "          </button>\n"
        "        ))}\n"
        '        {error && <span role="alert" style={{ color: "#b91c1c", fontSize: 11 }}>{error}</span>}\n'
        "      </span>\n"
        "    );\n"
        "  }\n\n"
        "  return (\n"
        f'    <section aria-label="{entity} status" style={{{{ margin: "0 0 20px", padding: "16px 18px", border: "1px solid #e2e8f0", borderRadius: 12, background: "#fff" }}}}>\n'
        '      <ol style={{ display: "flex", flexWrap: "wrap", gap: 6, listStyle: "none", margin: 0, padding: 0 }}>\n'
        "        {STATES.map((state, i) => (\n"
        "          <li key={state} aria-current={state === current ? \"step\" : undefined}\n"
        "            style={{ padding: \"4px 10px\", borderRadius: 999, fontSize: 12, fontWeight: 600, textTransform: \"capitalize\",\n"
        "              background: state === current ? \"#4f46e5\" : i < position ? \"#e0e7ff\" : \"#f1f5f9\",\n"
        "              color: state === current ? \"#fff\" : i < position ? \"#3730a3\" : \"#64748b\" }}>\n"
        "            {pretty(state)}\n"
        "          </li>\n"
        "        ))}\n"
        "      </ol>\n"
        "      {moves.length > 0 && (\n"
        '        <div style={{ display: "flex", flexWrap: "wrap", gap: 8, marginTop: 12 }}>\n'
        "          {moves.map((m) => (\n"
        '            <button key={m.name} type="button" onClick={() => run(m)} disabled={busy !== null}\n'
        '              style={{ padding: "7px 14px", border: "none", borderRadius: 8, fontSize: 13, fontWeight: 600,\n'
        '                background: "#4f46e5", color: "#fff", cursor: busy ? "default" : "pointer", opacity: busy && busy !== m.name ? 0.6 : 1 }}>\n'
        "              {busy === m.name ? \"Working\\u2026\" : m.label}\n"
        "            </button>\n"
        "          ))}\n"
        "        </div>\n"
        "      )}\n"
        '      {error && <p role="alert" style={{ margin: "10px 0 0", color: "#b91c1c", fontSize: 13 }}>{error}</p>}\n'
        "    </section>\n"
        "  );\n"
        "}\n"
    )


def web_lifecycle_files(ir: ApplicationIR, *, has_auth: bool) -> list[tuple[str, str]]:
    return [
        (lifecycle_component_path(w), web_lifecycle_component(ir, w, has_auth=has_auth))
        for w in workflows_of(ir)
    ]


def mobile_lifecycle_panel(ir: ApplicationIR, workflow: Workflow) -> str:
    """React Native: the same panel for the mobile detail screen."""
    routes = [r for r in transition_routes(ir) if r.workflow.entity == workflow.entity]
    moves_ts = ",\n".join(
        f'  {{ name: {json.dumps(r.transition.name)}, label: {json.dumps(_label(r.transition.name))}, '
        f'to: {json.dumps(r.transition.to)}, from: {json.dumps(list(r.transition.sources))}, '
        f'roles: {json.dumps(list(r.transition.roles))}, path: {json.dumps(r.path.split("/{")[0])} }}'
        for r in routes
    )
    entity = workflow.entity
    return (
        f"// Generated by OmniStackAI (R-590): the {entity} lifecycle on the phone.\n"
        "import React, { useState } from 'react';\n"
        "import { View, Text, StyleSheet } from 'react-native';\n"
        "import { Button } from '../../../design-system/components/Button';\n"
        "import { tokens } from '../../../design-system/tokens';\n"
        "import { apiClient } from '../../../shared/api/client';\n"
        "import { useAuth } from '../../../shared/auth/AuthContext';\n\n"
        f"const STATES = {json.dumps(list(workflow.states))};\n"
        f"const FIELD = {json.dumps(workflow.field)};\n"
        "const MOVES: { name: string; label: string; to: string; from: string[]; roles: string[]; path: string }[] = [\n"
        + moves_ts
        + ",\n];\n\n"
        f"export const {entity}Lifecycle: React.FC<{{ record: any; onChanged?: (updated: any) => void }}> = ({{ record, onChanged }}) => {{\n"
        "  const role = useAuth().user?.role ?? null;\n"
        "  const [busy, setBusy] = useState<string | null>(null);\n"
        "  const [error, setError] = useState<string | null>(null);\n"
        "  const current = String(record?.[FIELD] ?? STATES[0]);\n"
        "  const moves = MOVES.filter((m) => (m.from.length === 0 || m.from.includes(current)) && m.to !== current)\n"
        "    .filter((m) => m.roles.length === 0 || role === null || m.roles.includes(role));\n\n"
        "  const run = async (m: (typeof MOVES)[number]) => {\n"
        "    setBusy(m.name);\n"
        "    setError(null);\n"
        "    try {\n"
        "      const updated = await apiClient.post<any>(`${m.path}/${encodeURIComponent(String(record.id))}/${m.name}`, {});\n"
        "      onChanged?.(updated);\n"
        "    } catch (err) {\n"
        "      setError(err instanceof Error ? err.message : 'That change could not be made.');\n"
        "    } finally {\n"
        "      setBusy(null);\n"
        "    }\n"
        "  };\n\n"
        "  return (\n"
        "    <View style={styles.panel} accessibilityLabel=\"Status\">\n"
        "      <View style={styles.steps}>\n"
        "        {STATES.map((s) => (\n"
        "          <Text key={s} style={[styles.step, s === current && styles.stepCurrent]}>{s.replace(/_/g, ' ')}</Text>\n"
        "        ))}\n"
        "      </View>\n"
        "      {moves.map((m) => (\n"
        "        <Button key={m.name} title={m.label} onPress={() => run(m)} loading={busy === m.name}\n"
        "          disabled={busy !== null} style={styles.move} />\n"
        "      ))}\n"
        "      {error && <Text accessibilityRole=\"alert\" style={styles.error}>{error}</Text>}\n"
        "    </View>\n"
        "  );\n"
        "};\n\n"
        "const styles = StyleSheet.create({\n"
        "  panel: { marginBottom: tokens.spacing.md },\n"
        "  steps: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: tokens.spacing.sm },\n"
        "  step: { paddingHorizontal: 10, paddingVertical: 4, marginRight: 6, marginBottom: 6, borderRadius: 999,\n"
        "    overflow: 'hidden', fontSize: tokens.fontSize.xs, color: tokens.colors.textMuted,\n"
        "    backgroundColor: tokens.colors.surface, textTransform: 'capitalize' },\n"
        "  stepCurrent: { color: '#fff', backgroundColor: tokens.colors.primary },\n"
        "  move: { marginBottom: tokens.spacing.sm },\n"
        "  error: { color: tokens.colors.danger, fontSize: tokens.fontSize.sm },\n"
        "});\n"
    )
