"""R-567: money in a generated Node backend - one service, an Express and a Hono router over it.

The same books as Python and Go (see `money_python.py`): integer minor units, a double-entry
ledger whose sums are the balances, the amount read from the record, the mock provider offline,
Stripe / Razorpay with verified, idempotent webhooks.
"""

from __future__ import annotations

import json

from ..application_ir import ApplicationIR
from ..application_ir.money import money_of
from ..application_ir.ownership import ownership_for_entity
from .schema_sql import sql_identifier, table_name

#: (method, path, service function, guarded). Paths in Express/Hono syntax.
NODE_MONEY_ROUTES = (
    ("post", "/payments/checkout", "checkout", True),
    ("post", "/payments/:paymentId/confirm", "confirmMock", True),
    ("post", "/payments/:paymentId/refund", "refund", True),
    ("get", "/payments", "listPayments", True),
    ("post", "/payments/webhooks/stripe", "stripeWebhook", False),
    ("post", "/payments/webhooks/razorpay", "razorpayWebhook", False),
    ("get", "/money/balance", "myBalance", True),
    ("get", "/money/ledger", "myLedger", True),
    ("get", "/money/summary", "summary", True),
    ("post", "/money/payouts", "requestPayout", True),
    ("get", "/money/payouts", "listPayouts", True),
    ("post", "/money/payouts/:payoutId/pay", "payPayout", True),
    ("post", "/money/payouts/:payoutId/reject", "rejectPayout", True),
)


def node_money_service(ir: ApplicationIR) -> str:
    money = money_of(ir)
    assert money is not None
    charges = {}
    for charge in money.charges:
        entity = next(e for e in ir.entities if e.name == charge.entity)
        rule = ownership_for_entity(ir, charge.entity)
        paid = next((f.name for f in entity.fields if f.name in ("paid", "is_paid") and f.type.value == "bool"), None)
        charges[table_name(charge.entity)] = {
            "entity": charge.entity,
            "table": sql_identifier(table_name(charge.entity)),
            "amount": sql_identifier(charge.amount),
            "payee": sql_identifier(charge.payee) if charge.payee else None,
            "paid": sql_identifier(paid) if paid else None,
            "assignee": sql_identifier(rule.assignee) if rule and rule.assignee else None,
            "owned": rule is not None and rule.reads_own,
            "seeAll": list(rule.bypass_roles) if rule else [],
        }
    config = (
        f"const CURRENCY = {json.dumps(money.currency)};\n"
        f"const MINOR = {money.minor_unit};\n"
        f"const COMMISSION_BPS = {money.commission_bps};\n"
        f"const REFUNDERS: string[] = {json.dumps(list(money.refunders))};\n"
        f"const CHARGES: Record<string, Charge> = {json.dumps(charges, indent=2)};\n"
    )
    return _SERVICE.replace("__CONFIG__", config)


def node_money_router(framework: str) -> str:
    lines = [f"// Generated by OmniStackAI: money routes (R-567) for {framework}."]
    if framework == "hono":
        lines += [
            "import { Hono } from 'hono';",
            "import { requireAuth } from '../middleware/auth.js';",
            "import * as money from './service.js';",
            "",
            "export const router = new Hono();",
            "",
        ]
        for method, path, fn, guarded in NODE_MONEY_ROUTES:
            guard = "requireAuth, " if guarded else ""
            raw = "raw: await c.req.text(), " if not guarded else ""
            body = "body: await c.req.json().catch(() => ({})), " if method == "post" and guarded else ""
            lines += [
                f"router.{method}('{path}', {guard}async (c) => {{",
                f"  const out = await money.{fn}({{ claims: (c as any).get('user'), params: c.req.param(), "
                f"query: c.req.query(), {body}{raw}headers: Object.fromEntries(c.req.raw.headers) }});",
                "  return c.json(out.body as any, out.status as any);",
                "});",
                "",
            ]
    else:
        lines += [
            "import { Router, Request, Response } from 'express';",
            "import { requireAuth } from '../middleware/auth.js';",
            "import * as money from './service.js';",
            "",
            "export const router = Router();",
            "",
        ]
        for method, path, fn, guarded in NODE_MONEY_ROUTES:
            guard = "requireAuth, " if guarded else ""
            lines += [
                f"router.{method}('{path}', {guard}async (req: Request, res: Response) => {{",
                f"  const out = await money.{fn}({{ claims: (req as any).user, params: req.params as any, "
                "query: req.query as any, body: req.body ?? {}, raw: (req as any).rawBody?.toString('utf8') ?? '', "
                "headers: req.headers as any });",
                "  res.status(out.status).json(out.body);",
                "});",
                "",
            ]
    return "\n".join(lines) + "\n"


_SERVICE = r'''// Generated by OmniStackAI: money - payments, a double-entry ledger, refunds, commission, payouts (R-567).
//
// Amounts are integers in the currency's minor unit. Every ledger entry moves `amount` from the
// `debit` account to the `credit` account; a balance is credits minus debits, so the books always sum
// to zero. The amount to pay is read from the stored record, never the client. PAYMENT_PROVIDER picks
// mock (the default with no keys), stripe or razorpay; real providers mark a payment paid only from
// their signed webhook.
import crypto from 'node:crypto';
import type { PoolClient } from 'pg';
import { pool } from '../db/pool.js';
import { canTouchAssigned, ownerOf, seesAll, type AuthClaims } from '../middleware/auth.js';

interface Charge {
  entity: string; table: string; amount: string; payee: string | null; paid: string | null;
  assignee: string | null; owned: boolean; seeAll: string[];
}

__CONFIG__
const WEBHOOK_TOLERANCE_SECONDS = 300;
const NOBODY = '00000000-0000-0000-0000-000000000000';

export interface MoneyRequest {
  claims?: AuthClaims;
  params: Record<string, string>;
  query: Record<string, string | undefined>;
  body?: any;
  raw?: string;
  headers: Record<string, string | string[] | undefined>;
}
export interface MoneyResponse { status: number; body: unknown }

class Fail extends Error {
  constructor(public status: number, message: string) { super(message); }
}
const ok = (body: unknown): MoneyResponse => ({ status: 200, body });

async function guarded(work: () => Promise<MoneyResponse>): Promise<MoneyResponse> {
  try {
    return await work();
  } catch (error) {
    if (error instanceof Fail) return { status: error.status, body: { detail: error.message } };
    if ((error as any)?.code === '22P02') return { status: 422, body: { detail: 'invalid_value' } };
    throw error;
  }
}

async function inTransaction<T>(work: (client: PoolClient) => Promise<T>): Promise<T> {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    const result = await work(client);
    await client.query('COMMIT');
    return result;
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
}

type Q = { query: (text: string, values?: unknown[]) => Promise<{ rows: any[]; rowCount: number | null }> };

export function provider(): string {
  const chosen = (process.env.PAYMENT_PROVIDER ?? '').trim().toLowerCase();
  if (chosen) return chosen;
  if (process.env.STRIPE_SECRET_KEY) return 'stripe';
  if (process.env.RAZORPAY_KEY_ID) return 'razorpay';
  return 'mock';
}

/** "499.5" -> 49950, rounding half up, with integer arithmetic on the decimal text. */
export function toMinor(text: unknown): number {
  const match = /^(\d+)(?:\.(\d+))?$/.exec(String(text ?? '').trim());
  if (!match) return 0;
  const digits = String(MINOR).length - 1;
  const frac = (match[2] ?? '').padEnd(digits + 1, '0');
  let value = Number(match[1]) * MINOR + Number(frac.slice(0, digits) || '0');
  if (Number(frac[digits] ?? '0') >= 5) value += 1;
  return value;
}

async function account(q: Q, kind: string, holder: string | null = null): Promise<string> {
  if (kind === 'user') {
    await q.query(
      "INSERT INTO money_account (kind, holder_id) VALUES ('user', $1) ON CONFLICT (kind, COALESCE(holder_id, '00000000-0000-0000-0000-000000000000'::uuid)) DO NOTHING",
      [holder]);
    return (await q.query("SELECT id FROM money_account WHERE kind = 'user' AND holder_id = $1", [holder])).rows[0].id;
  }
  return (await q.query('SELECT id FROM money_account WHERE kind = $1 AND holder_id IS NULL', [kind])).rows[0].id;
}

async function post(q: Q, debit: string, credit: string, amount: number, kind: string,
                    paymentId: string | null = null, payoutId: string | null = null): Promise<void> {
  if (amount > 0) {
    await q.query('INSERT INTO ledger_entry (debit, credit, amount, kind, payment_id, payout_id) VALUES ($1, $2, $3, $4, $5, $6)',
      [debit, credit, amount, kind, paymentId, payoutId]);
  }
}

async function balance(q: Q, id: string): Promise<number> {
  const r = await q.query('SELECT COALESCE(SUM(CASE WHEN credit = $1 THEN amount ELSE -amount END), 0) AS b FROM ledger_entry WHERE credit = $1 OR debit = $1', [id]);
  return Number(r.rows[0].b);
}

/** pg returns BIGINT as text; amounts are well within a JS number. */
function asPayment(row: any): any {
  if (!row) return row;
  for (const key of ['amount', 'commission', 'refunded']) if (key in row) row[key] = Number(row[key]);
  return row;
}

function chargeFor(entity: string): Charge | undefined {
  const key = String(entity ?? '').toLowerCase();
  return CHARGES[key] ?? Object.values(CHARGES).find((c) => c.entity.toLowerCase() === key);
}

function header(req: MoneyRequest, name: string): string {
  const value = req.headers[name.toLowerCase()];
  return Array.isArray(value) ? value[0] ?? '' : value ?? '';
}

// --- paying ---------------------------------------------------------------------------------

export function checkout(req: MoneyRequest): Promise<MoneyResponse> {
  return guarded(async () => {
    const charge = chargeFor(req.body?.entity);
    if (!charge) throw new Fail(404, 'nothing to pay for');
    const recordId = String(req.body?.record_id ?? '');
    const r = await pool.query(
      `SELECT ${charge.amount}::text AS amount, ${charge.payee ?? 'NULL'}::text AS payee, "created_by"::text AS created_by, ${charge.assignee ?? 'NULL'}::text AS assignee FROM ${charge.table} WHERE "id" = $1`,
      [recordId]);
    const row = r.rows[0];
    if (!row || (charge.owned && !canTouchAssigned(req.claims, row.created_by, row.assignee, charge.seeAll))) {
      throw new Fail(404, 'not_found');
    }
    const paid = await pool.query("SELECT 1 FROM payment WHERE entity = $1 AND record_id = $2 AND status = 'succeeded'", [charge.entity, recordId]);
    if (paid.rows.length) throw new Fail(409, 'already paid');
    const amount = toMinor(row.amount); // from the record, never the client
    if (amount <= 0) throw new Fail(422, 'nothing to pay: the amount is zero');
    const payee = row.payee || null;
    const commission = payee ? Math.floor((amount * COMMISSION_BPS) / 10000) : amount;
    const chosen = provider();
    const created = await pool.query(
      'INSERT INTO payment (entity, record_id, payer_id, payee_id, amount, commission, currency, provider) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id',
      [charge.entity, recordId, ownerOf(req.claims), payee, amount, commission, CURRENCY, chosen]);
    const paymentId: string = created.rows[0].id;
    const out: Record<string, unknown> = { payment_id: paymentId, amount, currency: CURRENCY, provider: chosen };
    if (chosen === 'mock') {
      out.confirm = `/payments/${paymentId}/confirm`;
    } else if (chosen === 'stripe') {
      const session = await stripeRequest('/v1/checkout/sessions', {
        mode: 'payment',
        'line_items[0][quantity]': '1',
        'line_items[0][price_data][currency]': CURRENCY.toLowerCase(),
        'line_items[0][price_data][unit_amount]': String(amount),
        'line_items[0][price_data][product_data][name]': `${charge.entity} ${recordId.slice(0, 8)}`,
        'metadata[payment_id]': paymentId,
        'payment_intent_data[metadata][payment_id]': paymentId,
        success_url: process.env.PAYMENT_SUCCESS_URL || 'http://localhost:3000/checkout/success',
        cancel_url: process.env.PAYMENT_CANCEL_URL || 'http://localhost:3000/checkout/cancel',
      });
      await pool.query('UPDATE payment SET provider_ref = $1 WHERE id = $2', [session.id, paymentId]);
      out.url = session.url;
    } else if (chosen === 'razorpay') {
      const order = await razorpayRequest('/v1/orders', { amount, currency: CURRENCY, receipt: paymentId, notes: { payment_id: paymentId } });
      await pool.query('UPDATE payment SET provider_ref = $1 WHERE id = $2', [order.id, paymentId]);
      out.order_id = order.id;
      out.key_id = process.env.RAZORPAY_KEY_ID ?? '';
    } else {
      throw new Fail(500, `unknown PAYMENT_PROVIDER ${chosen}`);
    }
    return ok(out);
  });
}

/** The mock provider's "payment succeeded". Real providers confirm only through their webhook. */
export function confirmMock(req: MoneyRequest): Promise<MoneyResponse> {
  return guarded(async () => {
    const r = await pool.query('SELECT * FROM payment WHERE id = $1', [req.params.paymentId]);
    const payment = r.rows[0];
    const me = ownerOf(req.claims);
    if (!payment || payment.provider !== 'mock' || !me || payment.payer_id !== me) throw new Fail(404, 'not_found');
    return ok(await settle(payment.id, `mock_${payment.id}`));
  });
}

/** Mark a payment succeeded and book it: cash in, then the commission and the payee's share. */
async function settle(paymentId: string, providerRef: string): Promise<any> {
  return inTransaction(async (client) => {
    const current = (await client.query('SELECT * FROM payment WHERE id = $1 FOR UPDATE', [paymentId])).rows[0];
    if (!current) throw new Fail(404, 'not_found');
    if (current.status === 'succeeded') return asPayment(current); // a retried webhook: already booked
    const payment = asPayment((await client.query(
      "UPDATE payment SET status = 'succeeded', provider_ref = $1, updated_at = NOW() WHERE id = $2 RETURNING *",
      [providerRef, paymentId])).rows[0]);
    const external = await account(client, 'external');
    const escrow = await account(client, 'escrow');
    const revenue = await account(client, 'revenue');
    await post(client, external, escrow, payment.amount, 'payment', payment.id);
    await post(client, escrow, revenue, payment.commission, 'commission', payment.id);
    if (payment.payee_id) {
      await post(client, escrow, await account(client, 'user', payment.payee_id), payment.amount - payment.commission, 'sale', payment.id);
    }
    const charge = chargeFor(payment.entity);
    if (charge?.paid) await client.query(`UPDATE ${charge.table} SET ${charge.paid} = TRUE WHERE "id" = $1`, [payment.record_id]);
    return payment;
  });
}

// --- real providers --------------------------------------------------------------------------------

async function providerCall(url: string, init: RequestInit): Promise<any> {
  let response: Response;
  try {
    response = await fetch(url, { ...init, signal: AbortSignal.timeout(30000) });
  } catch {
    throw new Fail(502, 'payment provider unreachable');
  }
  const text = await response.text();
  if (!response.ok) throw new Fail(502, `payment provider refused: ${text.slice(0, 300)}`);
  return JSON.parse(text);
}

async function stripeRequest(path: string, form: Record<string, string>): Promise<any> {
  const key = process.env.STRIPE_SECRET_KEY;
  if (!key) throw new Fail(503, 'STRIPE_SECRET_KEY is not set');
  return providerCall(`https://api.stripe.com${path}`, {
    method: 'POST', body: new URLSearchParams(form).toString(),
    headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/x-www-form-urlencoded' },
  });
}

async function razorpayRequest(path: string, body: unknown): Promise<any> {
  const key = process.env.RAZORPAY_KEY_ID, secret = process.env.RAZORPAY_KEY_SECRET;
  if (!key || !secret) throw new Fail(503, 'RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET are not set');
  return providerCall(`https://api.razorpay.com${path}`, {
    method: 'POST', body: JSON.stringify(body),
    headers: { Authorization: `Basic ${Buffer.from(`${key}:${secret}`).toString('base64')}`, 'Content-Type': 'application/json' },
  });
}

function sameHex(expected: string, given: string): boolean {
  const a = Buffer.from(expected), b = Buffer.from(given);
  return a.length === b.length && crypto.timingSafeEqual(a, b);
}

/** A Stripe-Signature header, refusing events older than the tolerance (replays). */
export function verifyStripe(payload: string, sigHeader: string, secret: string, now = Date.now() / 1000): boolean {
  const parts = Object.fromEntries(sigHeader.split(',').map((p) => p.split('=') as [string, string]));
  const timestamp = parts.t ?? '', signature = parts.v1 ?? '';
  if (!/^\d+$/.test(timestamp) || !signature) return false;
  if (Math.abs(now - Number(timestamp)) > WEBHOOK_TOLERANCE_SECONDS) return false;
  const expected = crypto.createHmac('sha256', secret).update(`${timestamp}.${payload}`).digest('hex');
  return sameHex(expected, signature);
}

export function verifyRazorpay(payload: string, signature: string, secret: string): boolean {
  const expected = crypto.createHmac('sha256', secret).update(payload).digest('hex');
  return !!signature && sameHex(expected, signature);
}

async function firstTime(providerName: string, eventId: string): Promise<boolean> {
  const r = await pool.query('INSERT INTO processed_event (provider, event_id) VALUES ($1, $2) ON CONFLICT DO NOTHING', [providerName, eventId]);
  return (r.rowCount ?? 0) === 1;
}

async function settleChecked(paymentId: string | undefined, amount: number, currency: string, ref: string): Promise<void> {
  const r = await pool.query('SELECT amount, currency FROM payment WHERE id = $1', [paymentId ?? NOBODY]);
  const payment = r.rows[0];
  // What the provider charged must be what we asked for.
  if (!payment || Number(payment.amount) !== amount || payment.currency.toLowerCase() !== currency.toLowerCase()) {
    throw new Fail(400, 'payment does not match');
  }
  await settle(paymentId as string, ref);
}

export function stripeWebhook(req: MoneyRequest): Promise<MoneyResponse> {
  return guarded(async () => {
    const secret = process.env.STRIPE_WEBHOOK_SECRET ?? '';
    const payload = req.raw ?? '';
    if (!secret || !verifyStripe(payload, header(req, 'stripe-signature'), secret)) throw new Fail(400, 'invalid signature');
    const event = JSON.parse(payload);
    if (!(await firstTime('stripe', String(event.id)))) return ok({ received: true, duplicate: true });
    if (event.type === 'checkout.session.completed') {
      const session = event.data.object;
      await settleChecked(session.metadata?.payment_id, Number(session.amount_total ?? 0), String(session.currency ?? ''),
        String(session.payment_intent || session.id));
    }
    return ok({ received: true });
  });
}

export function razorpayWebhook(req: MoneyRequest): Promise<MoneyResponse> {
  return guarded(async () => {
    const secret = process.env.RAZORPAY_WEBHOOK_SECRET ?? '';
    const payload = req.raw ?? '';
    if (!secret || !verifyRazorpay(payload, header(req, 'x-razorpay-signature'), secret)) throw new Fail(400, 'invalid signature');
    const event = JSON.parse(payload);
    const eventId = header(req, 'x-razorpay-event-id') || String(event.created_at);
    if (!(await firstTime('razorpay', eventId))) return ok({ received: true, duplicate: true });
    if (event.event === 'payment.captured' || event.event === 'order.paid') {
      const entity = event.payload.payment.entity;
      await settleChecked(entity.notes?.payment_id, Number(entity.amount ?? 0), String(entity.currency ?? ''), String(entity.id));
    }
    return ok({ received: true });
  });
}

// --- refunds -----------------------------------------------------------------------------------------

export function refund(req: MoneyRequest): Promise<MoneyResponse> {
  return guarded(async () => {
    if (!seesAll(req.claims, REFUNDERS)) throw new Fail(403, 'forbidden');
    return ok(await inTransaction(async (client) => {
      const payment = asPayment((await client.query('SELECT * FROM payment WHERE id = $1 FOR UPDATE', [req.params.paymentId])).rows[0]);
      if (!payment || payment.status !== 'succeeded') throw new Fail(404, 'not_found');
      const remaining = payment.amount - payment.refunded;
      const amount = req.body?.amount == null ? remaining : Number(req.body.amount);
      if (!Number.isInteger(amount) || amount <= 0 || amount > remaining) throw new Fail(422, `refund 1..${remaining}`);
      if (payment.provider === 'stripe') {
        await stripeRequest('/v1/refunds', { payment_intent: payment.provider_ref, amount: String(amount) });
      } else if (payment.provider === 'razorpay') {
        await razorpayRequest(`/v1/payments/${payment.provider_ref}/refund`, { amount });
      }
      // Taken back in proportion: the payee's share from the payee, the rest from revenue.
      let payeeShare = 0;
      const external = await account(client, 'external');
      if (payment.payee_id) {
        payeeShare = Math.floor((amount * (payment.amount - payment.commission)) / payment.amount);
        await post(client, await account(client, 'user', payment.payee_id), external, payeeShare, 'refund', payment.id);
      }
      await post(client, await account(client, 'revenue'), external, amount - payeeShare, 'refund', payment.id);
      const updated = asPayment((await client.query(
        'UPDATE payment SET refunded = refunded + $1, updated_at = NOW() WHERE id = $2 RETURNING *', [amount, payment.id])).rows[0]);
      const charge = chargeFor(payment.entity);
      if (charge?.paid && updated.refunded === updated.amount) {
        await client.query(`UPDATE ${charge.table} SET ${charge.paid} = FALSE WHERE "id" = $1`, [payment.record_id]);
      }
      return updated;
    }));
  });
}

export function listPayments(req: MoneyRequest): Promise<MoneyResponse> {
  return guarded(async () => {
    const conditions: string[] = [], values: unknown[] = [];
    if (!seesAll(req.claims, REFUNDERS)) {
      values.push(ownerOf(req.claims) ?? NOBODY);
      conditions.push(`(payer_id = $${values.length} OR payee_id = $${values.length})`);
    }
    if (req.query.entity) { values.push(req.query.entity); conditions.push(`lower(entity) = lower($${values.length})`); }
    if (req.query.record_id) { values.push(req.query.record_id); conditions.push(`record_id = $${values.length}`); }
    const where = conditions.length ? ` WHERE ${conditions.join(' AND ')}` : '';
    const r = await pool.query(`SELECT * FROM payment${where} ORDER BY created_at DESC LIMIT 200`, values);
    return ok(r.rows.map(asPayment));
  });
}

// --- balances, the ledger and payouts ------------------------------------------------------------------

async function pending(q: Q, holder: string): Promise<number> {
  const r = await q.query("SELECT COALESCE(SUM(amount), 0) AS p FROM payout WHERE holder_id = $1 AND status = 'requested'", [holder]);
  return Number(r.rows[0].p);
}

export function myBalance(req: MoneyRequest): Promise<MoneyResponse> {
  return guarded(async () => {
    const me = ownerOf(req.claims);
    if (!me) return ok({ currency: CURRENCY, minor_unit: MINOR, balance: 0, pending_payouts: 0, available: 0 });
    const total = await balance(pool, await account(pool, 'user', me));
    const waiting = await pending(pool, me);
    return ok({ currency: CURRENCY, minor_unit: MINOR, balance: total, pending_payouts: waiting, available: total - waiting });
  });
}

export function myLedger(req: MoneyRequest): Promise<MoneyResponse> {
  return guarded(async () => {
    const me = ownerOf(req.claims);
    if (!me) return ok([]);
    const mine = await account(pool, 'user', me);
    const r = await pool.query(
      'SELECT id, kind, payment_id, payout_id, created_at, CASE WHEN credit = $1 THEN amount ELSE -amount END AS amount FROM ledger_entry WHERE credit = $1 OR debit = $1 ORDER BY created_at DESC LIMIT 200',
      [mine]);
    return ok(r.rows.map((row) => ({ ...row, amount: Number(row.amount) })));
  });
}

/** The platform's books: what it holds, what it earned, what users are owed - and that it balances. */
export function summary(req: MoneyRequest): Promise<MoneyResponse> {
  return guarded(async () => {
    if (!seesAll(req.claims, REFUNDERS)) throw new Fail(403, 'forbidden');
    const out: Record<string, unknown> = { currency: CURRENCY, minor_unit: MINOR };
    let total = 0;
    for (const kind of ['external', 'escrow', 'revenue']) {
      const b = await balance(pool, await account(pool, kind));
      out[kind] = b;
      total += b;
    }
    const r = await pool.query(
      "SELECT COALESCE(SUM(CASE WHEN l.credit = a.id THEN l.amount ELSE -l.amount END), 0) AS owed FROM money_account a JOIN ledger_entry l ON l.credit = a.id OR l.debit = a.id WHERE a.kind = 'user'");
    out.owed_to_users = Number(r.rows[0].owed);
    out.balanced = total + Number(r.rows[0].owed) === 0;
    return ok(out);
  });
}

const asPayout = (row: any) => (row ? { ...row, amount: Number(row.amount) } : row);

export function requestPayout(req: MoneyRequest): Promise<MoneyResponse> {
  return guarded(async () => {
    const me = ownerOf(req.claims);
    if (!me) throw new Fail(422, 'nothing to pay out');
    return ok(await inTransaction(async (client) => {
      const mine = await account(client, 'user', me);
      await client.query('SELECT id FROM money_account WHERE id = $1 FOR UPDATE', [mine]);
      const available = (await balance(client, mine)) - (await pending(client, me));
      const amount = req.body?.amount == null ? available : Number(req.body.amount);
      if (!Number.isInteger(amount) || amount <= 0 || amount > available) throw new Fail(422, `payout 1..${Math.max(available, 0)}`);
      return asPayout((await client.query('INSERT INTO payout (holder_id, amount) VALUES ($1, $2) RETURNING *', [me, amount])).rows[0]);
    }));
  });
}

export function listPayouts(req: MoneyRequest): Promise<MoneyResponse> {
  return guarded(async () => {
    const r = seesAll(req.claims, REFUNDERS)
      ? await pool.query('SELECT * FROM payout ORDER BY created_at DESC LIMIT 200')
      : await pool.query('SELECT * FROM payout WHERE holder_id = $1 ORDER BY created_at DESC LIMIT 200', [ownerOf(req.claims) ?? NOBODY]);
    return ok(r.rows.map(asPayout));
  });
}

function decide(req: MoneyRequest, status: 'paid' | 'rejected'): Promise<MoneyResponse> {
  return guarded(async () => {
    if (!seesAll(req.claims, REFUNDERS)) throw new Fail(403, 'forbidden');
    return ok(await inTransaction(async (client) => {
      const payout = (await client.query('SELECT * FROM payout WHERE id = $1 FOR UPDATE', [req.params.payoutId])).rows[0];
      if (!payout) throw new Fail(404, 'not_found');
      if (payout.status !== 'requested') throw new Fail(409, `payout already ${payout.status}`);
      if (status === 'paid') {
        await post(client, await account(client, 'user', payout.holder_id), await account(client, 'external'), Number(payout.amount), 'payout', null, payout.id);
      }
      return asPayout((await client.query(
        'UPDATE payout SET status = $1, reference = $2, decided_at = NOW() WHERE id = $3 RETURNING *',
        [status, req.body?.reference ?? null, payout.id])).rows[0]);
    }));
  });
}

export const payPayout = (req: MoneyRequest) => decide(req, 'paid');
export const rejectPayout = (req: MoneyRequest) => decide(req, 'rejected');
'''
