"""PC-113: money in the generated web and admin apps, over R-567's API.

    web    a Pay panel on a chargeable record's page (mock confirms in place, Stripe goes to its
           hosted checkout, Razorpay opens its checkout), and a Wallet page: balance, what is
           available, the ledger, payouts and a request for one
    admin  a Money page: the books (and whether they balance), payments with refunds, payout
           requests to pay or reject

The pages ask the API and show what it answers; every rule (who pays, who refunds, how much is
available) is enforced there, so a hidden button is courtesy, not security.
"""

from __future__ import annotations

import json

from ..application_ir import ApplicationIR
from ..application_ir.money import money_of

PAY_PANEL_PATH = "components/pay-panel.tsx"


def money_client(ir: ApplicationIR) -> str:
    money = money_of(ir)
    assert money is not None
    return (
        "// Generated by OmniStackAI (PC-113): the money API (R-567) for the pages.\n"
        'const BASE_URL = process.env.NEXT_PUBLIC_API_URL || "";\n\n'
        f"export const CURRENCY = {json.dumps(money.currency)};\n"
        f"export const MINOR = {money.minor_unit};\n\n"
        "/** 49950 -> \"₹499.50\" in the app's currency. */\n"
        "export function formatMoney(minor: number): string {\n"
        "  return new Intl.NumberFormat(undefined, { style: \"currency\", currency: CURRENCY }).format(minor / MINOR);\n"
        "}\n\n"
        "async function call<T>(path: string, method = \"GET\", body?: unknown): Promise<T> {\n"
        "  const token = typeof localStorage !== \"undefined\" ? localStorage.getItem(\"auth_token\") : null;\n"
        "  const res = await fetch(`${BASE_URL}${path}`, {\n"
        "    method,\n"
        "    headers: { ...(body !== undefined ? { \"Content-Type\": \"application/json\" } : {}), ...(token ? { Authorization: `Bearer ${token}` } : {}) },\n"
        "    body: body !== undefined ? JSON.stringify(body) : undefined,\n"
        "  });\n"
        "  const data = await res.json().catch(() => ({}));\n"
        "  if (!res.ok) throw new Error((data as { detail?: string }).detail || `Request failed (${res.status})`);\n"
        "  return data as T;\n"
        "}\n\n"
        "export interface Payment { id: string; entity: string; record_id: string; payer_id: string | null; payee_id: string | null;\n"
        "  amount: number; commission: number; currency: string; status: string; refunded: number; provider: string; created_at: string }\n"
        "export interface Checkout { payment_id: string; amount: number; currency: string; provider: string; confirm?: string; url?: string; order_id?: string; key_id?: string }\n"
        "export interface Balance { currency: string; balance: number; pending_payouts: number; available: number }\n"
        "export interface Entry { id: string; kind: string; amount: number; created_at: string; payment_id: string | null; payout_id: string | null }\n"
        "export interface Payout { id: string; holder_id: string; amount: number; status: string; reference: string | null; created_at: string }\n"
        "export interface Books { currency: string; external: number; escrow: number; revenue: number; owed_to_users: number; balanced: boolean }\n\n"
        "export const checkout = (entity: string, recordId: string) => call<Checkout>(\"/payments/checkout\", \"POST\", { entity, record_id: recordId });\n"
        "export const confirmMock = (paymentId: string) => call<Payment>(`/payments/${paymentId}/confirm`, \"POST\", {});\n"
        "export const paymentsFor = (entity: string, recordId: string) => call<Payment[]>(`/payments?entity=${encodeURIComponent(entity)}&record_id=${encodeURIComponent(recordId)}`);\n"
        "export const allPayments = () => call<Payment[]>(\"/payments\");\n"
        "export const refund = (paymentId: string, amount?: number) => call<Payment>(`/payments/${paymentId}/refund`, \"POST\", amount ? { amount } : {});\n"
        "export const myBalance = () => call<Balance>(\"/money/balance\");\n"
        "export const myLedger = () => call<Entry[]>(\"/money/ledger\");\n"
        "export const books = () => call<Books>(\"/money/summary\");\n"
        "export const payouts = () => call<Payout[]>(\"/money/payouts\");\n"
        "export const requestPayout = (amount?: number) => call<Payout>(\"/money/payouts\", \"POST\", amount ? { amount } : {});\n"
        "export const payPayout = (id: string, reference: string) => call<Payout>(`/money/payouts/${id}/pay`, \"POST\", { reference });\n"
        "export const rejectPayout = (id: string) => call<Payout>(`/money/payouts/${id}/reject`, \"POST\", {});\n"
    )


PAY_PANEL = r'''"use client";

// Generated by OmniStackAI (PC-113): pay for this record. The price is the API's, from the stored
// record; this only asks for it. Test payments (no provider keys) confirm here; Stripe opens its
// hosted checkout; Razorpay its checkout window.
import { useCallback, useEffect, useState } from "react";
import { checkout, confirmMock, formatMoney, paymentsFor, type Checkout, type Payment } from "@/lib/money";

declare global {
  interface Window { Razorpay?: new (options: Record<string, unknown>) => { open: () => void } }
}

function loadRazorpay(): Promise<void> {
  if (window.Razorpay) return Promise.resolve();
  return new Promise((resolve, reject) => {
    const script = document.createElement("script");
    script.src = "https://checkout.razorpay.com/v1/checkout.js";
    script.onload = () => resolve();
    script.onerror = () => reject(new Error("Razorpay checkout did not load"));
    document.body.appendChild(script);
  });
}

export function PayPanel({ entity, recordId, onPaid }: { entity: string; recordId: string; onPaid?: () => void }) {
  const [paid, setPaid] = useState<Payment | null>(null);
  const [pending, setPending] = useState<Checkout | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [loaded, setLoaded] = useState(false);

  const refresh = useCallback(async () => {
    try {
      const list = await paymentsFor(entity, recordId);
      setPaid(list.find((p) => p.status === "succeeded") ?? null);
    } catch {
      setPaid(null); // not signed in, or not this user's to see
    } finally {
      setLoaded(true);
    }
  }, [entity, recordId]);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      if (!cancelled) await refresh();
    })();
    return () => { cancelled = true; };
  }, [refresh]);

  async function start() {
    setBusy(true);
    setError(null);
    try {
      const started = await checkout(entity, recordId);
      if (started.url) {
        window.location.href = started.url; // Stripe's hosted checkout
        return;
      }
      if (started.provider === "razorpay" && started.order_id) {
        await loadRazorpay();
        const Razorpay = window.Razorpay!;
        new Razorpay({ key: started.key_id, order_id: started.order_id, amount: started.amount, currency: started.currency,
          handler: () => { setTimeout(refresh, 2500); onPaid?.(); } }).open();
        return;
      }
      setPending(started); // the test provider: confirm below
    } catch (err) {
      setError(err instanceof Error ? err.message : "Payment could not start.");
    } finally {
      setBusy(false);
    }
  }

  async function confirm() {
    if (!pending) return;
    setBusy(true);
    setError(null);
    try {
      setPaid(await confirmMock(pending.payment_id));
      setPending(null);
      onPaid?.();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Payment failed.");
    } finally {
      setBusy(false);
    }
  }

  if (!loaded) return null;
  const box = { margin: "0 0 20px", padding: "16px 18px", border: "1px solid #e2e8f0", borderRadius: 12, background: "#fff" } as const;
  const button = { padding: "9px 16px", border: "none", borderRadius: 8, fontSize: 14, fontWeight: 600, background: "#4f46e5", color: "#fff", cursor: busy ? "default" : "pointer" } as const;
  if (paid) {
    const refunded = paid.refunded > 0;
    return (
      <section aria-label="Payment" style={box}>
        <p style={{ margin: 0, fontWeight: 600, color: "#047857" }}>
          Paid {formatMoney(paid.amount)}
          {refunded && <span style={{ color: "#92400e", fontWeight: 500 }}> · {formatMoney(paid.refunded)} refunded</span>}
        </p>
        <p style={{ margin: "4px 0 0", fontSize: 13, color: "#475569" }}>{new Date(paid.created_at).toLocaleString()}</p>
      </section>
    );
  }
  return (
    <section aria-label="Payment" style={box}>
      {pending ? (
        <>
          <p style={{ margin: "0 0 4px", fontWeight: 600 }}>Pay {formatMoney(pending.amount)}</p>
          <p style={{ margin: "0 0 12px", fontSize: 13, color: "#475569" }}>Test mode: no card is charged until the app owner connects a payment provider.</p>
          <div style={{ display: "flex", gap: 8 }}>
            <button type="button" onClick={confirm} disabled={busy} style={button}>{busy ? "Paying…" : "Confirm payment"}</button>
            <button type="button" onClick={() => setPending(null)} disabled={busy} style={{ ...button, background: "#fff", color: "#334155", border: "1px solid #cbd5e1" }}>Cancel</button>
          </div>
        </>
      ) : (
        <button type="button" onClick={start} disabled={busy} style={button}>{busy ? "Starting…" : "Pay now"}</button>
      )}
      {error && <p role="alert" style={{ margin: "10px 0 0", color: "#b91c1c", fontSize: 13 }}>{error}</p>}
    </section>
  );
}
'''


WALLET_PAGE = r'''"use client";

// Generated by OmniStackAI (PC-113): what this user is owed, how it got there, and taking it out.
import { useCallback, useEffect, useState } from "react";
import { formatMoney, MINOR, myBalance, myLedger, payouts, requestPayout, type Balance, type Entry, type Payout } from "@/lib/money";

const KIND: Record<string, string> = { sale: "Sale", refund: "Refund", payout: "Payout", commission: "Commission", payment: "Payment" };

export default function WalletPage() {
  const [balance, setBalance] = useState<Balance | null>(null);
  const [entries, setEntries] = useState<Entry[]>([]);
  const [mine, setMine] = useState<Payout[]>([]);
  const [amount, setAmount] = useState("");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      const [b, e, p] = await Promise.all([myBalance(), myLedger(), payouts()]);
      setBalance(b); setEntries(e); setMine(p); setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Sign in to see your wallet.");
    }
  }, []);

  useEffect(() => {
    let cancelled = false;
    (async () => { if (!cancelled) await load(); })();
    return () => { cancelled = true; };
  }, [load]);

  async function withdraw(event: React.FormEvent) {
    event.preventDefault();
    setBusy(true); setMessage(null); setError(null);
    try {
      const minor = amount.trim() ? Math.round(Number(amount) * MINOR) : undefined;
      const payout = await requestPayout(minor);
      setMessage(`Payout of ${formatMoney(payout.amount)} requested.`);
      setAmount("");
      await load();
    } catch (err) {
      setError(err instanceof Error ? err.message : "The payout could not be requested.");
    } finally {
      setBusy(false);
    }
  }

  const card = { padding: "16px 18px", border: "1px solid #e2e8f0", borderRadius: 12, background: "#fff" } as const;
  return (
    <main style={{ maxWidth: 880, margin: "0 auto", padding: "32px 16px" }}>
      <h1 style={{ fontSize: 28, fontWeight: 700, margin: "0 0 20px" }}>Wallet</h1>
      {error && <p role="alert" style={{ color: "#b91c1c" }}>{error}</p>}
      {balance && (
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 12, marginBottom: 24 }}>
          <div style={card}><p style={{ margin: 0, fontSize: 13, color: "#475569" }}>Balance</p><p style={{ margin: "4px 0 0", fontSize: 24, fontWeight: 700 }}>{formatMoney(balance.balance)}</p></div>
          <div style={card}><p style={{ margin: 0, fontSize: 13, color: "#475569" }}>Requested payouts</p><p style={{ margin: "4px 0 0", fontSize: 24, fontWeight: 700 }}>{formatMoney(balance.pending_payouts)}</p></div>
          <div style={card}><p style={{ margin: 0, fontSize: 13, color: "#475569" }}>Available</p><p style={{ margin: "4px 0 0", fontSize: 24, fontWeight: 700, color: "#047857" }}>{formatMoney(balance.available)}</p></div>
        </div>
      )}
      {balance && balance.available > 0 && (
        <form onSubmit={withdraw} style={{ ...card, display: "flex", flexWrap: "wrap", gap: 8, alignItems: "end", marginBottom: 24 }}>
          <label style={{ display: "grid", gap: 4, fontSize: 13, color: "#334155" }}>
            Amount to withdraw (leave empty for everything)
            <input inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder={String(balance.available / MINOR)}
              style={{ padding: "8px 10px", border: "1px solid #cbd5e1", borderRadius: 8, minWidth: 180 }} />
          </label>
          <button type="submit" disabled={busy} style={{ padding: "9px 16px", border: "none", borderRadius: 8, fontWeight: 600, background: "#4f46e5", color: "#fff" }}>
            {busy ? "Requesting…" : "Request payout"}
          </button>
          {message && <p role="status" style={{ width: "100%", margin: 0, color: "#047857", fontSize: 13 }}>{message}</p>}
        </form>
      )}
      <h2 style={{ fontSize: 18, fontWeight: 600, margin: "0 0 8px" }}>Activity</h2>
      {entries.length === 0 ? <p style={{ color: "#475569" }}>No money has moved yet.</p> : (
        <ul style={{ ...card, listStyle: "none", margin: "0 0 24px", padding: 0 }}>
          {entries.map((e) => (
            <li key={e.id} style={{ display: "flex", justifyContent: "space-between", padding: "10px 16px", borderBottom: "1px solid #f1f5f9" }}>
              <span>{KIND[e.kind] ?? e.kind}<span style={{ marginLeft: 8, fontSize: 12, color: "#475569" }}>{new Date(e.created_at).toLocaleDateString()}</span></span>
              <span style={{ fontWeight: 600, color: e.amount < 0 ? "#b91c1c" : "#047857" }}>{e.amount < 0 ? "−" : "+"}{formatMoney(Math.abs(e.amount))}</span>
            </li>
          ))}
        </ul>
      )}
      <h2 style={{ fontSize: 18, fontWeight: 600, margin: "0 0 8px" }}>Payouts</h2>
      {mine.length === 0 ? <p style={{ color: "#475569" }}>No payouts yet.</p> : (
        <ul style={{ ...card, listStyle: "none", margin: 0, padding: 0 }}>
          {mine.map((p) => (
            <li key={p.id} style={{ display: "flex", justifyContent: "space-between", padding: "10px 16px", borderBottom: "1px solid #f1f5f9" }}>
              <span style={{ textTransform: "capitalize" }}>{p.status}{p.reference ? ` · ${p.reference}` : ""}</span>
              <span style={{ fontWeight: 600 }}>{formatMoney(p.amount)}</span>
            </li>
          ))}
        </ul>
      )}
    </main>
  );
}
'''


ADMIN_MONEY_PAGE = r'''"use client";

// Generated by OmniStackAI (PC-113): the books - what the platform holds, earned and owes - with
// refunds and payout requests. Only the app's refund roles and admin get answers from the API.
import { useCallback, useEffect, useState } from "react";
import { allPayments, books, formatMoney, MINOR, payouts, payPayout, refund, rejectPayout, type Books, type Payment, type Payout } from "@/lib/money";

export default function MoneyPage() {
  const [summary, setSummary] = useState<Books | null>(null);
  const [payments, setPayments] = useState<Payment[]>([]);
  const [requests, setRequests] = useState<Payout[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      const [s, p, r] = await Promise.all([books(), allPayments(), payouts()]);
      setSummary(s); setPayments(p); setRequests(r); setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "The books could not be loaded.");
    }
  }, []);

  useEffect(() => {
    let cancelled = false;
    (async () => { if (!cancelled) await load(); })();
    return () => { cancelled = true; };
  }, [load]);

  async function act(key: string, work: () => Promise<unknown>) {
    setBusy(key); setError(null);
    try { await work(); await load(); }
    catch (err) { setError(err instanceof Error ? err.message : "That could not be done."); }
    finally { setBusy(null); }
  }

  const card = { padding: "16px 18px", border: "1px solid #e2e8f0", borderRadius: 12, background: "#fff" } as const;
  const small = { padding: "5px 10px", border: "1px solid #c7d2fe", borderRadius: 6, background: "#fff", color: "#4338ca", fontSize: 13, fontWeight: 600 } as const;
  return (
    <main style={{ maxWidth: 1100, margin: "0 auto", padding: "28px 16px" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 16 }}>
        <h1 style={{ fontSize: 26, fontWeight: 700, margin: 0 }}>Money</h1>
        {summary && (
          <span style={{ padding: "3px 10px", borderRadius: 999, fontSize: 12, fontWeight: 700,
            background: summary.balanced ? "#dcfce7" : "#fee2e2", color: summary.balanced ? "#166534" : "#991b1b" }}>
            {summary.balanced ? "Books balanced" : "Books do not balance"}
          </span>
        )}
      </div>
      {error && <p role="alert" style={{ color: "#b91c1c" }}>{error}</p>}
      {summary && (
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: 12, marginBottom: 28 }}>
          {[["Collected", -summary.external], ["Platform revenue", summary.revenue], ["Owed to users", summary.owed_to_users], ["Held, not yet split", summary.escrow]].map(([label, value]) => (
            <div key={String(label)} style={card}>
              <p style={{ margin: 0, fontSize: 13, color: "#475569" }}>{label}</p>
              <p style={{ margin: "4px 0 0", fontSize: 22, fontWeight: 700 }}>{formatMoney(Number(value))}</p>
            </div>
          ))}
        </div>
      )}
      <h2 style={{ fontSize: 18, fontWeight: 600, margin: "0 0 8px" }}>Payout requests</h2>
      {requests.filter((p) => p.status === "requested").length === 0 ? <p style={{ color: "#475569" }}>No payouts waiting.</p> : (
        <ul style={{ ...card, listStyle: "none", margin: "0 0 28px", padding: 0 }}>
          {requests.filter((p) => p.status === "requested").map((p) => (
            <li key={p.id} style={{ display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center", justifyContent: "space-between", padding: "10px 16px", borderBottom: "1px solid #f1f5f9" }}>
              <span><strong>{formatMoney(p.amount)}</strong><span style={{ marginLeft: 8, fontSize: 12, color: "#475569" }}>{p.holder_id.slice(0, 8)} · {new Date(p.created_at).toLocaleDateString()}</span></span>
              <span style={{ display: "flex", gap: 6 }}>
                <button type="button" style={small} disabled={busy !== null}
                  onClick={() => { const reference = window.prompt("Transfer reference (bank / UPI)") ?? ""; if (reference) act(`pay-${p.id}`, () => payPayout(p.id, reference)); }}>
                  {busy === `pay-${p.id}` ? "…" : "Mark paid"}
                </button>
                <button type="button" style={{ ...small, color: "#b91c1c", borderColor: "#fecaca" }} disabled={busy !== null} onClick={() => act(`rej-${p.id}`, () => rejectPayout(p.id))}>Reject</button>
              </span>
            </li>
          ))}
        </ul>
      )}
      <h2 style={{ fontSize: 18, fontWeight: 600, margin: "0 0 8px" }}>Payments</h2>
      {payments.length === 0 ? <p style={{ color: "#475569" }}>No payments yet.</p> : (
        <div style={{ ...card, padding: 0, overflowX: "auto" }}>
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 14 }}>
            <thead><tr style={{ textAlign: "left", color: "#475569" }}>
              <th style={{ padding: "10px 16px" }}>For</th><th>Amount</th><th>Commission</th><th>Status</th><th>Refunded</th><th />
            </tr></thead>
            <tbody>
              {payments.map((p) => {
                const left = p.amount - p.refunded;
                return (
                  <tr key={p.id} style={{ borderTop: "1px solid #f1f5f9" }}>
                    <td style={{ padding: "10px 16px" }}>{p.entity} {p.record_id.slice(0, 8)}</td>
                    <td>{formatMoney(p.amount)}</td>
                    <td>{formatMoney(p.commission)}</td>
                    <td style={{ textTransform: "capitalize" }}>{p.status}</td>
                    <td>{p.refunded ? formatMoney(p.refunded) : "—"}</td>
                    <td style={{ paddingRight: 16, textAlign: "right" }}>
                      {p.status === "succeeded" && left > 0 && (
                        <button type="button" style={small} disabled={busy !== null}
                          onClick={() => { const answer = window.prompt(`Refund how much? (up to ${left / MINOR})`, String(left / MINOR)); if (answer) act(`ref-${p.id}`, () => refund(p.id, Math.round(Number(answer) * MINOR))); }}>
                          {busy === `ref-${p.id}` ? "…" : "Refund"}
                        </button>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </main>
  );
}
'''
