"""PC-053: notifications in a generated Node backend - one service, an Express and a Hono router.

The same API and outbox as Python's (see `notifications_python.py`).
"""

from __future__ import annotations

import json

from ..application_ir import ApplicationIR
from . import notifications_sql as q

#: (method, path, service function) - every one behind requireAuth. Static paths before :id ones.
NODE_NOTIFICATION_ROUTES = (
    ("get", "/notifications", "inbox"),
    ("get", "/notifications/unread", "unreadCount"),
    ("post", "/notifications/read-all", "readAll"),
    ("get", "/notifications/preferences", "preferences"),
    ("put", "/notifications/preferences", "setPreference"),
    ("post", "/notifications/devices", "registerDevice"),
    ("delete", "/notifications/devices/:token", "unregisterDevice"),
    ("post", "/notifications/:notificationId/read", "readOne"),
)


def node_notifications_service(ir: ApplicationIR) -> str:
    rules = [{"rule": r.rule, "label": r.label, "channels": list(r.channels), "onlyRoles": list(r.only_roles)}
             for r in q.rule_catalogue(ir)]
    statements = {
        "claimEmails": q.CLAIM_EMAILS, "emailSent": q.EMAIL_SENT, "emailSkipped": q.EMAIL_SKIPPED,
        "emailFailed": q.EMAIL_FAILED, "inbox": q.INBOX, "inboxUnread": q.INBOX_UNREAD, "unreadCount": q.UNREAD_COUNT,
        "markRead": q.MARK_READ, "markAllRead": q.MARK_ALL_READ, "mutes": q.MUTES, "mute": q.MUTE, "unmute": q.UNMUTE,
        "claimPushes": q.CLAIM_PUSHES, "devicesOf": q.DEVICES_OF, "pushSent": q.PUSH_SENT, "pushSkipped": q.PUSH_SKIPPED,
        "pushFailed": q.PUSH_FAILED, "forgetDevice": q.FORGET_DEVICE, "registerDevice": q.REGISTER_DEVICE,
        "unregisterDevice": q.UNREGISTER_DEVICE,
    }
    config = (
        f"const RULES: {{ rule: string; label: string; channels: string[]; onlyRoles: string[] }}[] = {json.dumps(rules, indent=2)};\n\n"
        f"const SQL = {json.dumps(statements, indent=2)};\n"
    )
    return _SERVICE.replace("__CONFIG__", config)


def node_notifications_router(framework: str) -> str:
    lines = [f"// Generated by OmniStackAI: notification routes (PC-053) for {framework}."]
    if framework == "hono":
        lines += ["import { Hono } from 'hono';", "import { requireAuth } from '../middleware/auth.js';",
                  "import * as notifications from './service.js';", "", "export const router = new Hono();", ""]
        for method, path, fn in NODE_NOTIFICATION_ROUTES:
            body = "body: await c.req.json().catch(() => ({})), " if method in ("post", "put") else ""
            lines += [
                f"router.{method}('{path}', requireAuth, async (c) => {{",
                f"  const out = await notifications.{fn}({{ claims: (c as any).get('user'), params: c.req.param() as any, "
                f"query: c.req.query(), {body}}});",
                "  return c.json(out.body as any, out.status as any);",
                "});",
                "",
            ]
    else:
        lines += ["import { Router, Request, Response } from 'express';", "import { requireAuth } from '../middleware/auth.js';",
                  "import * as notifications from './service.js';", "", "export const router = Router();", ""]
        for method, path, fn in NODE_NOTIFICATION_ROUTES:
            lines += [
                f"router.{method}('{path}', requireAuth, async (req: Request, res: Response) => {{",
                f"  const out = await notifications.{fn}({{ claims: (req as any).user, params: req.params as any, "
                "query: req.query as any, body: req.body ?? {} });",
                "  res.status(out.status).json(out.body);",
                "});",
                "",
            ]
    return "\n".join(lines) + "\n"


_SERVICE = r'''// Generated by OmniStackAI: notifications (PC-053) - a person's own, their preferences, the email outbox.
//
// The database writes each notification (a trigger per entity, a reminder per schedule), leaving out the
// channels its recipient muted. In-app ones reach the bell live (R-569); emails wait in the outbox here.
import { pool } from '../db/pool.js';
import { ownerOf, type AuthClaims } from '../middleware/auth.js';

interface Call { claims?: AuthClaims; params: Record<string, string>; query: Record<string, unknown>; body?: any }
type Out = { status: number; body: unknown };

__CONFIG__
const noAccount: Out = { status: 403, body: { detail: 'sign in with an account' } };

export async function inbox({ claims, query }: Call): Promise<Out> {
  const me = ownerOf(claims);
  if (!me) return noAccount;
  const unread = query.unread === '1' || query.unread === 'true';
  const res = await pool.query(unread ? SQL.inboxUnread : SQL.inbox, [me]);
  return { status: 200, body: res.rows };
}

export async function unreadCount({ claims }: Call): Promise<Out> {
  const me = ownerOf(claims);
  if (!me) return noAccount;
  const res = await pool.query(SQL.unreadCount, [me]);
  return { status: 200, body: { count: Number(res.rows[0].count) } };
}

export async function readAll({ claims }: Call): Promise<Out> {
  const me = ownerOf(claims);
  if (!me) return noAccount;
  const res = await pool.query(SQL.markAllRead, [me]);
  return { status: 200, body: { updated: res.rowCount ?? 0 } };
}

export async function readOne({ claims, params }: Call): Promise<Out> {
  const me = ownerOf(claims);
  if (!me) return noAccount;
  const res = await pool.query(SQL.markRead, [params.notificationId, me]);
  if (res.rows.length === 0) return { status: 404, body: { detail: 'not_found' } };
  return { status: 200, body: { id: params.notificationId, read: true } };
}

export async function preferences({ claims }: Call): Promise<Out> {
  const me = ownerOf(claims);
  if (!me) return noAccount;
  const res = await pool.query(SQL.mutes, [me]);
  const muted = new Set(res.rows.map((r: any) => `${r.rule}\u0000${r.channel}`));
  const allMuted = res.rows.filter((r: any) => r.rule === '*').map((r: any) => r.channel).sort();
  const held: string[] = Array.isArray((claims as any)?.roles) ? (claims as any).roles : [];
  // A rule only for some roles (staff hear of new orders) is not offered to anyone else.
  const rules = RULES.filter((rule) => rule.onlyRoles.length === 0 || rule.onlyRoles.some((r) => held.includes(r)))
    .map(({ onlyRoles: _only, ...rule }) => ({ ...rule, muted: rule.channels.filter((c) => muted.has(`${rule.rule}\u0000${c}`)).sort() }));
  return { status: 200, body: { all_muted: allMuted, rules } };
}

export async function setPreference({ claims, body }: Call): Promise<Out> {
  const me = ownerOf(claims);
  if (!me) return noAccount;
  const rule = String(body?.rule ?? '');
  const channel = String(body?.channel ?? '');
  if ((rule !== '*' && !RULES.some((r) => r.rule === rule)) || !['in_app', 'email', 'push'].includes(channel) || typeof body?.muted !== 'boolean') {
    return { status: 422, body: { detail: 'unknown rule or channel' } };
  }
  await pool.query(body.muted ? SQL.mute : SQL.unmute, [me, rule, channel]);
  return { status: 200, body: { rule, channel, muted: body.muted } };
}

// --- the phone app's devices (PC-121) ----------------------------------------------------------

export async function registerDevice({ claims, body }: Call): Promise<Out> {
  const me = ownerOf(claims);
  if (!me) return noAccount;
  const token = typeof body?.token === 'string' ? body.token : '';
  if (!token || token.length > 300) return { status: 422, body: { detail: 'a push token is required' } };
  await pool.query(SQL.registerDevice, [token, me, String(body?.platform ?? 'unknown').slice(0, 20)]);
  return { status: 200, body: { registered: true } };
}

export async function unregisterDevice({ claims, params }: Call): Promise<Out> {
  const me = ownerOf(claims);
  if (!me) return noAccount;
  await pool.query(SQL.unregisterDevice, [params.token, me]);
  return { status: 200, body: { registered: false } };
}

async function expoPush(messages: unknown[]): Promise<{ status?: string; details?: { error?: string } }[]> {
  const headers: Record<string, string> = { 'Content-Type': 'application/json', Accept: 'application/json' };
  if (process.env.EXPO_ACCESS_TOKEN) headers.Authorization = `Bearer ${process.env.EXPO_ACCESS_TOKEN}`;
  const res = await fetch(process.env.EXPO_PUSH_URL || 'https://exp.host/--/api/v2/push/send', {
    method: 'POST', headers, body: JSON.stringify(messages), signal: AbortSignal.timeout(15000),
  });
  if (!res.ok) throw new Error(`push service answered ${res.status}`);
  return ((await res.json()) as any)?.data ?? [];
}

/** Push what is due to each person's devices; forget devices that were uninstalled. */
export async function sendDuePushes(): Promise<number> {
  const due = (await pool.query(SQL.claimPushes)).rows;
  let sent = 0;
  for (const row of due) {
    const tokens: string[] = (await pool.query(SQL.devicesOf, [row.user_id])).rows.map((r: any) => r.token);
    if (tokens.length === 0) {
      await pool.query(SQL.pushSkipped, ['no device registered', row.id]);
      continue;
    }
    const data = { entity: row.entity, record_id: row.record_id ?? null, notification_id: row.id };
    let tickets: { status?: string; details?: { error?: string } }[];
    try {
      tickets = await expoPush(tokens.map((to) => ({ to, title: row.title, body: row.body || row.title, sound: 'default', data })));
    } catch (error) {
      await pool.query(SQL.pushFailed, [String((error as Error)?.message ?? error).slice(0, 500), row.id]);
      continue;
    }
    let delivered = false;
    for (let i = 0; i < tickets.length; i++) {
      if (tickets[i]?.status === 'ok') delivered = true;
      else if (tickets[i]?.details?.error === 'DeviceNotRegistered' && tokens[i]) await pool.query(SQL.forgetDevice, [tokens[i]]);
    }
    if (delivered) {
      await pool.query(SQL.pushSent, [row.id]);
      sent++;
    } else {
      await pool.query(SQL.pushFailed, [JSON.stringify(tickets).slice(0, 500), row.id]);
    }
  }
  return sent;
}

// --- the email outbox ---------------------------------------------------------------------------

async function sendEmail(to: string, subject: string, text: string): Promise<void> {
  const res = await fetch(process.env.EMAIL_API_URL || 'https://api.resend.com/emails', {
    method: 'POST',
    headers: { Authorization: `Bearer ${process.env.RESEND_API_KEY}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ from: process.env.EMAIL_FROM, to: [to], subject, text: text || subject }),
    signal: AbortSignal.timeout(15000),
  });
  if (!res.ok) throw new Error(`email provider answered ${res.status}`);
}

/** Send what is due in the outbox; how many were sent. */
export async function sendDueEmails(): Promise<number> {
  const due = (await pool.query(SQL.claimEmails)).rows;
  const configured = Boolean(process.env.RESEND_API_KEY && process.env.EMAIL_FROM);
  let sent = 0;
  for (const row of due) {
    if (!configured) {
      await pool.query(SQL.emailSkipped, ['email is not configured (RESEND_API_KEY, EMAIL_FROM)', row.id]);
      continue;
    }
    try {
      await sendEmail(row.email, row.title, row.body);
    } catch (error) {
      await pool.query(SQL.emailFailed, [String((error as Error)?.message ?? error).slice(0, 500), row.id]);
      console.warn('notification email failed:', (error as Error)?.message ?? error);
      continue;
    }
    await pool.query(SQL.emailSent, [row.id]);
    sent++;
  }
  return sent;
}

/** Started by the server: send the outbox every NOTIFICATIONS_EMAIL_SECONDS (10). */
export function startNotifications(): void {
  if (['1', 'true', 'yes'].includes((process.env.NOTIFICATIONS_EMAIL_DISABLED ?? '').trim().toLowerCase())) return;
  const seconds = Number(process.env.NOTIFICATIONS_EMAIL_SECONDS);
  const interval = Number.isFinite(seconds) && seconds >= 1 ? seconds * 1000 : 10_000;
  const loop = async () => {
    try {
      await sendDueEmails();
      await sendDuePushes();
    } catch (error) {
      console.warn('notifications:', (error as Error)?.message ?? error);
    }
    setTimeout(loop, interval);
  };
  void loop();
}
'''
