"""PC-053: notifications in the generated web and admin apps.

    components/notification-bell.tsx   the unread count beside the navigation, live (R-569)
    app/notifications/page.tsx          the list, mark read, and each person's preferences
    lib/notifications.ts                the API

The API answers only for the signed-in person; the pages show what it answers.
"""

from __future__ import annotations

NOTIFICATIONS_CLIENT = r'''// Generated by OmniStackAI (PC-053): a person's notifications and preferences.
const BASE_URL = process.env.NEXT_PUBLIC_API_URL || "";

async function call<T>(path: string, method = "GET", body?: unknown): Promise<T> {
  const token = typeof localStorage !== "undefined" ? localStorage.getItem("auth_token") : null;
  const res = await fetch(`${BASE_URL}${path}`, {
    method,
    headers: { ...(body !== undefined ? { "Content-Type": "application/json" } : {}), ...(token ? { Authorization: `Bearer ${token}` } : {}) },
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error((data as { detail?: string }).detail || `Request failed (${res.status})`);
  return data as T;
}

export interface Notification { id: string; rule: string; entity: string; record_id: string | null; title: string; body: string;
  read_at: string | null; created_at: string }
export interface Preferences { all_muted: string[]; rules: { rule: string; label: string; channels: string[]; muted: string[] }[] }

export const notifications = (unread = false) => call<Notification[]>(`/notifications${unread ? "?unread=1" : ""}`);
export const unreadCount = () => call<{ count: number }>("/notifications/unread");
export const markRead = (id: string) => call(`/notifications/${id}/read`, "POST", {});
export const markAllRead = () => call("/notifications/read-all", "POST", {});
export const preferences = () => call<Preferences>("/notifications/preferences");
export const setPreference = (rule: string, channel: string, muted: boolean) =>
  call("/notifications/preferences", "PUT", { rule, channel, muted });
'''

BELL = r'''"use client";

// Generated by OmniStackAI (PC-053): unread notifications, counted live.
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { unreadCount } from "@/lib/notifications";
import { useLive } from "@/lib/realtime";

export function NotificationBell() {
  const [count, setCount] = useState<number | null>(null);
  const load = useCallback(async () => {
    if (typeof localStorage === "undefined" || !localStorage.getItem("auth_token")) return;
    try { setCount((await unreadCount()).count); } catch { setCount(null); }
  }, []);
  useEffect(() => { void load(); }, [load]);
  useLive("Notification", () => { void load(); });
  if (count === null) return null;
  return (
    <Link href="/notifications" aria-label={count ? `${count} unread notifications` : "Notifications"}
      style={{ position: "relative", display: "inline-flex", alignItems: "center", padding: "6px 8px", borderRadius: 8, color: "inherit" }}>
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
        <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" /><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
      </svg>
      {count > 0 && (
        <span data-testid="unread-count" style={{ position: "absolute", top: 0, right: 0, minWidth: 18, height: 18, padding: "0 5px", borderRadius: 999,
          background: "#dc2626", color: "#fff", fontSize: 11, fontWeight: 700, display: "inline-flex", alignItems: "center", justifyContent: "center" }}>
          {count > 99 ? "99+" : count}
        </span>
      )}
    </Link>
  );
}
'''

PAGE = r'''"use client";

// Generated by OmniStackAI (PC-053): what happened that concerns you, and what you want to hear about.
import { useCallback, useEffect, useState } from "react";
import { markAllRead, markRead, notifications, preferences, setPreference, type Notification, type Preferences } from "@/lib/notifications";
import { useLive } from "@/lib/realtime";

const CHANNEL: Record<string, string> = { in_app: "In the app", email: "Email" };

export default function NotificationsPage() {
  const [items, setItems] = useState<Notification[]>([]);
  const [prefs, setPrefs] = useState<Preferences | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const load = useCallback(async () => {
    try {
      const [list, p] = await Promise.all([notifications(), preferences()]);
      setItems(list); setPrefs(p); setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Notifications could not be loaded.");
    }
  }, []);
  useEffect(() => { void load(); }, [load]);
  useLive("Notification", () => { void load(); });

  async function act(work: () => Promise<unknown>) {
    setBusy(true);
    try { await work(); await load(); } catch (err) { setError(err instanceof Error ? err.message : "That could not be done."); } finally { setBusy(false); }
  }

  const unread = items.filter((n) => !n.read_at).length;
  const card = { border: "1px solid #e2e8f0", borderRadius: 12, background: "#fff" } as const;
  const small = { padding: "5px 10px", border: "1px solid #c7d2fe", borderRadius: 6, background: "#fff", color: "#4338ca", fontSize: 13, fontWeight: 600 } as const;
  return (
    <main style={{ maxWidth: 860, margin: "0 auto", padding: "28px 16px" }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 14 }}>
        <h1 style={{ fontSize: 26, fontWeight: 700, margin: 0 }}>Notifications</h1>
        {unread > 0 && <button type="button" style={small} disabled={busy} onClick={() => act(markAllRead)}>Mark all read</button>}
      </div>
      {error && <p role="alert" style={{ color: "#b91c1c" }}>{error}</p>}
      {items.length === 0 ? <p style={{ color: "#475569" }}>Nothing yet. When something happens that concerns you, it shows up here.</p> : (
        <ul style={{ ...card, listStyle: "none", margin: "0 0 28px", padding: 0 }}>
          {items.map((n) => (
            <li key={n.id} data-testid="notification" style={{ padding: "12px 16px", borderBottom: "1px solid #f1f5f9", display: "flex", gap: 12,
              justifyContent: "space-between", alignItems: "flex-start", background: n.read_at ? "#fff" : "#eef2ff" }}>
              <span style={{ minWidth: 0 }}>
                <strong style={{ display: "block" }}>{n.title}</strong>
                {n.body && <span style={{ display: "block", color: "#334155", fontSize: 14 }}>{n.body}</span>}
                <span style={{ fontSize: 12, color: "#64748b" }}>{new Date(n.created_at).toLocaleString()}</span>
              </span>
              {!n.read_at && <button type="button" style={small} disabled={busy} onClick={() => act(() => markRead(n.id))}>Mark read</button>}
            </li>
          ))}
        </ul>
      )}
      {prefs && prefs.rules.length > 0 && (
        <section aria-labelledby="prefs" style={{ ...card, padding: "16px 18px" }}>
          <h2 id="prefs" style={{ fontSize: 18, fontWeight: 600, margin: "0 0 4px" }}>What you hear about</h2>
          <p style={{ margin: "0 0 12px", color: "#475569", fontSize: 14 }}>Turn a kind of notification off, or everything on a channel.</p>
          {["in_app", "email"].map((channel) => (
            <label key={channel} style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 6, fontWeight: 600 }}>
              <input type="checkbox" disabled={busy} checked={!prefs.all_muted.includes(channel)}
                onChange={(e) => act(() => setPreference("*", channel, !e.target.checked))} />
              {CHANNEL[channel]}: everything
            </label>
          ))}
          <ul style={{ listStyle: "none", margin: "10px 0 0", padding: 0 }}>
            {prefs.rules.map((rule) => (
              <li key={rule.rule} style={{ padding: "8px 0", borderTop: "1px solid #f1f5f9", display: "flex", flexWrap: "wrap", gap: 14, justifyContent: "space-between" }}>
                <span>{rule.label}</span>
                <span style={{ display: "flex", gap: 14 }}>
                  {rule.channels.map((channel) => (
                    <label key={channel} style={{ display: "flex", gap: 6, alignItems: "center", fontSize: 14 }}>
                      <input type="checkbox" disabled={busy || prefs.all_muted.includes(channel)} checked={!rule.muted.includes(channel) && !prefs.all_muted.includes(channel)}
                        onChange={(e) => act(() => setPreference(rule.rule, channel, !e.target.checked))} />
                      {CHANNEL[channel]}
                    </label>
                  ))}
                </span>
              </li>
            ))}
          </ul>
        </section>
      )}
    </main>
  );
}
'''

_OVERVIEW_LINK = (
    '            <Link href="/" style={navLinkStyle(isLinkActive("/"))}>\n'
    "              Overview\n"
    "            </Link>\n"
)


def with_bell(navbar: str) -> str:
    """The navbar with the bell after its first link, and its import."""
    if "NotificationBell" in navbar or _OVERVIEW_LINK not in navbar:
        return navbar
    navbar = navbar.replace(_OVERVIEW_LINK, _OVERVIEW_LINK + "            <NotificationBell />\n", 1)
    return navbar.replace('import Link from "next/link";\n',
                          'import Link from "next/link";\nimport { NotificationBell } from "@/components/notification-bell";\n', 1)
