"""PC-121: push notifications in the generated React Native app.

After sign-in the app asks permission, gets an Expo push token for this device and registers it with
the API (`POST /notifications/devices`); signing out forgets it. A real phone needs the project's EAS
id (EAS_PROJECT_ID, from `eas init`) - without it the app says so in its log and carries on.
"""

from __future__ import annotations

from .expo_sdk import PUSH as PUSH_DEPENDENCIES  # pinned to the SDK the app is on (PC-124)

PUSH_MODULE_PATH = "src/shared/notifications/PushRegistration.tsx"

PUSH_MODULE = r'''// Generated by OmniStackAI (PC-121): this phone receives the app's push notifications once signed in.
import { useEffect, useRef } from 'react';
import { Platform } from 'react-native';
import Constants, { ExecutionEnvironment } from 'expo-constants';
import * as Device from 'expo-device';
import { apiClient } from '../api/client';
import { useAuth } from '../auth/AuthContext';

type NotificationsModule = typeof import('expo-notifications');

// Expo Go has no remote push (since SDK 53): the preview a phone opens from the QR skips it, and
// the module is not even loaded there - loading it in Expo Go reports an error over the app.
const IN_EXPO_GO = Constants.executionEnvironment === ExecutionEnvironment.StoreClient;
let notifications: NotificationsModule | null = null;

function load(): NotificationsModule {
  if (!notifications) {
    notifications = require('expo-notifications') as NotificationsModule;
    // A notification that arrives while the app is open is still shown.
    notifications.setNotificationHandler({
      handleNotification: async () => ({ shouldShowBanner: true, shouldShowList: true, shouldPlaySound: true, shouldSetBadge: true }),
    });
  }
  return notifications;
}

async function pushToken(): Promise<string | null> {
  if (!Device.isDevice || IN_EXPO_GO) return null;  // simulators and Expo Go cannot receive push
  const Notifications = load();
  if (Platform.OS === 'android') {
    await Notifications.setNotificationChannelAsync('default', { name: 'default', importance: Notifications.AndroidImportance.DEFAULT });
  }
  const current = await Notifications.getPermissionsAsync();
  const granted = current.granted || (await Notifications.requestPermissionsAsync()).granted;
  if (!granted) return null;
  const projectId = (Constants.expoConfig?.extra as any)?.eas?.projectId ?? (Constants as any).easConfig?.projectId;
  if (!projectId) {
    console.warn('Push notifications need the EAS project id: run `eas init` and set EAS_PROJECT_ID.');
    return null;
  }
  return (await Notifications.getExpoPushTokenAsync({ projectId })).data;
}

/** Registers this device for push while someone is signed in, and forgets it when they sign out. */
export function PushRegistration(): null {
  const { token } = useAuth();
  const registered = useRef<string | null>(null);
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        if (token) {
          const device = await pushToken();
          if (device && !cancelled) {
            await apiClient.post('/notifications/devices', { token: device, platform: Platform.OS });
            registered.current = device;
          }
        } else if (registered.current) {
          registered.current = null;  // signed out: the API has no session left to unregister with
        }
      } catch (error) {
        console.warn('Push registration failed:', error);
      }
    })();
    return () => { cancelled = true; };
  }, [token]);
  return null;
}
'''
