"""PC-121: push notifications in the generated React Native app.

After sign-in the app asks permission, gets an Expo push token for this device and registers it with
the API (`POST /notifications/devices`); signing out forgets it. A real phone needs the project's EAS
id (EAS_PROJECT_ID, from `eas init`) - without it the app says so in its log and carries on.
"""

from __future__ import annotations

#: Pinned to the versions Expo SDK 51 bundles (expo/packages/expo/bundledNativeModules.json).
PUSH_DEPENDENCIES = {"expo-notifications": "~0.28.19", "expo-device": "~6.0.2"}

PUSH_MODULE_PATH = "src/shared/notifications/PushRegistration.tsx"

PUSH_MODULE = r'''// Generated by OmniStackAI (PC-121): this phone receives the app's push notifications once signed in.
import { useEffect, useRef } from 'react';
import { Platform } from 'react-native';
import Constants from 'expo-constants';
import * as Device from 'expo-device';
import * as Notifications from 'expo-notifications';
import { apiClient } from '../api/client';
import { useAuth } from '../auth/AuthContext';

// A notification that arrives while the app is open is still shown.
Notifications.setNotificationHandler({
  handleNotification: async () => ({ shouldShowAlert: true, shouldPlaySound: true, shouldSetBadge: true }),
});

async function pushToken(): Promise<string | null> {
  if (!Device.isDevice) return null;  // simulators cannot receive push
  if (Platform.OS === 'android') {
    await Notifications.setNotificationChannelAsync('default', { name: 'default', importance: Notifications.AndroidImportance.DEFAULT });
  }
  const current = await Notifications.getPermissionsAsync();
  const granted = current.granted || (await Notifications.requestPermissionsAsync()).granted;
  if (!granted) return null;
  const projectId = (Constants.expoConfig?.extra as any)?.eas?.projectId ?? (Constants as any).easConfig?.projectId;
  if (!projectId) {
    console.warn('Push notifications need the EAS project id: run `eas init` and set EAS_PROJECT_ID.');
    return null;
  }
  return (await Notifications.getExpoPushTokenAsync({ projectId })).data;
}

/** Registers this device for push while someone is signed in, and forgets it when they sign out. */
export function PushRegistration(): null {
  const { token } = useAuth();
  const registered = useRef<string | null>(null);
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        if (token) {
          const device = await pushToken();
          if (device && !cancelled) {
            await apiClient.post('/notifications/devices', { token: device, platform: Platform.OS });
            registered.current = device;
          }
        } else if (registered.current) {
          registered.current = null;  // signed out: the API has no session left to unregister with
        }
      } catch (error) {
        console.warn('Push registration failed:', error);
      }
    })();
    return () => { cancelled = true; };
  }, [token]);
  return null;
}
'''
