"""Every generated web app is an installable PWA (R-573).

`capabilities.py` has said since R-559 that a PWA "resolves to Next.js and says so rather than
claiming to be installable", because no manifest was generated. The founder's rule is that an app
request gets a React Native app *and* an installable PWA with a QR code, so this module makes the
claim true for every generated web app and admin console:

* `app/manifest.ts` — name, colours from the brand, standalone display, base-path aware;
* PNG icons at 192 and 512 (plus a maskable one and an Apple touch icon), drawn from the same brand
  mark the mobile app's store icon uses, because Chrome's install criteria want PNGs at those sizes
  and iOS ignores SVG touch icons;
* `public/sw.js` — caches only the build's static files and an offline page; navigations go to the
  network first. **API responses are never cached**: a stale order status is worse than an honest
  "you are offline";
* `components/pwa-support.tsx` — registers the worker, offers "Install app" where the browser
  supports it, explains Add to Home Screen on iOS, and shows a QR code of the page so a phone can
  open it. Loaded from localhost the QR would point the phone at itself, so the host is swapped for
  the machine's LAN address when the run plan provides one (`NEXT_PUBLIC_LAN_HOST`).
"""

from __future__ import annotations

import json

from ..application_ir import ApplicationIR
from .files import GeneratedFile
from .mobile_release import _mark_png, _png_file

ICON_SIZES = (192, 512)


def _short_name(name: str) -> str:
    """Home-screen labels truncate around 12 characters."""
    return name if len(name) <= 12 else name.split()[0][:12]


def manifest_file(ir: ApplicationIR) -> str:
    theme = ir.brand.primary_color
    name = json.dumps(ir.name or "App")
    short = json.dumps(_short_name(ir.name or "App"))
    desc = json.dumps(ir.description or ir.name or "")
    return (
        'import type { MetadataRoute } from "next";\n\n'
        "// Generated by OmniStackAI (R-573). Served at <base>/manifest.webmanifest.\n"
        'const base = process.env.NEXT_PUBLIC_BASE_PATH || "";\n\n'
        "export default function manifest(): MetadataRoute.Manifest {\n"
        "  return {\n"
        f"    name: {name},\n"
        f"    short_name: {short},\n"
        f"    description: {desc},\n"
        "    id: `${base}/`,\n"
        "    start_url: `${base}/`,\n"
        "    scope: `${base}/`,\n"
        '    display: "standalone",\n'
        '    background_color: "#ffffff",\n'
        f'    theme_color: "{theme}",\n'
        "    icons: [\n"
        '      { src: `${base}/icons/icon-192.png`, sizes: "192x192", type: "image/png", purpose: "any" },\n'
        '      { src: `${base}/icons/icon-512.png`, sizes: "512x512", type: "image/png", purpose: "any" },\n'
        '      { src: `${base}/icons/maskable-512.png`, sizes: "512x512", type: "image/png", purpose: "maskable" },\n'
        "    ],\n"
        "  };\n"
        "}\n"
    )


def icon_files(ir: ApplicationIR) -> list[GeneratedFile]:
    background = ir.brand.primary_color
    seed = ir.name or "app"
    files = [
        _png_file(f"public/icons/icon-{size}.png", _mark_png(size, background, "#ffffff", seed, margin_ratio=0.18))
        for size in ICON_SIZES
    ]
    # Maskable: launchers crop to a circle or squircle, so the mark keeps to the safe middle.
    files.append(_png_file("public/icons/maskable-512.png", _mark_png(512, background, "#ffffff", seed, margin_ratio=0.28)))
    files.append(_png_file("public/icons/apple-touch-icon.png", _mark_png(180, background, "#ffffff", seed, margin_ratio=0.18)))
    return files


SERVICE_WORKER = r"""// Generated by OmniStackAI (R-573): offline shell for an installable app.
//
// Caches only this build's static files and an offline page. Page loads go to the network first and
// fall back to the offline page. API calls are never cached or answered from cache: a stale record
// is worse than an honest "you are offline".
const VERSION = "v1";
const SHELL = `shell-${VERSION}`;
const scope = new URL(self.registration.scope).pathname.replace(/\/$/, "");
const OFFLINE = `${scope}/offline.html`;

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(SHELL).then((cache) => cache.addAll([OFFLINE])).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== SHELL).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return; // the API and anything else: straight to the network

  if (request.mode === "navigate") {
    event.respondWith(fetch(request).catch(() => caches.match(OFFLINE)));
    return;
  }
  const isStatic = url.pathname.includes("/_next/static/") || url.pathname.includes("/icons/");
  if (!isStatic) return;
  event.respondWith(
    caches.match(request).then((hit) => hit || fetch(request).then((response) => {
      if (response.ok) {
        const copy = response.clone();
        caches.open(SHELL).then((cache) => cache.put(request, copy));
      }
      return response;
    })),
  );
});
"""


def offline_page(ir: ApplicationIR) -> str:
    name = (ir.name or "This app").replace("<", "&lt;")
    theme = ir.brand.primary_color
    return (
        "<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
        f"<title>{name} — offline</title>"
        "<style>body{font-family:system-ui,sans-serif;display:flex;min-height:100vh;align-items:center;"
        "justify-content:center;margin:0;background:#f8fafc;color:#0f172a}main{text-align:center;padding:24px}"
        f"h1{{font-size:22px}}button{{margin-top:16px;padding:10px 18px;border:0;border-radius:10px;background:{theme};"
        "color:#fff;font-weight:600;cursor:pointer}</style></head>"
        f"<body><main><h1>You are offline</h1><p>{name} needs a connection for this. "
        "It will work again as soon as you are back online.</p>"
        "<button onclick=\"location.reload()\">Try again</button></main></body></html>\n"
    )


PWA_SUPPORT_COMPONENT = r'''"use client";

// Generated by OmniStackAI (R-573): installable app support.
// Registers the service worker, offers "Install app" where the browser allows it, explains
// Add to Home Screen on iOS, and shows a QR code so a phone can open this page.
import { useEffect, useState } from "react";
import { QrCode } from "@/components/qr-code";

const base = process.env.NEXT_PUBLIC_BASE_PATH || "";
const lanHost = process.env.NEXT_PUBLIC_LAN_HOST || "";

interface InstallPromptEvent extends Event {
  prompt: () => Promise<void>;
  userChoice: Promise<{ outcome: "accepted" | "dismissed" }>;
}

/** The page address a phone can reach: localhost would point the phone at itself. */
function phoneUrl(): string {
  const url = new URL(window.location.href);
  if (lanHost && (url.hostname === "localhost" || url.hostname === "127.0.0.1")) url.hostname = lanHost;
  return url.toString();
}

export function PwaSupport() {
  const [installEvent, setInstallEvent] = useState<InstallPromptEvent | null>(null);
  const [standalone, setStandalone] = useState(true);
  const [ios, setIos] = useState(false);
  const [open, setOpen] = useState(false);
  const [qrValue, setQrValue] = useState("");

  useEffect(() => {
    if ("serviceWorker" in navigator) {
      navigator.serviceWorker.register(`${base}/sw.js`, { scope: `${base}/` }).catch(() => undefined);
    }
    setStandalone(window.matchMedia("(display-mode: standalone)").matches || (navigator as any).standalone === true);
    setIos(/iphone|ipad|ipod/i.test(navigator.userAgent));
    setQrValue(phoneUrl());
    const onPrompt = (e: Event) => {
      e.preventDefault();
      setInstallEvent(e as InstallPromptEvent);
    };
    window.addEventListener("beforeinstallprompt", onPrompt);
    return () => window.removeEventListener("beforeinstallprompt", onPrompt);
  }, []);

  if (standalone) return null; // already installed and running as an app

  const install = async () => {
    if (!installEvent) return;
    await installEvent.prompt();
    await installEvent.userChoice.catch(() => undefined);
    setInstallEvent(null);
  };

  return (
    <div style={{ position: "fixed", right: 16, bottom: 16, zIndex: 50, display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 8 }}>
      {open && (
        <div role="dialog" aria-label="Get the app" style={{ background: "#fff", borderRadius: 14, padding: 16, width: 240,
          boxShadow: "0 20px 40px -12px rgba(15,23,42,0.25), 0 0 0 1px rgba(226,232,240,0.9)" }}>
          <p style={{ margin: "0 0 8px", fontWeight: 700, fontSize: 14, color: "#0f172a" }}>Open on your phone</p>
          {qrValue && <QrCode value={qrValue} size={160} />}
          <p style={{ margin: "8px 0 0", fontSize: 12, color: "#64748b" }}>
            {ios
              ? "On iPhone: tap Share, then Add to Home Screen."
              : "Scan with your camera, then choose Install or Add to Home Screen."}
          </p>
          {installEvent && (
            <button type="button" onClick={install} style={{ marginTop: 10, width: "100%", padding: "8px 12px", border: 0, borderRadius: 8,
              background: "var(--color-primary, #4f46e5)", color: "#fff", fontWeight: 600, cursor: "pointer" }}>
              Install on this device
            </button>
          )}
        </div>
      )}
      <button type="button" aria-expanded={open} onClick={() => setOpen((v) => !v)}
        style={{ padding: "10px 14px", border: 0, borderRadius: 999, fontWeight: 600, fontSize: 13, cursor: "pointer",
          background: "var(--color-primary, #4f46e5)", color: "#fff", boxShadow: "0 10px 24px -8px rgba(79,70,229,0.55)" }}>
        {open ? "Close" : "Get the app"}
      </button>
    </div>
  );
}
'''


def pwa_files(ir: ApplicationIR) -> list[GeneratedFile]:
    return [
        GeneratedFile("app/manifest.ts", manifest_file(ir)),
        GeneratedFile("public/sw.js", SERVICE_WORKER),
        GeneratedFile("public/offline.html", offline_page(ir)),
        GeneratedFile("components/pwa-support.tsx", PWA_SUPPORT_COMPONENT),
        *icon_files(ir),
    ]
