"""R-569: live updates in a generated Node backend - one service, an Express and a Hono router.

The same stream as Python and Go (see `realtime_python.py`): one pool client LISTENs, changes fan out
to open Server-Sent Event streams filtered by ownership, and a one-minute ticket opens a stream.
"""

from __future__ import annotations

import json

from ..application_ir import ApplicationIR
from . import realtime_sql as q


def node_realtime_service(ir: ApplicationIR) -> str:
    tables = {t.table: {"entity": t.entity, "owned": t.owned, "seeAll": list(t.see_all)} for t in q.live_tables(ir)}
    config = (
        f"const CHANNEL = {json.dumps(q.CHANNEL)};\n"
        f"const TICKET_SECONDS = {q.TICKET_SECONDS};\n"
        f"export const PING_SECONDS = {q.PING_SECONDS};\n"
        f"const LIVE: Record<string, {{ entity: string; owned: boolean; seeAll: string[] }}> = {json.dumps(tables, indent=2)};\n"
    )
    return _SERVICE.replace("__CONFIG__", config)


def node_realtime_router(framework: str) -> str:
    if framework == "hono":
        return _HONO
    return _EXPRESS


_SERVICE = r'''// Generated by OmniStackAI: live updates (R-569) - changes to live entities, streamed as they happen.
//
// A trigger publishes each change on the app_changes channel; this process listens once and sends each
// change to the open streams of the people who may see that record. An event names the entity, the
// operation and the id - the page fetches the record through the API, as it always does.
import crypto from 'node:crypto';
import { pool } from '../db/pool.js';
import { ownerOf, type AuthClaims } from '../middleware/auth.js';

__CONFIG__
export interface LiveEvent { entity: string; op: string; id: string }
interface Holder { sub: string; roles: string[]; exp: number }
interface Stream { holder: Holder; entities: Set<string> | null; send: (event: LiveEvent) => void; close: () => void }

const streams = new Set<Stream>();

function secret(): string {
  return process.env.JWT_SECRET ?? '';
}

function sign(payload: string): string {
  return crypto.createHmac('sha256', secret()).update(payload).digest('hex');
}

/** A one-minute ticket for the bearer of these claims; null when sign-in is not configured. */
export function makeTicket(claims: AuthClaims | undefined): { ticket: string; expires_in: number } | null {
  if (!secret()) return null;
  const roles = Array.isArray((claims as any)?.roles) ? ((claims as any).roles as unknown[]).map(String) : [];
  const holder: Holder = { sub: ownerOf(claims) ?? '', roles, exp: Math.floor(Date.now() / 1000) + TICKET_SECONDS };
  const payload = Buffer.from(JSON.stringify(holder)).toString('base64url');
  return { ticket: `${payload}.${sign(payload)}`, expires_in: TICKET_SECONDS };
}

/** The ticket's holder, or null when it is forged, malformed or more than a minute old. */
export function readTicket(ticket: string | undefined): Holder | null {
  if (!secret() || !ticket) return null;
  const [payload, signature] = ticket.split('.', 2);
  if (!payload || !signature) return null;
  const expected = sign(payload);
  if (signature.length !== expected.length || !crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null;
  try {
    const holder = JSON.parse(Buffer.from(payload, 'base64url').toString('utf8')) as Holder;
    return holder.exp >= Math.floor(Date.now() / 1000) ? holder : null;
  } catch {
    return null;
  }
}

export function mayHear(holder: Holder, change: Record<string, string | null>): boolean {
  const live = LIVE[change.t ?? ''];
  if (!live) return false;
  if (!live.owned) return true;
  if (holder.roles.some((r) => r === 'admin' || live.seeAll.includes(r))) return true;
  return Boolean(holder.sub) && (holder.sub === change.o || holder.sub === change.a);
}

function fanOut(payload: string): void {
  let change: Record<string, string | null>;
  try {
    change = JSON.parse(payload);
  } catch {
    return;
  }
  const live = LIVE[change.t ?? ''];
  if (!live) return;
  const event: LiveEvent = { entity: live.entity, op: String(change.op), id: String(change.id) };
  for (const stream of streams) {
    if (stream.entities && !stream.entities.has(live.entity)) continue;
    if (mayHear(stream.holder, change)) stream.send(event);
  }
}

/** Register an open stream; returns the function that removes it. */
export function addStream(holder: Holder, entities: string | undefined, send: Stream['send'], close: Stream['close']): () => void {
  const wanted = (entities ?? '').split(',').filter(Boolean);
  const stream: Stream = { holder, entities: wanted.length ? new Set(wanted) : null, send, close };
  streams.add(stream);
  return () => { streams.delete(stream); };
}

/** Started by the server: LISTEN on one pool client, reconnecting if the database goes away. */
export function startRealtime(): void {
  const listen = async () => {
    try {
      const client = await pool.connect();
      client.on('notification', (note) => { if (note.payload) fanOut(note.payload); });
      client.on('error', (error) => {
        console.warn('realtime:', error.message);
        client.release(true);
        setTimeout(listen, 2000);
      });
      await client.query(`LISTEN ${CHANNEL}`);
    } catch (error) {
      console.warn('realtime:', (error as Error)?.message ?? error);
      setTimeout(listen, 2000);
    }
  };
  void listen();
}
'''

_EXPRESS = r'''// Generated by OmniStackAI: live update routes (R-569) for express.
import { Router, Request, Response } from 'express';
import { requireAuth } from '../middleware/auth.js';
import { addStream, makeTicket, PING_SECONDS, readTicket } from './service.js';

export const router = Router();

router.post('/realtime/ticket', requireAuth, (req: Request, res: Response) => {
  const ticket = makeTicket((req as any).user);
  if (!ticket) return res.status(500).json({ detail: 'auth_not_configured' });
  res.json(ticket);
});

router.get('/realtime/stream', (req: Request, res: Response) => {
  const holder = readTicket(typeof req.query.ticket === 'string' ? req.query.ticket : undefined);
  if (!holder) return res.status(401).json({ detail: 'invalid_ticket' });
  res.writeHead(200, { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', 'X-Accel-Buffering': 'no', Connection: 'keep-alive' });
  res.write('event: ready\ndata: {}\n\n');
  let pending = 0;
  const remove = addStream(holder, typeof req.query.entities === 'string' ? req.query.entities : undefined,
    (event) => {
      // A stream that cannot keep up is closed; its page reconnects.
      if (!res.write(`event: change\ndata: ${JSON.stringify(event)}\n\n`) && ++pending > 256) res.end();
    },
    () => res.end());
  res.on('drain', () => { pending = 0; });
  const ping = setInterval(() => res.write(': ping\n\n'), PING_SECONDS * 1000);
  req.on('close', () => { clearInterval(ping); remove(); });
});
'''

_HONO = r'''// Generated by OmniStackAI: live update routes (R-569) for hono.
import { Hono } from 'hono';
import { streamSSE } from 'hono/streaming';
import { requireAuth } from '../middleware/auth.js';
import { addStream, makeTicket, PING_SECONDS, readTicket, type LiveEvent } from './service.js';

export const router = new Hono();

router.post('/realtime/ticket', requireAuth, (c) => {
  const ticket = makeTicket((c as any).get('user'));
  if (!ticket) return c.json({ detail: 'auth_not_configured' }, 500);
  return c.json(ticket);
});

router.get('/realtime/stream', (c) => {
  const holder = readTicket(c.req.query('ticket'));
  if (!holder) return c.json({ detail: 'invalid_ticket' }, 401);
  c.header('Cache-Control', 'no-cache');
  c.header('X-Accel-Buffering', 'no');
  return streamSSE(c, async (stream) => {
    const queue: LiveEvent[] = [];
    let wake: (() => void) | null = null;
    let closed = false;
    const remove = addStream(holder, c.req.query('entities'), (event) => {
      if (queue.length >= 256) { closed = true; } else { queue.push(event); }  // too far behind: close
      wake?.();
    }, () => { closed = true; wake?.(); });
    stream.onAbort(() => { closed = true; remove(); wake?.(); });
    await stream.writeSSE({ event: 'ready', data: '{}' });
    while (!closed) {
      const event = queue.shift();
      if (event) {
        await stream.writeSSE({ event: 'change', data: JSON.stringify(event) });
        continue;
      }
      const woke = await new Promise<boolean>((resolve) => {
        wake = () => resolve(true);
        setTimeout(() => resolve(false), PING_SECONDS * 1000);
      });
      wake = null;
      if (!woke && !closed) await stream.write(': ping\n\n');
    }
    remove();
  });
});
'''
