"""R-569: live updates in the generated web and admin apps.

`lib/realtime.ts` keeps one stream per page open while anything listens: it trades the signed-in
token for a ticket, opens `/realtime/stream`, and reconnects with backoff (a fresh ticket each time).
The data hooks of live entities (`lib/hooks.ts`) listen through `useLive` and refetch quietly - so
every page built on the hooks, generated or written by the model, updates without a reload.
"""

from __future__ import annotations

REALTIME_CLIENT = r'''"use client";

// Generated by OmniStackAI (R-569): live updates. One stream per page, opened while anything listens.
import { useEffect, useRef } from "react";

const BASE_URL = process.env.NEXT_PUBLIC_API_URL || "";

export interface LiveEvent { entity: string; op: "insert" | "update" | "delete"; id: string }
type Listener = (event: LiveEvent) => void;

const listeners = new Map<string, Set<Listener>>();
let source: EventSource | null = null;
let opening = false;
let attempts = 0;
let timer: ReturnType<typeof setTimeout> | null = null;

function count(): number {
  let n = 0;
  listeners.forEach((set) => { n += set.size; });
  return n;
}

function retryLater(): void {
  if (timer || count() === 0) return;
  const wait = Math.min(30000, 1000 * 2 ** attempts);
  attempts += 1;
  timer = setTimeout(() => { timer = null; void open(); }, wait);
}

async function open(): Promise<void> {
  if (source || opening || typeof window === "undefined" || count() === 0) return;
  const token = localStorage.getItem("auth_token");
  if (!token) return;  // live updates are for signed-in people
  opening = true;
  try {
    // A browser's EventSource cannot send the token, so it is traded for a one-minute ticket.
    const res = await fetch(`${BASE_URL}/realtime/ticket`, { method: "POST", headers: { Authorization: `Bearer ${token}` } });
    if (!res.ok) throw new Error(`ticket ${res.status}`);
    const { ticket } = (await res.json()) as { ticket: string };
    const stream = new EventSource(`${BASE_URL}/realtime/stream?ticket=${encodeURIComponent(ticket)}`);
    source = stream;
    stream.addEventListener("ready", () => { attempts = 0; });
    stream.addEventListener("change", (message) => {
      let event: LiveEvent;
      try { event = JSON.parse((message as MessageEvent).data) as LiveEvent; } catch { return; }
      listeners.get(event.entity)?.forEach((listener) => listener(event));
      listeners.get("*")?.forEach((listener) => listener(event));
    });
    stream.onerror = () => {
      // The ticket is single-use in practice (a minute), so reconnect with a fresh one.
      stream.close();
      if (source === stream) source = null;
      retryLater();
    };
  } catch {
    retryLater();
  } finally {
    opening = false;
  }
}

/** Listen for changes to `entity` ("*" for every live entity); returns the function that stops. */
export function subscribe(entity: string, listener: Listener): () => void {
  let set = listeners.get(entity);
  if (!set) { set = new Set(); listeners.set(entity, set); }
  set.add(listener);
  void open();
  return () => {
    listeners.get(entity)?.delete(listener);
    if (count() === 0) {
      source?.close();
      source = null;
      if (timer) { clearTimeout(timer); timer = null; }
    }
  };
}

/**
 * Call `onChange` when `entity` changes (only record `id`, when given). Bursts - a scheduled job
 * cancelling a hundred orders - are folded into one call a quarter-second later.
 */
export function useLive(entity: string, onChange: (event: LiveEvent) => void, id?: string): void {
  const latest = useRef(onChange);
  latest.current = onChange;
  useEffect(() => {
    let pending: ReturnType<typeof setTimeout> | null = null;
    const stop = subscribe(entity, (event) => {
      if (id && event.id !== id) return;
      if (pending) clearTimeout(pending);
      pending = setTimeout(() => { pending = null; latest.current(event); }, 250);
    });
    return () => { stop(); if (pending) clearTimeout(pending); };
  }, [entity, id]);
}
'''


def make_hook_live(block: list[str], entity: str, *, detail: bool) -> list[str]:
    """Turn one generated data hook into a live one: a quiet refetch, called on a change."""
    out: list[str] = []
    quiet_set = False
    listened = False
    for line in block:
        if line == "  const refetch = useCallback(async () => {":
            out.append("  const refetch = useCallback(async (quiet?: boolean) => {")
            continue
        if not quiet_set and line == "    setLoading(true);":
            # A live refresh keeps what is on screen until the new data arrives.
            out.append("    if (quiet !== true) setLoading(true);")
            quiet_set = True
            continue
        out.append(line)
        if not listened and line == "  }, [refetch]);":
            if detail:
                out.append(f"  // R-569: a change to this {entity} elsewhere refreshes it quietly.")
                out.append(f'  useLive("{entity}", () => {{ void refetch(true); }}, id ?? undefined);')
            else:
                out.append(f"  // R-569: a change to any {entity} elsewhere refreshes this list quietly.")
                out.append(f'  useLive("{entity}", () => {{ void refetch(true); }});')
            listened = True
    assert quiet_set and listened, f"the {entity} hook did not have the expected shape"
    return out
