"""PC-104: rich text in generated apps - one allowlist, enforced on every write, applied again on display.

A ``rich_text`` field holds HTML written with the tiptap editor (headings, bold, italic, lists,
quotes, links, code). Every backend cleans it on create and update with a proven allowlist
sanitizer - Python ``nh3`` (ammonia), Go ``bluemonday``, Node ``sanitize-html`` - so a script, an
event handler, a style or a ``javascript:`` link can never be stored, whoever calls the API. The
web and admin apps sanitize again with DOMPurify before rendering; tables and the mobile app show
plain text.
"""

from __future__ import annotations

import json

from ..application_ir import ApplicationIR, Entity, FieldType

#: What formatted text may contain - and nothing else.
TAGS: tuple[str, ...] = ("p", "br", "strong", "b", "em", "i", "u", "s", "h2", "h3", "h4", "ul", "ol", "li",
                         "blockquote", "code", "pre", "hr", "a")
LINK_ATTRIBUTES: tuple[str, ...] = ("href", "title", "target")
URL_SCHEMES: tuple[str, ...] = ("http", "https", "mailto")

#: The editor and the second sanitizing pass on display (React 18 compatible).
RICH_TEXT_LIBRARIES: dict[str, str] = {
    "@tiptap/react": "3.31.3",
    "@tiptap/pm": "3.31.3",
    "@tiptap/starter-kit": "3.31.3",
    "dompurify": "3.4.16",
}
PYTHON_REQUIREMENT = "nh3==0.3.7"
GO_REQUIRE = "github.com/microcosm-cc/bluemonday v1.0.27"
NODE_DEPENDENCY = ("sanitize-html", "^2.17.7")
NODE_TYPES = ("@types/sanitize-html", "^2.16.0")


#: Words in a prompt that ask for formatting (PC-104, found live: a built-in template planned an
#: article's body as plain text although the prompt asked for "headings, lists, links").
_FORMATTING_CUES = ("formatted", "formatting", "rich text", "rich-text", "wysiwyg", "markdown", "headings",
                    "bold", "bullet", "lists", "editor")
_LONG_CONTENT_NAMES = frozenset({"body", "content", "description", "notes", "article", "details", "about", "bio"})


def with_rich_text(ir: ApplicationIR, prompt: str) -> ApplicationIR:
    """When the prompt asks for formatting, long text fields named for content become rich text.

    Deterministic, and only for the cues above: a plain-text body stays plain unless formatting
    was asked for. A plan (from the model or a template) that already says rich_text is unchanged.
    """
    from dataclasses import replace

    text = (prompt or "").lower()
    if not any(cue in text for cue in _FORMATTING_CUES):
        return ir
    entities = []
    changed = False
    for entity in ir.entities:
        fields = []
        for field in entity.fields:
            if field.type is FieldType.TEXT and field.name in _LONG_CONTENT_NAMES and entity.name.lower() != "comment":
                field = replace(field, type=FieldType.RICH_TEXT)
                changed = True
            fields.append(field)
        entities.append(replace(entity, fields=tuple(fields)))
    return replace(ir, entities=tuple(entities)) if changed else ir


def rich_fields(entity: Entity) -> list[str]:
    return [field.name for field in entity.fields if field.type is FieldType.RICH_TEXT]


def has_rich_text(ir: ApplicationIR) -> bool:
    return any(rich_fields(entity) for entity in ir.entities)


# ── Python (FastAPI / Pydantic) ─────────────────────────────────────────────────────────────────

def python_module() -> str:
    tags = ", ".join(repr(t) for t in TAGS)
    return f'''"""Formatted text is cleaned before it is stored (generated by OmniStackAI, PC-104).

Only these tags survive; links keep http, https and mailto addresses and open safely. Scripts,
event handlers, styles and javascript: links are removed, whoever calls the API.
"""
from __future__ import annotations

import nh3

TAGS = {{{tags}}}
ATTRIBUTES = {{"a": {{{", ".join(repr(a) for a in LINK_ATTRIBUTES)}}}}}
URL_SCHEMES = {{{", ".join(repr(s) for s in URL_SCHEMES)}}}


def clean_html(value: object) -> object:
    if value is None or not isinstance(value, str):
        return value
    return nh3.clean(value, tags=TAGS, attributes=ATTRIBUTES, url_schemes=URL_SCHEMES,
                     link_rel="noopener noreferrer nofollow", strip_comments=True)
'''


def python_validator(fields: list[str]) -> list[str]:
    names = ", ".join(repr(name) for name in fields)
    return [
        "",
        f"    @field_validator({names}, mode=\"before\")",
        "    @classmethod",
        "    def _clean_rich_text(cls, value: object) -> object:",
        "        # PC-104: formatted text is cleaned on every create and update.",
        "        return clean_html(value)",
    ]


# ── Go ─────────────────────────────────────────────────────────────────────────────────────────

def go_policy() -> str:
    tags = ", ".join(f'"{t}"' for t in TAGS if t != "a")
    return (
        "// PC-104: formatted text is cleaned before it is stored. Only these tags survive; links keep\n"
        "// http, https and mailto addresses. Scripts, event handlers and styles are removed.\n"
        "var richTextPolicy = func() *bluemonday.Policy {\n"
        "\tp := bluemonday.NewPolicy()\n"
        f"\tp.AllowElements({tags})\n"
        '\tp.AllowAttrs("href", "title", "target").OnElements("a")\n'
        '\tp.AllowURLSchemes("http", "https", "mailto")\n'
        "\tp.RequireNoFollowOnLinks(true)\n"
        "\tp.RequireNoReferrerOnLinks(true)\n"
        "\tp.AddTargetBlankToFullyQualifiedLinks(true)\n"
        "\treturn p\n"
        "}()\n"
    )


def go_sanitize_method(entity: Entity, pascal) -> str:
    lines = [f"// SanitizeRichText cleans {entity.name}'s formatted text (PC-104).",
             f"func (m *{entity.name}) SanitizeRichText() {{"]
    for field in entity.fields:
        if field.type is not FieldType.RICH_TEXT:
            continue
        name = pascal(field.name)
        if field.required:
            lines.append(f"\tm.{name} = richTextPolicy.Sanitize(m.{name})")
        else:
            lines.append(f"\tif m.{name} != nil {{\n\t\tclean := richTextPolicy.Sanitize(*m.{name})\n\t\tm.{name} = &clean\n\t}}")
    lines.append("}")
    return "\n".join(lines) + "\n"


# ── Node (zod) ───────────────────────────────────────────────────────────────────────────────────

def node_prelude() -> str:
    return (
        "import sanitizeHtml from 'sanitize-html';\n\n"
        "// PC-104: formatted text is cleaned on every create and update, whoever calls the API.\n"
        "const RICH_TEXT: sanitizeHtml.IOptions = {\n"
        f"  allowedTags: {json.dumps(list(TAGS))},\n"
        # rel is allowed only because the transform below always sets it to the safe value.
        f"  allowedAttributes: {{ a: {json.dumps([*LINK_ATTRIBUTES, 'rel'])} }},\n"
        f"  allowedSchemes: {json.dumps(list(URL_SCHEMES))},\n"
        "  transformTags: { a: sanitizeHtml.simpleTransform('a', { rel: 'noopener noreferrer nofollow' }) },\n"
        "};\n"
        "const cleanRichText = (value: string) => sanitizeHtml(value, RICH_TEXT);\n\n"
    )


# ── Web and admin apps ───────────────────────────────────────────────────────────────────────────

RICH_TEXT_EDITOR = r'''"use client";

// Generated by OmniStackAI (PC-104): the editor for formatted text. It produces HTML, which the
// API cleans with an allowlist before storing it; <RichText> cleans it again before showing it.
import { useEffect, useRef } from "react";
import { EditorContent, useEditor } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import {
  Bold, Code, Heading2, Heading3, Italic, Link as LinkIcon, List, ListOrdered, Quote, Redo2, Strikethrough, Undo2,
} from "lucide-react";

export interface RichTextEditorProps {
  value: string;
  onChange: (html: string) => void;
  placeholder?: string;
  disabled?: boolean;
  /** For a <label htmlFor>. */
  id?: string;
}

// Created once: tiptap rebuilds the whole editor when its extensions change, and a new
// StarterKit on every render (found live) reset the text and dropped focus after each keystroke.
const EXTENSIONS = [StarterKit.configure({ heading: { levels: [2, 3] }, link: { openOnClick: false, autolink: true } })];

export function RichTextEditor({ value, onChange, placeholder, disabled, id }: RichTextEditorProps) {
  const emitted = useRef<string | null>(null);
  const produced = useRef<Set<string>>(new Set());
  // The latest onChange, read by the editor's update handler without rebuilding the editor.
  const onChangeRef = useRef(onChange);
  onChangeRef.current = onChange;
  const editor = useEditor({
    extensions: EXTENSIONS,
    content: value || "",
    editable: !disabled,
    immediatelyRender: false, // Next renders on the server first; the editor starts in the browser
    editorProps: {
      attributes: {
        ...(id ? { id } : {}),
        "aria-label": placeholder || "Formatted text",
        class: "rich-text min-h-[140px] px-3 py-2 text-sm outline-none",
      },
    },
    onUpdate: ({ editor: current }) => {
      // The editor keeps an empty line at the end for typing; it is not part of the text.
      const html = current.isEmpty ? "" : current.getHTML().replace(/(<p><\/p>)+$/, "");
      emitted.current = html;
      produced.current.add(html);
      if (produced.current.size > 200) produced.current = new Set([html]);
      onChangeRef.current(html);
    },
  }, []);

  // A form that loads a record after the editor opened (an edit form) hands it the stored text.
  // Found live: a form can re-render with a value a keystroke or two older than the editor's, and
  // loading it reset the editor - text typed after a toolbar click vanished. Only a value the
  // editor never produced itself (a record arriving from the API) is loaded.
  useEffect(() => {
    if (!editor || value === emitted.current || produced.current.has(value)) return;
    emitted.current = value;
    editor.commands.setContent(value || "", { emitUpdate: false });
  }, [editor, value]);

  const button = (label: string, active: boolean, run: () => void, Icon: typeof Bold) => (
    // onMouseDown: a click must not take focus (and the selection) from the text being formatted -
    // found live, text typed after a toolbar click was lost. Keyboard users still tab to it.
    <button key={label} type="button" onMouseDown={(event) => event.preventDefault()} onClick={run}
      disabled={disabled || !editor} aria-label={label} title={label}
      aria-pressed={active}
      className={`rounded p-1.5 ${active ? "bg-muted text-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}>
      <Icon className="h-4 w-4" aria-hidden />
    </button>
  );

  const link = () => {
    if (!editor) return;
    const previous = editor.getAttributes("link").href as string | undefined;
    const href = window.prompt("Link address (https://...)", previous || "https://");
    if (href === null) return;
    if (href === "" || href === "https://") editor.chain().focus().unsetLink().run();
    else editor.chain().focus().setLink({ href }).run();
  };

  return (
    <div className="overflow-hidden rounded-md border bg-background focus-within:border-primary focus-within:ring-2 focus-within:ring-primary/20">
      <div className="flex flex-wrap gap-0.5 border-b bg-muted/40 px-1.5 py-1" role="toolbar" aria-label="Formatting">
        {editor && [
          button("Bold", editor.isActive("bold"), () => editor.chain().focus().toggleBold().run(), Bold),
          button("Italic", editor.isActive("italic"), () => editor.chain().focus().toggleItalic().run(), Italic),
          button("Strikethrough", editor.isActive("strike"), () => editor.chain().focus().toggleStrike().run(), Strikethrough),
          button("Heading", editor.isActive("heading", { level: 2 }), () => editor.chain().focus().toggleHeading({ level: 2 }).run(), Heading2),
          button("Subheading", editor.isActive("heading", { level: 3 }), () => editor.chain().focus().toggleHeading({ level: 3 }).run(), Heading3),
          button("Bulleted list", editor.isActive("bulletList"), () => editor.chain().focus().toggleBulletList().run(), List),
          button("Numbered list", editor.isActive("orderedList"), () => editor.chain().focus().toggleOrderedList().run(), ListOrdered),
          button("Quote", editor.isActive("blockquote"), () => editor.chain().focus().toggleBlockquote().run(), Quote),
          button("Code", editor.isActive("codeBlock"), () => editor.chain().focus().toggleCodeBlock().run(), Code),
          button("Link", editor.isActive("link"), link, LinkIcon),
          button("Undo", false, () => editor.chain().focus().undo().run(), Undo2),
          button("Redo", false, () => editor.chain().focus().redo().run(), Redo2),
        ]}
      </div>
      <EditorContent editor={editor} />
    </div>
  );
}
'''

RICH_TEXT_VIEW = r'''"use client";

// Generated by OmniStackAI (PC-104): shows formatted text. The API already cleaned it; this cleans
// it again (DOMPurify, the same allowlist) so nothing a browser would run is ever rendered.
import { useEffect, useState } from "react";

const ALLOWED_TAGS = __TAGS__;
const ALLOWED_ATTR = ["href", "title", "target", "rel"];

/** The words without the formatting - for tables, previews and search results. */
export function plainText(html: unknown, max = 0): string {
  // Block tags separate words; inline ones (<strong>, <a>) do not (PC-108: "same day ." read oddly).
  const text = typeof html === "string" ? html.replace(/<\/?(p|h[1-6]|li|ul|ol|blockquote|pre|div|br)\b[^>]*>/gi, " ")
    .replace(/<[^>]*>/g, "").replace(/&nbsp;/g, " ").replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/\s+/g, " ").trim() : "";
  return max > 0 && text.length > max ? `${text.slice(0, max).trimEnd()}...` : text;
}

export function RichText({ html, className = "" }: { html: unknown; className?: string }) {
  const [clean, setClean] = useState<string | null>(null);
  useEffect(() => {
    let alive = true;
    import("dompurify").then(({ default: DOMPurify }) => {
      if (!alive) return;
      DOMPurify.addHook("afterSanitizeAttributes", (node) => {
        if (node.tagName === "A") { node.setAttribute("rel", "noopener noreferrer nofollow"); node.setAttribute("target", "_blank"); }
      });
      setClean(DOMPurify.sanitize(typeof html === "string" ? html : "", { ALLOWED_TAGS, ALLOWED_ATTR, ALLOWED_URI_REGEXP: /^(?:https?:|mailto:)/i }));
      DOMPurify.removeHook("afterSanitizeAttributes");
    });
    return () => { alive = false; };
  }, [html]);
  if (typeof html !== "string" || !html) return <span className="text-muted-foreground">—</span>;
  // Until the sanitizer has loaded (and on the server), show the words only.
  if (clean === null) return <div className={`rich-text ${className}`}>{plainText(html)}</div>;
  return <div className={`rich-text ${className}`} dangerouslySetInnerHTML={{ __html: clean }} />;
}
'''.replace("__TAGS__", json.dumps(list(TAGS)))

#: Typography for formatted text (the Tailwind preflight removes list bullets and heading sizes).
RICH_TEXT_CSS = """
/* PC-104: formatted text (the editor and <RichText>). */
.rich-text h2 { font-size: 1.25rem; font-weight: 700; margin: 0.75em 0 0.4em; font-family: var(--font-heading, inherit); }
.rich-text h3 { font-size: 1.05rem; font-weight: 600; margin: 0.7em 0 0.35em; font-family: var(--font-heading, inherit); }
.rich-text p { margin: 0.4em 0; }
.rich-text ul { list-style: disc; padding-left: 1.4em; margin: 0.4em 0; }
.rich-text ol { list-style: decimal; padding-left: 1.4em; margin: 0.4em 0; }
.rich-text blockquote { border-left: 3px solid var(--color-border); padding-left: 0.8em; color: var(--color-text-muted); margin: 0.5em 0; }
.rich-text a { color: var(--color-primary); text-decoration: underline; }
.rich-text pre { background: var(--color-surface-subtle); padding: 0.6em 0.8em; border-radius: 6px; overflow-x: auto; font-size: 0.85em; }
.rich-text code { font-family: var(--font-mono, monospace); }
.rich-text hr { border: 0; border-top: 1px solid var(--color-border); margin: 1em 0; }
"""
