"""Render a PostgreSQL schema from the Application IR — the generated backend's persistence layer.

`render_postgres_schema(ir)` is pure and deterministic: one CREATE TABLE per entity, columns typed from
`FieldType`, `NOT NULL` for required fields, a UUID primary key (the entity's own ``id`` field if it
declares one, else a surrogate), foreign-key columns for many_to_one/one_to_one relations, and a join
table per many_to_many relation. Nothing connects to or runs a database; this only emits SQL text that
a later migration file carries.
"""

from __future__ import annotations

import re

from ..application_ir import ApplicationIR, Entity, FieldType, RelationKind

_PG_TYPE: dict[FieldType, str] = {
    FieldType.STRING: "TEXT",
    FieldType.TEXT: "TEXT",
    FieldType.INT: "BIGINT",
    FieldType.FLOAT: "DOUBLE PRECISION",
    FieldType.BOOL: "BOOLEAN",
    FieldType.DATETIME: "TIMESTAMPTZ",
    FieldType.UUID: "UUID",
    FieldType.JSON: "JSONB",
}

_FK_KINDS = frozenset({RelationKind.MANY_TO_ONE, RelationKind.ONE_TO_ONE})


def _snake(name: str) -> str:
    """PascalCase/camelCase -> snake_case (entity names are [A-Za-z][A-Za-z0-9]*)."""

    stepped = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    stepped = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", stepped)
    return stepped.lower()


def _table(entity_name: str) -> str:
    return _snake(entity_name)


def _column_lines(entity: Entity) -> list[str]:
    lines: list[str] = []
    has_id = any(field.name == "id" for field in entity.fields)
    if not has_id:
        lines.append("    id UUID PRIMARY KEY DEFAULT gen_random_uuid()")

    for field in entity.fields:
        pg = _PG_TYPE[field.type]
        if field.name == "id":
            default = " DEFAULT gen_random_uuid()" if field.type is FieldType.UUID else ""
            lines.append(f"    {field.name} {pg} PRIMARY KEY{default}")
        else:
            null = " NOT NULL" if field.required else ""
            lines.append(f"    {field.name} {pg}{null}")

    for relation in entity.relations:
        if relation.kind in _FK_KINDS:
            target = _table(relation.target_entity)
            lines.append(f"    {relation.name}_id UUID REFERENCES {target}(id)")
    return lines


def _join_tables(ir: ApplicationIR) -> list[str]:
    """One deterministic join table per unique many_to_many relation pair."""

    seen: dict[tuple[str, str], str] = {}
    for entity in ir.entities:
        left = _table(entity.name)
        for relation in entity.relations:
            if relation.kind is RelationKind.MANY_TO_MANY:
                right = _table(relation.target_entity)
                key = tuple(sorted((left, right)))
                if key in seen:
                    continue
                a, b = key
                join = f"{a}_{b}"
                seen[key] = (
                    f"CREATE TABLE {join} (\n"
                    f"    {a}_id UUID NOT NULL REFERENCES {a}(id),\n"
                    f"    {b}_id UUID NOT NULL REFERENCES {b}(id),\n"
                    f"    PRIMARY KEY ({a}_id, {b}_id)\n"
                    f");"
                )
    return [seen[key] for key in sorted(seen)]


def render_postgres_schema(ir: ApplicationIR) -> str:
    """Deterministic PostgreSQL DDL for the IR's entities and relations (empty if no entities)."""

    if not isinstance(ir, ApplicationIR):
        raise TypeError("render_postgres_schema expects an ApplicationIR")
    if not ir.entities:
        return ""

    blocks: list[str] = [
        f"-- PostgreSQL schema for {ir.name}",
        "-- Generated by OmniStackAI from the Application IR. Review before applying.",
        "",
    ]
    for entity in ir.entities:
        columns = ",\n".join(_column_lines(entity))
        blocks.append(f"CREATE TABLE {_table(entity.name)} (\n{columns}\n);")
        blocks.append("")

    join_tables = _join_tables(ir)
    if join_tables:
        blocks.append("-- Association tables (many-to-many)")
        for table in join_tables:
            blocks.append(table)
            blocks.append("")

    return "\n".join(blocks).rstrip("\n") + "\n"
