"""Render an honest PostgreSQL seed migration from the IR fixtures (R-248).

`render_postgres_seed(ir)` emits one INSERT per fixture row using ONLY the columns and values explicitly
declared in the IR — it never invents, defaults, or guesses a value; a column absent from a row is
simply not inserted (it falls to the schema's DB default / NULL). Pure and deterministic; nothing
connects to or runs a database. This is the one place the codebase produces SQL value literals, so it
owns the quoting: single quotes are doubled, bool -> TRUE/FALSE, None -> NULL, and dict/list -> a jsonb
literal. Standard-conforming strings are assumed (only single-quote doubling is needed).
"""

from __future__ import annotations

import json
from typing import Any

from ..application_ir import ApplicationIR
from .schema_sql import ordered_entities, sql_identifier, table_name


def _sql_literal(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):  # bool before int (bool is a subclass of int)
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    if isinstance(value, (dict, list)):
        return "'" + json.dumps(value, sort_keys=True).replace("'", "''") + "'::jsonb"
    raise TypeError(f"unsupported seed value type: {type(value).__name__}")


def render_postgres_seed(ir: ApplicationIR) -> str:
    """Deterministic INSERTs from the IR fixtures (empty string when there are no fixtures)."""

    if not isinstance(ir, ApplicationIR):
        raise TypeError("render_postgres_seed expects an ApplicationIR")
    if not ir.fixtures:
        return ""

    blocks: list[str] = [
        f"-- Seed data for {ir.name}",
        "-- Generated by OmniStackAI from explicit Application IR fixtures — values are authored, not fabricated.",
        "",
    ]
    entity_order = {entity.name: index for index, entity in enumerate(ordered_entities(ir))}
    fixtures = sorted(
        enumerate(ir.fixtures),
        key=lambda item: (entity_order.get(item[1].entity, len(entity_order)), item[0]),
    )
    for _, fixture in fixtures:
        table = sql_identifier(table_name(fixture.entity))
        for row in fixture.rows:
            columns = sorted(row)
            column_sql = ", ".join(sql_identifier(column) for column in columns)
            value_sql = ", ".join(_sql_literal(row[column]) for column in columns)
            blocks.append(f"INSERT INTO {table} ({column_sql}) VALUES ({value_sql});")
        blocks.append("")

    return "\n".join(blocks).rstrip("\n") + "\n"
