"""PC-105: file uploads in the Go and Node (Express and Hono) backends - the Python behaviour, ported.

The same contract as ``uploads.python_upload_files`` (PC-102): ``POST /uploads`` takes one file for
one field ("Entity.field"), refuses an extension the field does not take (415), a file over the
field's size (413), an empty file or an unknown field (422), and content that is not what its name
says (415: magic bytes, Office/OpenDocument parts, macros); stores it under the project's prefix in
S3-compatible storage (Cloudflare R2, AWS S3) or on the local disk; ``GET /files/<key>`` answers
with a short-lived signed link or the file. The same messages, so the upload window reads the same.
"""

from __future__ import annotations

import json

from ..application_ir import ApplicationIR
from .upload_policy import MIME
from .uploads import upload_policies

GO_REQUIRES = (
    "github.com/aws/aws-sdk-go-v2 v1.47.1",
    "github.com/aws/aws-sdk-go-v2/credentials v1.20.6",
    "github.com/aws/aws-sdk-go-v2/service/s3 v1.113.4",
)
NODE_DEPENDENCIES = {"@aws-sdk/client-s3": "3.1142.0", "@aws-sdk/s3-request-presigner": "3.1142.0", "busboy": "1.6.0"}
NODE_DEV_DEPENDENCIES = {"@types/busboy": "1.5.4"}
_INLINE = ("jpg", "jpeg", "png", "webp", "gif", "avif", "pdf", "mp3", "wav", "m4a", "ogg", "mp4", "webm", "mov", "txt")
_KEY_PATTERN = r"^[a-z0-9_]+/[a-z0-9_]+/[0-9a-f]{32}/[A-Za-z0-9._-]{1,120}$"


# ── Go ───────────────────────────────────────────────────────────────────────────────────────────

def go_upload_files(ir: ApplicationIR, module: str) -> list[tuple[str, str]]:
    policies = upload_policies(ir)
    entries = _go_aligned({
        json.dumps(field): f'{{Folder: {json.dumps(p["folder"])}, Extensions: []string{{'
        + ", ".join(json.dumps(e) for e in p["extensions"])
        + f'}}, MaxBytes: {p["max_bytes"]}, Describe: {json.dumps(p["describe"])}}},'
        for field, p in sorted(policies.items())
    })
    mime = _go_aligned({json.dumps(k): f"{json.dumps(v)}," for k, v in sorted(MIME.items())})
    inline = ", ".join(f'"{e}": true' for e in _INLINE)
    handlers = (
        _GO_HANDLERS.replace("__MODULE__", module)
        .replace("__POLICIES__", entries)
        .replace("__MIME__", mime)
        .replace("__INLINE__", inline)
        .replace("__KEY__", _KEY_PATTERN)
    )
    return [
        ("internal/storage/storage.go", _GO_STORAGE),
        ("internal/uploads/checks.go", _GO_CHECKS),
        ("internal/handlers/uploads.go", handlers),
    ]


def _go_aligned(pairs: dict[str, str]) -> str:
    """Map literal lines with the values lined up, as gofmt writes them."""
    width = max(map(len, pairs), default=0)
    return "\n".join(f"\t{key}:{' ' * (width - len(key) + 1)}{value}" for key, value in pairs.items())


def go_routes(has_auth: bool) -> list[str]:
    upload = "handlers.RequireAuth(handlers.Upload)" if has_auth else "handlers.Upload"
    return [
        "\t// PC-105: uploads (checked and stored) and the files they became.",
        f'\tmux.HandleFunc("POST /uploads", {upload})',
        '\tmux.HandleFunc("GET /files/{key...}", handlers.ServeFile)',
    ]


_GO_STORAGE = """// Package storage keeps uploaded files (generated by OmniStackAI, PC-105).
//
// S3-compatible storage when S3_BUCKET, S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY are set -
// Cloudflare R2 (S3_ENDPOINT=https://<account>.r2.cloudflarestorage.com) or AWS S3 (S3_REGION) -
// otherwise the local disk (LOCAL_STORAGE_DIR, default ./uploads). STORAGE_DRIVER=s3 or local
// forces one; STORAGE_PREFIX is this app's folder in a shared bucket. Keys are never logged.
package storage

import (
\t"context"
\t"errors"
\t"fmt"
\t"io"
\t"os"
\t"path/filepath"
\t"strings"
\t"sync"
\t"time"

\t"github.com/aws/aws-sdk-go-v2/aws"
\t"github.com/aws/aws-sdk-go-v2/credentials"
\t"github.com/aws/aws-sdk-go-v2/service/s3"
)

// Store is where uploaded files live.
type Store interface {
\tKind() string
\tPut(ctx context.Context, key string, body io.ReadSeeker, size int64, contentType string) error
\tExists(ctx context.Context, key string) bool
}

// LocalStore keeps files in a folder on this machine.
type LocalStore struct{ root string }

func (s *LocalStore) Kind() string { return "local" }

// Path is where a key lives on disk; a key that would leave the folder is refused.
func (s *LocalStore) Path(key string) (string, error) {
\ttarget := filepath.Clean(filepath.Join(s.root, filepath.FromSlash(key)))
\tif !strings.HasPrefix(target, s.root+string(os.PathSeparator)) {
\t\treturn "", errors.New("invalid_key")
\t}
\treturn target, nil
}

func (s *LocalStore) Put(_ context.Context, key string, body io.ReadSeeker, _ int64, _ string) error {
\ttarget, err := s.Path(key)
\tif err != nil {
\t\treturn err
\t}
\tif err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
\t\treturn err
\t}
\tout, err := os.Create(target)
\tif err != nil {
\t\treturn err
\t}
\tdefer out.Close()
\t_, err = io.Copy(out, body)
\treturn err
}

func (s *LocalStore) Exists(_ context.Context, key string) bool {
\ttarget, err := s.Path(key)
\tif err != nil {
\t\treturn false
\t}
\tinfo, err := os.Stat(target)
\treturn err == nil && info.Mode().IsRegular()
}

// S3Store keeps files in an S3-compatible bucket and serves them by short-lived signed links.
type S3Store struct {
\tclient  *s3.Client
\tpresign *s3.PresignClient
\tbucket  string
\tprefix  string
}

func (s *S3Store) Kind() string { return "s3" }

func (s *S3Store) full(key string) string {
\tif s.prefix == "" {
\t\treturn key
\t}
\treturn s.prefix + "/" + key
}

func (s *S3Store) Put(ctx context.Context, key string, body io.ReadSeeker, size int64, contentType string) error {
\t_, err := s.client.PutObject(ctx, &s3.PutObjectInput{
\t\tBucket:        aws.String(s.bucket),
\t\tKey:           aws.String(s.full(key)),
\t\tBody:          body,
\t\tContentLength: aws.Int64(size),
\t\tContentType:   aws.String(contentType),
\t})
\treturn err
}

func (s *S3Store) Exists(ctx context.Context, key string) bool {
\t_, err := s.client.HeadObject(ctx, &s3.HeadObjectInput{Bucket: aws.String(s.bucket), Key: aws.String(s.full(key))})
\treturn err == nil
}

// SignedURL is a link to the file that expires after five minutes.
func (s *S3Store) SignedURL(ctx context.Context, key, filename, contentType string, inline bool) (string, error) {
\tdisposition := "attachment"
\tif inline {
\t\tdisposition = "inline"
\t}
\treq, err := s.presign.PresignGetObject(ctx, &s3.GetObjectInput{
\t\tBucket:                     aws.String(s.bucket),
\t\tKey:                        aws.String(s.full(key)),
\t\tResponseContentType:        aws.String(contentType),
\t\tResponseContentDisposition: aws.String(fmt.Sprintf(`%s; filename="%s"`, disposition, filename)),
\t}, s3.WithPresignExpires(5*time.Minute))
\tif err != nil {
\t\treturn "", err
\t}
\treturn req.URL, nil
}

var (
\tonce     sync.Once
\tstore    Store
\tstoreErr error
)

// Get returns the store the environment describes (chosen once).
func Get() (Store, error) {
\tonce.Do(func() { store, storeErr = fromEnv() })
\treturn store, storeErr
}

func env(name string) string { return strings.TrimSpace(os.Getenv(name)) }

func fromEnv() (Store, error) {
\tdriver := strings.ToLower(env("STORAGE_DRIVER"))
\tif driver == "" {
\t\tdriver = "auto"
\t}
\tready := env("S3_BUCKET") != "" && env("S3_ACCESS_KEY_ID") != "" && env("S3_SECRET_ACCESS_KEY") != ""
\tif driver == "s3" || (driver == "auto" && ready) {
\t\tif !ready {
\t\t\treturn nil, errors.New("storage_not_configured: S3_BUCKET, S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY")
\t\t}
\t\tendpoint := env("S3_ENDPOINT")
\t\tregion := env("S3_REGION")
\t\tif region == "" {
\t\t\tregion = "us-east-1"
\t\t\tif endpoint != "" {
\t\t\t\tregion = "auto"
\t\t\t}
\t\t}
\t\tcfg := aws.Config{
\t\t\tRegion:      region,
\t\t\tCredentials: credentials.NewStaticCredentialsProvider(env("S3_ACCESS_KEY_ID"), env("S3_SECRET_ACCESS_KEY"), ""),
\t\t}
\t\tclient := s3.NewFromConfig(cfg, func(o *s3.Options) {
\t\t\tif endpoint != "" {
\t\t\t\to.BaseEndpoint = aws.String(endpoint)
\t\t\t\to.UsePathStyle = true
\t\t\t}
\t\t\t// S3-compatible services (R2) accept checksums only where S3 requires them.
\t\t\to.RequestChecksumCalculation = aws.RequestChecksumCalculationWhenRequired
\t\t\to.ResponseChecksumValidation = aws.ResponseChecksumValidationWhenRequired
\t\t})
\t\treturn &S3Store{client: client, presign: s3.NewPresignClient(client), bucket: env("S3_BUCKET"),
\t\t\tprefix: strings.Trim(env("STORAGE_PREFIX"), "/")}, nil
\t}
\troot := env("LOCAL_STORAGE_DIR")
\tif root == "" {
\t\troot = "./uploads"
\t}
\tabs, err := filepath.Abs(root)
\tif err != nil {
\t\treturn nil, err
\t}
\tif err := os.MkdirAll(abs, 0o755); err != nil {
\t\treturn nil, err
\t}
\treturn &LocalStore{root: abs}, nil
}
"""

_GO_CHECKS = """// Package uploads decides whether a file is what its name says (generated by OmniStackAI, PC-105).
//
// The name and the browser's declared type are both chosen by the sender, so neither is trusted:
// the first bytes are, and for Office and OpenDocument files the parts inside the archive.
package uploads

import (
\t"archive/zip"
\t"bytes"
\t"io"
\t"os"
\t"strings"
\t"unicode/utf8"
)

var (
\tole          = []byte{0xd0, 0xcf, 0x11, 0xe0, 0xa1, 0xb1, 0x1a, 0xe1}
\tftypImage    = map[string][]string{"heic": {"heic", "heix", "mif1", "msf1", "hevc", "heim", "heis"}, "avif": {"avif", "avis"}}
\tofficePart   = map[string]string{"docx": "word/document.xml", "xlsx": "xl/workbook.xml", "pptx": "ppt/presentation.xml"}
\topenDocument = map[string]string{
\t\t"odt": "application/vnd.oasis.opendocument.text",
\t\t"ods": "application/vnd.oasis.opendocument.spreadsheet",
\t\t"odp": "application/vnd.oasis.opendocument.presentation",
\t}
)

func in(list []string, v string) bool {
\tfor _, item := range list {
\t\tif item == v {
\t\t\treturn true
\t\t}
\t}
\treturn false
}

func isText(head []byte) bool {
\tif bytes.IndexByte(head, 0) >= 0 {
\t\treturn false
\t}
\t// A multi-byte character cut at the end of the sample is still text.
\tfor cut := 0; cut <= 3 && cut <= len(head); cut++ {
\t\tif utf8.Valid(head[:len(head)-cut]) {
\t\t\treturn true
\t\t}
\t}
\treturn false
}

// Matches reports whether the file really is what its extension says.
func Matches(ext string, f *os.File, size int64) bool {
\thead := make([]byte, 8192)
\tn, _ := f.ReadAt(head, 0)
\thead = head[:n]
\thas := func(prefix []byte) bool { return bytes.HasPrefix(head, prefix) }
\tat := func(from, to int) string {
\t\tif len(head) < to {
\t\t\treturn ""
\t\t}
\t\treturn string(head[from:to])
\t}
\tswitch ext = strings.ToLower(ext); ext {
\tcase "jpg", "jpeg":
\t\treturn has([]byte{0xff, 0xd8, 0xff})
\tcase "png":
\t\treturn has([]byte("\\x89PNG\\r\\n\\x1a\\n"))
\tcase "gif":
\t\treturn at(0, 6) == "GIF87a" || at(0, 6) == "GIF89a"
\tcase "webp":
\t\treturn at(0, 4) == "RIFF" && at(8, 12) == "WEBP"
\tcase "heic", "avif":
\t\treturn at(4, 8) == "ftyp" && in(ftypImage[ext], at(8, 12))
\tcase "mp4", "mov", "m4a":
\t\treturn at(4, 8) == "ftyp" && !in(append(append([]string{}, ftypImage["heic"]...), ftypImage["avif"]...), at(8, 12))
\tcase "webm":
\t\treturn has([]byte{0x1a, 0x45, 0xdf, 0xa3})
\tcase "ogg":
\t\treturn has([]byte("OggS"))
\tcase "mp3":
\t\treturn has([]byte("ID3")) || (len(head) > 1 && head[0] == 0xff && head[1]&0xe0 == 0xe0)
\tcase "wav":
\t\treturn at(0, 4) == "RIFF" && at(8, 12) == "WAVE"
\tcase "pdf":
\t\treturn bytes.Contains(head[:min(len(head), 1024)], []byte("%PDF-"))
\tcase "doc", "xls", "ppt":
\t\treturn has(ole)
\tcase "rtf":
\t\treturn has([]byte(`{\\rtf`))
\tcase "txt", "csv":
\t\treturn isText(head)
\tcase "dcm":
\t\treturn at(128, 132) == "DICM"
\tcase "docx", "xlsx", "pptx", "odt", "ods", "odp", "zip":
\t\tif !has([]byte("PK")) {
\t\t\treturn false
\t\t}
\t\tarchive, err := zip.NewReader(f, size)
\t\tif err != nil {
\t\t\treturn false
\t\t}
\t\tparts := map[string]*zip.File{}
\t\tfor _, part := range archive.File {
\t\t\tif strings.HasSuffix(strings.ToLower(part.Name), "vbaproject.bin") {
\t\t\t\treturn false // macros: a .docx never carries them, a renamed .docm does
\t\t\t}
\t\t\tparts[part.Name] = part
\t\t}
\t\tif want, ok := officePart[ext]; ok {
\t\t\t_, found := parts[want]
\t\t\treturn found
\t\t}
\t\tif want, ok := openDocument[ext]; ok {
\t\t\tpart, found := parts["mimetype"]
\t\t\tif !found {
\t\t\t\treturn false
\t\t\t}
\t\t\trc, err := part.Open()
\t\t\tif err != nil {
\t\t\t\treturn false
\t\t\t}
\t\t\tdefer rc.Close()
\t\t\tgot, _ := io.ReadAll(io.LimitReader(rc, 200))
\t\t\treturn strings.TrimSpace(string(got)) == want
\t\t}
\t\treturn true
\t}
\treturn false
}
"""

_GO_HANDLERS = """package handlers

// Uploads and downloads (generated by OmniStackAI, PC-105). POST /uploads takes one file for one
// field ("Entity.field"), checks it against that field's policy - extension, real content and
// size - and stores it. GET /files/<key> serves it: a short-lived signed link from S3-compatible
// storage, or the file itself from the local disk.

import (
\t"crypto/rand"
\t"encoding/hex"
\t"encoding/json"
\t"errors"
\t"fmt"
\t"io"
\t"net/http"
\t"os"
\t"path"
\t"regexp"
\t"strings"

\t"__MODULE__/internal/storage"
\t"__MODULE__/internal/uploads"
)

type uploadPolicy struct {
\tFolder     string
\tExtensions []string
\tMaxBytes   int64
\tDescribe   string
}

// Per field: the types and size it accepts (from the plan).
var uploadPolicies = map[string]uploadPolicy{
__POLICIES__
}

var uploadMIME = map[string]string{
__MIME__
}

var (
\tfileKeyPattern  = regexp.MustCompile(`__KEY__`)
\tunsafeFileChars = regexp.MustCompile(`[^A-Za-z0-9._-]+`)
\tinlineTypes     = map[string]bool{__INLINE__}
)

func uploadError(w http.ResponseWriter, status int, detail string) {
\tw.Header().Set("Content-Type", "application/json")
\tw.WriteHeader(status)
\t_ = json.NewEncoder(w).Encode(map[string]string{"detail": detail})
}

func safeFileName(name string) string {
\tname = path.Base(strings.ReplaceAll(name, `\\`, "/"))
\tstem, ext := name, ""
\tif i := strings.LastIndex(name, "."); i >= 0 {
\t\tstem, ext = name[:i], strings.ToLower(name[i+1:])
\t}
\tstem = strings.Trim(unsafeFileChars.ReplaceAllString(stem, "-"), "-._")
\tif stem == "" {
\t\tstem = "file"
\t}
\tif len(stem) > 80 {
\t\tstem = stem[:80]
\t}
\tif ext == "" {
\t\treturn stem
\t}
\treturn stem + "." + ext
}

func accepts(extensions []string, ext string) bool {
\tfor _, allowed := range extensions {
\t\tif allowed == ext {
\t\t\treturn true
\t\t}
\t}
\treturn false
}

func randomHex() string {
\tbuf := make([]byte, 16)
\t_, _ = rand.Read(buf)
\treturn hex.EncodeToString(buf)
}

// Upload receives one file for one field. The field must come before the file (Uppy sends it so).
func Upload(w http.ResponseWriter, r *http.Request) {
\treader, err := r.MultipartReader()
\tif err != nil {
\t\tuploadError(w, http.StatusBadRequest, "send the file as multipart/form-data")
\t\treturn
\t}
\tfield := ""
\tfor {
\t\tpart, err := reader.NextPart()
\t\tif errors.Is(err, io.EOF) {
\t\t\tuploadError(w, http.StatusUnprocessableEntity, "no file was sent")
\t\t\treturn
\t\t}
\t\tif err != nil {
\t\t\tuploadError(w, http.StatusBadRequest, "the upload could not be read")
\t\t\treturn
\t\t}
\t\tif part.FormName() == "field" {
\t\t\tvalue, _ := io.ReadAll(io.LimitReader(part, 200))
\t\t\tfield = strings.TrimSpace(string(value))
\t\t\tcontinue
\t\t}
\t\tif part.FormName() != "file" {
\t\t\tcontinue
\t\t}
\t\tpolicy, ok := uploadPolicies[field]
\t\tif !ok {
\t\t\tuploadError(w, http.StatusUnprocessableEntity, "unknown_field")
\t\t\treturn
\t\t}
\t\tname := safeFileName(part.FileName())
\t\text := ""
\t\tif i := strings.LastIndex(name, "."); i >= 0 {
\t\t\text = strings.ToLower(name[i+1:])
\t\t}
\t\tif !accepts(policy.Extensions, ext) {
\t\t\tuploadError(w, http.StatusUnsupportedMediaType, "This field accepts "+policy.Describe+".")
\t\t\treturn
\t\t}
\t\ttmp, err := os.CreateTemp("", "upload-*")
\t\tif err != nil {
\t\t\tuploadError(w, http.StatusInternalServerError, "internal_error")
\t\t\treturn
\t\t}
\t\tdefer os.Remove(tmp.Name())
\t\tdefer tmp.Close()
\t\tsize, err := io.Copy(tmp, io.LimitReader(part, policy.MaxBytes+1))
\t\tif err != nil {
\t\t\tuploadError(w, http.StatusBadRequest, "the upload could not be read")
\t\t\treturn
\t\t}
\t\tif size > policy.MaxBytes {
\t\t\tuploadError(w, http.StatusRequestEntityTooLarge, fmt.Sprintf("This field accepts files up to %d MB.", policy.MaxBytes/(1<<20)))
\t\t\treturn
\t\t}
\t\tif size == 0 {
\t\t\tuploadError(w, http.StatusUnprocessableEntity, "The file is empty.")
\t\t\treturn
\t\t}
\t\tif !uploads.Matches(ext, tmp, size) {
\t\t\tuploadError(w, http.StatusUnsupportedMediaType, fmt.Sprintf("This is not a real .%s file.", ext))
\t\t\treturn
\t\t}
\t\tstore, err := storage.Get()
\t\tif err != nil {
\t\t\tuploadError(w, http.StatusInternalServerError, "storage_not_configured")
\t\t\treturn
\t\t}
\t\tkey := policy.Folder + "/" + randomHex() + "/" + name
\t\tif _, err := tmp.Seek(0, io.SeekStart); err != nil {
\t\t\tuploadError(w, http.StatusInternalServerError, "internal_error")
\t\t\treturn
\t\t}
\t\tif err := store.Put(r.Context(), key, tmp, size, uploadMIME[ext]); err != nil {
\t\t\tuploadError(w, http.StatusBadGateway, "the file could not be stored")
\t\t\treturn
\t\t}
\t\tw.Header().Set("Content-Type", "application/json")
\t\t_ = json.NewEncoder(w).Encode(map[string]any{"key": key, "name": name, "size": size, "type": uploadMIME[ext], "url": "/files/" + key})
\t\treturn
\t}
}

// ServeFile answers with a short-lived signed link (S3) or the file (local disk).
func ServeFile(w http.ResponseWriter, r *http.Request) {
\tkey := r.PathValue("key")
\tif !fileKeyPattern.MatchString(key) {
\t\thttp.NotFound(w, r)
\t\treturn
\t}
\tname := path.Base(key)
\text := strings.ToLower(name[strings.LastIndex(name, ".")+1:])
\tcontentType := uploadMIME[ext]
\tif contentType == "" {
\t\tcontentType = "application/octet-stream"
\t}
\tdownload := r.URL.Query().Get("download")
\tinline := inlineTypes[ext] && download != "1" && download != "true"
\tstore, err := storage.Get()
\tif err != nil {
\t\tuploadError(w, http.StatusInternalServerError, "storage_not_configured")
\t\treturn
\t}
\tif !store.Exists(r.Context(), key) {
\t\thttp.NotFound(w, r)
\t\treturn
\t}
\tswitch s := store.(type) {
\tcase *storage.S3Store:
\t\turl, err := s.SignedURL(r.Context(), key, name, contentType, inline)
\t\tif err != nil {
\t\t\tuploadError(w, http.StatusBadGateway, "the file could not be reached")
\t\t\treturn
\t\t}
\t\tw.Header().Set("Cache-Control", "private, max-age=60")
\t\thttp.Redirect(w, r, url, http.StatusFound)
\tcase *storage.LocalStore:
\t\ttarget, err := s.Path(key)
\t\tif err != nil {
\t\t\thttp.NotFound(w, r)
\t\t\treturn
\t\t}
\t\tfile, err := os.Open(target)
\t\tif err != nil {
\t\t\thttp.NotFound(w, r)
\t\t\treturn
\t\t}
\t\tdefer file.Close()
\t\tinfo, err := file.Stat()
\t\tif err != nil {
\t\t\thttp.NotFound(w, r)
\t\t\treturn
\t\t}
\t\tdisposition := "attachment"
\t\tif inline {
\t\t\tdisposition = "inline"
\t\t}
\t\tw.Header().Set("Content-Type", contentType)
\t\tw.Header().Set("Content-Disposition", fmt.Sprintf(`%s; filename="%s"`, disposition, name))
\t\tw.Header().Set("X-Content-Type-Options", "nosniff")
\t\tw.Header().Set("Cache-Control", "private, max-age=300")
\t\thttp.ServeContent(w, r, name, info.ModTime(), file)
\t}
}
"""


# ── Node (Express and Hono) ──────────────────────────────────────────────────────────────────────

def node_upload_files(ir: ApplicationIR, framework: str, has_auth: bool) -> list[tuple[str, str]]:
    policies = {
        field: {"folder": p["folder"], "extensions": p["extensions"], "maxBytes": p["max_bytes"], "describe": p["describe"]}
        for field, p in upload_policies(ir).items()
    }
    receive = (
        _NODE_RECEIVE.replace("__POLICIES__", json.dumps(policies, indent=2, sort_keys=True))
        .replace("__MIME__", json.dumps(MIME, indent=2, sort_keys=True))
        .replace("__INLINE__", json.dumps(list(_INLINE)))
        .replace("__KEY__", _KEY_PATTERN.replace("/", "\\/"))
    )
    route = _NODE_ROUTE_HONO if framework == "hono" else _NODE_ROUTE_EXPRESS
    guard_import = "import { requireAuth } from '../middleware/auth.js';\n" if has_auth else ""
    route = route.replace("__AUTH_IMPORT__", guard_import).replace("__GUARD__", "requireAuth, " if has_auth else "")
    return [
        ("src/storage.ts", _NODE_STORAGE),
        ("src/uploads/checks.ts", _NODE_CHECKS),
        ("src/uploads/receive.ts", receive),
        ("src/uploads/router.ts", route),
    ]


_NODE_STORAGE = """// Where uploaded files live (generated by OmniStackAI, PC-105).
//
// S3-compatible storage when S3_BUCKET, S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY are set -
// Cloudflare R2 (S3_ENDPOINT=https://<account>.r2.cloudflarestorage.com) or AWS S3 (S3_REGION) -
// otherwise the local disk (LOCAL_STORAGE_DIR, default ./uploads). STORAGE_DRIVER=s3 or local
// forces one; STORAGE_PREFIX is this app's folder in a shared bucket. Keys are never logged.
import { createReadStream, promises as fs } from 'node:fs';
import path from 'node:path';
import { GetObjectCommand, HeadObjectCommand, PutObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';

const env = (name: string) => (process.env[name] ?? '').trim();

export class LocalStore {
  readonly kind = 'local' as const;
  constructor(private readonly root: string) {}

  /** Where a key lives on disk; a key that would leave the folder is refused. */
  path(key: string): string {
    const target = path.resolve(this.root, key);
    if (!target.startsWith(this.root + path.sep)) throw new Error('invalid_key');
    return target;
  }

  async put(key: string, file: string): Promise<void> {
    const target = this.path(key);
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.copyFile(file, target);
  }

  async exists(key: string): Promise<boolean> {
    try {
      return (await fs.stat(this.path(key))).isFile();
    } catch {
      return false;
    }
  }
}

export class S3Store {
  readonly kind = 's3' as const;
  private readonly client: S3Client;
  private readonly bucket = env('S3_BUCKET');
  private readonly prefix = env('STORAGE_PREFIX').replace(/^\\/+|\\/+$/g, '');

  constructor() {
    const endpoint = env('S3_ENDPOINT') || undefined;
    this.client = new S3Client({
      region: env('S3_REGION') || (endpoint ? 'auto' : 'us-east-1'),
      endpoint,
      forcePathStyle: Boolean(endpoint),
      credentials: { accessKeyId: env('S3_ACCESS_KEY_ID'), secretAccessKey: env('S3_SECRET_ACCESS_KEY') },
      // S3-compatible services (R2) accept checksums only where S3 requires them.
      requestChecksumCalculation: 'WHEN_REQUIRED',
      responseChecksumValidation: 'WHEN_REQUIRED',
    });
  }

  private full(key: string): string {
    return this.prefix ? `${this.prefix}/${key}` : key;
  }

  async put(key: string, file: string, size: number, contentType: string): Promise<void> {
    await this.client.send(new PutObjectCommand({
      Bucket: this.bucket, Key: this.full(key), Body: createReadStream(file), ContentLength: size, ContentType: contentType,
    }));
  }

  async exists(key: string): Promise<boolean> {
    try {
      await this.client.send(new HeadObjectCommand({ Bucket: this.bucket, Key: this.full(key) }));
      return true;
    } catch {
      return false;
    }
  }

  /** A link to the file that expires after five minutes. */
  signedUrl(key: string, filename: string, contentType: string, inline: boolean): Promise<string> {
    return getSignedUrl(this.client, new GetObjectCommand({
      Bucket: this.bucket,
      Key: this.full(key),
      ResponseContentType: contentType,
      ResponseContentDisposition: `${inline ? 'inline' : 'attachment'}; filename="${filename}"`,
    }), { expiresIn: 300 });
  }
}

export type Store = LocalStore | S3Store;
let store: Store | null = null;

export async function getStore(): Promise<Store> {
  if (store) return store;
  const driver = (env('STORAGE_DRIVER') || 'auto').toLowerCase();
  const ready = Boolean(env('S3_BUCKET') && env('S3_ACCESS_KEY_ID') && env('S3_SECRET_ACCESS_KEY'));
  if (driver === 's3' || (driver === 'auto' && ready)) {
    if (!ready) throw new Error('storage_not_configured: S3_BUCKET, S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY');
    store = new S3Store();
  } else {
    const root = path.resolve(env('LOCAL_STORAGE_DIR') || './uploads');
    await fs.mkdir(root, { recursive: true });
    store = new LocalStore(root);
  }
  return store;
}
"""

_NODE_CHECKS = """// Is this file what its name says? (generated by OmniStackAI, PC-105)
//
// The name and the browser's declared type are both chosen by the sender, so neither is trusted:
// the first bytes are, and for Office and OpenDocument files the parts inside the archive.
import { promises as fs } from 'node:fs';

const OLE = Buffer.from([0xd0, 0xcf, 0x11, 0xe0, 0xa1, 0xb1, 0x1a, 0xe1]);
const FTYP_IMAGE: Record<string, string[]> = {
  heic: ['heic', 'heix', 'mif1', 'msf1', 'hevc', 'heim', 'heis'],
  avif: ['avif', 'avis'],
};
const OFFICE_PART: Record<string, string> = { docx: 'word/document.xml', xlsx: 'xl/workbook.xml', pptx: 'ppt/presentation.xml' };
const OPEN_DOCUMENT: Record<string, string> = {
  odt: 'application/vnd.oasis.opendocument.text',
  ods: 'application/vnd.oasis.opendocument.spreadsheet',
  odp: 'application/vnd.oasis.opendocument.presentation',
};

type Entry = { method: number; size: number; offset: number };

/** The entries of a zip archive, from its central directory (null when it is not a zip). */
function zipEntries(buf: Buffer): Map<string, Entry> | null {
  let end = -1;
  for (let i = buf.length - 22; i >= Math.max(0, buf.length - 65557); i--) {
    if (buf.readUInt32LE(i) === 0x06054b50) { end = i; break; }
  }
  if (end < 0) return null;
  const count = buf.readUInt16LE(end + 10);
  let at = buf.readUInt32LE(end + 16);
  const entries = new Map<string, Entry>();
  for (let n = 0; n < count; n++) {
    if (at + 46 > buf.length || buf.readUInt32LE(at) !== 0x02014b50) return null;
    const nameLength = buf.readUInt16LE(at + 28);
    entries.set(buf.toString('utf8', at + 46, at + 46 + nameLength), {
      method: buf.readUInt16LE(at + 10), size: buf.readUInt32LE(at + 20), offset: buf.readUInt32LE(at + 42),
    });
    at += 46 + nameLength + buf.readUInt16LE(at + 30) + buf.readUInt16LE(at + 32);
  }
  return entries;
}

/** A stored (uncompressed) entry's bytes - how OpenDocument keeps its "mimetype". */
function storedEntry(buf: Buffer, entry: Entry): Buffer | null {
  if (entry.method !== 0 || buf.readUInt32LE(entry.offset) !== 0x04034b50) return null;
  const start = entry.offset + 30 + buf.readUInt16LE(entry.offset + 26) + buf.readUInt16LE(entry.offset + 28);
  return buf.subarray(start, start + entry.size);
}

function isText(head: Buffer): boolean {
  if (head.includes(0)) return false;
  // A multi-byte character cut at the end of the sample is still text.
  for (let cut = 0; cut <= 3 && cut <= head.length; cut++) {
    try {
      new TextDecoder('utf-8', { fatal: true }).decode(head.subarray(0, head.length - cut));
      return true;
    } catch {
      // try a shorter sample
    }
  }
  return false;
}

export async function matches(extension: string, file: string): Promise<boolean> {
  const handle = await fs.open(file, 'r');
  const sample = Buffer.alloc(8192);
  const { bytesRead } = await handle.read(sample, 0, 8192, 0);
  await handle.close();
  const head = sample.subarray(0, bytesRead);
  const at = (from: number, to: number) => (head.length >= to ? head.toString('latin1', from, to) : '');
  const has = (prefix: Buffer | string) => head.subarray(0, Buffer.from(prefix as never).length).equals(Buffer.from(prefix as never));
  const ext = extension.toLowerCase();
  switch (ext) {
    case 'jpg': case 'jpeg': return has(Buffer.from([0xff, 0xd8, 0xff]));
    case 'png': return has(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]));
    case 'gif': return at(0, 6) === 'GIF87a' || at(0, 6) === 'GIF89a';
    case 'webp': return at(0, 4) === 'RIFF' && at(8, 12) === 'WEBP';
    case 'heic': case 'avif': return at(4, 8) === 'ftyp' && FTYP_IMAGE[ext].includes(at(8, 12));
    case 'mp4': case 'mov': case 'm4a':
      return at(4, 8) === 'ftyp' && ![...FTYP_IMAGE.heic, ...FTYP_IMAGE.avif].includes(at(8, 12));
    case 'webm': return has(Buffer.from([0x1a, 0x45, 0xdf, 0xa3]));
    case 'ogg': return has('OggS');
    case 'mp3': return has('ID3') || (head.length > 1 && head[0] === 0xff && (head[1] & 0xe0) === 0xe0);
    case 'wav': return at(0, 4) === 'RIFF' && at(8, 12) === 'WAVE';
    case 'pdf': return head.subarray(0, 1024).includes('%PDF-');
    case 'doc': case 'xls': case 'ppt': return has(OLE);
    case 'rtf': return has('{\\\\rtf');
    case 'txt': case 'csv': return isText(head);
    case 'dcm': return at(128, 132) === 'DICM';
    case 'docx': case 'xlsx': case 'pptx': case 'odt': case 'ods': case 'odp': case 'zip': {
      if (!has('PK')) return false;
      const whole = await fs.readFile(file);
      const entries = zipEntries(whole);
      if (!entries) return false;
      // Macros: a .docx never carries them, a renamed .docm does.
      if ([...entries.keys()].some((name) => name.toLowerCase().endsWith('vbaproject.bin'))) return false;
      if (OFFICE_PART[ext]) return entries.has(OFFICE_PART[ext]);
      if (OPEN_DOCUMENT[ext]) {
        const mimetype = entries.get('mimetype');
        const stored = mimetype ? storedEntry(whole, mimetype) : null;
        return stored !== null && stored.toString('utf8').trim() === OPEN_DOCUMENT[ext];
      }
      return true;
    }
    default: return false;
  }
}
"""

_NODE_RECEIVE = """// Uploads and downloads, shared by the router (generated by OmniStackAI, PC-105).
//
// POST /uploads takes one file for one field ("Entity.field"), checks it against that field's
// policy - extension, real content and size - and stores it. GET /files/<key> serves it: a
// short-lived signed link from S3-compatible storage, or the file itself from the local disk.
import busboy from 'busboy';
import { randomBytes } from 'node:crypto';
import { createWriteStream, promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type { Readable } from 'node:stream';
import { getStore } from '../storage.js';
import { matches } from './checks.js';

type Policy = { folder: string; extensions: string[]; maxBytes: number; describe: string };

/** Per field: the types and size it accepts (from the plan). */
export const POLICIES: Record<string, Policy> = __POLICIES__;

export const MIME: Record<string, string> = __MIME__;

const INLINE = new Set<string>(__INLINE__);
const KEY = /__KEY__/;

export type Answer = { status: number; body: Record<string, unknown> };

function safeName(filename: string | undefined): string {
  const name = (filename || 'file').replace(/\\\\/g, '/').split('/').pop() || 'file';
  const dot = name.lastIndexOf('.');
  const ext = dot >= 0 ? name.slice(dot + 1).toLowerCase() : '';
  const stem = (dot >= 0 ? name.slice(0, dot) : name).replace(/[^A-Za-z0-9._-]+/g, '-').replace(/^[-._]+|[-._]+$/g, '') || 'file';
  return ext ? `${stem.slice(0, 80)}.${ext}` : stem.slice(0, 80);
}

const refuse = (status: number, detail: string): Answer => ({ status, body: { detail } });

/** Receive one upload from a multipart body. The field must come before the file (Uppy sends it so). */
export function receiveUpload(headers: Record<string, string | string[] | undefined>, body: Readable): Promise<Answer> {
  return new Promise((resolve) => {
    let settled = false;
    let pending: Promise<Answer> | null = null;
    const finish = (answer: Answer | Promise<Answer>) => {
      if (settled) return;
      settled = true;
      Promise.resolve(answer).then(resolve, () => resolve(refuse(500, 'internal_error')));
    };
    let parser: ReturnType<typeof busboy>;
    try {
      parser = busboy({ headers: headers as Record<string, string>, limits: { files: 1, fields: 5 } });
    } catch {
      finish(refuse(400, 'send the file as multipart/form-data'));
      return;
    }
    let field = '';
    parser.on('field', (name, value) => { if (name === 'field') field = String(value).trim().slice(0, 200); });
    parser.on('file', (name, stream, info) => {
      if (name !== 'file' || settled) { stream.resume(); return; }
      const policy = POLICIES[field];
      if (!policy) { stream.resume(); finish(refuse(422, 'unknown_field')); return; }
      const filename = safeName(info.filename);
      const ext = filename.includes('.') ? filename.split('.').pop()!.toLowerCase() : '';
      if (!policy.extensions.includes(ext)) {
        stream.resume();
        finish(refuse(415, `This field accepts ${policy.describe}.`));
        return;
      }
      const tmp = path.join(os.tmpdir(), `upload-${randomBytes(12).toString('hex')}`);
      const out = createWriteStream(tmp);
      let size = 0;
      let tooLarge = false;
      stream.on('data', (chunk: Buffer) => {
        size += chunk.length;
        if (size > policy.maxBytes && !tooLarge) {
          tooLarge = true;
          stream.unpipe(out);
          stream.resume();
          out.destroy();
        }
      });
      stream.pipe(out);
      pending = new Promise<Answer>((done) => {
        const complete = async () => {
          try {
            if (tooLarge) return done(refuse(413, `This field accepts files up to ${Math.floor(policy.maxBytes / 1048576)} MB.`));
            if (size === 0) return done(refuse(422, 'The file is empty.'));
            if (!(await matches(ext, tmp))) return done(refuse(415, `This is not a real .${ext} file.`));
            const key = `${policy.folder}/${randomBytes(16).toString('hex')}/${filename}`;
            const store = await getStore();
            await store.put(key, tmp, size, MIME[ext]);
            done({ status: 200, body: { key, name: filename, size, type: MIME[ext], url: `/files/${key}` } });
          } catch {
            done(refuse(502, 'the file could not be stored'));
          } finally {
            fs.rm(tmp, { force: true }).catch(() => undefined);
          }
        };
        stream.on('end', () => { if (tooLarge) void complete(); else out.on('close', () => void complete()); });
        out.on('error', () => void complete());
      });
    });
    parser.on('close', () => finish(pending ?? refuse(422, 'no file was sent')));
    parser.on('error', () => finish(refuse(400, 'the upload could not be read')));
    body.pipe(parser);
  });
}

export type FileAnswer =
  | { status: 404 | 500 | 502 }
  | { status: 302; location: string }
  | { status: 200; path: string; headers: Record<string, string> };

/** What GET /files/<key> answers. */
export async function fileAnswer(key: string, download: string | undefined): Promise<FileAnswer> {
  if (!KEY.test(key)) return { status: 404 };
  const name = key.split('/').pop()!;
  const ext = name.split('.').pop()!.toLowerCase();
  const contentType = MIME[ext] ?? 'application/octet-stream';
  const inline = INLINE.has(ext) && download !== '1' && download !== 'true';
  let store;
  try {
    store = await getStore();
  } catch {
    return { status: 500 };
  }
  if (!(await store.exists(key))) return { status: 404 };
  if (store.kind === 's3') {
    try {
      return { status: 302, location: await store.signedUrl(key, name, contentType, inline) };
    } catch {
      return { status: 502 };
    }
  }
  return {
    status: 200,
    path: store.path(key),
    headers: {
      'Content-Type': contentType,
      'Content-Disposition': `${inline ? 'inline' : 'attachment'}; filename="${name}"`,
      'X-Content-Type-Options': 'nosniff',
      'Cache-Control': 'private, max-age=300',
    },
  };
}
"""

_NODE_ROUTE_EXPRESS = """// Uploads and downloads (generated by OmniStackAI, PC-105).
import { createReadStream } from 'node:fs';
import { Router, Request, Response } from 'express';
__AUTH_IMPORT__import { fileAnswer, receiveUpload } from './receive.js';

export const router = Router();

router.post('/uploads', __GUARD__async (req: Request, res: Response) => {
  const answer = await receiveUpload(req.headers, req);
  res.status(answer.status).json(answer.body);
});

router.get(/^\\/files\\/(.+)$/, async (req: Request, res: Response) => {
  const key = decodeURIComponent(String((req.params as Record<string, string>)[0] ?? ''));
  const answer = await fileAnswer(key, typeof req.query.download === 'string' ? req.query.download : undefined);
  if (answer.status === 302) {
    res.set('Cache-Control', 'private, max-age=60');
    return res.redirect(302, answer.location);
  }
  if (answer.status !== 200) return res.status(answer.status).json({ detail: answer.status === 404 ? 'not_found' : 'unavailable' });
  res.set(answer.headers);
  createReadStream(answer.path).pipe(res);
});
"""

_NODE_ROUTE_HONO = """// Uploads and downloads (generated by OmniStackAI, PC-105).
import { createReadStream } from 'node:fs';
import { Readable } from 'node:stream';
import { Hono } from 'hono';
__AUTH_IMPORT__import { fileAnswer, receiveUpload } from './receive.js';

export const router = new Hono();

router.post('/uploads', __GUARD__async (c) => {
  const body = c.req.raw.body ? Readable.fromWeb(c.req.raw.body as never) : Readable.from([]);
  const answer = await receiveUpload(Object.fromEntries(c.req.raw.headers.entries()), body);
  return c.json(answer.body, answer.status as never);
});

router.get('/files/*', async (c) => {
  const key = decodeURIComponent(c.req.path.replace(/^\\/files\\//, ''));
  const answer = await fileAnswer(key, c.req.query('download'));
  if (answer.status === 302) return c.redirect(answer.location, 302);
  if (answer.status !== 200) return c.json({ detail: answer.status === 404 ? 'not_found' : 'unavailable' }, answer.status as never);
  return new Response(Readable.toWeb(createReadStream(answer.path)) as never, { headers: answer.headers });
});
"""
