"""PC-102: file uploads in generated apps - storage, content checks, the upload window, cloud sources.

A file goes from the upload window (Uppy) to the app's API, which streams it to a temporary file
with a size cap, checks its real content against the field's policy (the first bytes, and for
Office files the parts inside the archive - never only the name), and stores it:

- S3-compatible storage when ``S3_BUCKET``/``S3_ACCESS_KEY_ID``/``S3_SECRET_ACCESS_KEY`` are set
  (Cloudflare R2 with ``S3_ENDPOINT``, or AWS S3 with ``S3_REGION``);
- otherwise the local disk (``LOCAL_STORAGE_DIR``), so an app runs with no account at all.

Files are private. ``GET /files/<key>`` answers with a short-lived signed link (S3) or the file
(local disk); keys carry a random 128-bit part, so a key is the permission to read the file.

The platform chooses the store from its own ``.env`` (``OMNISTACKAI_STORAGE_TARGET``) and passes
the generic ``S3_*`` settings to the app, so moving to production changes keys, not code
(``localrun`` and ``publish``). Cloud drives (Google Drive, Dropbox, OneDrive, Box) and web links
come through a self-hosted Uppy Companion, generated here too and started only when configured.
"""

from __future__ import annotations

import json

from ..application_ir import ApplicationIR
from .schema_sql import table_name
from .upload_policy import MIME, attachment_fields

#: The upload window and its sources, pinned together (Uppy 6, React 18 compatible).
UPLOAD_LIBRARIES: dict[str, str] = {
    "@uppy/core": "6.1.0",
    "@uppy/react": "6.0.0",
    "@uppy/dashboard": "6.0.0",
    "@uppy/xhr-upload": "6.0.0",
    "@uppy/webcam": "6.0.0",
    "@uppy/url": "6.0.0",
    "@uppy/google-drive": "6.0.0",
    "@uppy/dropbox": "6.0.0",
    "@uppy/onedrive": "6.0.0",
    "@uppy/box": "5.0.0",
}

PYTHON_UPLOAD_REQUIREMENTS = ("python-multipart==0.0.12", "boto3==1.35.36")


def field_key(entity_name: str, field_name: str) -> str:
    """How a form names a field to the API: "Product.photos"."""
    return f"{entity_name}.{field_name}"


def upload_policies(ir: ApplicationIR) -> dict[str, dict]:
    return {
        field_key(entity.name, field.name): {
            "folder": f"{table_name(entity.name)}/{field.name}",
            "extensions": list(policy.extensions),
            "max_bytes": policy.max_size_mb * 1024 * 1024,
            "max_files": policy.max_files,
            "describe": policy.describe(),
        }
        for entity, field, policy in attachment_fields(ir)
    }


# ── Python (FastAPI) ────────────────────────────────────────────────────────────────────────────


def python_upload_files(ir: ApplicationIR, has_auth: bool) -> list[tuple[str, str]]:
    policies = json.dumps(upload_policies(ir), indent=4, sort_keys=True)
    router = (
        _PY_ROUTER.replace("__POLICIES__", policies)
        .replace("__MIME__", json.dumps(MIME, indent=4, sort_keys=True))
        .replace("__AUTH_IMPORT__", "from fastapi import Depends\n\nfrom app.auth import require_auth\n" if has_auth else "")
        .replace("__GUARD__", ", dependencies=[Depends(require_auth)]" if has_auth else "")
    )
    return [
        ("app/storage.py", _PY_STORAGE),
        ("app/file_checks.py", _PY_CHECKS),
        ("app/routers/uploads.py", router),
    ]


_PY_STORAGE = '''"""Where uploaded files live (generated by OmniStackAI, PC-102).

S3-compatible storage when S3_BUCKET, S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY are set -
Cloudflare R2 (S3_ENDPOINT=https://<account>.r2.cloudflarestorage.com) or AWS S3 (S3_REGION) -
otherwise the local disk (LOCAL_STORAGE_DIR, default ./uploads). STORAGE_DRIVER=s3 or local forces
one. Keys are never logged.
"""
from __future__ import annotations

import os
import shutil
from pathlib import Path
from typing import BinaryIO


def _env(name: str) -> str:
    return os.environ.get(name, "").strip()


class LocalStore:
    kind = "local"

    def __init__(self, root: str) -> None:
        self.root = Path(root).expanduser().resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def path(self, key: str) -> Path:
        target = (self.root / key).resolve()
        if self.root not in target.parents:
            raise ValueError("invalid_key")
        return target

    def put(self, key: str, data: BinaryIO, content_type: str) -> None:
        target = self.path(key)
        target.parent.mkdir(parents=True, exist_ok=True)
        with open(target, "wb") as out:
            shutil.copyfileobj(data, out)

    def exists(self, key: str) -> bool:
        return self.path(key).is_file()


class S3Store:
    kind = "s3"

    def __init__(self) -> None:
        import boto3
        from botocore.config import Config

        endpoint = _env("S3_ENDPOINT") or None
        self.bucket = _env("S3_BUCKET")
        # The app's folder in a shared bucket (set by the platform; empty for a bucket of its own).
        self.prefix = _env("STORAGE_PREFIX").strip("/")
        self.client = boto3.client(
            "s3",
            endpoint_url=endpoint,
            region_name=_env("S3_REGION") or ("auto" if endpoint else "us-east-1"),
            aws_access_key_id=_env("S3_ACCESS_KEY_ID"),
            aws_secret_access_key=_env("S3_SECRET_ACCESS_KEY"),
            config=Config(signature_version="s3v4", retries={"max_attempts": 3, "mode": "standard"}),
        )

    def _key(self, key: str) -> str:
        return f"{self.prefix}/{key}" if self.prefix else key

    def put(self, key: str, data: BinaryIO, content_type: str) -> None:
        self.client.upload_fileobj(data, self.bucket, self._key(key), ExtraArgs={"ContentType": content_type})

    def exists(self, key: str) -> bool:
        try:
            self.client.head_object(Bucket=self.bucket, Key=self._key(key))
            return True
        except Exception:  # noqa: BLE001 - missing and forbidden both mean "cannot serve it"
            return False

    def signed_url(self, key: str, filename: str, content_type: str, inline: bool, seconds: int = 300) -> str:
        disposition = "inline" if inline else "attachment"
        return self.client.generate_presigned_url(
            "get_object",
            Params={
                "Bucket": self.bucket,
                "Key": self._key(key),
                "ResponseContentType": content_type,
                "ResponseContentDisposition": f\'{disposition}; filename="{filename}"\',
            },
            ExpiresIn=seconds,
        )


_store: LocalStore | S3Store | None = None


def get_store() -> LocalStore | S3Store:
    global _store
    if _store is None:
        driver = (_env("STORAGE_DRIVER") or "auto").lower()
        s3_ready = all(_env(name) for name in ("S3_BUCKET", "S3_ACCESS_KEY_ID", "S3_SECRET_ACCESS_KEY"))
        if driver == "s3" or (driver == "auto" and s3_ready):
            if not s3_ready:
                raise RuntimeError("storage_not_configured: S3_BUCKET, S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY")
            _store = S3Store()
        else:
            _store = LocalStore(_env("LOCAL_STORAGE_DIR") or "./uploads")
    return _store
'''


_PY_CHECKS = '''"""Is this file what its name says? (generated by OmniStackAI, PC-102)

The name and the browser's declared type are both chosen by the sender, so neither is trusted:
the first bytes are, and for Office and OpenDocument files the parts inside the archive.
"""
from __future__ import annotations

import zipfile
from typing import BinaryIO

_OLE = bytes.fromhex("d0cf11e0a1b11ae1")
_FTYP_IMAGE = {"heic": {b"heic", b"heix", b"mif1", b"msf1", b"hevc", b"heim", b"heis"}, "avif": {b"avif", b"avis"}}
_OPEN_DOCUMENT = {
    "odt": b"application/vnd.oasis.opendocument.text",
    "ods": b"application/vnd.oasis.opendocument.spreadsheet",
    "odp": b"application/vnd.oasis.opendocument.presentation",
}
_OFFICE_PART = {"docx": "word/document.xml", "xlsx": "xl/workbook.xml", "pptx": "ppt/presentation.xml"}


def _zip_names(data: BinaryIO) -> set[str] | None:
    try:
        data.seek(0)
        with zipfile.ZipFile(data) as archive:
            return set(archive.namelist())
    except (zipfile.BadZipFile, OSError, ValueError):
        return None


def _text(head: bytes) -> bool:
    if b"\\x00" in head:
        return False
    try:
        head.decode("utf-8")
        return True
    except UnicodeDecodeError as error:
        # A multi-byte character cut at the end of the sample is still text.
        return error.start >= len(head) - 3


def matches(extension: str, data: BinaryIO) -> bool:
    data.seek(0)
    head = data.read(8192)
    data.seek(0)
    ext = extension.lower()
    brand = head[8:12]
    if ext in ("jpg", "jpeg"):
        return head.startswith(b"\\xff\\xd8\\xff")
    if ext == "png":
        return head.startswith(b"\\x89PNG\\r\\n\\x1a\\n")
    if ext == "gif":
        return head[:6] in (b"GIF87a", b"GIF89a")
    if ext == "webp":
        return head[:4] == b"RIFF" and head[8:12] == b"WEBP"
    if ext in _FTYP_IMAGE:
        return head[4:8] == b"ftyp" and brand in _FTYP_IMAGE[ext]
    if ext in ("mp4", "mov", "m4a"):
        images = set().union(*_FTYP_IMAGE.values())
        return head[4:8] == b"ftyp" and brand not in images
    if ext == "webm":
        return head.startswith(b"\\x1a\\x45\\xdf\\xa3")
    if ext == "ogg":
        return head.startswith(b"OggS")
    if ext == "mp3":
        return head.startswith(b"ID3") or (len(head) > 1 and head[0] == 0xFF and (head[1] & 0xE0) == 0xE0)
    if ext == "wav":
        return head[:4] == b"RIFF" and head[8:12] == b"WAVE"
    if ext == "pdf":
        return b"%PDF-" in head[:1024]
    if ext in ("doc", "xls", "ppt"):
        return head.startswith(_OLE)
    if ext == "rtf":
        return head.startswith(b"{\\\\rtf")
    if ext in ("txt", "csv"):
        return _text(head)
    if ext == "dcm":
        return head[128:132] == b"DICM"
    if ext in _OFFICE_PART or ext in _OPEN_DOCUMENT or ext == "zip":
        if not head.startswith(b"PK"):
            return False
        names = _zip_names(data)
        data.seek(0)
        if names is None:
            return False
        if any(name.lower().endswith("vbaproject.bin") for name in names):
            return False  # macros: a .docx never carries them, a renamed .docm does
        if ext in _OFFICE_PART:
            return _OFFICE_PART[ext] in names
        if ext in _OPEN_DOCUMENT:
            try:
                data.seek(0)
                with zipfile.ZipFile(data) as archive:
                    return archive.read("mimetype").strip() == _OPEN_DOCUMENT[ext]
            except (KeyError, zipfile.BadZipFile, OSError):
                return False
            finally:
                data.seek(0)
        return True
    return False
'''


_PY_ROUTER = '''"""Uploads and downloads (generated by OmniStackAI, PC-102).

POST /uploads takes one file for one field ("Entity.field"), checks it against that field's
policy - extension, real content and size - and stores it. GET /files/<key> serves it: a
short-lived signed link from S3-compatible storage, or the file itself from the local disk.
"""
from __future__ import annotations

import re
import tempfile
import uuid

from fastapi import APIRouter, File, Form, HTTPException, Query, UploadFile
from fastapi.concurrency import run_in_threadpool
from fastapi.responses import FileResponse, RedirectResponse
__AUTH_IMPORT__
from app.file_checks import matches
from app.storage import get_store

router = APIRouter(tags=["uploads"])

# Per field: the types, size and count it accepts (from the plan; see the app's README).
POLICIES: dict[str, dict] = __POLICIES__

MIME: dict[str, str] = __MIME__

_CHUNK = 1024 * 1024
_KEY = re.compile(r"^[a-z0-9_]+/[a-z0-9_]+/[0-9a-f]{32}/[A-Za-z0-9._-]{1,120}$")
_INLINE = {"jpg", "jpeg", "png", "webp", "gif", "avif", "pdf", "mp3", "wav", "m4a", "ogg", "mp4", "webm", "mov", "txt"}


def _safe_name(filename: str | None) -> str:
    name = (filename or "file").replace("\\\\", "/").rsplit("/", 1)[-1]
    stem, dot, ext = name.rpartition(".")
    stem = re.sub(r"[^A-Za-z0-9._-]+", "-", stem if dot else name).strip("-._") or "file"
    return f"{stem[:80]}.{ext.lower()}" if dot and ext else stem[:80]


@router.post("/uploads"__GUARD__)
async def upload_file(field: str = Form(...), file: UploadFile = File(...)) -> dict:
    policy = POLICIES.get(field)
    if policy is None:
        raise HTTPException(status_code=422, detail="unknown_field")
    name = _safe_name(file.filename)
    extension = name.rpartition(".")[2].lower() if "." in name else ""
    if extension not in policy["extensions"]:
        raise HTTPException(status_code=415, detail=f"This field accepts {policy['describe']}.")
    spooled = tempfile.SpooledTemporaryFile(max_size=8 * _CHUNK)
    size = 0
    try:
        while chunk := await file.read(_CHUNK):
            size += len(chunk)
            if size > policy["max_bytes"]:
                raise HTTPException(status_code=413, detail=f"This field accepts files up to {policy['max_bytes'] // _CHUNK} MB.")
            spooled.write(chunk)
        if size == 0:
            raise HTTPException(status_code=422, detail="The file is empty.")
        if not matches(extension, spooled):
            raise HTTPException(status_code=415, detail=f"This is not a real .{extension} file.")
        key = f"{policy['folder']}/{uuid.uuid4().hex}/{name}"
        spooled.seek(0)
        await run_in_threadpool(get_store().put, key, spooled, MIME[extension])
    finally:
        spooled.close()
    return {"key": key, "name": name, "size": size, "type": MIME[extension], "url": f"/files/{key}"}


@router.get("/files/{key:path}")
async def get_file(key: str, download: bool = Query(default=False)):
    if not _KEY.match(key):
        raise HTTPException(status_code=404, detail="not_found")
    name = key.rsplit("/", 1)[-1]
    extension = name.rpartition(".")[2].lower()
    content_type = MIME.get(extension, "application/octet-stream")
    inline = extension in _INLINE and not download
    store = get_store()
    if not await run_in_threadpool(store.exists, key):
        raise HTTPException(status_code=404, detail="not_found")
    if store.kind == "s3":
        url = await run_in_threadpool(store.signed_url, key, name, content_type, inline)
        return RedirectResponse(url, status_code=302, headers={"Cache-Control": "private, max-age=60"})
    return FileResponse(
        store.path(key),
        media_type=content_type,
        filename=name,
        content_disposition_type="inline" if inline else "attachment",
        headers={"X-Content-Type-Options": "nosniff", "Cache-Control": "private, max-age=300"},
    )
'''


# ── The upload window (web and admin apps) ──────────────────────────────────────────────────────

FILE_UPLOADER = r'''"use client";

// Generated by OmniStackAI (PC-102): the upload window. Files come from the device, the camera, a
// web link, or a cloud drive (Google Drive, Dropbox, OneDrive, Box) when the app has their keys;
// the field's rules decide the types, size and count, and the API checks the real content again.
import { useEffect, useState } from "react";
import Uppy, { type UppyFile } from "@uppy/core";
import Dashboard from "@uppy/react/dashboard";
import XHRUpload from "@uppy/xhr-upload";
import Webcam from "@uppy/webcam";
import Url from "@uppy/url";
import GoogleDrive from "@uppy/google-drive";
import Dropbox from "@uppy/dropbox";
import OneDrive from "@uppy/onedrive";
import Box from "@uppy/box";
import "@uppy/core/css/style.min.css";
import "@uppy/dashboard/css/style.min.css";
import "@uppy/webcam/css/style.min.css";
import "@uppy/url/css/style.min.css";
import { Download, FileText, Paperclip, X } from "lucide-react";

const API = process.env.NEXT_PUBLIC_API_URL || "";
const COMPANION = process.env.NEXT_PUBLIC_COMPANION_URL || "";
// Where Companion (a server) posts files it fetched from a drive: it cannot use a relative path.
const REMOTE_ENDPOINT = process.env.NEXT_PUBLIC_REMOTE_UPLOAD_ENDPOINT || "";
const SOURCES = new Set((process.env.NEXT_PUBLIC_UPLOAD_SOURCES || "").split(",").map((s) => s.trim()).filter(Boolean));

type Meta = { field: string };
type Body = { key?: string; name?: string };

/** The keys a field holds: one key, or a JSON list of keys for a field that takes several. */
export function fileKeys(value: unknown): string[] {
  if (typeof value !== "string" || !value) return [];
  if (value.startsWith("[")) {
    try {
      const list = JSON.parse(value);
      return Array.isArray(list) ? list.filter((k): k is string => typeof k === "string") : [];
    } catch {
      return [];
    }
  }
  return [value];
}

export function fileName(key: string): string {
  return key.split("/").pop() || key;
}

/** A link that opens the file (a stored key) or the address itself (an older full URL). */
export function fileUrl(key: string, download = false): string {
  if (/^https?:\/\//.test(key)) return key;
  const path = key.split("/").map(encodeURIComponent).join("/");
  return `${API}/files/${path}${download ? "?download=1" : ""}`;
}

const IMAGE = /\.(jpe?g|png|webp|gif|avif)$/i;

export function FileList({ value, onRemove, compact = false }: { value: unknown; onRemove?: (key: string) => void; compact?: boolean }) {
  const keys = fileKeys(value);
  if (keys.length === 0) return compact ? <span className="text-muted-foreground">—</span> : null;
  return (
    <ul className={compact ? "flex flex-wrap gap-1.5" : "mt-2 space-y-1.5"}>
      {keys.map((key) => (
        <li key={key} className="flex items-center gap-2 rounded-md border bg-card px-2 py-1 text-sm">
          {IMAGE.test(key) ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img src={fileUrl(key)} alt="" className="h-7 w-7 rounded object-cover" />
          ) : (
            <FileText className="h-4 w-4 shrink-0 text-muted-foreground" aria-hidden />
          )}
          <a href={fileUrl(key)} target="_blank" rel="noreferrer" className="max-w-[16rem] truncate text-primary hover:underline">
            {fileName(key).replace(/^[0-9a-f]{32}-/, "")}
          </a>
          {!compact && (
            <a href={fileUrl(key, true)} className="text-muted-foreground hover:text-foreground" aria-label={`Download ${fileName(key)}`}>
              <Download className="h-3.5 w-3.5" aria-hidden />
            </a>
          )}
          {onRemove && (
            <button type="button" onClick={() => onRemove(key)} className="text-muted-foreground hover:text-destructive" aria-label={`Remove ${fileName(key)}`}>
              <X className="h-3.5 w-3.5" aria-hidden />
            </button>
          )}
        </li>
      ))}
    </ul>
  );
}

export interface FileUploaderProps {
  /** "Entity.field", as the API's upload rules name it. */
  field: string;
  /** Extensions the field accepts, e.g. ["pdf", "docx"]. */
  accept: string[];
  maxSizeMb: number;
  maxFiles: number;
  /** Plain words for the rules: "PDF, DOC or DOCX, up to 10 MB". */
  hint?: string;
  value: unknown;
  onChange: (value: string) => void;
  disabled?: boolean;
}

export function FileUploader({ field, accept, maxSizeMb, maxFiles, hint, value, onChange, disabled }: FileUploaderProps) {
  const keys = fileKeys(value);
  const [open, setOpen] = useState(false);
  const store = (next: string[]) => onChange(maxFiles > 1 ? JSON.stringify(next) : next[0] ?? "");

  // One instance for the component's life (useState, not useMemo: React may drop a memo). It is
  // not destroyed on unmount: React's development double-mount would destroy it before it drew.
  const [uppy] = useState(() => {
    const instance = new Uppy<Meta, Body>({
      meta: { field },
      autoProceed: false,
      restrictions: {
        allowedFileTypes: accept.map((ext) => `.${ext}`),
        maxFileSize: maxSizeMb * 1024 * 1024,
        maxNumberOfFiles: maxFiles,
      },
    });
    instance.use(XHRUpload, {
      endpoint: (file) => (!Array.isArray(file) && file.isRemote && REMOTE_ENDPOINT ? REMOTE_ENDPOINT : `${API}/uploads`),
      fieldName: "file",
      formData: true,
      allowedMetaFields: ["field"],
      headers: (): Record<string, string> => {
        const token = typeof localStorage !== "undefined" ? localStorage.getItem("auth_token") : null;
        return token ? { Authorization: `Bearer ${token}` } : {};
      },
      // A refusal (wrong type, too large) will not change on a retry; a dropped connection may.
      shouldRetry: (xhr) => xhr.status === 0 || xhr.status >= 500,
      // Show the API's own reason ("This is not a real .pdf file.") rather than "Upload failed".
      onAfterResponse: (xhr) => {
        if (xhr.status < 400) return;
        let detail = `The upload was refused (${xhr.status}).`;
        try {
          const body = JSON.parse(xhr.responseText || "{}");
          if (typeof body.detail === "string") detail = body.detail;
        } catch {
          // not JSON: keep the generic words
        }
        throw new Error(detail);
      },
    });
    instance.on("upload-error", (_file, error) => instance.info(error?.message || "The upload failed.", "error", 8000));
    if (SOURCES.has("camera")) instance.use(Webcam, { modes: ["picture", "video-audio"] });
    if (COMPANION) {
      if (SOURCES.has("url")) instance.use(Url, { companionUrl: COMPANION });
      if (SOURCES.has("google-drive")) instance.use(GoogleDrive, { companionUrl: COMPANION });
      if (SOURCES.has("dropbox")) instance.use(Dropbox, { companionUrl: COMPANION });
      if (SOURCES.has("onedrive")) instance.use(OneDrive, { companionUrl: COMPANION });
      if (SOURCES.has("box")) instance.use(Box, { companionUrl: COMPANION });
    }
    return instance;
  });

  useEffect(() => () => uppy.cancelAll(), [uppy]);

  useEffect(() => {
    const done = (result: { successful?: UppyFile<Meta, Body>[] }) => {
      const added = (result.successful ?? []).map((f) => f.response?.body?.key).filter((k): k is string => Boolean(k));
      if (added.length === 0) return;
      store(maxFiles > 1 ? [...keys, ...added].slice(0, maxFiles) : added.slice(-1));
      uppy.clear();
      setOpen(false);
    };
    uppy.on("complete", done);
    return () => { uppy.off("complete", done); };
  });

  useEffect(() => {
    uppy.setOptions({ restrictions: { allowedFileTypes: accept.map((ext) => `.${ext}`), maxFileSize: maxSizeMb * 1024 * 1024, maxNumberOfFiles: Math.max(1, maxFiles > 1 ? maxFiles - keys.length : 1) } });
  }, [uppy, accept, maxSizeMb, maxFiles, keys.length]);

  const full = maxFiles > 1 && keys.length >= maxFiles;
  return (
    <div>
      <button
        type="button"
        disabled={disabled || full}
        onClick={() => setOpen(true)}
        className="flex w-full items-center justify-center gap-2 rounded-md border border-dashed bg-background px-3 py-4 text-sm text-muted-foreground transition-colors hover:border-primary hover:text-primary disabled:opacity-50"
      >
        <Paperclip className="h-4 w-4" aria-hidden />
        {keys.length > 0 && maxFiles === 1 ? "Replace file" : full ? `${maxFiles} files attached` : maxFiles > 1 ? "Add files" : "Choose a file"}
      </button>
      {hint && <p className="mt-1 text-xs text-muted-foreground">{hint}</p>}
      <FileList value={value} onRemove={disabled ? undefined : (key) => store(keys.filter((k) => k !== key))} />
      {/* Inline, not a modal: forms often sit in a dialog or drawer, which blocks everything outside it. */}
      {open && (
        <div className="mt-2 overflow-hidden rounded-md border">
          <div className="flex items-center justify-between border-b bg-muted/60 px-3 py-1.5 text-xs text-muted-foreground">
            <span>Add from your device{SOURCES.size > 0 ? ", camera or other sources" : ""}</span>
            <button type="button" onClick={() => { uppy.cancelAll(); setOpen(false); }}
              className="rounded p-1 hover:bg-muted hover:text-foreground" aria-label="Close the upload panel">
              <X className="h-4 w-4" aria-hidden />
            </button>
          </div>
          <Dashboard uppy={uppy} height={300} width="100%" proudlyDisplayPoweredByUppy={false} note={hint} />
        </div>
      )}
    </div>
  );
}
'''


# ── Uppy Companion (cloud drives and web links) ─────────────────────────────────────────────────

COMPANION_VERSION = "7.1.0"


def companion_files() -> list[tuple[str, str]]:
    package = {
        "name": "companion",
        "private": True,
        "type": "module",
        "engines": {"node": ">=22"},
        "scripts": {"start": "node index.js"},
        "dependencies": {"@uppy/companion": COMPANION_VERSION, "express": "4.21.2", "express-session": "1.18.1"},
    }
    return [
        ("services/companion/package.json", json.dumps(package, indent=2) + "\n"),
        ("services/companion/index.js", _COMPANION_INDEX),
        ("services/companion/.env.example", _COMPANION_ENV),
        ("services/companion/README.md", _COMPANION_README),
    ]


_COMPANION_INDEX = r'''// Generated by OmniStackAI (PC-102): Uppy Companion - lets users pick files from Google Drive,
// Dropbox, OneDrive, Box or a web link. It signs them in to their drive and posts the chosen
// file to the app's API (/uploads), which checks and stores it like any other upload. A drive
// is offered only when its client ID and secret are set. Keys are never logged.
import { mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import express from "express";
import session from "express-session";
import { app as companionApp, socket as companionSocket } from "@uppy/companion";

const env = (name) => (process.env[name] || "").trim();
const secret = env("COMPANION_SECRET");
if (!secret) {
  // Not configured: cloud drives and links are simply not offered. Exit cleanly (no restart loop).
  console.log("COMPANION_SECRET is not set; cloud file sources are off.");
  process.exit(0);
}
const port = Number(env("PORT") || 3020);
const publicUrl = new URL(env("COMPANION_URL") || `http://localhost:${port}`);
// Published behind the app's own domain at /companion; served at the root locally.
const basePath = publicUrl.pathname.replace(/\/+$/, "");
const providers = {};
const pair = (name, id, key) => (env(id) && env(key) ? { [name]: { key: env(id), secret: env(key) } } : {});
Object.assign(
  providers,
  pair("drive", "GOOGLE_DRIVE_CLIENT_ID", "GOOGLE_DRIVE_CLIENT_SECRET"),
  pair("dropbox", "DROPBOX_APP_KEY", "DROPBOX_APP_SECRET"),
  pair("onedrive", "ONEDRIVE_CLIENT_ID", "ONEDRIVE_CLIENT_SECRET"),
  pair("box", "BOX_CLIENT_ID", "BOX_CLIENT_SECRET"),
);
const uploadUrls = env("COMPANION_UPLOAD_URLS").split(",").map((u) => u.trim()).filter(Boolean);
const clientOrigins = env("COMPANION_CLIENT_ORIGINS").split(",").map((u) => u.trim()).filter(Boolean);

// Companion keeps in-flight downloads here; it must exist before Companion starts.
const dataDir = env("COMPANION_DATA_DIR") || join(tmpdir(), "omnistackai-companion");
mkdirSync(dataDir, { recursive: true });

const app = express();
app.use(session({ secret, resave: true, saveUninitialized: true }));
const options = {
  providerOptions: providers,
  server: { host: publicUrl.host, protocol: publicUrl.protocol.replace(":", ""), ...(basePath ? { path: basePath } : {}) },
  filePath: dataDir,
  secret,
  // Companion may post only to the app's own upload endpoint, never to an address a user supplies.
  uploadUrls: uploadUrls.length ? uploadUrls : [/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\//],
  corsOrigins: clientOrigins.length ? clientOrigins : true,
  enableUrlEndpoint: true,
  enableGooglePickerEndpoint: false,
};
const { app: companionRoutes } = companionApp(options);
app.get(`${basePath}/healthz`, (_req, res) => res.json({ status: "ok", providers: Object.keys(providers) }));
app.use(basePath || "/", companionRoutes);
const server = app.listen(port, () => console.log(`Companion on :${port} (sources: link${Object.keys(providers).map((p) => ", " + p).join("")})`));
companionSocket(server, options);
'''

_COMPANION_ENV = """# Uppy Companion (PC-102). Keys only in .env, never committed.
PORT=3020
COMPANION_URL=http://localhost:3020
COMPANION_SECRET=
# The app's upload endpoint(s) Companion may post to, comma separated (regex source not supported here).
COMPANION_UPLOAD_URLS=
# Origins of the web and admin apps, comma separated.
COMPANION_CLIENT_ORIGINS=
GOOGLE_DRIVE_CLIENT_ID=
GOOGLE_DRIVE_CLIENT_SECRET=
DROPBOX_APP_KEY=
DROPBOX_APP_SECRET=
ONEDRIVE_CLIENT_ID=
ONEDRIVE_CLIENT_SECRET=
BOX_CLIENT_ID=
BOX_CLIENT_SECRET=
"""

_COMPANION_README = """# Companion (cloud file sources)

Lets users pick files from Google Drive, Dropbox, OneDrive and Box, or paste a web link. Each drive
appears only when its client ID and secret are set. Redirect URI to register with each provider:
`<COMPANION_URL>/<drive|dropbox|onedrive|box>/redirect`.

```
npm install
npm start
```
"""
