"""PC-008: the production bundle — what a generated project needs to run in production, anywhere.

Written into the project itself (and committed), so the owner is never tied to OmniStackAI to run
what they built: `docker compose -f deploy/compose.yaml --env-file <secrets> up -d` on any machine
with Docker starts the whole app — a dedicated PostgreSQL, the API, the web app, the admin console
and one entry point in front of them:

    /         the web app
    /admin    the admin console (built with that base path)
    /api/...  the API (the prefix is removed, exactly as the Studio preview proxy does)

The entry point is Caddy (open source). Given a real domain it obtains and renews HTTPS
certificates on its own; without one it serves plain HTTP on a local port — the stand-in used
until a server and domain are supplied (PC-070).

Every file here is deterministic for a given project layout, and nothing secret is written: the
database password and signing secret live in an env file outside the project (see `stack.py`).
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

WEB_PORT = 3000
API_PORT = 8000


@dataclass(frozen=True)
class Layout:
    """Which parts a project has, read from its files (edits can add or remove parts)."""

    slug: str
    api_kind: str | None  # "python" | "go" | "node" | None
    web_apps: tuple[str, ...]  # "web" first, then "admin", then any role surfaces

    @property
    def has_admin(self) -> bool:
        return "admin" in self.web_apps


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")[:40] or "app"


def _is_next_app(app_dir: Path) -> bool:
    """A Next.js web surface, known by its dependencies (an Expo app may carry no app.json)."""
    try:
        manifest = json.loads((app_dir / "package.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return False
    deps = {**(manifest.get("dependencies") or {}), **(manifest.get("devDependencies") or {})}
    return "next" in deps and "expo" not in deps


def read_layout(repo: Path, slug: str) -> Layout:
    api = repo / "services" / "api"
    api_kind = (
        "python" if (api / "requirements.txt").is_file()
        else "go" if (api / "go.mod").is_file()
        else "node" if (api / "package.json").is_file()
        else None
    )
    apps = sorted(
        (p.parent.name for p in (repo / "apps").glob("*/package.json") if _is_next_app(p.parent)),
        key=lambda name: (name != "web", name != "admin", name),
    )
    return Layout(slug=_slug(slug), api_kind=api_kind, web_apps=tuple(apps))


def base_path(app: str) -> str:
    return "" if app == "web" else f"/{app}"


# ── Dockerfiles ───────────────────────────────────────────────────────────────────────────────────

NEXT_DOCKERFILE = f"""\
# Production image for this Next.js app (generated by OmniStackAI; safe to edit).
# Built from the project root: the app imports the shared brand files there (brand.json, brand/).
FROM node:22-bookworm-slim AS build
ARG APP=web
WORKDIR /repo/apps/$APP
RUN corepack enable && corepack prepare pnpm@9.15.0 --activate
ENV npm_config_store_dir=/pnpm-store NEXT_TELEMETRY_DISABLED=1
COPY apps/$APP/package.json ./
RUN pnpm install --ignore-scripts
COPY . /repo
# Baked in at build time: where the browser finds the API, and the path this app is served under.
ARG NEXT_PUBLIC_API_URL=/api
ARG BASE_PATH=
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL BASE_PATH=$BASE_PATH
RUN pnpm build

FROM node:22-bookworm-slim
ARG APP=web
ARG BASE_PATH=
WORKDIR /app
ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1 BASE_PATH=$BASE_PATH
COPY --from=build /repo/apps/$APP ./
EXPOSE {WEB_PORT}
CMD ["node_modules/.bin/next", "start", "-p", "{WEB_PORT}"]
"""

PYTHON_DOCKERFILE = f"""\
# Production image for this FastAPI service (generated by OmniStackAI; safe to edit).
FROM python:3.12-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PIP_DISABLE_PIP_VERSION_CHECK=1
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE {API_PORT}
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "{API_PORT}", "--proxy-headers", "--forwarded-allow-ips", "*"]
"""

GO_DOCKERFILE = f"""\
# Production image for this Go service (generated by OmniStackAI; safe to edit).
FROM golang:1.23-bookworm AS build
WORKDIR /src
COPY . .
RUN go mod tidy && CGO_ENABLED=0 go build -trimpath -o /server .

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=build /server /server
ENV PORT={API_PORT} ADDR=:{API_PORT}
EXPOSE {API_PORT}
CMD ["/server"]
"""

NODE_API_DOCKERFILE = f"""\
# Production image for this Node API (generated by OmniStackAI; safe to edit).
FROM node:22-bookworm-slim AS build
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@9.15.0 --activate
COPY package.json ./
RUN pnpm install --ignore-scripts
COPY . .
RUN pnpm build

FROM node:22-bookworm-slim
WORKDIR /app
ENV NODE_ENV=production PORT={API_PORT}
COPY --from=build /app ./
EXPOSE {API_PORT}
CMD ["node", "dist/index.js"]
"""

ROOT_DOCKERIGNORE = (".git\n**/node_modules\n**/.next\n**/.venv\n**/__pycache__\n**/*.pyc\n**/.env\n"
                     "**/.env.*\n**/.pnpm-store\n**/dist\nservices/api/bin\n")
DOCKERIGNORE = "node_modules\n.next\n.venv\n__pycache__\n*.pyc\n.env\n.env.*\n.pnpm-store\ndist\nbin\n"


# ── compose and the entry point ───────────────────────────────────────────────────────────────────

CADDYFILE = f"""\
# One address for the whole app (generated by OmniStackAI; safe to edit).
# SITE_ADDRESS is ":80" for plain HTTP, or a domain name, for which Caddy obtains HTTPS itself.
{{$SITE_ADDRESS}} {{
\tencode gzip
\thandle_path /api/* {{
\t\treverse_proxy api:{API_PORT}
\t}}
__SURFACES__
\thandle {{
\t\treverse_proxy web:{WEB_PORT}
\t}}
}}
"""


def caddyfile(layout: Layout) -> str:
    surfaces = []
    for app in layout.web_apps:
        if app == "web":
            continue
        # Both "/admin" and "/admin/..." go to the app; Next itself redirects "/admin/" to "/admin",
        # so redirecting the other way here would loop.
        surfaces.append(f"\t@{app} path {base_path(app)} {base_path(app)}/*\n"
                        f"\thandle @{app} {{\n\t\treverse_proxy {app}:{WEB_PORT}\n\t}}")
    text = CADDYFILE.replace("__SURFACES__", "\n".join(surfaces))
    if layout.api_kind is None:
        text = re.sub(r"\thandle_path /api/\* \{\n.*?\n\t\}\n", "", text, flags=re.S)
    return text


def compose(layout: Layout) -> str:
    """The whole app as one compose project. Images are tagged per release for rollback."""
    image = f"omnistackai/{layout.slug}"
    lines = [
        "# The whole app, production mode (generated by OmniStackAI; safe to edit).",
        "# Run: docker compose -f deploy/compose.yaml --env-file <secrets file> up -d --build",
        "# The secrets file sets DB_PASSWORD, JWT_SECRET, SITE_ADDRESS, PUBLIC_URL, PUBLISH_BIND,",
        "# HTTP_PORT, HTTPS_PORT and RELEASE, plus any keys the app itself needs.",
        f"name: {layout.slug}",
        "services:",
        "  db:",
        "    image: postgres:16-alpine",
        "    restart: unless-stopped",
        "    environment:",
        "      POSTGRES_DB: app",
        "      POSTGRES_USER: app",
        "      POSTGRES_PASSWORD: ${DB_PASSWORD:?set DB_PASSWORD}",
        "    volumes:",
        "      - db-data:/var/lib/postgresql/data",
        "    healthcheck:",
        '      test: ["CMD-SHELL", "pg_isready -U app -d app"]',
        "      interval: 2s",
        "      timeout: 3s",
        "      retries: 30",
    ]
    if layout.api_kind is not None:
        lines += [
            "  api:",
            f"    image: {image}-api:${{RELEASE:-latest}}",
            "    build: ../services/api",
            "    restart: unless-stopped",
            "    env_file:",
            "      # The project's own secrets (payment, email and other keys), kept outside the project.",
            "      - path: ${APP_ENV_FILE:-/dev/null}",
            "        required: false",
            "    environment:",
            "      DATABASE_URL: postgresql://app:${DB_PASSWORD}@db:5432/app",
            "      JWT_SECRET: ${JWT_SECRET:?set JWT_SECRET}",
            "      CORS_ALLOWED_ORIGIN: ${PUBLIC_URL:-*}",
            "      APP_BASE_URL: ${PUBLIC_URL:-}",
            "    depends_on:",
            "      db:",
            "        condition: service_healthy",
        ]
    for app in layout.web_apps:
        lines += [
            f"  {app}:",
            f"    image: {image}-{app}:${{RELEASE:-latest}}",
            "    build:",
            "      context: ..",
            f"      dockerfile: apps/{app}/Dockerfile",
            "      args:",
            f"        APP: {app}",
            "        NEXT_PUBLIC_API_URL: /api",
            f"        BASE_PATH: \"{base_path(app)}\"",
            "    restart: unless-stopped",
        ]
    lines += [
        "  proxy:",
        f"    image: {image}-proxy:${{RELEASE:-latest}}",
        "    # The config is baked in rather than mounted, so the stack runs unchanged on a remote",
        "    # Docker host (a bind mount would name a path on that host, not this machine).",
        "    build:",
        "      context: .",
        "      dockerfile: proxy.Dockerfile",
        "    restart: unless-stopped",
        "    environment:",
        "      SITE_ADDRESS: ${SITE_ADDRESS:-:80}",
        "    ports:",
        '      - "${PUBLISH_BIND:-127.0.0.1}:${HTTP_PORT:-8080}:80"',
        '      - "${PUBLISH_BIND:-127.0.0.1}:${HTTPS_PORT:-8443}:443"',
        "    volumes:",
        "      - caddy-data:/data",
        "    depends_on:",
        *[f"      - {s}" for s in ((["api"] if layout.api_kind else []) + list(layout.web_apps))],
        "volumes:",
        "  db-data:",
        "  caddy-data:",
    ]
    return "\n".join(lines) + "\n"


def migrations(repo: Path) -> list[Path]:
    """SQL to apply to a new database, in order: migrations/*.sql, or the Node API's schema + seed."""
    api = repo / "services" / "api"
    found = sorted((api / "migrations").glob("*.sql"))
    if found:
        return found
    return [p for p in (api / "schema.sql", api / "seed.sql") if p.is_file()]


def write_bundle(repo: Path, layout: Layout) -> list[str]:
    """Write the bundle into the project; return the paths written (relative to the project)."""
    files: dict[str, str] = {
        "deploy/compose.yaml": compose(layout),
        "deploy/Caddyfile": caddyfile(layout),
        "deploy/proxy.Dockerfile": "FROM caddy:2-alpine\nCOPY Caddyfile /etc/caddy/Caddyfile\n",
        # The web apps build from the project root; keep dependencies and caches out of the context.
        ".dockerignore": ROOT_DOCKERIGNORE,
        "deploy/README.md": README.format(slug=layout.slug),
    }
    for app in layout.web_apps:
        files[f"apps/{app}/Dockerfile"] = NEXT_DOCKERFILE
    if layout.api_kind is not None:
        files["services/api/Dockerfile"] = {
            "python": PYTHON_DOCKERFILE, "go": GO_DOCKERFILE, "node": NODE_API_DOCKERFILE}[layout.api_kind]
        files["services/api/.dockerignore"] = DOCKERIGNORE
    written = []
    # A Dockerfile this bundle wrote for an app that is no longer a web surface goes (only when it
    # is exactly ours: an owner's own Dockerfile is never touched).
    for stale in (repo / "apps").glob("*/Dockerfile"):
        if stale.parent.name not in layout.web_apps and stale.read_text(encoding="utf-8") == NEXT_DOCKERFILE:
            stale.unlink()
            written.append(str(stale.relative_to(repo)))
    for rel, content in files.items():
        target = repo / rel
        if target.is_file() and target.read_text(encoding="utf-8") == content:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(rel)
    return written


README = """\
# Running {slug} in production

This folder runs the whole app — database, API, web app, admin console and one entry point with
HTTPS — on any machine with Docker. OmniStackAI's Publish uses exactly these files.

1. Create a secrets file outside the project (never commit it), for example `~/{slug}.env`:

       DB_PASSWORD=<long random string>
       JWT_SECRET=<long random string>
       SITE_ADDRESS=app.example.com        # or :80 for plain HTTP on a local port
       PUBLIC_URL=https://app.example.com
       PUBLISH_BIND=0.0.0.0                # 127.0.0.1 keeps it on this machine
       HTTP_PORT=80
       HTTPS_PORT=443
       RELEASE=1

2. Point the domain's DNS at the server, then:

       docker compose -f deploy/compose.yaml --env-file ~/{slug}.env up -d --build

3. Apply the database schema once (and each new migration file after that):

       docker compose -f deploy/compose.yaml --env-file ~/{slug}.env exec -T db \\
         psql -U app -d app < services/api/migrations/0001_init.sql

The site is served at `/`, the admin console at `/admin` and the API under `/api`.
"""


def layout_json(layout: Layout) -> str:
    return json.dumps({"slug": layout.slug, "api": layout.api_kind, "apps": list(layout.web_apps)})
