"""Vendor-neutral model-provider contract and registry."""

from .contracts import (
    CapabilityStatus,
    ChatRole,
    FinishReason,
    GenerateRequest,
    GenerateResponse,
    HealthStatus,
    Message,
    ModelCapabilities,
    ModelDescriptor,
    ModelProvider,
    ModelRef,
    ProviderHealth,
    StreamEvent,
    TokenUsage,
)
from .errors import (
    DuplicateProviderError,
    InvalidProviderError,
    InvalidProviderConfigurationError,
    ModelProfileMismatchError,
    ModelProviderError,
    ProviderHTTPError,
    ProviderRegistryError,
    ProviderResponseError,
    ProviderResponseTooLargeError,
    ProviderTimeoutError,
    ProviderUnavailableError,
    UnknownModelError,
    UnknownProviderError,
    UnsupportedModelRequestError,
)
from .ollama import OLLAMA_PROVIDER_ID, OllamaModelProfile, OllamaProvider
from .registry import ProviderRegistry

__all__ = [
    "CapabilityStatus",
    "ChatRole",
    "DuplicateProviderError",
    "FinishReason",
    "GenerateRequest",
    "GenerateResponse",
    "HealthStatus",
    "InvalidProviderError",
    "InvalidProviderConfigurationError",
    "Message",
    "ModelCapabilities",
    "ModelDescriptor",
    "ModelProvider",
    "ModelProviderError",
    "ModelProfileMismatchError",
    "ModelRef",
    "OLLAMA_PROVIDER_ID",
    "OllamaModelProfile",
    "OllamaProvider",
    "ProviderHealth",
    "ProviderHTTPError",
    "ProviderRegistry",
    "ProviderRegistryError",
    "ProviderResponseError",
    "ProviderResponseTooLargeError",
    "ProviderTimeoutError",
    "ProviderUnavailableError",
    "StreamEvent",
    "TokenUsage",
    "UnknownModelError",
    "UnknownProviderError",
    "UnsupportedModelRequestError",
]
