"""Connectors framework and codegen hooks for generated apps (G-03 / R-511).

Provides honest codegen injection and cleanup for:
1. Google Analytics 4 (ga4): injects GA4 script component into app layout and lib.
2. Transactional Email (resend / smtp): generates lib/email.ts and app/api/send/route.ts.
3. Clean removal on disable, committing changes to the project's git repository.
"""

from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path
from typing import Any


class ConnectorError(Exception):
    """Raised when connector validation or codegen fails."""


GA4_COMPONENT_TSX = """'use client';

import Script from 'next/script';

export function GoogleAnalytics({ measurementId }: { measurementId: string }) {
  if (!measurementId) return null;
  return (
    <>
      <Script
        strategy="afterInteractive"
        src={`https://www.googletagmanager.com/gtag/js?id=${measurementId}`}
      />
      <Script
        id="google-analytics"
        strategy="afterInteractive"
      >
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', '${measurementId}');
        `}
      </Script>
    </>
  );
}
"""

RESEND_LIB_EMAIL_TS = """// Generated by OmniStackAI Connector: Resend Transactional Email
// Uses Resend REST API (zero npm dependencies)

export interface SendEmailOptions {
  to: string | string[];
  subject: string;
  html?: string;
  text?: string;
  from?: string;
  replyTo?: string;
  cc?: string | string[];
  bcc?: string | string[];
}

export interface SendEmailResult {
  success: boolean;
  id?: string;
  error?: string;
}

export async function sendEmail(options: SendEmailOptions): Promise<SendEmailResult> {
  const apiKey = process.env.RESEND_API_KEY;
  const fromEmail = options.from || process.env.RESEND_FROM_EMAIL || "onboarding@resend.dev";

  if (!apiKey) {
    return { success: false, error: "RESEND_API_KEY environment variable is not configured" };
  }

  const toArray = Array.isArray(options.to) ? options.to : [options.to];
  const ccArray = options.cc ? (Array.isArray(options.cc) ? options.cc : [options.cc]) : undefined;
  const bccArray = options.bcc ? (Array.isArray(options.bcc) ? options.bcc : [options.bcc]) : undefined;

  try {
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: fromEmail,
        to: toArray,
        subject: options.subject,
        html: options.html,
        text: options.text,
        reply_to: options.replyTo,
        cc: ccArray,
        bcc: bccArray,
      }),
    });

    const data = await res.json();
    if (!res.ok) {
      return { success: false, error: data?.message || data?.error || `Resend API returned status ${res.status}` };
    }

    return { success: true, id: data.id };
  } catch (err: any) {
    return { success: false, error: err?.message || "Failed to dispatch email via Resend" };
  }
}
"""

SMTP_LIB_EMAIL_TS = """// Generated by OmniStackAI Connector: Pure Node.js SMTP Client
// Speaks RFC 5321 / RFC 4954 socket protocol using built-in node:net & node:tls (zero npm dependencies)
import * as net from 'node:net';
import * as tls from 'node:tls';
import * as crypto from 'node:crypto';

export interface SendEmailOptions {
  to: string | string[];
  subject: string;
  html?: string;
  text?: string;
  from?: string;
  replyTo?: string;
  cc?: string | string[];
  bcc?: string | string[];
}

export interface SendEmailResult {
  success: boolean;
  id?: string;
  error?: string;
}

/**
 * Sends an email directly over SMTP socket connection using standard Node.js APIs.
 * Supports direct SSL/TLS (port 465) and STARTTLS (ports 587 and 25).
 */
export async function sendEmail(options: SendEmailOptions): Promise<SendEmailResult> {
  const host = process.env.SMTP_HOST;
  const port = parseInt(process.env.SMTP_PORT || "587", 10);
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;
  const fromEmail = options.from || process.env.SMTP_FROM || user || "no-reply@example.com";

  if (!host || !user || !pass) {
    return { success: false, error: "SMTP configuration incomplete (SMTP_HOST, SMTP_USER, or SMTP_PASS missing)" };
  }

  const toList = Array.isArray(options.to) ? options.to : [options.to];
  const ccList = options.cc ? (Array.isArray(options.cc) ? options.cc : [options.cc]) : [];
  const bccList = options.bcc ? (Array.isArray(options.bcc) ? options.bcc : [options.bcc]) : [];
  const allRecipients = [...toList, ...ccList, ...bccList].map(e => e.trim()).filter(Boolean);

  if (allRecipients.length === 0) {
    return { success: false, error: "No recipients specified" };
  }

  const messageId = `<${crypto.randomUUID()}@${host}>`;
  const boundary = `----=_Part_${crypto.randomBytes(8).toString('hex')}`;

  // Build RFC 2822 message payload
  const headers = [
    `From: ${fromEmail}`,
    `To: ${toList.join(', ')}`,
    ...(ccList.length > 0 ? [`Cc: ${ccList.join(', ')}`] : []),
    `Subject: ${options.subject}`,
    `Date: ${new Date().toUTCString()}`,
    `Message-ID: ${messageId}`,
    ...(options.replyTo ? [`Reply-To: ${options.replyTo}`] : []),
    `MIME-Version: 1.0`,
  ];

  let body = '';
  if (options.html && options.text) {
    headers.push(`Content-Type: multipart/alternative; boundary="${boundary}"`);
    body = [
      `--${boundary}`,
      'Content-Type: text/plain; charset=utf-8',
      'Content-Transfer-Encoding: 7bit',
      '',
      options.text,
      `--${boundary}`,
      'Content-Type: text/html; charset=utf-8',
      'Content-Transfer-Encoding: 7bit',
      '',
      options.html,
      `--${boundary}--`,
    ].join('\\r\\n');
  } else if (options.html) {
    headers.push('Content-Type: text/html; charset=utf-8');
    body = options.html;
  } else {
    headers.push('Content-Type: text/plain; charset=utf-8');
    body = options.text || '';
  }

  const rawMessage = `${headers.join('\\r\\n')}\\r\\n\\r\\n${body}\\r\\n`;

  return new Promise((resolve) => {
    let socket: net.Socket;
    const isDirectTls = port === 465;

    const timeout = setTimeout(() => {
      cleanup();
      resolve({ success: false, error: `Connection to SMTP server ${host}:${port} timed out` });
    }, 15000);

    const cleanup = () => {
      clearTimeout(timeout);
      if (socket && !socket.destroyed) {
        socket.destroy();
      }
    };

    let step = 0;
    let buffer = '';

    const sendCmd = (cmd: string) => {
      socket.write(`${cmd}\\r\\n`);
    };

    const handleLine = (line: string) => {
      const code = parseInt(line.slice(0, 3), 10);
      const isFinal = line[3] !== '-'; // Continuation lines have '-'

      if (!isFinal) return;

      switch (step) {
        case 0: // Banner received (220)
          if (code !== 220) {
            cleanup();
            return resolve({ success: false, error: `SMTP greeting rejected: ${line}` });
          }
          step = 1;
          sendCmd('EHLO localhost');
          break;

        case 1: // EHLO response (250)
          if (code !== 250) {
            cleanup();
            return resolve({ success: false, error: `EHLO rejected: ${line}` });
          }
          if (!isDirectTls) {
            step = 2;
            sendCmd('STARTTLS');
          } else {
            step = 4;
            sendCmd('AUTH LOGIN');
          }
          break;

        case 2: // STARTTLS response (220)
          if (code !== 220) {
            cleanup();
            return resolve({ success: false, error: `STARTTLS rejected: ${line}` });
          }
          step = 3;
          {
            const tlsSocket = tls.connect({
              socket,
              host,
              rejectUnauthorized: false,
            }, () => {
              socket = tlsSocket;
              sendCmd('EHLO localhost');
            });
            tlsSocket.on('error', (err) => {
              cleanup();
              resolve({ success: false, error: `TLS handshake error: ${err.message}` });
            });
            tlsSocket.on('data', onData);
          }
          break;

        case 3: // EHLO after TLS (250)
          if (code !== 250) {
            cleanup();
            return resolve({ success: false, error: `EHLO after TLS failed: ${line}` });
          }
          step = 4;
          sendCmd('AUTH LOGIN');
          break;

        case 4: // AUTH LOGIN response (334) -> username
          if (code !== 334) {
            cleanup();
            return resolve({ success: false, error: `AUTH LOGIN rejected: ${line}` });
          }
          step = 5;
          sendCmd(Buffer.from(user).toString('base64'));
          break;

        case 5: // Username accepted (334) -> password
          if (code !== 334) {
            cleanup();
            return resolve({ success: false, error: `Username rejected: ${line}` });
          }
          step = 6;
          sendCmd(Buffer.from(pass).toString('base64'));
          break;

        case 6: // Password accepted (235) -> MAIL FROM
          if (code !== 235) {
            cleanup();
            return resolve({ success: false, error: `Authentication failed: ${line}` });
          }
          step = 7;
          sendCmd(`MAIL FROM:<${fromEmail}>`);
          break;

        case 7: // MAIL FROM accepted (250) -> RCPT TO
          if (code !== 250) {
            cleanup();
            return resolve({ success: false, error: `MAIL FROM rejected: ${line}` });
          }
          step = 8;
          sendRcpt(0);
          break;

        case 8: // RCPT TO accepted (250/251)
          if (code !== 250 && code !== 251) {
            cleanup();
            return resolve({ success: false, error: `Recipient rejected: ${line}` });
          }
          break;

        case 9: // DATA accepted (354) -> payload
          if (code !== 354) {
            cleanup();
            return resolve({ success: false, error: `DATA command rejected: ${line}` });
          }
          step = 10;
          {
            const escaped = rawMessage.replace(/\\r\\n\\./g, '\\r\\n..');
            socket.write(escaped.endsWith('\\r\\n') ? `${escaped}.\\r\\n` : `${escaped}\\r\\n.\\r\\n`);
          }
          break;

        case 10: // Message accepted (250)
          if (code !== 250) {
            cleanup();
            return resolve({ success: false, error: `Message delivery failed: ${line}` });
          }
          step = 11;
          sendCmd('QUIT');
          cleanup();
          resolve({ success: true, id: messageId.replace(/[<>]/g, '') });
          break;
      }
    };

    let rcptIdx = 0;
    const sendRcpt = (index: number) => {
      rcptIdx = index;
      if (rcptIdx < allRecipients.length) {
        sendCmd(`RCPT TO:<${allRecipients[rcptIdx]}>`);
        rcptIdx++;
      } else {
        step = 9;
        sendCmd('DATA');
      }
    };

    const onData = (chunk: Buffer) => {
      buffer += chunk.toString('utf-8');
      let idx;
      while ((idx = buffer.indexOf('\\r\\n')) !== -1) {
        const line = buffer.slice(0, idx);
        buffer = buffer.slice(idx + 2);
        handleLine(line);
      }
    };

    try {
      if (isDirectTls) {
        socket = tls.connect({ host, port, rejectUnauthorized: false }, () => {});
      } else {
        socket = net.connect({ host, port }, () => {});
      }

      socket.on('data', onData);
      socket.on('error', (err) => {
        cleanup();
        resolve({ success: false, error: `Socket error: ${err.message}` });
      });
    } catch (err: any) {
      cleanup();
      resolve({ success: false, error: `Failed to connect: ${err?.message}` });
    }
  });
}
"""

EMAIL_TEMPLATES_TS = """// Generated by OmniStackAI: Responsive HTML Email Templates
// Compatible with all modern desktop and mobile email clients

export interface EmailTemplateResult {
  subject: string;
  html: string;
  text: string;
}

function baseLayout(appName: string, contentHtml: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 0; background-color: #f8fafc; color: #1e293b; }
    .wrapper { max-width: 580px; margin: 24px auto; background: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.08); border: 1px solid #e2e8f0; }
    .header { background: #0f172a; padding: 24px 32px; text-align: left; }
    .header h1 { margin: 0; font-size: 20px; font-weight: 700; color: #ffffff; letter-spacing: -0.02em; }
    .content { padding: 32px; font-size: 15px; line-height: 1.6; color: #334155; }
    .btn { display: inline-block; padding: 12px 24px; font-size: 14px; font-weight: 600; color: #ffffff !important; background-color: #2563eb; text-decoration: none; border-radius: 6px; margin: 20px 0; text-align: center; }
    .otp-box { font-family: 'Courier New', monospace; font-size: 28px; font-weight: 700; letter-spacing: 6px; color: #0f172a; background: #f1f5f9; padding: 16px; text-align: center; border-radius: 6px; margin: 20px 0; border: 1px dashed #cbd5e1; }
    .footer { padding: 20px 32px; background: #f8fafc; font-size: 12px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <h1>${appName}</h1>
    </div>
    <div class="content">
      ${contentHtml}
    </div>
    <div class="footer">
      <p>&copy; ${new Date().getFullYear()} ${appName}. All rights reserved.</p>
    </div>
  </div>
</body>
</html>`;
}

export function welcomeEmailTemplate(params: {
  name: string;
  appName: string;
  loginUrl?: string;
  supportEmail?: string;
}): EmailTemplateResult {
  const subject = `Welcome to ${params.appName}!`;
  const html = baseLayout(
    params.appName,
    `<h2 style="margin-top:0; color:#0f172a;">Welcome aboard, ${params.name}!</h2>
     <p>We are thrilled to have you join ${params.appName}. Your account is ready to go.</p>
     ${params.loginUrl ? `<a href="${params.loginUrl}" class="btn">Get Started &rarr;</a>` : ''}
     <p style="margin-top:24px; font-size:13px; color:#64748b;">If you have any questions, feel free to reply to this email${params.supportEmail ? ` or contact us at ${params.supportEmail}` : ''}.</p>`
  );
  const text = `Welcome aboard, ${params.name}!\\n\\nWe are thrilled to have you join ${params.appName}.\\n${params.loginUrl ? `Get started here: ${params.loginUrl}\\n\\n` : ''}Best,\\nThe ${params.appName} Team`;
  return { subject, html, text };
}

export function otpVerificationTemplate(params: {
  code: string;
  appName: string;
  expiresInMinutes?: number;
}): EmailTemplateResult {
  const subject = `${params.code} is your ${params.appName} verification code`;
  const expires = params.expiresInMinutes || 10;
  const html = baseLayout(
    params.appName,
    `<h2 style="margin-top:0; color:#0f172a;">Verification Code</h2>
     <p>Please use the verification code below to complete your sign in or verification.</p>
     <div class="otp-box">${params.code}</div>
     <p style="font-size:13px; color:#64748b;">This code will expire in ${expires} minutes. If you did not request this, please ignore this email.</p>`
  );
  const text = `Your verification code for ${params.appName} is: ${params.code}\\n\\nThis code will expire in ${expires} minutes.\\nIf you did not request this code, you can safely ignore this email.`;
  return { subject, html, text };
}

export function passwordResetTemplate(params: {
  name?: string;
  appName: string;
  resetUrl: string;
  expiresInMinutes?: number;
}): EmailTemplateResult {
  const subject = `Reset your password for ${params.appName}`;
  const expires = params.expiresInMinutes || 30;
  const greeting = params.name ? `Hello ${params.name},` : 'Hello,';
  const html = baseLayout(
    params.appName,
    `<h2 style="margin-top:0; color:#0f172a;">Password Reset Request</h2>
     <p>${greeting}</p>
     <p>We received a request to reset the password for your ${params.appName} account. Click the button below to choose a new password:</p>
     <a href="${params.resetUrl}" class="btn">Reset Password</a>
     <p style="font-size:13px; color:#64748b;">This link is valid for ${expires} minutes. If you did not request a password reset, you can safely ignore this email.</p>`
  );
  const text = `${greeting}\\n\\nWe received a request to reset your password for ${params.appName}.\\nReset your password here: ${params.resetUrl}\\n\\nThis link will expire in ${expires} minutes.`;
  return { subject, html, text };
}

export function notificationTemplate(params: {
  title: string;
  message: string;
  ctaText?: string;
  ctaUrl?: string;
  appName: string;
}): EmailTemplateResult {
  const subject = `${params.title} — ${params.appName}`;
  const html = baseLayout(
    params.appName,
    `<h2 style="margin-top:0; color:#0f172a;">${params.title}</h2>
     <p>${params.message.replace(/\\n/g, '<br/>')}</p>
     ${params.ctaUrl && params.ctaText ? `<a href="${params.ctaUrl}" class="btn">${params.ctaText}</a>` : ''}`
  );
  const text = `${params.title}\\n\\n${params.message}\\n${params.ctaUrl ? `\\nLink: ${params.ctaUrl}` : ''}`;
  return { subject, html, text };
}
"""

CONTACT_FORM_TSX = """'use client';

import React, { useState } from 'react';

export function ContactForm() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [subject, setSubject] = useState('');
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState<{ type: 'success' | 'error'; message: string } | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setStatus(null);

    try {
      const res = await fetch('/api/send', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          to: email,
          subject: subject || `Contact request from ${name}`,
          text: `Name: ${name}\\nEmail: ${email}\\n\\nMessage:\\n${message}`,
          html: `<p><strong>From:</strong> ${name} (${email})</p><p>${message.replace(/\\n/g, '<br/>')}</p>`,
          replyTo: email,
        }),
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.error || 'Failed to send message');
      }

      setStatus({ type: 'success', message: 'Thank you! Your message has been sent successfully.' });
      setName('');
      setEmail('');
      setSubject('');
      setMessage('');
    } catch (err: any) {
      setStatus({ type: 'error', message: err.message || 'An unexpected error occurred.' });
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4 max-w-md mx-auto p-6 bg-card border rounded-xl shadow-sm">
      <h3 className="text-xl font-semibold tracking-tight">Contact Us</h3>
      
      {status && (
        <div className={`p-3 rounded-lg text-sm ${status.type === 'success' ? 'bg-emerald-50 text-emerald-800 border border-emerald-200' : 'bg-red-50 text-red-800 border border-red-200'}`}>
          {status.message}
        </div>
      )}

      <div>
        <label className="block text-sm font-medium mb-1">Name</label>
        <input
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
          required
          className="w-full px-3 py-2 border rounded-lg text-sm bg-background"
          placeholder="Your name"
        />
      </div>

      <div>
        <label className="block text-sm font-medium mb-1">Email</label>
        <input
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          required
          className="w-full px-3 py-2 border rounded-lg text-sm bg-background"
          placeholder="you@example.com"
        />
      </div>

      <div>
        <label className="block text-sm font-medium mb-1">Subject</label>
        <input
          type="text"
          value={subject}
          onChange={(e) => setSubject(e.target.value)}
          className="w-full px-3 py-2 border rounded-lg text-sm bg-background"
          placeholder="How can we help?"
        />
      </div>

      <div>
        <label className="block text-sm font-medium mb-1">Message</label>
        <textarea
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          required
          rows={4}
          className="w-full px-3 py-2 border rounded-lg text-sm bg-background"
          placeholder="Your message here..."
        />
      </div>

      <button
        type="submit"
        disabled={loading}
        className="w-full py-2.5 px-4 bg-primary text-primary-foreground font-medium rounded-lg text-sm hover:opacity-90 disabled:opacity-50 transition"
      >
        {loading ? 'Sending...' : 'Send Message'}
      </button>
    </form>
  );
}
"""

API_SEND_ROUTE_TS = """// Generated by OmniStackAI Connector: Transactional Email API Route
import { NextResponse } from 'next/server';
import { sendEmail } from '@/lib/email';

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { to, subject, html, text, replyTo } = body;

    if (!to || !subject) {
      return NextResponse.json(
        { error: 'Missing required fields: to and subject are required' },
        { status: 400 }
      );
    }

    const result = await sendEmail({ to, subject, html, text, replyTo });
    if (!result.success) {
      return NextResponse.json({ error: result.error }, { status: 500 });
    }

    return NextResponse.json({ success: true, id: result.id });
  } catch (err: any) {
    return NextResponse.json(
      { error: err?.message || 'Invalid request body' },
      { status: 400 }
    );
  }
}
"""


def _find_layout_file(repo_dir: Path) -> Path | None:
    """Find app/layout.tsx or src/app/layout.tsx if present."""
    candidates = [
        repo_dir / "app" / "layout.tsx",
        repo_dir / "src" / "app" / "layout.tsx",
        repo_dir / "app" / "layout.js",
        repo_dir / "src" / "app" / "layout.js",
    ]
    for c in candidates:
        if c.is_file():
            return c
    return None


def _inject_ga4_into_layout(layout_path: Path, measurement_id: str) -> bool:
    """Inject GoogleAnalytics import and component tag into layout file."""
    content = layout_path.read_text(encoding="utf-8")
    modified = False

    # 1. Ensure import is present
    import_stmt = "import { GoogleAnalytics } from '@/components/GoogleAnalytics';"
    if "GoogleAnalytics" not in content:
        content = f"{import_stmt}\n{content}"
        modified = True

    # 2. Inject component tag inside body or html
    tag = f"<GoogleAnalytics measurementId=\"{measurement_id}\" />"
    if "GoogleAnalytics measurementId=" not in content:
        if "<body" in content:
            # inject right after opening body tag
            pattern = re.compile(r"(<body[^>]*>)")
            if pattern.search(content):
                content = pattern.sub(r"\1\n        " + tag, content, count=1)
                modified = True
        elif "</head>" in content:
            content = content.replace("</head>", f"  {tag}\n      </head>", 1)
            modified = True
        else:
            # append at end of children or return
            content = content + f"\n{tag}\n"
            modified = True

    if modified:
        layout_path.write_text(content, encoding="utf-8")
    return modified


def _remove_ga4_from_layout(layout_path: Path) -> bool:
    """Remove GoogleAnalytics import and component tag from layout file."""
    content = layout_path.read_text(encoding="utf-8")
    original = content

    # Remove import line
    content = re.sub(r"import\s*\{\s*GoogleAnalytics\s*\}\s*from\s*['\"]@/components/GoogleAnalytics['\"];?\n?", "", content)

    # Remove component tag
    content = re.sub(r"<GoogleAnalytics\s+measurementId=[^/]+/>\n?", "", content)

    if content != original:
        layout_path.write_text(content, encoding="utf-8")
        return True
    return False


def _git_commit(repo_dir: Path, message: str) -> None:
    """Stage and commit changes if repo_dir is inside a git repository."""
    if not (repo_dir / ".git").is_dir():
        return

    env = {
        **os.environ,
        "GIT_AUTHOR_NAME": "OmniStackAI",
        "GIT_AUTHOR_EMAIL": "agent@omnistack.ai",
        "GIT_COMMITTER_NAME": "OmniStackAI",
        "GIT_COMMITTER_EMAIL": "agent@omnistack.ai",
    }
    subprocess.run(["git", "add", "-A"], cwd=str(repo_dir), env=env, capture_output=True, text=True, check=False)
    subprocess.run(["git", "commit", "-m", message], cwd=str(repo_dir), env=env, capture_output=True, text=True, check=False)


def apply_connector(repo_dir: Path, provider: str, config: dict[str, Any]) -> dict[str, Any]:
    """Apply connector codegen to the workspace repository and commit the changes."""
    if not repo_dir.is_dir():
        raise ConnectorError(f"repository directory does not exist: {repo_dir}")

    provider = provider.lower().strip()
    files_created: list[str] = []
    files_modified: list[str] = []

    if provider == "ga4":
        measurement_id = str(config.get("measurement_id", "")).strip()
        if not measurement_id:
            raise ConnectorError("measurement_id is required for Google Analytics 4")
        if not re.match(r"^G-[A-Z0-9]+$", measurement_id, re.IGNORECASE):
            raise ConnectorError(f"invalid GA4 measurement ID format: {measurement_id}")

        # Create components/GoogleAnalytics.tsx
        components_dir = repo_dir / "components"
        components_dir.mkdir(parents=True, exist_ok=True)
        ga_file = components_dir / "GoogleAnalytics.tsx"
        ga_file.write_text(GA4_COMPONENT_TSX, encoding="utf-8")
        files_created.append("components/GoogleAnalytics.tsx")

        # Inject into layout
        layout_path = _find_layout_file(repo_dir)
        if layout_path:
            if _inject_ga4_into_layout(layout_path, measurement_id):
                files_modified.append(str(layout_path.relative_to(repo_dir)))

        _git_commit(repo_dir, f"chore(connector): enable Google Analytics 4 ({measurement_id})")

        return {
            "status": "applied",
            "provider": "ga4",
            "files_created": files_created,
            "files_modified": files_modified,
            "message": f"Google Analytics 4 ({measurement_id}) enabled successfully",
        }

    elif provider == "resend":
        api_key = str(config.get("api_key", "")).strip()
        from_email = str(config.get("from_email", "onboarding@resend.dev")).strip()
        if not api_key:
            raise ConnectorError("api_key is required for Resend")

        lib_dir = repo_dir / "lib"
        lib_dir.mkdir(parents=True, exist_ok=True)
        email_file = lib_dir / "email.ts"
        email_file.write_text(RESEND_LIB_EMAIL_TS, encoding="utf-8")
        files_created.append("lib/email.ts")

        templates_file = lib_dir / "email-templates.ts"
        templates_file.write_text(EMAIL_TEMPLATES_TS, encoding="utf-8")
        files_created.append("lib/email-templates.ts")

        api_send_dir = repo_dir / "app" / "api" / "send"
        api_send_dir.mkdir(parents=True, exist_ok=True)
        route_file = api_send_dir / "route.ts"
        route_file.write_text(API_SEND_ROUTE_TS, encoding="utf-8")
        files_created.append("app/api/send/route.ts")

        components_dir = repo_dir / "components"
        components_dir.mkdir(parents=True, exist_ok=True)
        contact_form_file = components_dir / "contact-form.tsx"
        contact_form_file.write_text(CONTACT_FORM_TSX, encoding="utf-8")
        files_created.append("components/contact-form.tsx")

        # Update .env.local
        env_file = repo_dir / ".env.local"
        env_content = env_file.read_text(encoding="utf-8") if env_file.is_file() else ""
        lines = [line for line in env_content.splitlines() if not line.startswith("RESEND_")]
        lines.append(f"RESEND_API_KEY={api_key}")
        lines.append(f"RESEND_FROM_EMAIL={from_email}")
        env_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
        files_modified.append(".env.local")

        _git_commit(repo_dir, "chore(connector): enable Resend transactional email")

        return {
            "status": "applied",
            "provider": "resend",
            "files_created": files_created,
            "files_modified": files_modified,
            "message": "Resend transactional email connector enabled successfully",
        }

    elif provider == "smtp":
        host = str(config.get("host", "")).strip()
        user = str(config.get("username", "")).strip()
        pass_val = str(config.get("password", "")).strip()
        port = str(config.get("port", "587")).strip()
        from_email = str(config.get("from_email", user)).strip()

        if not host or not user or not pass_val:
            raise ConnectorError("host, username, and password are required for SMTP")

        lib_dir = repo_dir / "lib"
        lib_dir.mkdir(parents=True, exist_ok=True)
        email_file = lib_dir / "email.ts"
        email_file.write_text(SMTP_LIB_EMAIL_TS, encoding="utf-8")
        files_created.append("lib/email.ts")

        templates_file = lib_dir / "email-templates.ts"
        templates_file.write_text(EMAIL_TEMPLATES_TS, encoding="utf-8")
        files_created.append("lib/email-templates.ts")

        api_send_dir = repo_dir / "app" / "api" / "send"
        api_send_dir.mkdir(parents=True, exist_ok=True)
        route_file = api_send_dir / "route.ts"
        route_file.write_text(API_SEND_ROUTE_TS, encoding="utf-8")
        files_created.append("app/api/send/route.ts")

        components_dir = repo_dir / "components"
        components_dir.mkdir(parents=True, exist_ok=True)
        contact_form_file = components_dir / "contact-form.tsx"
        contact_form_file.write_text(CONTACT_FORM_TSX, encoding="utf-8")
        files_created.append("components/contact-form.tsx")

        # Update .env.local
        env_file = repo_dir / ".env.local"
        env_content = env_file.read_text(encoding="utf-8") if env_file.is_file() else ""
        lines = [line for line in env_content.splitlines() if not line.startswith("SMTP_")]
        lines.append(f"SMTP_HOST={host}")
        lines.append(f"SMTP_PORT={port}")
        lines.append(f"SMTP_USER={user}")
        lines.append(f"SMTP_PASS={pass_val}")
        lines.append(f"SMTP_FROM={from_email}")
        env_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
        files_modified.append(".env.local")

        _git_commit(repo_dir, "chore(connector): enable custom SMTP transactional email")

        return {
            "status": "applied",
            "provider": "smtp",
            "files_created": files_created,
            "files_modified": files_modified,
            "message": "Custom SMTP connector enabled successfully",
        }

    else:
        raise ConnectorError(f"unsupported connector provider: {provider}")


def remove_connector(repo_dir: Path, provider: str) -> dict[str, Any]:
    """Remove connector codegen from workspace repository and commit the deletion."""
    if not repo_dir.is_dir():
        raise ConnectorError(f"repository directory does not exist: {repo_dir}")

    provider = provider.lower().strip()
    files_removed: list[str] = []
    files_modified: list[str] = []

    if provider == "ga4":
        ga_file = repo_dir / "components" / "GoogleAnalytics.tsx"
        if ga_file.is_file():
            ga_file.unlink()
            files_removed.append("components/GoogleAnalytics.tsx")

        layout_path = _find_layout_file(repo_dir)
        if layout_path:
            if _remove_ga4_from_layout(layout_path):
                files_modified.append(str(layout_path.relative_to(repo_dir)))

        _git_commit(repo_dir, "chore(connector): disable Google Analytics 4")

        return {
            "status": "removed",
            "provider": "ga4",
            "files_removed": files_removed,
            "files_modified": files_modified,
            "message": "Google Analytics 4 connector disabled and code removed",
        }

    elif provider in {"resend", "smtp"}:
        email_file = repo_dir / "lib" / "email.ts"
        if email_file.is_file():
            email_file.unlink()
            files_removed.append("lib/email.ts")

        templates_file = repo_dir / "lib" / "email-templates.ts"
        if templates_file.is_file():
            templates_file.unlink()
            files_removed.append("lib/email-templates.ts")

        contact_form_file = repo_dir / "components" / "contact-form.tsx"
        if contact_form_file.is_file():
            contact_form_file.unlink()
            files_removed.append("components/contact-form.tsx")

        route_file = repo_dir / "app" / "api" / "send" / "route.ts"
        if route_file.is_file():
            route_file.unlink()
            files_removed.append("app/api/send/route.ts")
            # Try to remove empty dir
            try:
                (repo_dir / "app" / "api" / "send").rmdir()
            except OSError:
                pass

        # Clean env vars from .env.local
        env_file = repo_dir / ".env.local"
        if env_file.is_file():
            env_content = env_file.read_text(encoding="utf-8")
            prefix = "RESEND_" if provider == "resend" else "SMTP_"
            lines = [line for line in env_content.splitlines() if not line.startswith(prefix)]
            env_file.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
            files_modified.append(".env.local")

        _git_commit(repo_dir, f"chore(connector): disable {provider} transactional email")

        return {
            "status": "removed",
            "provider": provider,
            "files_removed": files_removed,
            "files_modified": files_modified,
            "message": f"{provider.capitalize()} connector disabled and code removed",
        }

    else:
        raise ConnectorError(f"unsupported connector provider: {provider}")
