"""Framework-neutral Application IR — the source of truth for code generation (Brief 9)."""

from .errors import ApplicationIRError, InvalidIRError, UnsupportedIRVersionError
from .ir import (
    IR_SCHEMA_VERSION,
    AcceptanceCriterion,
    AdminStrategy,
    ApiEndpoint,
    ApplicationIR,
    BackendStrategy,
    DatabaseStrategy,
    Entity,
    Field,
    FieldType,
    HttpMethod,
    MobileProfile,
    Platform,
    ProjectStrategy,
    Relation,
    RelationKind,
    RepoStrategy,
    Role,
    Screen,
    WebStrategy,
)

__all__ = [
    "AcceptanceCriterion",
    "AdminStrategy",
    "ApiEndpoint",
    "ApplicationIR",
    "ApplicationIRError",
    "BackendStrategy",
    "DatabaseStrategy",
    "Entity",
    "Field",
    "FieldType",
    "HttpMethod",
    "IR_SCHEMA_VERSION",
    "InvalidIRError",
    "MobileProfile",
    "Platform",
    "ProjectStrategy",
    "Relation",
    "RelationKind",
    "RepoStrategy",
    "Role",
    "Screen",
    "UnsupportedIRVersionError",
    "WebStrategy",
]
