"""R-526: the RideNow template's API unit tests and seed reproducibility, run offline.

RideNow's API is TypeScript that Node (>= 22.18) runs natively. Its unit tests import only pure
modules (fares, promos, the trip state machine, tokens, passwords, geo, dispatch ranking), so they
need no dependencies installed and no database. The live workflow test in the same folder skips
without API_BASE. The seed is generated by a script that reuses the API's own fare code; the
committed seed must be exactly what the script produces.
"""

from __future__ import annotations

import hashlib
import os
import re
import shutil
import subprocess
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[3] / "templates" / "catalog"
API_CANDIDATES = [REPO / "ride-now" / "repo" / "services" / "api", REPO / "_ride-now" / "repo" / "services" / "api"]
API = next((path for path in API_CANDIDATES if path.is_dir()), API_CANDIDATES[0])


def _node_supports_typescript() -> bool:
    node = shutil.which("node")
    if not node:
        return False
    version = subprocess.run([node, "--version"], capture_output=True, text=True, check=False).stdout.strip()
    match = re.match(r"v(\d+)\.(\d+)", version)
    return bool(match) and (int(match.group(1)), int(match.group(2))) >= (22, 18)


@unittest.skipUnless(API.is_dir() and _node_supports_typescript(), "needs the RideNow template and Node >= 22.18")
class RideNowApiTests(unittest.TestCase):
    def test_unit_tests_pass(self) -> None:
        tests = sorted(str(p.relative_to(API)) for p in (API / "test").glob("*.test.ts"))
        self.assertGreaterEqual(len(tests), 5)
        result = subprocess.run(
            ["node", "--test", *tests], cwd=str(API), capture_output=True, text=True, timeout=180, check=False,
            env={"PATH": os.environ.get("PATH", ""), "HOME": os.environ.get("HOME", "")},
        )
        self.assertEqual(result.returncode, 0, result.stdout[-3000:] + result.stderr[-2000:])
        passed = re.search(r"pass (\d+)", result.stdout)
        self.assertIsNotNone(passed)
        self.assertGreaterEqual(int(passed.group(1)), 20)

    def test_shared_package_tests_pass(self) -> None:
        shared = API.parents[1] / "packages" / "shared"
        if not shared.is_dir():
            self.skipTest("packages/shared arrives with R-527")
        tests = sorted(str(p.relative_to(shared)) for p in (shared / "test").glob("*.test.ts"))
        result = subprocess.run(
            ["node", "--test", *tests], cwd=str(shared), capture_output=True, text=True, timeout=120, check=False,
            env={"PATH": os.environ.get("PATH", ""), "HOME": os.environ.get("HOME", "")},
        )
        self.assertEqual(result.returncode, 0, result.stdout[-2000:] + result.stderr[-1000:])

    def test_seed_matches_its_generator(self) -> None:
        result = subprocess.run(
            ["node", "scripts/generate-seed.mjs"], cwd=str(API), capture_output=True, timeout=180, check=False,
        )
        self.assertEqual(result.returncode, 0, result.stderr.decode()[-2000:])
        committed = (API / "seed" / "001_demo.sql").read_bytes()
        self.assertEqual(
            hashlib.sha256(result.stdout).hexdigest(),
            hashlib.sha256(committed).hexdigest(),
            "seed/001_demo.sql is stale: run `node scripts/generate-seed.mjs > seed/001_demo.sql`",
        )

    def test_demo_logins_are_documented_in_the_seed(self) -> None:
        head = (API / "seed" / "001_demo.sql").read_text(encoding="utf-8")[:600]
        for login in ("asha@ridenow.test", "ravi@ridenow.test", "admin@ridenow.test"):
            self.assertIn(login, head)


API_MOUNTS = ("/auth", "/rider", "/driver", "/admin", "/support", "/stream")
# A string literal in app code that names an API path, e.g. "/driver/me" or `/driver/trips/${id}/arrive`.
_API_LITERAL = re.compile(r"[\"`](/(?:auth|rider|driver|admin|support|stream)(?:/[^\"`?\s]*)?)(?:\?[^\"`]*)?[\"`]")
_ROUTE = re.compile(r"(\w+)Routes\.(?:get|post|patch|put|delete)\(\"([^\"]*)\"")


def _api_routes(api: Path) -> list[re.Pattern[str]]:
    mounts = {"public": "", "auth": "/auth", "rider": "/rider", "driver": "/driver", "admin": "/admin", "support": "/support", "stream": "/stream"}
    patterns = []
    for source in (api / "src" / "routes").glob("*.ts"):
        for group, path in _ROUTE.findall(source.read_text(encoding="utf-8")):
            full = (mounts[group] + path).rstrip("/") or "/"
            patterns.append(re.compile("^" + re.sub(r":\w+", "[^/]+", full) + "$"))
    return patterns


@unittest.skipUnless(API.is_dir(), "needs the RideNow template")
class RideNowAppsTests(unittest.TestCase):
    """R-528/R-530: the apps are complete, and every API path their code names exists in the API."""

    def test_driver_app_pages_and_pwa_files(self) -> None:
        driver = API.parents[1] / "apps" / "driver"
        for page in ("", "login", "apply", "trip", "earnings", "wallet", "trips", "trips/[id]", "ratings", "account",
                     "help", "help/[id]", "notifications"):
            self.assertTrue((driver / "app" / page / "page.tsx").is_file(), f"driver page missing: /{page}")
        for extra in ("app/manifest.ts", "app/not-found.tsx", "public/icon.svg", "public/icon-maskable.svg", "components/offer-sheet.tsx"):
            self.assertTrue((driver / extra).is_file(), extra)
        manifest = (driver / "app" / "manifest.ts").read_text(encoding="utf-8")
        self.assertIn('display: "standalone"', manifest)
        self.assertIn("BASE_PATH", manifest, "the manifest must respect the preview base path")

    def test_ops_app_pages_and_admin_only_sign_in(self) -> None:
        """R-530: the operations console has the full page set and signs in as admin only."""
        admin = API.parents[1] / "apps" / "admin"
        for page in ("", "login", "live", "trips", "trips/[id]", "riders", "riders/[id]", "drivers", "drivers/[id]",
                     "pricing", "zones", "promos", "payouts", "finance", "tickets", "tickets/[id]", "audit", "settings"):
            self.assertTrue((admin / "app" / page / "page.tsx").is_file(), f"ops page missing: /{page}")
        for extra in ("app/not-found.tsx", "app/icon.svg", "lib/session.tsx", "components/shell.tsx"):
            self.assertTrue((admin / extra).is_file(), extra)
        login = (admin / "app" / "login" / "page.tsx").read_text(encoding="utf-8")
        self.assertIn('role: "admin"', login, "the ops sign-in must ask the API for an admin account")
        session = (admin / "lib" / "session.tsx").read_text(encoding="utf-8")
        self.assertIn('role !== "admin"', session, "a stored non-admin session must be dropped")
        self.assertIn("ridenow.admin.session", (admin / "lib" / "api.ts").read_text(encoding="utf-8"))

    def test_every_api_path_used_by_the_apps_exists(self) -> None:
        routes = _api_routes(API)
        self.assertGreater(len(routes), 60)
        checked = 0
        for app in ("rider", "driver", "admin"):
            root = API.parents[1] / "apps" / app
            for source in [*root.rglob("*.ts"), *root.rglob("*.tsx")]:
                if "node_modules" in source.parts or ".next" in source.parts:
                    continue
                for path in _API_LITERAL.findall(source.read_text(encoding="utf-8")):
                    concrete = re.sub(r"\$\{[^}]*\}", "x", path).rstrip("/")
                    checked += 1
                    self.assertTrue(any(r.match(concrete) for r in routes), f"{source.relative_to(root)} calls {path}, which the API does not define")
        self.assertGreater(checked, 70)


if __name__ == "__main__":
    unittest.main()
