"""R-526: the RideNow template's API unit tests and seed reproducibility, run offline.

RideNow's API is TypeScript that Node (>= 22.18) runs natively. Its unit tests import only pure
modules (fares, promos, the trip state machine, tokens, passwords, geo, dispatch ranking), so they
need no dependencies installed and no database. The live workflow test in the same folder skips
without API_BASE. The seed is generated by a script that reuses the API's own fare code; the
committed seed must be exactly what the script produces.
"""

from __future__ import annotations

import hashlib
import os
import re
import shutil
import subprocess
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[3] / "templates" / "catalog"
API_CANDIDATES = [REPO / "ride-now" / "repo" / "services" / "api", REPO / "_ride-now" / "repo" / "services" / "api"]
API = next((path for path in API_CANDIDATES if path.is_dir()), API_CANDIDATES[0])


def _node_supports_typescript() -> bool:
    node = shutil.which("node")
    if not node:
        return False
    version = subprocess.run([node, "--version"], capture_output=True, text=True, check=False).stdout.strip()
    match = re.match(r"v(\d+)\.(\d+)", version)
    return bool(match) and (int(match.group(1)), int(match.group(2))) >= (22, 18)


@unittest.skipUnless(API.is_dir() and _node_supports_typescript(), "needs the RideNow template and Node >= 22.18")
class RideNowApiTests(unittest.TestCase):
    def test_unit_tests_pass(self) -> None:
        tests = sorted(str(p.relative_to(API)) for p in (API / "test").glob("*.test.ts"))
        self.assertGreaterEqual(len(tests), 5)
        result = subprocess.run(
            ["node", "--test", *tests], cwd=str(API), capture_output=True, text=True, timeout=180, check=False,
            env={"PATH": os.environ.get("PATH", ""), "HOME": os.environ.get("HOME", "")},
        )
        self.assertEqual(result.returncode, 0, result.stdout[-3000:] + result.stderr[-2000:])
        passed = re.search(r"pass (\d+)", result.stdout)
        self.assertIsNotNone(passed)
        self.assertGreaterEqual(int(passed.group(1)), 20)

    def test_seed_matches_its_generator(self) -> None:
        result = subprocess.run(
            ["node", "scripts/generate-seed.mjs"], cwd=str(API), capture_output=True, timeout=180, check=False,
        )
        self.assertEqual(result.returncode, 0, result.stderr.decode()[-2000:])
        committed = (API / "seed" / "001_demo.sql").read_bytes()
        self.assertEqual(
            hashlib.sha256(result.stdout).hexdigest(),
            hashlib.sha256(committed).hexdigest(),
            "seed/001_demo.sql is stale: run `node scripts/generate-seed.mjs > seed/001_demo.sql`",
        )

    def test_demo_logins_are_documented_in_the_seed(self) -> None:
        head = (API / "seed" / "001_demo.sql").read_text(encoding="utf-8")[:600]
        for login in ("asha@ridenow.test", "ravi@ridenow.test", "admin@ridenow.test"):
            self.assertIn(login, head)


if __name__ == "__main__":
    unittest.main()
