import json
import subprocess
import tempfile
from pathlib import Path
from unittest import TestCase

from omnistackai_agent_engine.application_ir import (
    AdminStrategy,
    ApplicationIR,
    BackendStrategy,
    DatabaseStrategy,
    Entity,
    Field,
    FieldType,
    MobileProfile,
    Platform,
    ProjectStrategy,
    RepoStrategy,
    WebStrategy,
    example_ir,
)
from omnistackai_agent_engine.codegen import (
    GenerationTarget,
    MONOREPO_TARGET,
    assemble_project,
    default_registry,
)
from omnistackai_agent_engine.git_service import create_repository


class DefaultRegistryTests(TestCase):
    def test_has_six_adapters(self) -> None:
        self.assertEqual(
            set(default_registry().targets()),
            {
                GenerationTarget.NEXTJS_WEB,
                GenerationTarget.NEXTJS_ADMIN,
                GenerationTarget.BACKEND_PYTHON,
                GenerationTarget.BACKEND_GO,
                GenerationTarget.REACT_NATIVE,
                GenerationTarget.BACKEND_NODE,
            },
        )


class AssembleTests(TestCase):
    def test_web_and_go_backend_layout(self) -> None:
        project = assemble_project(example_ir("rideshare-favourites"))  # web nextjs + backend go
        self.assertEqual(project.target, MONOREPO_TARGET)
        paths = set(project.paths())
        self.assertIn("apps/web/package.json", paths)
        self.assertIn("apps/web/app/page.tsx", paths)
        self.assertIn("services/api/go.mod", paths)
        self.assertIn("README.md", paths)
        self.assertIn(".gitignore", paths)
        readme = project.get("README.md").content
        self.assertIn("apps/web", readme)
        self.assertIn("services/api", readme)

    def test_python_backend_web_and_admin_are_all_assembled(self) -> None:
        """R-541: an IR asking for a web app and an admin panel gets both, plus the backend.

        Until the NEXTJS_ADMIN adapter existed the console was recorded as "not assembled yet"
        and silently dropped, so this IR produced a single app that served neither audience.
        """
        project = assemble_project(example_ir("minimal-blog"))  # web nextjs + backend python + admin nextjs
        paths = set(project.paths())
        self.assertIn("services/api/requirements.txt", paths)
        self.assertIn("apps/web/package.json", paths)
        self.assertIn("apps/admin/package.json", paths)
        # Two Next.js apps in one monorepo need distinct package names or pnpm refuses the workspace.
        self.assertNotEqual(
            json.loads(project.get("apps/web/package.json").content)["name"],
            json.loads(project.get("apps/admin/package.json").content)["name"],
        )
        # Nothing is skipped any more, so the README carries no "not assembled" note for admin.
        self.assertNotIn("admin_strategy", project.get("README.md").content)

    def test_node_backend_is_assembled(self) -> None:
        ir = ApplicationIR(
            name="Api Only", description="d", platforms=(Platform.BACKEND,),
            project_strategy=ProjectStrategy(
                MobileProfile.NONE, WebStrategy.NONE, AdminStrategy.NONE,
                BackendStrategy.NODE, DatabaseStrategy.POSTGRES, RepoStrategy.CUSTOMER_PROJECT_MONOREPO,
            ),
            entities=(Entity("Thing", (Field("id", FieldType.UUID),)),),
        )
        project = assemble_project(ir)
        paths = set(project.paths())
        self.assertTrue(any(p.startswith("services/api/") for p in paths))
        self.assertIn("services/api/package.json", paths)
        self.assertIn("services/api/src/index.ts", paths)
        self.assertIn("services/api", project.get("README.md").content)

    def test_deterministic(self) -> None:
        ir = example_ir("rideshare-favourites")
        self.assertEqual(assemble_project(ir).paths(), assemble_project(ir).paths())


class EndToEndTests(TestCase):
    def test_one_ir_materializes_into_one_customer_repo(self) -> None:
        project = assemble_project(example_ir("rideshare-favourites"))
        with tempfile.TemporaryDirectory() as tmp:
            result = create_repository(
                project, tmp, author_name="Customer Owner", author_email="owner@example.com",
                commit_message="Generated by OmniStackAI",
            )
            self.assertRegex(result.commit_sha, r"^[0-9a-f]{40}$")
            self.assertTrue((Path(tmp) / "apps/web/package.json").is_file())
            self.assertTrue((Path(tmp) / "services/api/go.mod").is_file())
            count = subprocess.run(
                ["git", "rev-list", "--count", "HEAD"], cwd=tmp, capture_output=True, text=True, check=True
            ).stdout.strip()
            self.assertEqual(count, "1")
