import re
import subprocess
import tempfile
from pathlib import Path
from unittest import TestCase

from omnistackai_agent_engine.application_ir import (
    AdminStrategy,
    ApplicationIR,
    BackendStrategy,
    DatabaseStrategy,
    Entity,
    Field,
    FieldType,
    MobileProfile,
    Platform,
    ProjectStrategy,
    RepoStrategy,
    WebStrategy,
)
from omnistackai_agent_engine.codegen import GeneratedFile, GeneratedProject, NextjsWebAdapter
from omnistackai_agent_engine.git_service import (
    RepositoryError,
    TargetNotEmptyError,
    create_repository,
    materialize_project,
)


def _project() -> GeneratedProject:
    ir = ApplicationIR(
        name="Demo App",
        description="demo",
        platforms=(Platform.WEB,),
        project_strategy=ProjectStrategy(
            MobileProfile.NONE, WebStrategy.NEXTJS, AdminStrategy.NONE,
            BackendStrategy.GO, DatabaseStrategy.POSTGRES, RepoStrategy.CUSTOMER_PROJECT_MONOREPO,
        ),
        entities=(Entity("Item", (Field("id", FieldType.UUID), Field("title", FieldType.STRING))),),
    )
    return NextjsWebAdapter().generate(ir)


class MaterializeTests(TestCase):
    def test_writes_all_files_to_disk(self) -> None:
        project = _project()
        with tempfile.TemporaryDirectory() as tmp:
            result = materialize_project(project, tmp)
            self.assertEqual(result.file_count, len(project))
            for generated in project.files():
                on_disk = Path(tmp) / generated.path
                self.assertTrue(on_disk.is_file(), generated.path)
                self.assertEqual(on_disk.read_text(encoding="utf-8"), generated.content)

    def test_non_empty_target_requires_overwrite(self) -> None:
        project = _project()
        with tempfile.TemporaryDirectory() as tmp:
            (Path(tmp) / "existing.txt").write_text("keep")
            with self.assertRaises(TargetNotEmptyError):
                materialize_project(project, tmp)
            # overwrite proceeds
            result = materialize_project(project, tmp, overwrite=True)
            self.assertEqual(result.file_count, len(project))

    def test_nested_paths_are_created(self) -> None:
        project = GeneratedProject("t", (GeneratedFile("deep/nested/dir/file.txt", "hi"),))
        with tempfile.TemporaryDirectory() as tmp:
            materialize_project(project, tmp)
            self.assertEqual((Path(tmp) / "deep/nested/dir/file.txt").read_text(), "hi")


class RepositoryTests(TestCase):
    def _log(self, cwd: str, fmt: str) -> str:
        return subprocess.run(
            ["git", "log", "-1", f"--format={fmt}"], cwd=cwd, capture_output=True, text=True, check=True
        ).stdout.strip()

    def test_creates_repo_with_single_commit_and_identity(self) -> None:
        project = _project()
        with tempfile.TemporaryDirectory() as tmp:
            result = create_repository(
                project, tmp, author_name="Ada Owner", author_email="ada@example.com",
                commit_message="Generated by OmniStackAI",
            )
            self.assertEqual(result.file_count, len(project))
            self.assertRegex(result.commit_sha, r"^[0-9a-f]{40}$")
            self.assertTrue((Path(tmp) / ".git").is_dir())
            count = subprocess.run(
                ["git", "rev-list", "--count", "HEAD"], cwd=tmp, capture_output=True, text=True, check=True
            ).stdout.strip()
            self.assertEqual(count, "1")
            self.assertEqual(self._log(tmp, "%an"), "Ada Owner")
            self.assertEqual(self._log(tmp, "%ae"), "ada@example.com")
            self.assertEqual(self._log(tmp, "%s"), "Generated by OmniStackAI")

    def test_committed_tree_matches_project(self) -> None:
        project = _project()
        with tempfile.TemporaryDirectory() as tmp:
            create_repository(project, tmp, author_name="Owner", author_email="owner@example.com")
            tracked = subprocess.run(
                ["git", "ls-files"], cwd=tmp, capture_output=True, text=True, check=True
            ).stdout.split()
            self.assertEqual(sorted(tracked), sorted(project.paths()))

    def test_requires_author_identity(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            with self.assertRaises(RepositoryError):
                create_repository(_project(), tmp, author_name="", author_email="x@example.com")
